# A1 lesson 13-17: soal latihan baru (m025-376). Format: lihat build_pack.py.
LESSONS = {
    "present_continuous_basics": dict(
        obj=("Use am, is, or are + verb-ing for something happening right now.",
             "Pakai “am”, “is”, atau “are” + kata kerja -ing untuk kejadian yang sedang berlangsung sekarang.",
             "ใช้ 'am', 'is' หรือ 'are' + คำกริยาเติม -ing กับสิ่งที่กำลังเกิดขึ้นตอนนี้"),
        mis=("Learner writes the -ing verb without am, is, or are, because 'sedang' and 'กำลัง' need no helper verb, or uses the habit form for an action happening now.",
             "Kamu menulis kata kerja -ing tanpa “am”, “is”, atau “are”, karena kata “sedang” nggak butuh kata bantu, atau memakai bentuk kebiasaan untuk kejadian sekarang.",
             "คุณเขียนคำกริยา -ing โดยไม่มี 'am', 'is' หรือ 'are' เพราะคำว่า 'กำลัง' ไม่ต้องมีกริยาช่วย หรือใช้รูปกิจวัตรกับสิ่งที่กำลังเกิดขึ้น"),
        rule=("Happening now: am, is, or are to match the subject, then verb-ing. Clues: now, look!, at the moment.",
              "Kejadian yang sedang berlangsung saat berbicara atau situasi sementara wajib memakai pasangan to be (am/is/are) ditambah kata kerja berakhiran -ing.<br><br>💡 <b>RUMUS KILAT</b>:<br>Subjek I ➡️ <b>am + Verb-ing</b>.<br>Subjek He / She / It ➡️ <b>is + Verb-ing</b>.<br>Subjek You / We / They ➡️ <b>are + Verb-ing</b>.<br>Pantangan ➡️ Dilarang membuang to be (salah: <i>he eating</i> ❌) atau lupa -ing (salah: <i>he is eat</i> ❌).",
              "สิ่งที่กำลังเกิดขึ้นตอนนี้ใช้ 'am', 'is' หรือ 'are' ให้ตรงกับประธาน แล้วตามด้วยคำกริยาเติม -ing คำใบ้ที่เจอบ่อยคือ 'now' และ 'look!'"),
        avoid=("Check two parts: the right be word for the subject, and -ing on the verb.",
               "Cek dua bagian: bentuk “be” yang cocok dengan subjeknya, dan akhiran -ing pada kata kerjanya.",
               "เช็กสองส่วน คือรูป 'be' ที่ตรงกับประธาน และ -ing ที่คำกริยา"),
    ),
    "past_be_was_were": dict(
        obj=("Use was or were to talk about the past: was with I, he, she, it; were with you, we, they.",
             "Pakai “was” atau “were” untuk cerita masa lalu: “was” untuk “I”, “he”, “she”, “it”; “were” untuk “you”, “we”, “they”.",
             "ใช้ 'was' หรือ 'were' เล่าเรื่องในอดีต โดย 'was' ใช้กับ 'I', 'he', 'she', 'it' และ 'were' ใช้กับ 'you', 'we', 'they'"),
        mis=("Learner uses the present form with a past time word, since Indonesian and Thai do not change for time, or uses was for every subject.",
             "Kamu memakai bentuk sekarang walaupun ada kata waktu lampau, karena bahasa Indonesia nggak berubah bentuk menurut waktu, atau memakai “was” untuk semua subjek.",
             "คุณใช้รูปปัจจุบันทั้งที่มีคำบอกเวลาในอดีต เพราะภาษาไทยไม่เปลี่ยนรูปตามเวลา หรือใช้ 'was' กับทุกประธาน"),
        rule=("I, he, she, it: was. You, we, they: were. In questions, was or were moves before the subject.",
              "Bentuk lampau dari to be (am/is/are) untuk kalimat yang tidak memiliki kata kerja aksi (menjelaskan sifat, profesi, atau lokasi di masa lalu):<br>• Subjek I, He, She, It memakai “was”.<br>• Subjek You, We, They memakai “were”.<br><br>💡 <b>RUMUS KILAT</b>:<br>Subjek tunggal (I / He / She / It) ➡️ Pakai <b>was</b> (negatif: <b>wasn't</b>).<br>Subjek jamak (You / We / They) ➡️ Pakai <b>were</b> (negatif: <b>weren't</b>).<br>Setelah was/were ➡️ Diikuti kata sifat, benda, atau tempat (contoh: <i>was tired, were at home</i>).",
              "ประธาน 'I', 'he', 'she', 'it' ใช้ 'was' ส่วน 'you', 'we', 'they' ใช้ 'were' ถ้าเป็นคำถามให้ย้ายคำนี้ไปไว้หน้าประธาน"),
        avoid=("Look for a past time word (yesterday, last…, ago), then match was or were to the subject.",
               "Cari kata waktu lampau (“yesterday”, “last…”, “ago”), lalu cocokkan “was” atau “were” dengan subjeknya.",
               "หาคำบอกเวลาในอดีต เช่น 'yesterday', 'last…', 'ago' แล้วเลือก 'was' หรือ 'were' ให้ตรงกับประธาน"),
    ),
    "past_simple_regular_forms": dict(
        obj=("Add -ed to regular verbs for finished past actions, and use the base verb after did.",
             "Tambah -ed pada kata kerja beraturan untuk kejadian yang sudah selesai, dan pakai bentuk dasar sesudah “did”.",
             "เติม -ed ให้คำกริยาปกติเมื่อเล่าเรื่องที่จบไปแล้ว และใช้รูปพื้นฐานหลัง 'did'"),
        mis=("Learner leaves the verb in the base form after yesterday, since Indonesian and Thai verbs do not change, or keeps -ed after did.",
             "Kamu membiarkan kata kerjanya dalam bentuk dasar walaupun ada “yesterday”, karena kata kerja bahasa Indonesia nggak berubah, atau tetap memakai -ed sesudah “did”.",
             "คุณใช้คำกริยารูปเดิมทั้งที่มี 'yesterday' เพราะคำกริยาภาษาไทยไม่เปลี่ยนรูป หรือยังเติม -ed หลัง 'did'"),
        rule=("Past: verb + -ed (played). Verb ending in e: add -d (danced). Consonant + y: -ied (studied). After did or didn't: base verb.",
              "Kejadian lampau yang sudah selesai di masa lalu menggunakan Verb 2 (untuk kata kerja beraturan, tambahkan akhiran <b>-ed</b>). Jika kalimat tanya atau negatif, bentuk lampau diambil alih oleh “did/didn't”, sehingga kata kerjanya wajib kembali ke bentuk dasar (Verb 1).<br><br>💡 <b>RUMUS KILAT</b>:<br>Kalimat positif lampau ➡️ Pakai <b>Verb 2</b> (contoh: <i>walked, visited</i>).<br>Ada kata <b>did / didn't</b> ➡️ Kata kerja WAJIB balik ke <b>dasar (Verb 1)</b>.<br>Pantangan ➡️ Dilarang mendobelkan lampau (salah: <i>didn't walked</i> ❌).",
              "อดีต: คำกริยา + -ed ('played') ถ้าลงท้ายด้วย e เติมแค่ -d ('danced') ถ้าลงท้ายด้วยพยัญชนะ + y เปลี่ยนเป็น -ied ('studied') หลัง 'did' หรือ 'didn't' ใช้รูปพื้นฐาน"),
        avoid=("See a past time word? Add -ed once. See did? Go back to the base verb.",
               "Ada kata waktu lampau? Tambah -ed sekali saja. Ada “did”? Kembali ke bentuk dasar.",
               "ถ้ามีคำบอกเวลาในอดีต ให้เติม -ed ครั้งเดียว ถ้ามี 'did' ให้กลับไปใช้รูปพื้นฐาน"),
    ),
    "some_any_countable_uncountable": dict(
        obj=("Use some in positive sentences and any in negatives and questions, with plural or uncountable nouns.",
             "Pakai “some” di kalimat positif dan “any” di kalimat negatif atau tanya, untuk benda jamak atau benda yang nggak bisa dihitung.",
             "ใช้ 'some' ในประโยคบอกเล่า และ 'any' ในประโยคปฏิเสธหรือคำถาม กับคำนามพหูพจน์หรือคำนามนับไม่ได้"),
        mis=("Learner uses some in a negative sentence, or uses a or many with nouns like bread and rice.",
             "Kamu memakai “some” di kalimat negatif, atau memakai “a” dan “many” untuk benda seperti “bread” dan “rice”.",
             "คุณใช้ 'some' ในประโยคปฏิเสธ หรือใช้ 'a' และ 'many' กับคำนามอย่าง 'bread' และ 'rice'"),
        rule=("Positive: some. Negative and question: any. Bread, milk, rice, and money cannot be counted: no a, no many.",
              "Aturan pemakaian “some” vs “any” untuk menyatakan sejumlah barang:<br>• “Some” dipakai pada kalimat POSITIF dan tawaran sopan.<br>• “Any” dipakai pada kalimat NEGATIF (ada not/n't) dan kalimat TANYA biasa.<br><br>💡 <b>RUMUS KILAT</b>:<br>Kalimat POSITIF ➡️ Pakai <b>some</b> (contoh: <i>I have some apples</i>).<br>Kalimat NEGATIF (ada n't) ➡️ Wajib pakai <b>any</b> (contoh: <i>I don't have any apples</i>).<br>Kalimat TANYA biasa ➡️ Pakai <b>any</b> (contoh: <i>Do you have any questions?</i>).<br>Tawaran sopan (Would you like...?) ➡️ Pakai <b>some</b> (contoh: <i>Would you like some tea?</i>).",
              "ประโยคบอกเล่าใช้ 'some' ประโยคปฏิเสธและคำถามใช้ 'any' ส่วนคำนามอย่าง 'bread', 'milk', 'rice' และ 'money' นับไม่ได้ จึงไม่ใช้ 'a' และไม่ใช้ 'many'"),
        avoid=("Check two things: is the sentence positive or negative? Can you count the noun?",
               "Cek dua hal: kalimatnya positif atau negatif? Bendanya bisa dihitung atau nggak?",
               "เช็กสองอย่าง คือประโยคบอกเล่าหรือปฏิเสธ และคำนามนับได้หรือไม่"),
    ),
    "time_prepositions_in_on_at": dict(
        obj=("Choose in, on, or at for time: in for months and parts of the day, on for days, at for clock times.",
             "Pilih “in”, “on”, atau “at” untuk waktu: “in” untuk bulan dan bagian hari, “on” untuk hari, “at” untuk jam.",
             "เลือก 'in', 'on' หรือ 'at' สำหรับเวลา โดย 'in' ใช้กับเดือนและช่วงของวัน 'on' ใช้กับวัน และ 'at' ใช้กับเวลาบนนาฬิกา"),
        mis=("Learner uses one preposition for every time, since 'pada' and 'ตอน' cover them all.",
             "Kamu memakai satu kata depan untuk semua waktu, karena kata “pada” bisa dipakai untuk semuanya.",
             "คุณใช้คำบุพบทคำเดียวกับเวลาทุกแบบ เพราะคำว่า 'ตอน' ใช้ได้กับทุกอย่าง"),
        rule=("In + month, year, or part of the day (in July, in the evening). On + day or date (on Tuesday). At + clock time (at 6:15).",
              "Kalau periode waktu luas (bulan, tahun, musim, bagian hari): Pakai “in”. Contoh: <b>in July</b> (di bulan Juli), <b>in 2024</b>, <b>in the morning</b> (di pagi hari).<br>Kalau hari dan tanggal spesifik: Pakai “on”. Contoh: <b>on Monday</b> (pada hari Senin), <b>on October 5th</b> (pada tanggal 5 Oktober), <b>on my birthday</b>.<br>Kalau jam yang tepat atau titik waktu tertentu: Pakai “at”. Contoh: <b>at 7 o'clock</b> (pada jam 7 tepat), <b>at noon</b> (tengah hari), <b>at night</b> (malam hari).<br><br>💡 <b>RUMUS KILAT</b>:<br>Periode luas (bulan, tahun, abad, pagi/siang/malam) ➡️ Pakai <b>in</b>.<br>Hari & tanggal spesifik (ada nama hari / tanggal) ➡️ Pakai <b>on</b>.<br>Jam tepat & titik waktu spesifik (jam dinding, noon, night) ➡️ Pakai <b>at</b>.",
              "'in' ใช้กับเดือน ปี หรือช่วงของวัน ('in July', 'in the evening') 'on' ใช้กับวันหรือวันที่ ('on Tuesday') และ 'at' ใช้กับเวลาบนนาฬิกา ('at 6:15')"),
        avoid=("Ask first: a month, a day, or a clock time? Then choose in, on, or at.",
               "Tanya dulu: bulan, hari, atau jam? Baru pilih “in”, “on”, atau “at”.",
               "ถามก่อนว่าเป็นเดือน วันในสัปดาห์ หรือเวลาบนนาฬิกา แล้วค่อยเลือก 'in', 'on' หรือ 'at'"),
    ),
}

# ---- label bersama ----
PC_PL_SG = ("plural be used in present continuous with a singular subject",
            "bentuk “be” jamak dipakai untuk satu orang yang sedang melakukan sesuatu.",
            "ใช้รูป 'be' พหูพจน์กับคนเดียวที่กำลังทำอะไรอยู่")
PC_SG_PL = ("singular be used in present continuous with a plural subject",
            "bentuk “be” tunggal dipakai untuk banyak orang yang sedang melakukan sesuatu.",
            "ใช้รูป 'be' เอกพจน์กับหลายคนที่กำลังทำอะไรอยู่")
HE_BE_I = ("he-she-it be form used with I",
           "bentuk “be” untuk “he”, “she”, “it” dipakai bersama “I”.",
           "ใช้รูป 'be' ของ 'he', 'she', 'it' กับ 'I'")
ING_MISSING = ("-ing missing after am, is, or are",
               "akhiran -ing lupa ditambahkan sesudah bentuk “be”.",
               "ลืมเติม -ing หลังรูป 'be'")
WERE_I = ("plural past be used with I",
          "bentuk lampau untuk “you”, “we”, “they” dipakai bersama “I”.",
          "ใช้รูปอดีตของ 'you', 'we', 'they' กับ 'I'")
IS_I_PAST = ("present he-she-it be used for I in the past",
             "bentuk sekarang untuk “he”, “she”, “it” dipakai untuk “I” di masa lalu.",
             "ใช้รูปปัจจุบันของ 'he', 'she', 'it' กับ 'I' ในอดีต")
DID_BE = ("did used in place of a past be verb",
          "“did” dipakai di tempat yang butuh bentuk lampau dari “be”.",
          "ใช้ 'did' ในตำแหน่งที่ต้องใช้รูปอดีตของ 'be'")
WERE_SG = ("plural past be used with a singular subject",
           "bentuk lampau jamak dipakai untuk satu orang atau satu benda.",
           "ใช้รูปอดีตพหูพจน์กับคนหรือสิ่งเดียว")
ED_E = ("-ed added to a verb ending in e",
        "akhiran -ed ditambahkan penuh ke kata kerja yang sudah berakhiran e.",
        "เติม -ed เต็ม ๆ กับคำกริยาที่ลงท้ายด้วย e อยู่แล้ว")
ED_KEEP_Y = ("-ed added to a consonant + y verb without changing y",
             "kata kerja berakhiran konsonan + y diberi -ed tanpa mengubah y jadi i.",
             "เติม -ed กับกริยาที่ลงท้ายด้วยพยัญชนะ + y โดยไม่เปลี่ยน y เป็น i")
S_AFTER_DID = ("-s added to the verb after did",
               "akhiran -s ditambahkan ke kata kerja sesudah “did”.",
               "เติม -s ให้คำกริยาหลัง 'did'")
ING_AFTER_DID = ("-ing form used after did",
                 "bentuk -ing dipakai sesudah “did”.",
                 "ใช้รูป -ing หลัง 'did'")
ANY_POS = ("negative quantifier used in a positive sentence",
           "kata jumlah untuk kalimat negatif dipakai di kalimat positif.",
           "ใช้คำบอกปริมาณของประโยคปฏิเสธในประโยคบอกเล่า")
AT_MONTH = ("clock-time preposition used with a month",
            "kata depan untuk jam dipakai untuk bulan.",
            "ใช้คำบุพบทของเวลานาฬิกากับเดือน")
BY_MONTH = ("deadline preposition used to name a month",
            "kata depan tenggat (“paling lambat”) dipakai untuk menyebut bulan.",
            "ใช้คำบุพบทบอกเส้นตายกับการบอกเดือน")
AT_EVENING = ("at night pattern copied to the evening",
              "pola “at night” disamakan dengan waktu sore.",
              "เอารูปแบบ 'at night' มาใช้กับช่วงเย็น")


def ON_NOT_DAY(item_id, item_th):
    return ("day preposition used for a time that is not a day",
            "kata depan untuk hari dipakai untuk waktu yang bukan hari.",
            "ใช้คำบุพบทของวันกับเวลาที่ไม่ใช่วัน", item_id, item_th)


def TO_TIME(item_id, item_th):
    return ("direction preposition used for a time",
            "kata depan arah dipakai untuk menyebut waktu.",
            "ใช้คำบุพบทบอกทิศทางกับเวลา", item_id, item_th)


ITEMS = [
    # ---------------- 13. present continuous ----------------
    dict(s="present_continuous_basics", id="A1-349",
         stem="Shh! The baby ___ now.", opts=["is sleeping", "sleeping", "sleeps", "are sleeping"], ans="is sleeping",
         why=("'Now' shows it is happening at this moment, and 'the baby' is one, so: is sleeping.",
              "“Now” menunjukkan kejadiannya sedang berlangsung, dan “the baby” cuma satu, jadi “is sleeping”.",
              "'now' บอกว่ากำลังเกิดขึ้นตอนนี้ และ 'the baby' มีคนเดียว จึงใช้ 'is sleeping'"),
         others=("'Sleeping' has no be word, 'sleeps' is for habits, and 'are sleeping' is for more than one.",
                 "“Sleeping” nggak punya bentuk “be”, “sleeps” untuk kebiasaan, dan “are sleeping” untuk lebih dari satu.",
                 "'sleeping' ไม่มีรูป 'be' ส่วน 'sleeps' ใช้กับกิจวัตร และ 'are sleeping' ใช้กับมากกว่าหนึ่ง"),
         cue=("Shh! + now = it is happening: is sleeping.", "“Shh!” + “now” = sedang terjadi: “is sleeping”.", "เห็น 'Shh!' กับ 'now' แปลว่ากำลังเกิดขึ้น จึงใช้ 'is sleeping'"),
         rsn=("notice the word now -> find the subject the baby -> combine the be form for one with -ing",
              "perhatikan kata “now” → cari subjeknya, “the baby” → gabungkan bentuk “be” untuk satu orang dengan -ing",
              "สังเกตคำว่า 'now' → หาประธาน 'the baby' → รวมรูป 'be' ของคนเดียวกับ -ing"),
         d=[("sleeping", ("missing-be-auxiliary", "kata bantu “is” dihilangkan di depan kata kerja -ing.", "ตัด 'is' ที่ต้องอยู่หน้าคำกริยา -ing ออก"),
             "An -ing verb cannot stand alone; it needs a be word before it.",
             "kata kerja -ing nggak bisa berdiri sendiri, butuh bentuk “be” di depannya.",
             "คำกริยา -ing อยู่ลำพังไม่ได้ ต้องมีรูป 'be' อยู่ข้างหน้า"),
            ("sleeps", ("present-simple-habit", "bentuk kebiasaan dipakai untuk kejadian yang sedang berlangsung.", "ใช้รูปกิจวัตรกับสิ่งที่กำลังเกิดขึ้น"),
             "It is for habits, but 'now' shows this is happening at the moment.",
             "untuk kebiasaan, padahal “now” menunjukkan kejadiannya sedang berlangsung.",
             "ใช้กับกิจวัตร แต่ 'now' บอกว่ากำลังเกิดขึ้นตอนนี้"),
            ("are sleeping", PC_PL_SG,
             "Its be word is for more than one, but 'the baby' is one.",
             "bentuk “be”-nya untuk lebih dari satu, padahal “the baby” cuma satu.",
             "รูป 'be' ที่ใช้เป็นของมากกว่าหนึ่ง แต่ 'the baby' มีคนเดียว")]),
    dict(s="present_continuous_basics", id="A1-350",
         stem="Look! My friends ___ a sandcastle on the beach.", opts=["are building", "is building", "building", "build"], ans="are building",
         why=("'Look!' shows it is happening now, and 'my friends' are many, so: are building.",
              "“Look!” menunjukkan kejadiannya sedang berlangsung, dan “my friends” banyak, jadi “are building”.",
              "'Look!' บอกว่ากำลังเกิดขึ้นตอนนี้ และ 'my friends' มีหลายคน จึงใช้ 'are building'"),
         others=("'Is building' is for one person, 'building' has no be word, and 'build' is for habits.",
                 "“Is building” untuk satu orang, “building” nggak punya bentuk “be”, dan “build” untuk kebiasaan.",
                 "'is building' ใช้กับคนเดียว 'building' ไม่มีรูป 'be' และ 'build' ใช้กับกิจวัตร"),
         cue=("Look! + many people: are + -ing.", "“Look!” + banyak orang: “are” + -ing.", "เห็น 'Look!' และมีหลายคน ใช้ 'are' + -ing"),
         rsn=("notice the word look -> count the friends -> combine the be form for many with -ing",
              "perhatikan kata “Look!” → hitung teman-temannya → gabungkan bentuk “be” untuk banyak orang dengan -ing",
              "สังเกตคำว่า 'Look!' → นับจำนวนเพื่อน → รวมรูป 'be' ของหลายคนกับ -ing"),
         d=[("is building", PC_SG_PL,
             "Its be word is for one person, but 'my friends' are many.",
             "bentuk “be”-nya untuk satu orang, padahal “my friends” banyak.",
             "รูป 'be' ที่ใช้เป็นของคนเดียว แต่ 'my friends' มีหลายคน"),
            ("building", ("missing-be-auxiliary", "kata bantu “are” dihilangkan di depan kata kerja -ing.", "ตัด 'are' ที่ต้องอยู่หน้าคำกริยา -ing ออก"),
             "It has no be word, and an -ing verb always needs one.",
             "nggak punya bentuk “be”, padahal kata kerja -ing selalu butuh itu.",
             "ไม่มีรูป 'be' ทั้งที่คำกริยา -ing ต้องมีเสมอ"),
            ("build", ("present-simple-habit", "bentuk kebiasaan dipakai untuk kejadian yang sedang terlihat.", "ใช้รูปกิจวัตรกับสิ่งที่เห็นว่ากำลังเกิดขึ้น"),
             "It is for habits, but 'Look!' shows this is happening now.",
             "untuk kebiasaan, padahal “Look!” menunjukkan kejadiannya sedang berlangsung.",
             "ใช้กับกิจวัตร แต่ 'Look!' บอกว่ากำลังเกิดขึ้นตอนนี้")]),
    dict(s="present_continuous_basics", id="A1-351",
         stem="I ___ my homework at the moment, so I can't play.", opts=["am doing", "is doing", "doing", "do"], ans="am doing",
         why=("'At the moment' means now, and the subject is 'I', so: am doing.",
              "“At the moment” artinya sekarang, dan subjeknya “I”, jadi “am doing”.",
              "'at the moment' แปลว่าตอนนี้ และประธานคือ 'I' จึงใช้ 'am doing'"),
         others=("'Is doing' does not go with I, 'doing' has no be word, and 'do' is for habits.",
                 "“Is doing” nggak cocok dengan “I”, “doing” nggak punya bentuk “be”, dan “do” untuk kebiasaan.",
                 "'is doing' ใช้กับ 'I' ไม่ได้ 'doing' ไม่มีรูป 'be' และ 'do' ใช้กับกิจวัตร"),
         cue=("I am + -ing: I am doing, I am reading.", "“I am” + -ing: “I am doing”, “I am reading”.", "ถ้าฉันกำลังทำอยู่ ให้ใช้ 'I am' + -ing เช่น 'I am doing'"),
         rsn=("notice at the moment -> find the subject I -> combine the be form for I with -ing",
              "perhatikan “at the moment” → cari subjeknya, “I” → gabungkan bentuk “be” untuk “I” dengan -ing",
              "สังเกต 'at the moment' → หาประธาน 'I' → รวมรูป 'be' ของ 'I' กับ -ing"),
         d=[("is doing", HE_BE_I,
             "This be word is for he, she, or it, not for I.",
             "bentuk “be” ini untuk “he”, “she”, atau “it”, bukan untuk “I”.",
             "รูป 'be' นี้ใช้กับ 'he', 'she', 'it' ไม่ใช่กับ 'I'"),
            ("doing", ("missing-be-auxiliary", "kata bantu “am” dihilangkan di depan kata kerja -ing.", "ตัด 'am' ที่ต้องอยู่หน้าคำกริยา -ing ออก"),
             "It has no be word, so the sentence is not complete.",
             "nggak punya bentuk “be”, jadi kalimatnya belum lengkap.",
             "ไม่มีรูป 'be' ประโยคจึงยังไม่สมบูรณ์"),
            ("do", ("present-simple-habit", "bentuk kebiasaan dipakai untuk kejadian yang sedang berlangsung.", "ใช้รูปกิจวัตรกับสิ่งที่กำลังเกิดขึ้น"),
             "It is for habits, but 'at the moment' means now.",
             "untuk kebiasaan, padahal “at the moment” artinya sekarang.",
             "ใช้กับกิจวัตร แต่ 'at the moment' แปลว่าตอนนี้")]),
    dict(s="present_continuous_basics", id="A1-352",
         stem="“What are you doing?” “I ___ for my pen.”", opts=["am looking", "look", "looking", "am look"], ans="am looking",
         why=("The question 'What are you doing?' asks about now, so the answer uses am + -ing: am looking.",
              "Pertanyaan “What are you doing?” menanyakan yang sedang terjadi, jadi jawabannya “am” + -ing. Hasilnya “am looking”.",
              "คำถาม 'What are you doing?' ถามสิ่งที่กำลังทำ คำตอบจึงใช้ 'am' + -ing เป็น 'am looking'"),
         others=("'Look' is for habits, 'looking' has no be word, and 'am look' forgets -ing.",
                 "“Look” untuk kebiasaan, “looking” nggak punya bentuk “be”, dan “am look” lupa -ing.",
                 "'look' ใช้กับกิจวัตร 'looking' ไม่มีรูป 'be' และ 'am look' ลืมเติม -ing"),
         cue=("Answer in the same form as the question: are you doing → I am looking.", "Jawab dengan pola yang sama: “are you doing?” → “I am looking”.", "ตอบด้วยรูปเดียวกับคำถาม ถ้าถามว่า 'are you doing?' ก็ตอบว่า 'I am looking'"),
         rsn=("check the question what are you doing -> recall the be form for I -> combine it with look + -ing",
              "lihat pertanyaan “What are you doing?” → ingat bentuk “be” untuk “I” → gabungkan dengan “look” + -ing",
              "ดูคำถามที่ถามว่ากำลังทำอะไรอยู่ → นึกถึงรูป 'be' ของ 'I' → รวมกับ 'look' + -ing"),
         d=[("look", ("present-simple-habit", "bentuk kebiasaan dipakai untuk menjawab pertanyaan tentang sekarang.", "ใช้รูปกิจวัตรตอบคำถามเรื่องตอนนี้"),
             "It is for habits, but the question asks what is happening now.",
             "untuk kebiasaan, padahal pertanyaannya tentang yang sedang terjadi.",
             "ใช้กับกิจวัตร แต่คำถามถามถึงสิ่งที่กำลังเกิดขึ้น"),
            ("looking", ("missing-be-auxiliary", "kata bantu “am” dihilangkan di depan kata kerja -ing.", "ตัด 'am' ที่ต้องอยู่หน้าคำกริยา -ing ออก"),
             "It has no be word, but 'I' needs am before an -ing verb.",
             "nggak punya bentuk “be”, padahal “I” butuh “am” di depan kata kerja -ing.",
             "ไม่มีรูป 'be' ทั้งที่ 'I' ต้องมี 'am' หน้าคำกริยา -ing"),
            ("am look", ING_MISSING,
             "After am, the verb needs -ing.",
             "lupa -ing, padahal sesudah “am” kata kerjanya butuh -ing.",
             "ลืมเติม -ing ทั้งที่หลัง 'am' คำกริยาต้องเติม -ing")]),
    # ---------------- 14. was / were ----------------
    dict(s="past_be_was_were", id="A1-353",
         stem="I ___ sick yesterday, so I stayed at home.", opts=["was", "were", "am", "is"], ans="was",
         why=("'Yesterday' is past, and the subject is 'I', so we use 'was'.",
              "“Yesterday” menunjukkan masa lalu, dan subjeknya “I”, jadi pakai “was”.",
              "'yesterday' บอกว่าเป็นอดีต และประธานคือ 'I' จึงใช้ 'was'"),
         others=("'Were' is for you, we, or they, and 'am' and 'is' are present forms.",
                 "“Were” untuk “you”, “we”, atau “they”, sedangkan “am” dan “is” bentuk sekarang.",
                 "'were' ใช้กับ 'you', 'we', 'they' ส่วน 'am' และ 'is' เป็นรูปปัจจุบัน"),
         cue=("Yesterday + I: I was.", "“Yesterday” + “I” jadi “I was”.", "เล่าเรื่องเมื่อวานของตัวเอง ใช้ 'I was'"),
         rsn=("notice the word yesterday -> find the subject I -> choose the past form for I",
              "perhatikan kata “yesterday” → cari subjeknya, “I” → pilih bentuk lampau untuk “I”",
              "สังเกตคำว่า 'yesterday' → หาประธาน 'I' → เลือกรูปอดีตของ 'I'"),
         d=[("were", WERE_I,
             "It is for you, we, or they, not for I.",
             "untuk “you”, “we”, atau “they”, bukan untuk “I”.",
             "ใช้กับ 'you', 'we', 'they' ไม่ใช่กับ 'I'"),
            ("am", ("present-tense substitution", "bentuk sekarang dipakai untuk kejadian kemarin.", "ใช้รูปปัจจุบันกับเรื่องเมื่อวาน"),
             "It is a present form, but 'yesterday' is past.",
             "bentuk sekarang, padahal “yesterday” sudah lewat.",
             "เป็นรูปปัจจุบัน แต่ 'yesterday' เป็นอดีตไปแล้ว"),
            ("is", IS_I_PAST,
             "It is a present form, and it does not go with I.",
             "bentuk sekarang, dan nggak cocok dengan “I”.",
             "เป็นรูปปัจจุบัน และใช้กับ 'I' ไม่ได้")]),
    dict(s="past_be_was_were", id="A1-354",
         stem="We ___ at the beach last Sunday. It was fun!", opts=["were", "was", "are", "did"], ans="were",
         why=("'Last Sunday' is past, and the subject is 'we', so we use 'were'.",
              "“Last Sunday” menunjukkan masa lalu, dan subjeknya “we”, jadi pakai “were”.",
              "'last Sunday' บอกว่าเป็นอดีต และประธานคือ 'we' จึงใช้ 'were'"),
         others=("'Was' is for I, he, she, or it; 'are' is present; 'did' cannot come before 'at the beach'.",
                 "“Was” untuk “I”, “he”, “she”, atau “it”. “Are” bentuk sekarang. “Did” nggak bisa dipakai sebelum “at the beach”.",
                 "'was' ใช้กับ 'I', 'he', 'she', 'it' ส่วน 'are' เป็นรูปปัจจุบัน และ 'did' ใช้หน้า 'at the beach' ไม่ได้"),
         cue=("We, you, they + past: were.", "“We”, “you”, “they” di masa lalu: “were”.", "เล่าเรื่องในอดีตของพวกเรา พวกคุณ หรือพวกเขา ใช้ 'were'"),
         rsn=("notice last Sunday -> find the subject we -> choose the past form for we",
              "perhatikan “last Sunday” → cari subjeknya, “we” → pilih bentuk lampau untuk “we”",
              "สังเกต 'last Sunday' → หาประธาน 'we' → เลือกรูปอดีตของ 'we'"),
         d=[("was", ("singular-past transfer", "bentuk tunggal “was” dipakai untuk “we”.", "ใช้ 'was' รูปเอกพจน์กับ 'we'"),
             "It is for I, he, she, or it, but the subject is 'we'.",
             "untuk “I”, “he”, “she”, atau “it”, padahal subjeknya “we”.",
             "ใช้กับ 'I', 'he', 'she', 'it' แต่ประธานคือ 'we'"),
            ("are", ("present-tense substitution", "bentuk sekarang dipakai untuk hari Minggu lalu.", "ใช้รูปปัจจุบันกับวันอาทิตย์ที่แล้ว"),
             "It is a present form, but 'last Sunday' is past.",
             "bentuk sekarang, padahal “last Sunday” sudah lewat.",
             "เป็นรูปปัจจุบัน แต่ 'last Sunday' เป็นอดีตไปแล้ว"),
            ("did", DID_BE,
             "It cannot be followed directly by a place; to say where we were, we need a be word.",
             "nggak bisa langsung diikuti keterangan tempat. Untuk bilang “berada di pantai”, butuh bentuk “be”.",
             "ตามด้วยสถานที่ทันทีไม่ได้ ถ้าจะบอกว่าอยู่ที่ไหน ต้องใช้รูป 'be'")]),
    dict(s="past_be_was_were", id="A1-355",
         stem="“___ the test easy?” “Yes, it was!”", opts=["Was", "Were", "Did", "Is"], ans="Was",
         why=("The answer 'it was' shows the past, and 'the test' is one thing, so the question starts with 'Was'.",
              "Jawaban “it was” menunjukkan masa lalu, dan ujiannya cuma satu, jadi kalimat tanyanya diawali “Was”.",
              "คำตอบ 'it was' บอกว่าเป็นอดีต และการสอบมีครั้งเดียว คำถามจึงขึ้นต้นด้วย 'Was'"),
         others=("'Were' is for you, we, or they; 'Did' is not used with 'easy'; 'Is' is present.",
                 "“Were” untuk “you”, “we”, atau “they”. “Did” nggak dipakai dengan “easy”. “Is” bentuk sekarang.",
                 "'were' ใช้กับ 'you', 'we', 'they' ส่วน 'did' ไม่ใช้กับ 'easy' และ 'is' เป็นรูปปัจจุบัน"),
         cue=("To ask, move was before the subject.", "Mau bertanya? Pindahkan “was” ke depan subjeknya.", "ถ้าจะถาม ให้ย้าย 'was' ไปไว้หน้าประธาน"),
         rsn=("check the answer it was -> find the subject the test -> place the past form for one thing before the subject",
              "lihat jawaban “it was” → cari subjeknya, yaitu ujiannya → taruh bentuk lampau untuk satu benda di depan subjek",
              "ดูคำตอบ 'it was' → หาประธานซึ่งก็คือการสอบ → วางรูปอดีตของสิ่งเดียวไว้หน้าประธาน"),
         d=[("Were", WERE_SG,
             "It is for you, we, or they, but 'the test' is one thing.",
             "untuk “you”, “we”, atau “they”, padahal “the test” cuma satu.",
             "ใช้กับ 'you', 'we', 'they' แต่ 'the test' มีอย่างเดียว"),
            ("Did", ("do-support added to a be question", "“did” dipakai di kalimat tanya yang cukup memakai bentuk “be”.", "ใช้ 'did' ในคำถามที่ใช้แค่รูป 'be' ก็พอ"),
             "'Easy' is not an action, so the question needs a be word.",
             "dipakai untuk tindakan, padahal “easy” bukan tindakan. Kalimat tanya ini butuh bentuk “be”.",
             "ใช้กับการกระทำ แต่ 'easy' ไม่ใช่การกระทำ คำถามนี้จึงต้องใช้รูป 'be'"),
            ("Is", ("present-tense substitution", "bentuk sekarang dipakai untuk ujian yang sudah lewat.", "ใช้รูปปัจจุบันกับการสอบที่ผ่านไปแล้ว"),
             "It is a present form, but the answer shows the past.",
             "bentuk sekarang, padahal jawabannya menunjukkan masa lalu.",
             "เป็นรูปปัจจุบัน แต่คำตอบบอกว่าเป็นอดีต")]),
    dict(s="past_be_was_were", id="A1-356",
         stem="Ten years ago, this town ___ very small.", opts=["was", "were", "is", "be"], ans="was",
         why=("'Ten years ago' is past, and 'this town' is one place, so we use 'was'.",
              "“Ten years ago” menunjukkan masa lalu, dan “this town” cuma satu tempat, jadi pakai “was”.",
              "'ten years ago' บอกว่าเป็นอดีต และ 'this town' มีที่เดียว จึงใช้ 'was'"),
         others=("'Were' is for more than one, 'is' is present, and 'be' is the base form.",
                 "“Were” untuk lebih dari satu, “is” bentuk sekarang, dan “be” bentuk dasar.",
                 "'were' ใช้กับมากกว่าหนึ่ง 'is' เป็นรูปปัจจุบัน และ 'be' เป็นรูปพื้นฐาน"),
         cue=("…ago = past: it was.", "Ada “ago”? Itu masa lalu: “it was”.", "ถ้ามีคำว่า 'ago' แปลว่าเป็นอดีต ให้ใช้ 'it was'"),
         rsn=("notice ten years ago -> identify this town as one place -> choose the past form for one thing",
              "perhatikan “ten years ago” → pastikan “this town” itu satu tempat → pilih bentuk lampau untuk satu benda",
              "สังเกต 'ten years ago' → ดูว่า 'this town' เป็นที่เดียว → เลือกรูปอดีตของสิ่งเดียว"),
         d=[("were", WERE_SG,
             "It is for more than one, but 'this town' is one place.",
             "untuk lebih dari satu, padahal “this town” cuma satu tempat.",
             "ใช้กับมากกว่าหนึ่ง แต่ 'this town' มีที่เดียว"),
            ("is", ("present-tense substitution", "bentuk sekarang dipakai untuk keadaan sepuluh tahun lalu.", "ใช้รูปปัจจุบันกับสภาพเมื่อสิบปีก่อน"),
             "It is a present form, but 'ten years ago' is past.",
             "bentuk sekarang, padahal “ten years ago” sudah lewat.",
             "เป็นรูปปัจจุบัน แต่ 'ten years ago' เป็นอดีต"),
            ("be", ("bare-infinitive substitution", "bentuk dasar dipakai untuk keadaan di masa lalu.", "ใช้รูปพื้นฐานกับสภาพในอดีต"),
             "It is the base form, but 'ten years ago' needs a past form.",
             "bentuk dasar, padahal “ten years ago” butuh bentuk lampau.",
             "เป็นรูปพื้นฐาน แต่ 'ten years ago' ต้องใช้รูปอดีต")]),
    # ---------------- 15. past simple (regular) ----------------
    dict(s="past_simple_regular_forms", id="A1-357",
         stem="We ___ at the school party last Friday.", opts=["danced", "dance", "danceed", "dancing"], ans="danced",
         why=("'Last Friday' is past, and 'dance' ends in e, so we add only -d: danced.",
              "“Last Friday” menunjukkan masa lalu, dan “dance” berakhiran e, jadi cukup tambah -d. Hasilnya “danced”.",
              "'last Friday' บอกว่าเป็นอดีต และ 'dance' ลงท้ายด้วย e จึงเติมแค่ -d เป็น 'danced'"),
         others=("'Dance' is present, 'danceed' adds an extra e, and 'dancing' needs a be word.",
                 "“Dance” bentuk sekarang, “danceed” punya huruf e dobel, dan “dancing” butuh bentuk “be”.",
                 "'dance' เป็นรูปปัจจุบัน 'danceed' มี e ซ้ำ และ 'dancing' ต้องมีรูป 'be'"),
         cue=("Ends in e? Just add -d: dance, danced.", "Berakhiran e? Cukup tambah -d: “dance” jadi “danced”.", "ถ้าคำกริยาลงท้ายด้วย e ให้เติมแค่ -d เช่น 'danced'"),
         rsn=("notice last Friday -> check the verb ending e -> add -d",
              "perhatikan “last Friday” → cek akhiran e pada kata kerja → tambah -d",
              "สังเกต 'last Friday' → ดูว่ากริยาลงท้ายด้วย e → เติม -d"),
         d=[("dance", ("missing-past-marking", "tanda lampau hilang walaupun ada “last Friday”.", "ลืมทำเครื่องหมายอดีตทั้งที่มี 'last Friday'"),
             "It has no past ending, but 'last Friday' is past.",
             "nggak punya tanda lampau, padahal “last Friday” sudah lewat.",
             "ไม่มีเครื่องหมายอดีต แต่ 'last Friday' ผ่านไปแล้ว"),
            ("danceed", ED_E,
             "The verb already ends in e, so we add only -d.",
             "menambah e lagi, padahal “dance” sudah berakhiran e, jadi cukup -d.",
             "เติม e ซ้ำ ทั้งที่ 'dance' ลงท้ายด้วย e อยู่แล้ว จึงเติมแค่ -d"),
            ("dancing", ("progressive-form substitution", "bentuk -ing dipakai tanpa kata bantu untuk kejadian yang sudah selesai.", "ใช้รูป -ing โดยไม่มีกริยาช่วยกับเรื่องที่จบแล้ว"),
             "An -ing verb needs a be word, and the party is already over.",
             "bentuk -ing butuh bentuk “be”, dan pestanya sudah selesai.",
             "รูป -ing ต้องมีรูป 'be' และงานเลี้ยงก็จบไปแล้ว")]),
    dict(s="past_simple_regular_forms", id="A1-358",
         stem="Ali ___ for his math test two days ago.", opts=["studied", "studyed", "studies", "study"], ans="studied",
         why=("'Two days ago' is past, and 'study' ends in consonant + y, so y becomes i: studied.",
              "“Two days ago” menunjukkan masa lalu, dan “study” berakhiran konsonan + y, jadi y berubah jadi i. Hasilnya “studied”.",
              "'two days ago' บอกว่าเป็นอดีต และ 'study' ลงท้ายด้วยพยัญชนะ + y จึงเปลี่ยน y เป็น i เป็น 'studied'"),
         others=("'Studyed' keeps the y, 'studies' is present, and 'study' has no past ending.",
                 "“Studyed” masih menyimpan huruf y, “studies” bentuk sekarang, dan “study” nggak punya tanda lampau.",
                 "'studyed' ยังคง y ไว้ 'studies' เป็นรูปปัจจุบัน และ 'study' ไม่มีเครื่องหมายอดีต"),
         cue=("Consonant + y: study, studied; cry, cried.", "Konsonan + y: “study” jadi “studied”, “cry” jadi “cried”.", "ถ้าลงท้ายด้วยพยัญชนะ + y ให้เปลี่ยนเป็น -ied เช่น 'studied'"),
         rsn=("notice two days ago -> check the ending consonant + y -> convert y to ied",
              "perhatikan “two days ago” → cek akhiran konsonan + y → ubah y jadi -ied",
              "สังเกต 'two days ago' → ดูตัวท้ายพยัญชนะ + y → เปลี่ยน y เป็น -ied"),
         d=[("studyed", ED_KEEP_Y,
             "After a consonant + y, the y changes to i first.",
             "masih menyimpan huruf y, padahal sesudah konsonan, y harus jadi i dulu.",
             "ยังคง y ไว้ แต่หลังพยัญชนะต้องเปลี่ยน y เป็น i ก่อน"),
            ("studies", ("third-person-present form", "bentuk sekarang dipakai untuk kejadian dua hari lalu.", "ใช้รูปปัจจุบันกับเรื่องเมื่อสองวันก่อน"),
             "It is a present form, but 'two days ago' is past.",
             "bentuk sekarang, padahal “two days ago” sudah lewat.",
             "เป็นรูปปัจจุบัน แต่ 'two days ago' เป็นอดีต"),
            ("study", ("missing-past-marking", "tanda lampau hilang walaupun ada “two days ago”.", "ลืมทำเครื่องหมายอดีตทั้งที่มี 'two days ago'"),
             "It has no past ending, but this happened two days ago.",
             "nggak punya tanda lampau, padahal kejadiannya dua hari lalu.",
             "ไม่มีเครื่องหมายอดีต แต่เรื่องนี้เกิดเมื่อสองวันก่อน")]),
    dict(s="past_simple_regular_forms", id="A1-359",
         stem="Did you ___ your grandma yesterday?", opts=["visit", "visited", "visits", "visiting"], ans="visit",
         why=("'Did' already shows the past, so the verb goes back to the base form: visit.",
              "“Did” sudah menunjukkan masa lalu, jadi kata kerjanya kembali ke bentuk dasar, yaitu “visit”.",
              "'Did' บอกว่าเป็นอดีตแล้ว คำกริยาจึงกลับไปใช้รูปพื้นฐาน 'visit'"),
         others=("'Visited' marks the past twice, 'visits' has -s, and 'visiting' has -ing; after did, none of them fit.",
                 "“Visited” menandai lampau dua kali, “visits” memakai -s, dan “visiting” memakai -ing. Sesudah “did”, semuanya nggak cocok.",
                 "'visited' ทำเครื่องหมายอดีตซ้ำ 'visits' เติม -s และ 'visiting' เติม -ing หลัง 'did' จึงใช้ไม่ได้ทั้งหมด"),
         cue=("Did + base verb: Did you visit? Did she play?", "“Did” + bentuk dasar: “Did you visit?”, “Did she play?”", "หลัง 'did' ให้ใช้รูปพื้นฐาน เช่น 'Did you visit?'"),
         rsn=("notice did before the subject -> recall that did takes the base verb -> keep the verb in its base form",
              "lihat “Did” di awal kalimat → ingat “did” butuh bentuk dasar → pakai kata kerja dalam bentuk dasarnya",
              "เห็น 'Did' ต้นประโยค → นึกว่า 'did' ตามด้วยรูปพื้นฐาน → ใช้คำกริยารูปพื้นฐาน"),
         d=[("visited", ("doubles the past marking with 'did' plus -ed", "tanda lampau dipakai dua kali: “did” dan -ed.", "ทำเครื่องหมายอดีตซ้ำสองครั้ง: 'did' และ -ed"),
             "'Did' already shows the past, so -ed marks it twice.",
             "memakai -ed, padahal “did” sudah menunjukkan lampau, jadi tandanya dobel.",
             "เติม -ed แต่ 'did' บอกอดีตแล้ว จึงซ้ำสองครั้ง"),
            ("visits", S_AFTER_DID,
             "After 'did' the verb takes no -s.",
             "memakai -s, padahal sesudah “did” kata kerjanya harus bentuk dasar.",
             "เติม -s แต่หลัง 'did' คำกริยาต้องเป็นรูปพื้นฐาน"),
            ("visiting", ING_AFTER_DID,
             "After 'did' the verb takes no -ing.",
             "memakai -ing, padahal sesudah “did” kata kerjanya harus bentuk dasar.",
             "เติม -ing แต่หลัง 'did' คำกริยาต้องเป็นรูปพื้นฐาน")]),
    dict(s="past_simple_regular_forms", id="A1-360",
         stem="The shop ___ at nine o'clock yesterday.", opts=["opened", "opens", "open", "opening"], ans="opened",
         why=("'Yesterday' is past, so the regular verb 'open' takes -ed: opened.",
              "“Yesterday” menunjukkan masa lalu, jadi kata kerja beraturan “open” diberi -ed. Hasilnya “opened”.",
              "'yesterday' บอกว่าเป็นอดีต คำกริยาปกติ 'open' จึงเติม -ed เป็น 'opened'"),
         others=("'Opens' is present, 'open' has no past ending, and 'opening' needs a be word.",
                 "“Opens” bentuk sekarang, “open” nggak punya tanda lampau, dan “opening” butuh bentuk “be”.",
                 "'opens' เป็นรูปปัจจุบัน 'open' ไม่มีเครื่องหมายอดีต และ 'opening' ต้องมีรูป 'be'"),
         cue=("Yesterday: open → opened.", "Ada “yesterday”? “Open” jadi “opened”.", "ถ้ามี 'yesterday' ให้เปลี่ยน 'open' เป็น 'opened'"),
         rsn=("notice the word yesterday -> identify open as a regular verb -> add -ed",
              "perhatikan kata “yesterday” → kenali “open” sebagai kata kerja beraturan → tambah -ed",
              "สังเกตคำว่า 'yesterday' → ดูว่า 'open' เป็นกริยาปกติ → เติม -ed"),
         d=[("opens", ("third-person-present form", "bentuk sekarang dipakai untuk kejadian kemarin.", "ใช้รูปปัจจุบันกับเรื่องเมื่อวาน"),
             "It is a present form, but 'yesterday' is past.",
             "bentuk sekarang, padahal “yesterday” sudah lewat.",
             "เป็นรูปปัจจุบัน แต่ 'yesterday' เป็นอดีตไปแล้ว"),
            ("open", ("missing-past-marking", "tanda lampau hilang walaupun ada “yesterday”.", "ลืมทำเครื่องหมายอดีตทั้งที่มี 'yesterday'"),
             "It has no past ending, but this happened yesterday.",
             "nggak punya tanda lampau, padahal kejadiannya kemarin.",
             "ไม่มีเครื่องหมายอดีต แต่เรื่องนี้เกิดเมื่อวาน"),
            ("opening", ("progressive-form substitution", "bentuk -ing dipakai tanpa kata bantu untuk kejadian kemarin.", "ใช้รูป -ing โดยไม่มีกริยาช่วยกับเรื่องเมื่อวาน"),
             "An -ing verb needs a be word, and this happened once, yesterday.",
             "bentuk -ing butuh bentuk “be”, dan kejadiannya cuma sekali, kemarin.",
             "รูป -ing ต้องมีรูป 'be' และเรื่องนี้เกิดครั้งเดียวเมื่อวาน")]),
    # ---------------- 16. some / any ----------------
    dict(s="some_any_countable_uncountable", id="A1-361",
         stem="There isn't ___ bread left. Let's buy some.", opts=["any", "some", "a", "many"], ans="any",
         why=("'Isn't' makes the sentence negative, so we use 'any'. Bread cannot be counted, too.",
              "“Isn't” membuat kalimatnya negatif, jadi pakai “any”. “Bread” juga nggak bisa dihitung.",
              "'isn't' ทำให้ประโยคเป็นปฏิเสธ จึงใช้ 'any' และ 'bread' ก็นับไม่ได้ด้วย"),
         others=("'Some' is for positive sentences, 'a' is for one countable thing, and 'many' is for things you can count.",
                 "“Some” untuk kalimat positif, “a” untuk satu benda yang bisa dihitung, dan “many” untuk benda yang bisa dihitung.",
                 "'some' ใช้ในประโยคบอกเล่า 'a' ใช้กับของนับได้ชิ้นเดียว และ 'many' ใช้กับของที่นับได้"),
         cue=("Not + any: There isn't any bread.", "Kalimat dengan “not” pakai “any”: “There isn't any bread”.", "ประโยคปฏิเสธใช้คู่กับ 'any' เช่น 'There isn't any bread'"),
         rsn=("notice isn't -> identify the sentence as negative -> choose the word for negative sentences",
              "perhatikan “isn't” → pastikan kalimatnya negatif → pilih kata untuk kalimat negatif",
              "สังเกต 'isn't' → ดูว่าเป็นประโยคปฏิเสธ → เลือกคำสำหรับประโยคปฏิเสธ"),
         d=[("some", ("positive-quantifier-in-negative", "“some” dipakai di kalimat negatif.", "ใช้ 'some' ในประโยคปฏิเสธ"),
             "It is for positive sentences, but 'isn't' makes this one negative.",
             "untuk kalimat positif, padahal “isn't” membuat kalimat ini negatif.",
             "ใช้ในประโยคบอกเล่า แต่ 'isn't' ทำให้ประโยคนี้เป็นปฏิเสธ"),
            ("a", ("singular-article-with-uncountable", "kata sandang untuk satu benda dipakai untuk “bread”.", "ใช้คำนำหน้านามของสิ่งเดียวกับ 'bread'"),
             "'Bread' cannot be counted, so it never takes an article for one thing.",
             "untuk satu benda yang bisa dihitung, padahal “bread” nggak bisa dihitung.",
             "ใช้กับของนับได้ชิ้นเดียว แต่ 'bread' นับไม่ได้"),
            ("many", ("countable-quantity-substitution", "“many” dipakai untuk benda yang nggak bisa dihitung.", "ใช้ 'many' กับคำนามนับไม่ได้"),
             "It is for things you can count, but bread cannot be counted.",
             "untuk benda yang bisa dihitung, padahal “bread” nggak bisa dihitung.",
             "ใช้กับของที่นับได้ แต่ 'bread' นับไม่ได้")]),
    dict(s="some_any_countable_uncountable", id="A1-362",
         stem="I need ___ eggs for the cake.", opts=["some", "any", "an", "much"], ans="some",
         why=("It is a positive sentence with a plural noun, 'eggs', so we use 'some'.",
              "Kalimatnya positif dan “eggs” jamak, jadi pakai “some”.",
              "เป็นประโยคบอกเล่า และ 'eggs' เป็นพหูพจน์ จึงใช้ 'some'"),
         others=("'Any' is for negatives and questions, 'an' is for one thing, and 'much' is for nouns you cannot count.",
                 "“Any” untuk kalimat negatif dan tanya, “an” untuk satu benda, dan “much” untuk benda yang nggak bisa dihitung.",
                 "'any' ใช้ในประโยคปฏิเสธและคำถาม 'an' ใช้กับสิ่งเดียว และ 'much' ใช้กับคำนามนับไม่ได้"),
         cue=("Positive + plural: I need some eggs.", "Positif + jamak: “I need some eggs”.", "ประโยคบอกเล่ากับคำนามพหูพจน์ใช้ 'some' เช่น 'I need some eggs'"),
         rsn=("check if the sentence is positive -> notice the plural eggs -> choose the word for positive sentences",
              "cek kalimatnya positif atau negatif → lihat “eggs” yang jamak → pilih kata untuk kalimat positif",
              "ดูว่าเป็นประโยคบอกเล่าหรือไม่ → สังเกต 'eggs' ที่เป็นพหูพจน์ → เลือกคำสำหรับประโยคบอกเล่า"),
         d=[("any", ANY_POS,
             "It is for negatives and questions, but this sentence is positive.",
             "untuk kalimat negatif dan tanya, padahal kalimat ini positif.",
             "ใช้ในประโยคปฏิเสธและคำถาม แต่ประโยคนี้เป็นประโยคบอกเล่า"),
            ("an", ("applies a singular indefinite article to a plural noun", "kata sandang untuk satu benda dipakai sebelum benda jamak.", "ใช้คำนำหน้านามเอกพจน์หน้าคำนามพหูพจน์"),
             "It is for one thing, but 'eggs' are many.",
             "untuk satu benda, padahal “eggs” banyak.",
             "ใช้กับสิ่งเดียว แต่ 'eggs' มีหลายฟอง"),
            ("much", ("applies the uncountable-noun quantifier to a countable plural noun", "“much” dipakai untuk benda yang bisa dihitung.", "ใช้ 'much' กับคำนามนับได้"),
             "It is for nouns you cannot count, but eggs can be counted.",
             "untuk benda yang nggak bisa dihitung, padahal telur bisa dihitung.",
             "ใช้กับคำนามนับไม่ได้ แต่ไข่นับได้")]),
    dict(s="some_any_countable_uncountable", id="A1-363",
         stem="We don't have ___ tomatoes. Can you buy some?", opts=["any", "some", "a", "much"], ans="any",
         why=("'Don't' makes the sentence negative, so we use 'any' with 'tomatoes'.",
              "“Don't” membuat kalimatnya negatif, jadi pakai “any” untuk “tomatoes”.",
              "'don't' ทำให้ประโยคเป็นปฏิเสธ จึงใช้ 'any' กับ 'tomatoes'"),
         others=("'Some' is for positive sentences, 'a' is for one thing, and 'much' is for nouns you cannot count.",
                 "“Some” untuk kalimat positif, “a” untuk satu benda, dan “much” untuk benda yang nggak bisa dihitung.",
                 "'some' ใช้ในประโยคบอกเล่า 'a' ใช้กับสิ่งเดียว และ 'much' ใช้กับคำนามนับไม่ได้"),
         cue=("Don't have any…? Buy some!", "“Don't have any”, lalu “buy some”.", "ไม่มีเลยใช้ 'don't have any' แต่ซื้อมาบ้างใช้ 'buy some'"),
         rsn=("notice don't -> identify the sentence as negative -> choose the word for negative sentences",
              "perhatikan “don't” → pastikan kalimatnya negatif → pilih kata untuk kalimat negatif",
              "สังเกต 'don't' → ดูว่าเป็นประโยคปฏิเสธ → เลือกคำสำหรับประโยคปฏิเสธ"),
         d=[("some", ("positive-quantifier-in-negative", "“some” dipakai di kalimat negatif.", "ใช้ 'some' ในประโยคปฏิเสธ"),
             "It is for positive sentences, but 'don't' makes this one negative.",
             "untuk kalimat positif, padahal “don't” membuat kalimat ini negatif.",
             "ใช้ในประโยคบอกเล่า แต่ 'don't' ทำให้ประโยคนี้เป็นปฏิเสธ"),
            ("a", ("applies a singular indefinite article to a plural noun", "kata sandang untuk satu benda dipakai sebelum benda jamak.", "ใช้คำนำหน้านามเอกพจน์หน้าคำนามพหูพจน์"),
             "It is for one thing, but 'tomatoes' are many.",
             "untuk satu benda, padahal “tomatoes” banyak.",
             "ใช้กับสิ่งเดียว แต่ 'tomatoes' มีหลายลูก"),
            ("much", ("applies the uncountable-noun quantifier to a countable plural noun", "“much” dipakai untuk benda yang bisa dihitung.", "ใช้ 'much' กับคำนามนับได้"),
             "It is for nouns you cannot count, but tomatoes can be counted.",
             "untuk benda yang nggak bisa dihitung, padahal tomat bisa dihitung.",
             "ใช้กับคำนามนับไม่ได้ แต่มะเขือเทศนับได้")]),
    dict(s="some_any_countable_uncountable", id="A1-364",
         stem="Grandma cooked ___ rice for us.", opts=["some", "any", "a", "many"], ans="some",
         why=("It is a positive sentence, and 'rice' cannot be counted, so we use 'some'.",
              "Kalimatnya positif dan “rice” nggak bisa dihitung, jadi pakai “some”.",
              "เป็นประโยคบอกเล่า และ 'rice' นับไม่ได้ จึงใช้ 'some'"),
         others=("'Any' is for negatives and questions, 'a' is for one countable thing, and 'many' is for things you can count.",
                 "“Any” untuk kalimat negatif dan tanya, “a” untuk satu benda yang bisa dihitung, dan “many” untuk benda yang bisa dihitung.",
                 "'any' ใช้ในประโยคปฏิเสธและคำถาม 'a' ใช้กับของนับได้ชิ้นเดียว และ 'many' ใช้กับของที่นับได้"),
         cue=("Rice, milk, water + positive: some.", "“Rice”, “milk”, “water” di kalimat positif: “some”.", "คำนามอย่าง 'rice', 'milk', 'water' ในประโยคบอกเล่าใช้ 'some'"),
         rsn=("check if the sentence is positive -> check if rice can be counted -> choose the word for positive sentences",
              "cek kalimatnya positif atau negatif → cek “rice” bisa dihitung atau nggak → pilih kata untuk kalimat positif",
              "ดูว่าเป็นประโยคบอกเล่าหรือไม่ → ดูว่า 'rice' นับได้หรือไม่ → เลือกคำสำหรับประโยคบอกเล่า"),
         d=[("any", ANY_POS,
             "It is for negatives and questions, but Grandma really cooked rice.",
             "untuk kalimat negatif dan tanya, padahal nenek memang memasak nasi.",
             "ใช้ในประโยคปฏิเสธและคำถาม แต่คุณยายหุงข้าวจริง ๆ"),
            ("a", ("singular-article-with-uncountable", "kata sandang untuk satu benda dipakai untuk “rice”.", "ใช้คำนำหน้านามของสิ่งเดียวกับ 'rice'"),
             "'Rice' cannot be counted, so it never takes an article for one thing.",
             "untuk satu benda yang bisa dihitung, padahal “rice” nggak bisa dihitung.",
             "ใช้กับของนับได้ชิ้นเดียว แต่ 'rice' นับไม่ได้"),
            ("many", ("countable-quantity-substitution", "“many” dipakai untuk benda yang nggak bisa dihitung.", "ใช้ 'many' กับคำนามนับไม่ได้"),
             "It is for things you can count, but rice cannot be counted.",
             "untuk benda yang bisa dihitung, padahal “rice” nggak bisa dihitung.",
             "ใช้กับของที่นับได้ แต่ 'rice' นับไม่ได้")]),
    # ---------------- 17. in / on / at (time) ----------------
    dict(s="time_prepositions_in_on_at", id="A1-365",
         stem="My birthday is ___ July.", opts=["in", "on", "at", "by"], ans="in",
         why=("'July' is a month, and months take 'in'.",
              "“July” itu bulan, dan bulan pakai “in”.",
              "'July' เป็นเดือน และเดือนใช้ 'in'"),
         others=("'On' is for days, 'at' is for clock times, and 'by' means 'no later than'.",
                 "“On” untuk hari, “at” untuk jam, dan “by” artinya “paling lambat”.",
                 "'on' ใช้กับวัน 'at' ใช้กับเวลาบนนาฬิกา และ 'by' แปลว่าไม่เกิน"),
         cue=("Months are long: in July, in May.", "Bulan itu rentang panjang: “in July”, “in May”.", "เดือนเป็นช่วงเวลายาว จึงใช้ 'in July'"),
         rsn=("identify July as a month -> recall the preposition for months -> apply it before July",
              "kenali “July” sebagai bulan → ingat kata depan untuk bulan → pakai kata itu sebelum “July”",
              "ดูว่า 'July' เป็นเดือน → นึกถึงคำบุพบทของเดือน → ใช้คำนั้นหน้า 'July'"),
         d=[("on", ON_NOT_DAY("kata depan untuk hari dipakai untuk bulan.", "ใช้คำบุพบทของวันกับเดือน"),
             "It is for days and dates, but July is a whole month.",
             "untuk hari dan tanggal, padahal “July” satu bulan penuh.",
             "ใช้กับวันและวันที่ แต่ 'July' เป็นทั้งเดือน"),
            ("at", AT_MONTH,
             "It is for clock times, like seven o'clock, not for months.",
             "untuk jam, seperti pukul tujuh, bukan untuk bulan.",
             "ใช้กับเวลาบนนาฬิกา เช่น เจ็ดโมง ไม่ใช้กับเดือน"),
            ("by", BY_MONTH,
             "It means 'no later than', but a birthday simply falls in that month.",
             "artinya “paling lambat”, padahal ulang tahun memang jatuh di bulan itu.",
             "แปลว่าไม่เกิน แต่วันเกิดตรงกับเดือนนั้นพอดี")]),
    dict(s="time_prepositions_in_on_at", id="A1-366",
         stem="We have English class ___ Tuesday.", opts=["on", "in", "at", "by"], ans="on",
         why=("'Tuesday' is a day, and days take 'on'.",
              "“Tuesday” itu hari, dan hari pakai “on”.",
              "'Tuesday' เป็นวัน และวันใช้ 'on'"),
         others=("'In' is for months and years, 'at' is for clock times, and 'by' means 'no later than'.",
                 "“In” untuk bulan dan tahun, “at” untuk jam, dan “by” artinya “paling lambat”.",
                 "'in' ใช้กับเดือนและปี 'at' ใช้กับเวลาบนนาฬิกา และ 'by' แปลว่าไม่เกิน"),
         cue=("Names of days always take on: on Tuesday, on Sunday.", "Nama hari selalu pakai “on”: “on Tuesday”, “on Sunday”.", "ชื่อวันใช้ 'on' เสมอ เช่น 'on Tuesday'"),
         rsn=("identify Tuesday as a day -> recall the preposition for days -> apply it before Tuesday",
              "kenali “Tuesday” sebagai hari → ingat kata depan untuk hari → pakai kata itu sebelum “Tuesday”",
              "ดูว่า 'Tuesday' เป็นวัน → นึกถึงคำบุพบทของวัน → ใช้คำนั้นหน้า 'Tuesday'"),
         d=[("in", ("day-level expression treated as a broad time period", "kata depan untuk bulan dipakai untuk hari.", "ใช้คำบุพบทของเดือนกับวัน"),
             "It is for months and years, but Tuesday is one day.",
             "untuk bulan dan tahun, padahal “Tuesday” cuma satu hari.",
             "ใช้กับเดือนและปี แต่ 'Tuesday' เป็นวันเดียว"),
            ("at", ("day-level expression treated as clock time", "kata depan untuk jam dipakai untuk hari.", "ใช้คำบุพบทของเวลานาฬิกากับวัน"),
             "It is for clock times, but Tuesday is a day.",
             "untuk jam, padahal “Tuesday” itu hari.",
             "ใช้กับเวลาบนนาฬิกา แต่ 'Tuesday' เป็นวัน"),
            ("by", ("time preposition confused with deadline preposition", "kata depan tenggat dipakai untuk menyebut hari pelajaran.", "ใช้คำบุพบทบอกเส้นตายกับวันเรียน"),
             "It means 'no later than', but the class simply happens on that day.",
             "artinya “paling lambat”, padahal kelasnya memang berlangsung di hari itu.",
             "แปลว่าไม่เกิน แต่ชั้นเรียนมีในวันนั้นพอดี")]),
    dict(s="time_prepositions_in_on_at", id="A1-367",
         stem="The bus leaves ___ 6:15, so don't be late!", opts=["at", "on", "in", "to"], ans="at",
         why=("'6:15' is a clock time, and clock times take 'at'.",
              "“6:15” itu jam, dan jam pakai “at”.",
              "'6:15' เป็นเวลาบนนาฬิกา และเวลาบนนาฬิกาใช้ 'at'"),
         others=("'On' is for days, 'in' is for months or parts of the day, and 'to' shows direction.",
                 "“On” untuk hari, “in” untuk bulan atau bagian hari, dan “to” menunjukkan arah.",
                 "'on' ใช้กับวัน 'in' ใช้กับเดือนหรือช่วงของวัน และ 'to' บอกทิศทาง"),
         cue=("Clock times: at 6:15, at noon.", "Jam pakai “at”: “at 6:15”, “at noon”.", "เวลาบนนาฬิกาใช้ 'at' เช่น 'at 6:15'"),
         rsn=("identify 6:15 as a clock time -> recall the preposition for clock times -> apply it before 6:15",
              "kenali “6:15” sebagai jam → ingat kata depan untuk jam → pakai kata itu sebelum “6:15”",
              "ดูว่า '6:15' เป็นเวลาบนนาฬิกา → นึกถึงคำบุพบทของเวลาบนนาฬิกา → ใช้คำนั้นหน้า '6:15'"),
         d=[("on", ("clock-time expression treated as a calendar day", "kata depan untuk hari dipakai untuk jam.", "ใช้คำบุพบทของวันกับเวลานาฬิกา"),
             "It is for days and dates, not for clock times.",
             "untuk hari dan tanggal, bukan untuk jam.",
             "ใช้กับวันและวันที่ ไม่ใช่เวลาบนนาฬิกา"),
            ("in", ("clock-time expression treated as a broad time period", "kata depan untuk rentang waktu dipakai untuk jam.", "ใช้คำบุพบทของช่วงเวลายาวกับเวลานาฬิกา"),
             "It is for long periods like months, but 6:15 is an exact time.",
             "untuk rentang panjang seperti bulan, padahal “6:15” waktu yang persis.",
             "ใช้กับช่วงเวลายาวอย่างเดือน แต่ '6:15' เป็นเวลาที่แน่นอน"),
            ("to", TO_TIME("kata depan arah dipakai untuk menyebut jam.", "ใช้คำบุพบทบอกทิศทางกับเวลานาฬิกา"),
             "It shows direction, not the time the bus leaves.",
             "menunjukkan arah, bukan jam berangkat busnya.",
             "บอกทิศทาง ไม่ได้บอกเวลาที่รถออก")]),
    dict(s="time_prepositions_in_on_at", id="A1-368",
         stem="I always do my homework ___ the evening.", opts=["in", "on", "at", "to"], ans="in",
         why=("'The evening' is a part of the day, and parts of the day take 'in'.",
              "“The evening” itu bagian dari hari, dan bagian hari pakai “in”.",
              "'the evening' เป็นช่วงหนึ่งของวัน และช่วงของวันใช้ 'in'"),
         others=("'On' is for days, 'at' is for clock times (and 'at night'), and 'to' shows direction.",
                 "“On” untuk hari, “at” untuk jam (dan “at night”), dan “to” menunjukkan arah.",
                 "'on' ใช้กับวัน 'at' ใช้กับเวลาบนนาฬิกา (และ 'at night') ส่วน 'to' บอกทิศทาง"),
         cue=("Morning, afternoon, evening take in; night takes at.", "Pagi, siang, sore pakai “in”: “in the evening”. Malam pakai “at”: “at night”.", "ช่วงเวลาของวันอย่างตอนเช้าหรือตอนเย็นใช้ 'in' แต่กลางคืนใช้ 'at night'"),
         rsn=("identify the evening as a part of the day -> recall the preposition for parts of the day -> apply it before the evening",
              "kenali “the evening” sebagai bagian hari → ingat kata depan untuk bagian hari → pakai kata itu sebelum “the evening”",
              "ดูว่า 'the evening' เป็นช่วงของวัน → นึกถึงคำบุพบทของช่วงของวัน → ใช้คำนั้นหน้า 'the evening'"),
         d=[("on", ON_NOT_DAY("kata depan untuk hari dipakai untuk bagian hari.", "ใช้คำบุพบทของวันกับช่วงของวัน"),
             "It is for days like Monday, not for parts of the day.",
             "untuk nama hari seperti “Monday”, bukan untuk bagian hari.",
             "ใช้กับชื่อวันอย่าง 'Monday' ไม่ใช่ช่วงของวัน"),
            ("at", AT_EVENING,
             "It fits clock times and night, but not the evening.",
             "cocok untuk jam dan untuk malam hari, tapi bukan untuk “the evening”.",
             "ใช้กับเวลาบนนาฬิกาและตอนกลางคืน แต่ไม่ใช้กับ 'the evening'"),
            ("to", TO_TIME("kata depan arah dipakai untuk menyebut bagian hari.", "ใช้คำบุพบทบอกทิศทางกับช่วงของวัน"),
             "It shows direction, not when you do your homework.",
             "menunjukkan arah, bukan kapan kamu mengerjakan PR.",
             "บอกทิศทาง ไม่ได้บอกว่าทำการบ้านตอนไหน")]),
]
