# A1 lesson 1-6: soal latihan baru (m025-376). Format: lihat build_pack.py.
LESSONS = {
    "subject_object_pronouns_and_possessives": dict(
        obj=("Choose the pronoun form that fits its place: subject, after a verb, before a noun, or alone.",
             "Pilih bentuk kata ganti yang cocok dengan tempatnya: subjek, sesudah kata kerja, sebelum kata benda, atau berdiri sendiri.",
             "เลือกรูปคำสรรพนามให้ตรงกับตำแหน่งในประโยค ไม่ว่าจะเป็นประธาน อยู่หลังคำกริยา อยู่หน้าคำนาม หรือใช้ลำพัง"),
        mis=("Learner uses one pronoun form everywhere, the way 'dia' or 'เขา' never changes.",
             "Kamu pakai satu bentuk kata ganti di semua tempat, seperti “dia” yang nggak pernah berubah bentuk.",
             "คุณใช้คำสรรพนามรูปเดียวทุกตำแหน่ง เหมือนคำว่า 'เขา' ที่ไม่เคยเปลี่ยนรูป"),
        rule=("Subject: I, he, she. After a verb: me, him, her. Before a noun: my, his, her. Alone: mine, his, hers.",
              "Subjek: “I”, “he”, “she”. Sesudah kata kerja: “me”, “him”, “her”. Sebelum kata benda: “my”, “his”, “her”. Berdiri sendiri: “mine”, “his”, “hers”.",
              "ประธาน: 'I', 'he', 'she' หลังคำกริยา: 'me', 'him', 'her' หน้าคำนาม: 'my', 'his', 'her' ใช้ลำพัง: 'mine', 'his', 'hers'"),
        avoid=("Look at the blank's position first: before the verb, after the verb, or before a noun.",
               "Cek dulu posisi titik-titiknya: sebelum kata kerja, sesudah kata kerja, atau sebelum kata benda.",
               "ดูตำแหน่งของช่องว่างก่อน: หน้าคำกริยา หลังคำกริยา หรือหน้าคำนาม"),
    ),
    "be_subject_agreement": dict(
        obj=("Match am, is, or are to the subject.",
             "Pasangkan “am”, “is”, atau “are” dengan subjeknya.",
             "จับคู่ 'am', 'is' หรือ 'are' ให้ตรงกับประธาน"),
        mis=("Learner uses one form of 'be' for every subject, or leaves it out, because Indonesian and Thai often need no 'be'.",
             "Kamu pakai satu bentuk “be” untuk semua subjek, atau malah menghilangkannya, karena bahasa Indonesia sering nggak butuh kata itu.",
             "คุณใช้ 'be' รูปเดียวกับทุกประธาน หรือตัดทิ้งไป เพราะภาษาไทยมักไม่ต้องใช้คำนี้"),
        rule=("I am. He, she, it is. You, we, they are. One person or thing takes 'is'; two or more take 'are'.",
              "Subjek “I” pakai “am”. Subjek “he”, “she”, “it”, atau satu benda pakai “is”. Subjek “you”, “we”, “they”, atau lebih dari satu benda pakai “are”.",
              "'I' ใช้ 'am' ส่วน 'he', 'she', 'it' ใช้ 'is' และ 'you', 'we', 'they' ใช้ 'are' คนหรือสิ่งเดียวใช้ 'is' ถ้ามากกว่าหนึ่งใช้ 'are'"),
        avoid=("Find the subject first and ask: is it I, one person or thing, or more than one?",
               "Cari subjeknya dulu, lalu tanya: “I”, satu orang atau benda, atau lebih dari satu?",
               "หาประธานก่อน แล้วถามว่าเป็น 'I' เป็นคนหรือสิ่งเดียว หรือมากกว่าหนึ่ง"),
    ),
    "articles_a_an_the": dict(
        obj=("Choose a, an, or the from the first sound and from whether the thing is already known.",
             "Pilih “a”, “an”, atau “the” dari bunyi awal kata dan dari apakah bendanya sudah jelas.",
             "เลือก 'a', 'an' หรือ 'the' จากเสียงแรกของคำ และดูว่ารู้แล้วหรือยังว่าหมายถึงสิ่งไหน"),
        mis=("Learner chooses a or an by the first letter, or uses no article, since Indonesian and Thai have none.",
             "Kamu memilih “a” atau “an” dari huruf pertama, atau nggak pakai kata sandang sama sekali, karena bahasa Indonesia nggak punya.",
             "คุณเลือก 'a' หรือ 'an' จากตัวอักษรตัวแรก หรือไม่ใส่คำนำหน้านามเลย เพราะภาษาไทยไม่มี"),
        rule=("A before a consonant sound (a cat). An before a vowel sound (an apple, an hour). The when both people know which one.",
              "“A” sebelum bunyi konsonan (“a cat”). “An” sebelum bunyi vokal (“an apple”, “an hour”). “The” kalau sudah jelas yang mana.",
              "'a' ใช้หน้าเสียงพยัญชนะ ('a cat') 'an' ใช้หน้าเสียงสระ ('an apple', 'an hour') 'the' ใช้เมื่อรู้แล้วว่าหมายถึงอันไหน"),
        avoid=("Say the next word aloud and listen to its first sound, not its first letter.",
               "Ucapkan kata sesudahnya dan dengarkan bunyi awalnya, bukan huruf awalnya.",
               "ออกเสียงคำถัดไป แล้วฟังเสียงแรก ไม่ใช่ดูตัวอักษรแรก"),
    ),
    "plural_nouns_basic": dict(
        obj=("Write the plural form that fits the noun's ending.",
             "Tulis bentuk jamak yang cocok dengan akhiran kata bendanya.",
             "เขียนรูปพหูพจน์ให้ตรงกับตัวลงท้ายของคำนาม"),
        mis=("Learner keeps the singular after a number, because Indonesian and Thai nouns do not change, or adds -s to every word.",
             "Kamu membiarkan kata benda tetap tunggal sesudah angka, karena kata benda bahasa Indonesia nggak berubah, atau menambah -s ke semua kata.",
             "คุณใช้คำนามรูปเอกพจน์หลังตัวเลข เพราะคำนามภาษาไทยไม่เปลี่ยนรูป หรือเติม -s ให้ทุกคำ"),
        rule=("Most nouns add -s. Nouns ending in s, x, ch, sh add -es. Consonant + y becomes -ies. Some change: child, children; man, men.",
              "Kebanyakan kata benda tambah -s. Akhiran s, x, ch, sh tambah -es. Konsonan + y jadi -ies. Ada yang berubah: “child” jadi “children”, “man” jadi “men”.",
              "คำนามส่วนใหญ่เติม -s ลงท้ายด้วย s, x, ch, sh เติม -es พยัญชนะ + y เปลี่ยนเป็น -ies บางคำเปลี่ยนรูป: 'child' เป็น 'children', 'man' เป็น 'men'"),
        avoid=("After two, three, or many, check the last letters, then choose -s, -es, or -ies.",
               "Sesudah “two”, “three”, atau “many”, cek huruf terakhirnya, lalu pilih -s, -es, atau -ies.",
               "หลัง 'two', 'three' หรือ 'many' ให้ดูตัวอักษรท้ายคำ แล้วเลือกเติม -s, -es หรือ -ies"),
    ),
    "demonstrative_reference_distance_this_these_that_those": dict(
        obj=("Choose this, that, these, or those from number and distance.",
             "Pilih “this”, “that”, “these”, atau “those” dari jumlah dan jaraknya.",
             "เลือก 'this', 'that', 'these' หรือ 'those' จากจำนวนและระยะทาง"),
        mis=("Learner checks only near or far and forgets one or many, since 'ini' and 'itu' do not change for plurals.",
             "Kamu cuma melihat dekat atau jauh dan lupa satu atau banyak, karena “ini” dan “itu” nggak berubah untuk benda jamak.",
             "คุณดูแค่ใกล้หรือไกล แล้วลืมดูว่าหนึ่งหรือหลาย เพราะ 'นี้' กับ 'นั้น' ไม่เปลี่ยนตามจำนวน"),
        rule=("Near: this (one), these (many). Far: that (one), those (many).",
              "Dekat: “this” (satu), “these” (banyak). Jauh: “that” (satu), “those” (banyak).",
              "ใกล้: 'this' (หนึ่ง) 'these' (หลาย) ไกล: 'that' (หนึ่ง) 'those' (หลาย)"),
        avoid=("Ask two questions: near or far? One or many?",
               "Tanya dua hal: dekat atau jauh? Satu atau banyak?",
               "ถามสองข้อ: ใกล้หรือไกล? หนึ่งหรือหลาย?"),
    ),
    "possessive_adjectives": dict(
        obj=("Choose my, your, his, her, its, our, or their to show who owns the noun.",
             "Pilih “my”, “your”, “his”, “her”, “its”, “our”, atau “their” untuk menunjukkan pemilik benda.",
             "เลือก 'my', 'your', 'his', 'her', 'its', 'our' หรือ 'their' เพื่อบอกเจ้าของสิ่งนั้น"),
        mis=("Learner puts a subject or object pronoun before a noun, since 'dia' and 'mereka' do not change for owners.",
             "Kamu menaruh kata ganti subjek atau objek sebelum kata benda, karena “dia” dan “mereka” nggak berubah waktu menunjukkan pemilik.",
             "คุณวางสรรพนามรูปประธานหรือรูปกรรมไว้หน้าคำนาม เพราะ 'เขา' กับ 'พวกเขา' ไม่เปลี่ยนรูปเมื่อบอกความเป็นเจ้าของ"),
        rule=("Before a noun, use the owner form: I, my; you, your; he, his; she, her; it, its; we, our; they, their.",
              "Sebelum kata benda, pakai bentuk pemilik: “I” jadi “my”, “he” jadi “his”, “she” jadi “her”, “it” jadi “its”, “we” jadi “our”, “they” jadi “their”.",
              "หน้าคำนามใช้รูปแสดงความเป็นเจ้าของ: 'I' เป็น 'my', 'he' เป็น 'his', 'she' เป็น 'her', 'it' เป็น 'its', 'we' เป็น 'our', 'they' เป็น 'their'"),
        avoid=("Find the owner first, then check that a noun follows the blank.",
               "Cari pemiliknya dulu, lalu pastikan ada kata benda sesudah titik-titik.",
               "หาเจ้าของก่อน แล้วดูว่ามีคำนามตามหลังช่องว่าง"),
    ),
}

GENDER = ("pronoun gender does not match the person",
          "kata ganti untuk laki-laki dan perempuan tertukar.",
          "สลับสรรพนามเพศชายกับเพศหญิง")
BASE_BE = ("base form", "bentuk dasar “be” dipakai sebagai kata kerja utama.", "ใช้ 'be' รูปพื้นฐานเป็นกริยาหลัก")
FIRST_BE = ("first-person be", "bentuk “am” dipakai untuk subjek selain “I”.", "ใช้ 'am' กับประธานที่ไม่ใช่ 'I'")
QUANT = ("plural-or-uncountable quantifier", "kata jumlah untuk benda jamak dipakai untuk satu benda.", "ใช้คำบอกปริมาณของพหูพจน์กับของสิ่งเดียว")
THE_OVER = ("specific-article overuse", "“the” dipakai untuk benda yang baru pertama disebut.", "ใช้ 'the' กับสิ่งที่เพิ่งพูดถึงครั้งแรก")
AN_CONS = ("vowel-article before consonant sound", "“an” dipakai tanpa mengecek bunyi awal katanya.", "ใช้ 'an' โดยไม่ฟังเสียงแรกของคำ")
KEEP_SG = ("singular-retention", "kata benda dibiarkan tunggal sesudah kata jumlah.", "ใช้คำนามเอกพจน์หลังคำบอกจำนวน")
IES_WRONG = ("-ies ending added to a word that does not end in consonant + y",
             "akhiran -ies dipakai untuk kata yang nggak berakhiran konsonan + y.",
             "เติม -ies กับคำที่ไม่ได้ลงท้ายด้วยพยัญชนะ + y")
SUBJ = ("subject pronoun", "kata ganti subjek ditaruh sebelum kata benda.", "วางสรรพนามรูปประธานไว้หน้าคำนาม")
OBJ = ("object pronoun", "kata ganti objek ditaruh sebelum kata benda.", "วางสรรพนามรูปกรรมไว้หน้าคำนาม")
DO_BE_Q = ("do added to a present be question", "kata bantu “do” dipakai di kalimat tanya yang butuh bentuk “be”.", "ใช้ 'do' ในคำถามที่ต้องใช้ 'be'")
POSS_PRON = ("possessive pronoun", "bentuk pemilik yang berdiri sendiri ditaruh sebelum kata benda.", "วางรูปแสดงความเป็นเจ้าของแบบใช้ลำพังไว้หน้าคำนาม")

ITEMS = [
    # ---------------- 1. subject / object / possessive ----------------
    dict(s="subject_object_pronouns_and_possessives", id="A1-301",
         stem="My brother is at school. ___ is ten years old.", opts=["He", "Him", "His", "She"], ans="He",
         why=("The blank is the subject before 'is', and it means 'my brother', a boy. So: He.",
              "Titik-titiknya jadi subjek sebelum “is” dan menunjuk “my brother”, laki-laki. Jadi “He”.",
              "ช่องว่างเป็นประธานหน้า 'is' และหมายถึง 'my brother' ซึ่งเป็นผู้ชาย จึงใช้ 'He'"),
         others=("'Him' and 'His' cannot be the subject; 'She' is for a girl or a woman.",
                 "“Him” dan “His” nggak bisa jadi subjek. “She” untuk perempuan.",
                 "'Him' และ 'His' เป็นประธานไม่ได้ ส่วน 'She' ใช้กับผู้หญิง"),
         cue=("Brother is 'he'; sister is 'she'.", "“Brother” jadi “he”, “sister” jadi “she”.", "พี่ชายหรือน้องชาย ('brother') ใช้ 'he' ส่วนพี่สาวหรือน้องสาว ('sister') ใช้ 'she'"),
         rsn=("find the subject position -> identify the person -> select the subject form for a boy",
              "cari posisi subjek → lihat orangnya siapa → pilih bentuk subjek untuk laki-laki",
              "หาตำแหน่งประธาน → ดูว่าหมายถึงใคร → เลือกรูปประธานของผู้ชาย"),
         d=[("Him", ("object pronoun used as subject", "kata ganti objek dipakai sebagai subjek.", "ใช้สรรพนามรูปกรรมเป็นประธาน"),
             "'Him' is an object form; it cannot be the subject of 'is'.",
             "bentuk objek, nggak bisa jadi subjek sebelum “is”.",
             "เป็นรูปกรรม ใช้เป็นประธานหน้า 'is' ไม่ได้"),
            ("His", ("possessive form used as subject", "bentuk pemilik dipakai sebagai subjek.", "ใช้รูปแสดงความเป็นเจ้าของเป็นประธาน"),
             "It shows an owner and needs a noun after it, but here 'is' comes next.",
             "kata pemilik harus diikuti kata benda, padahal sesudahnya langsung “is”.",
             "คำบอกความเป็นเจ้าของต้องมีคำนามตามหลัง แต่ตรงนี้ตามด้วย 'is' ทันที"),
            ("She", GENDER,
             "'She' is for a girl or a woman, but a brother is a boy.",
             "untuk perempuan, padahal “brother” itu laki-laki.",
             "ใช้กับผู้หญิง แต่ 'brother' เป็นผู้ชาย")]),
    dict(s="subject_object_pronouns_and_possessives", id="A1-302",
         stem="Ms. Rina is our teacher. We like ___ very much.", opts=["her", "she", "hers", "him"], ans="her",
         why=("The blank comes after the verb 'like' and means Ms. Rina. The object form is 'her'.",
              "Titik-titiknya ada sesudah kata kerja “like” dan menunjuk “Ms. Rina”. Bentuk objeknya “her”.",
              "ช่องว่างอยู่หลังคำกริยา 'like' และหมายถึง 'Ms. Rina' รูปกรรมคือ 'her'"),
         others=("'She' is a subject form, 'hers' stands alone, and 'him' is for a man.",
                 "“She” bentuk subjek, “hers” dipakai berdiri sendiri, dan “him” untuk laki-laki.",
                 "'She' เป็นรูปประธาน 'hers' ใช้ลำพัง ส่วน 'him' ใช้กับผู้ชาย"),
         cue=("After a verb: me, him, her, us, them.", "Sesudah kata kerja: “me”, “him”, “her”, “us”, “them”.", "หลังคำกริยาใช้ 'me', 'him', 'her', 'us', 'them'"),
         rsn=("find the verb before the blank -> identify the person -> select the object form for a woman",
              "cari kata kerja sebelum titik-titik → lihat orangnya siapa → pilih bentuk objek untuk perempuan",
              "หาคำกริยาหน้าช่องว่าง → ดูว่าหมายถึงใคร → เลือกรูปกรรมของผู้หญิง"),
         d=[("she", ("subject-pronoun-in-object-position", "kata ganti subjek ditaruh di posisi objek.", "วางสรรพนามรูปประธานไว้ในตำแหน่งกรรม"),
             "'She' is a subject form; after 'like' we need an object form.",
             "bentuk subjek, padahal sesudah “like” butuh bentuk objek.",
             "เป็นรูปประธาน แต่หลัง 'like' ต้องใช้รูปกรรม"),
            ("hers", ("possessive-form-as-person-object", "bentuk pemilik dipakai untuk menggantikan orangnya.", "ใช้รูปแสดงความเป็นเจ้าของแทนตัวบุคคล"),
             "'Hers' means 'the thing that belongs to her', not the person herself.",
             "artinya “punya dia”, bukan orangnya.",
             "หมายถึง 'ของของเธอ' ไม่ใช่ตัวเธอเอง"),
            ("him", GENDER,
             "'Him' is for a man or a boy, but Ms. Rina is a woman.",
             "untuk laki-laki, padahal “Ms. Rina” perempuan.",
             "ใช้กับผู้ชาย แต่ 'Ms. Rina' เป็นผู้หญิง")]),
    dict(s="subject_object_pronouns_and_possessives", id="A1-303",
         stem="This is not my bag. ___ bag is blue.", opts=["My", "Mine", "Me", "I"], ans="My",
         why=("A noun, 'bag', comes right after the blank, so we need the owner word 'My'.",
              "Sesudah titik-titik ada kata benda “bag”, jadi pakai kata pemilik “My”.",
              "หลังช่องว่างมีคำนาม 'bag' จึงใช้คำแสดงความเป็นเจ้าของ 'My'"),
         others=("'Mine' stands alone, 'Me' is an object form, and 'I' is a subject form.",
                 "“Mine” berdiri sendiri, “Me” bentuk objek, dan “I” bentuk subjek.",
                 "'Mine' ใช้ลำพัง 'Me' เป็นรูปกรรม ส่วน 'I' เป็นรูปประธาน"),
         cue=("My always has a noun after it: my bag, my book.", "“My” selalu ditemani kata benda: “my bag”, “my book”.", "'my' ต้องมีคำนามตามหลังเสมอ: 'my bag', 'my book'"),
         rsn=("check the word after the blank -> identify it as a noun -> select the owner word that goes before a noun",
              "lihat kata sesudah titik-titik → pastikan itu kata benda → pilih kata pemilik yang ditaruh sebelum kata benda",
              "ดูคำหลังช่องว่าง → ดูว่าเป็นคำนาม → เลือกคำแสดงความเป็นเจ้าของที่วางหน้าคำนาม"),
         d=[("Mine", ("stand-alone-possessive-before-noun", "bentuk pemilik yang berdiri sendiri ditaruh sebelum kata benda.", "วางรูปแสดงความเป็นเจ้าของแบบใช้ลำพังไว้หน้าคำนาม"),
             "It stands alone at the end of a sentence, never before a noun.",
             "dipakai berdiri sendiri di akhir kalimat, bukan sebelum kata benda.",
             "ใช้ลำพังท้ายประโยค ไม่ใช้หน้าคำนาม"),
            ("Me", ("object-pronoun-substitution", "bentuk objek dipakai untuk menyebut pemilik.", "ใช้รูปกรรมแทนรูปแสดงความเป็นเจ้าของ"),
             "'Me' is an object form; it cannot show who owns the bag.",
             "bentuk objek, nggak bisa menunjukkan pemilik tas.",
             "เป็นรูปกรรม บอกเจ้าของกระเป๋าไม่ได้"),
            ("I", ("subject-pronoun-before-noun", "kata ganti subjek ditaruh sebelum kata benda.", "วางสรรพนามรูปประธานไว้หน้าคำนาม"),
             "'I' is a subject form; before a noun we need an owner word.",
             "bentuk subjek, padahal sebelum kata benda butuh kata pemilik.",
             "เป็นรูปประธาน แต่หน้าคำนามต้องใช้คำแสดงความเป็นเจ้าของ")]),
    dict(s="subject_object_pronouns_and_possessives", id="A1-304",
         stem="“Whose bag is this?” “It's ___. My name is on it.”", opts=["mine", "my", "me", "I"], ans="mine",
         why=("No noun comes after the blank, so the owner word must stand alone: mine.",
              "Nggak ada kata benda sesudah titik-titik, jadi kata pemiliknya harus berdiri sendiri, yaitu “mine”.",
              "หลังช่องว่างไม่มีคำนาม คำแสดงความเป็นเจ้าของจึงต้องใช้ลำพัง คือ 'mine'"),
         others=("'My' needs a noun after it; 'me' and 'I' do not show an owner.",
                 "“My” butuh kata benda sesudahnya. “Me” dan “I” nggak menunjukkan pemilik.",
                 "'my' ต้องมีคำนามตามหลัง ส่วน 'me' และ 'I' ไม่ได้บอกความเป็นเจ้าของ"),
         cue=("My bag, but the bag is mine.", "“My bag”, tapi “the bag is mine”.", "จำไว้: 'my' ต้องมีคำนามตาม ถ้าไม่มีคำนามให้ใช้ 'mine'"),
         rsn=("check the word after the blank -> notice there is no noun -> select the owner word that stands alone",
              "lihat sesudah titik-titik → sadari nggak ada kata benda → pilih kata pemilik yang berdiri sendiri",
              "ดูหลังช่องว่าง → สังเกตว่าไม่มีคำนาม → เลือกคำแสดงความเป็นเจ้าของที่ใช้ลำพัง"),
         d=[("my", ("possessive adjective used without a noun", "“my” dipakai tanpa kata benda sesudahnya.", "ใช้ 'my' โดยไม่มีคำนามตามหลัง"),
             "It must have a noun after it, but the sentence ends here.",
             "harus diikuti kata benda, padahal kalimatnya selesai di situ.",
             "ต้องมีคำนามตามหลัง แต่ประโยคจบตรงนี้เลย"),
            ("me", ("object-pronoun-substitution", "bentuk objek dipakai untuk menyebut pemilik.", "ใช้รูปกรรมแทนรูปแสดงความเป็นเจ้าของ"),
             "'Me' is an object form; it does not mean 'my thing'.",
             "bentuk objek, artinya bukan “punyaku”.",
             "เป็นรูปกรรม ไม่ได้แปลว่า 'ของฉัน'"),
            ("I", ("subject pronoun used to show ownership", "kata ganti subjek dipakai untuk menunjukkan pemilik.", "ใช้สรรพนามรูปประธานบอกความเป็นเจ้าของ"),
             "'I' is a subject form; it cannot show who owns the bag.",
             "bentuk subjek, nggak bisa menunjukkan pemilik tas.",
             "เป็นรูปประธาน บอกเจ้าของกระเป๋าไม่ได้")]),
    # ---------------- 2. am / is / are ----------------
    dict(s="be_subject_agreement", id="A1-305",
         stem="My cat ___ very small.", opts=["is", "are", "am", "be"], ans="is",
         why=("'My cat' is one animal, like 'it', so the verb is 'is'.",
              "“My cat” itu satu hewan, sama seperti “it”, jadi pakai “is”.",
              "'My cat' เป็นสัตว์ตัวเดียว เหมือน 'it' จึงใช้ 'is'"),
         others=("'Are' is for more than one, 'am' is only for I, and 'be' cannot follow a subject like this.",
                 "“Are” untuk lebih dari satu, “am” cuma untuk “I”, dan “be” nggak bisa langsung dipakai sesudah subjek.",
                 "'are' ใช้กับมากกว่าหนึ่ง 'am' ใช้กับ 'I' เท่านั้น และ 'be' ใช้ตามหลังประธานแบบนี้ไม่ได้"),
         cue=("One cat: is. Two cats: are.", "Satu kucing: “is”. Dua kucing: “are”.", "แมวตัวเดียวใช้ 'is' สองตัวใช้ 'are'"),
         rsn=("find the subject -> count one or more -> select the be form for one",
              "cari subjeknya → hitung satu atau lebih → pilih bentuk “be” untuk satu",
              "หาประธาน → นับว่าหนึ่งหรือมากกว่า → เลือกรูป 'be' ของสิ่งเดียว"),
         d=[("are", ("plural agreement", "bentuk jamak “are” dipakai untuk satu hewan.", "ใช้ 'are' รูปพหูพจน์กับสัตว์ตัวเดียว"),
             "'Are' is for more than one; 'my cat' is only one.",
             "untuk lebih dari satu, padahal “my cat” cuma satu.",
             "ใช้กับมากกว่าหนึ่ง แต่ 'my cat' มีตัวเดียว"),
            ("am", FIRST_BE, "'Am' goes only with 'I'.", "cuma dipakai bersama “I”.", "ใช้คู่กับ 'I' เท่านั้น"),
            ("be", BASE_BE, "'Be' is the base form; it cannot follow the subject in a present sentence.",
             "bentuk dasar, nggak bisa langsung dipakai sesudah subjek di kalimat sekarang.",
             "เป็นรูปพื้นฐาน ใช้ตามหลังประธานในประโยคปัจจุบันไม่ได้")]),
    dict(s="be_subject_agreement", id="A1-306",
         stem="Rudi and I ___ in the same class.", opts=["are", "am", "is", "be"], ans="are",
         why=("'Rudi and I' means two people, like 'we', so the verb is 'are'.",
              "“Rudi and I” artinya dua orang, sama seperti “we”, jadi pakai “are”.",
              "'Rudi and I' คือสองคน เหมือน 'we' จึงใช้ 'are'"),
         others=("'Am' fits only 'I' alone, 'is' is for one person, and 'be' is the base form.",
                 "“Am” cuma untuk “I” sendirian, “is” untuk satu orang, dan “be” bentuk dasar.",
                 "'am' ใช้กับ 'I' คนเดียวเท่านั้น 'is' ใช้กับคนเดียว และ 'be' เป็นรูปพื้นฐาน"),
         cue=("Rudi and I = we, so: we are.", "“Rudi and I” = “we”, jadi “we are”.", "รูดีกับฉันรวมกันเป็น 'we' จึงใช้ 'we are'"),
         rsn=("find the whole subject -> count the people -> select the be form for more than one",
              "cari subjek lengkapnya → hitung orangnya → pilih bentuk “be” untuk lebih dari satu",
              "หาประธานทั้งหมด → นับจำนวนคน → เลือกรูป 'be' ของมากกว่าหนึ่ง"),
         d=[("am", ("be verb matched to the nearest word instead of the whole subject",
                    "“be” dicocokkan dengan kata terdekat, bukan dengan seluruh subjek.",
                    "เลือก 'be' ตามคำที่อยู่ใกล้ที่สุด ไม่ใช่ตามประธานทั้งหมด"),
             "'Am' matches only the word 'I', but the subject is 'Rudi and I'.",
             "cuma cocok dengan kata “I”, padahal subjeknya “Rudi and I”.",
             "เข้าคู่กับคำว่า 'I' อย่างเดียว แต่ประธานคือ 'Rudi and I'"),
            ("is", ("singular be", "bentuk tunggal “is” dipakai untuk dua orang.", "ใช้ 'is' รูปเอกพจน์กับคนสองคน"),
             "'Is' is for one person, but here there are two.",
             "untuk satu orang, padahal di sini ada dua orang.",
             "ใช้กับคนเดียว แต่ในที่นี้มีสองคน"),
            ("be", BASE_BE, "'Be' is the base form and cannot follow a subject like this.",
             "bentuk dasar, nggak bisa langsung dipakai sesudah subjek.",
             "เป็นรูปพื้นฐาน ใช้ตามหลังประธานแบบนี้ไม่ได้")]),
    dict(s="be_subject_agreement", id="A1-307",
         stem="___ you ready for the test?", opts=["Are", "Is", "Am", "Do"], ans="Are",
         why=("The subject is 'you', and 'you' always takes 'are', also in questions.",
              "Subjeknya “you”, dan “you” selalu pakai “are”, termasuk di kalimat tanya.",
              "ประธานคือ 'you' และ 'you' ใช้ 'are' เสมอ รวมถึงในประโยคคำถาม"),
         others=("'Is' and 'Am' do not go with 'you', and 'Do' is for action verbs, not for 'ready'.",
                 "“Is” dan “Am” nggak cocok dengan “you”, dan “Do” untuk kata kerja aksi, bukan untuk “ready”.",
                 "'is' และ 'am' ไม่ใช้กับ 'you' ส่วน 'do' ใช้กับกริยาที่เป็นการกระทำ ไม่ใช่กับ 'ready'"),
         cue=("You are ready → Are you ready?", "“You are ready” jadi “Are you ready?”", "ในประโยคคำถาม ให้ย้าย 'are' ไปไว้หน้า 'you'"),
         rsn=("find the subject after the blank -> recall the be form for you -> place it at the start",
              "cari subjek sesudah titik-titik → ingat bentuk “be” untuk “you” → taruh bentuk itu di awal kalimat",
              "หาประธานหลังช่องว่าง → นึกถึงรูป 'be' ของ 'you' → วางรูปนั้นไว้ต้นประโยค"),
         d=[("Is", ("he-she-it be form used with you", "bentuk untuk “he”, “she”, “it” dipakai untuk “you”.", "ใช้รูป 'be' ของ 'he', 'she', 'it' กับ 'you'"),
             "'Is' is for he, she, or it, not for 'you'.",
             "untuk “he”, “she”, atau “it”, bukan untuk “you”.",
             "ใช้กับ 'he', 'she' หรือ 'it' ไม่ใช่ 'you'"),
            ("Am", FIRST_BE, "'Am' goes only with 'I'.", "cuma dipakai bersama “I”.", "ใช้คู่กับ 'I' เท่านั้น"),
            ("Do", DO_BE_Q,
             "'Do' helps action verbs; 'ready' needs a form of 'be'.",
             "dipakai untuk kata kerja aksi, padahal “ready” butuh bentuk “be”.",
             "ใช้กับคำกริยาที่เป็นการกระทำ แต่ 'ready' ต้องใช้ 'be'")]),
    dict(s="be_subject_agreement", id="A1-308",
         stem="These cookies ___ delicious!", opts=["are", "is", "am", "be"], ans="are",
         why=("'These cookies' are more than one, so the verb is 'are'.",
              "“These cookies” lebih dari satu, jadi pakai “are”.",
              "'These cookies' มีมากกว่าหนึ่ง จึงใช้ 'are'"),
         others=("'Is' is for one thing, 'am' is only for I, and 'be' is the base form.",
                 "“Is” untuk satu benda, “am” cuma untuk “I”, dan “be” bentuk dasar.",
                 "'is' ใช้กับสิ่งเดียว 'am' ใช้กับ 'I' เท่านั้น และ 'be' เป็นรูปพื้นฐาน"),
         cue=("Look for -s: cookies are, a cookie is.", "Lihat akhiran -s: “cookies are”, “a cookie is”.", "ถ้ามี -s แปลว่ามีหลายชิ้น ให้ใช้ 'are' เช่น 'cookies are'"),
         rsn=("find the subject -> check the plural -s -> select the be form for many things",
              "cari subjeknya → cek akhiran -s jamak → pilih bentuk “be” untuk banyak benda",
              "หาประธาน → ดู -s ที่บอกพหูพจน์ → เลือกรูป 'be' ของหลายสิ่ง"),
         d=[("is", ("singular be", "bentuk tunggal “is” dipakai untuk benda jamak.", "ใช้ 'is' รูปเอกพจน์กับของหลายชิ้น"),
             "'Is' is for one cookie, but 'these cookies' are many.",
             "untuk satu benda, padahal “these cookies” banyak.",
             "ใช้กับสิ่งเดียว แต่ 'these cookies' มีหลายชิ้น"),
            ("am", FIRST_BE, "'Am' goes only with 'I'.", "cuma dipakai bersama “I”.", "ใช้คู่กับ 'I' เท่านั้น"),
            ("be", BASE_BE, "'Be' is the base form and cannot follow a subject like this.",
             "bentuk dasar, nggak bisa langsung dipakai sesudah subjek.",
             "เป็นรูปพื้นฐาน ใช้ตามหลังประธานแบบนี้ไม่ได้")]),
    # ---------------- 3. a / an / the ----------------
    dict(s="articles_a_an_the", id="A1-309",
         stem="The film is ___ hour long.", opts=["an", "a", "the", "some"], ans="an",
         why=("In 'hour' the h is silent, so the word starts with a vowel sound: an hour.",
              "Huruf h di “hour” nggak dibaca, jadi bunyinya diawali vokal. Hasilnya “an hour”.",
              "ตัว h ใน 'hour' ไม่ออกเสียง คำนี้จึงขึ้นต้นด้วยเสียงสระ และได้เป็น 'an hour'"),
         others=("'A' follows the letter h, not the sound; 'the' and 'some' do not fit 'one hour long'.",
                 "“A” cuma melihat huruf h, bukan bunyinya; “the” dan “some” nggak cocok untuk lama waktu satu jam.",
                 "'a' ดูแค่ตัว h ไม่ได้ฟังเสียง ส่วน 'the' และ 'some' ไม่เข้ากับความยาวหนึ่งชั่วโมง"),
         cue=("Hour sounds like 'our': an hour.", "“Hour” dibaca seperti “our”, jadi “an hour”.", "'hour' ออกเสียงเหมือน 'our' จึงเป็น 'an hour'"),
         rsn=("check the next word -> identify its first sound -> choose the article for a vowel sound",
              "ucapkan kata sesudahnya → dengarkan bunyi awalnya → pilih kata sandang untuk bunyi vokal",
              "ออกเสียงคำถัดไป → ฟังเสียงแรก → เลือกคำนำหน้านามสำหรับเสียงสระ"),
         d=[("a", ("consonant-letter shortcut", "memilih dari huruf pertama, bukan dari bunyinya.", "เลือกจากตัวอักษรแรก ไม่ใช่จากเสียง"),
             "'A' matches the letter h, but the h in 'hour' is silent.",
             "cocok dengan huruf h, padahal h di “hour” nggak dibaca.",
             "ดูจากตัว h แต่ h ใน 'hour' ไม่ออกเสียง"),
            ("the", THE_OVER, "'The' points to a known thing; here we only say how long the film is.",
             "untuk benda yang sudah jelas, padahal kalimat ini cuma menyebut lamanya film.",
             "ใช้กับสิ่งที่รู้แล้ว แต่ประโยคนี้บอกแค่ความยาวของหนัง"),
            ("some", QUANT, "'Some' is for plural or uncountable nouns, not for one hour.",
             "untuk benda jamak atau yang nggak bisa dihitung, bukan untuk satu jam.",
             "ใช้กับคำนามพหูพจน์หรือนับไม่ได้ ไม่ใช่หนึ่งชั่วโมง")]),
    dict(s="articles_a_an_the", id="A1-310",
         stem="Sam is ___ university student.", opts=["a", "an", "the", "some"], ans="a",
         why=("'University' starts with a 'you' sound, which is a consonant sound, so we use 'a'.",
              "“University” dibaca diawali bunyi “yu”, dan itu bunyi konsonan. Jadi pakai “a”.",
              "'university' ออกเสียงขึ้นต้นว่า 'ยู' ซึ่งเป็นเสียงพยัญชนะ จึงใช้ 'a'"),
         others=("'An' follows the letter u, not the sound; 'the' and 'some' do not fit one student among many.",
                 "“An” cuma melihat huruf u, bukan bunyinya; “the” dan “some” nggak cocok untuk satu dari banyak mahasiswa.",
                 "'an' ดูแค่ตัว u ไม่ได้ฟังเสียง ส่วน 'the' และ 'some' ไม่เข้ากับนักศึกษาคนหนึ่งในหลายคน"),
         cue=("The 'you' sound takes 'a': a university, a uniform.", "Bunyi “yu” pakai “a”: “a university”, “a uniform”.", "คำที่ขึ้นต้นด้วยเสียง 'ยู' ให้ใช้ 'a' เช่น 'a university'"),
         rsn=("check the next word -> identify its first sound -> choose the article for a consonant sound",
              "ucapkan kata sesudahnya → dengarkan bunyi awalnya → pilih kata sandang untuk bunyi konsonan",
              "ออกเสียงคำถัดไป → ฟังเสียงแรก → เลือกคำนำหน้านามสำหรับเสียงพยัญชนะ"),
         d=[("an", AN_CONS, "'An' matches the letter u, but 'university' starts with a consonant sound.",
             "cocok dengan huruf u, padahal “university” diawali bunyi konsonan.",
             "ดูจากตัว u แต่ 'university' ขึ้นต้นด้วยเสียงพยัญชนะ"),
            ("the", THE_OVER, "'The' is for someone already known; Sam is just one of many students.",
             "untuk yang sudah jelas, padahal Sam cuma salah satu dari banyak mahasiswa.",
             "ใช้กับคนที่รู้แล้ว แต่ 'Sam' เป็นแค่นักศึกษาคนหนึ่งในหลายคน"),
            ("some", QUANT, "'Some' is for plural or uncountable nouns, not for one student.",
             "untuk benda jamak atau yang nggak bisa dihitung, bukan untuk satu orang.",
             "ใช้กับคำนามพหูพจน์หรือนับไม่ได้ ไม่ใช่คนเดียว")]),
    dict(s="articles_a_an_the", id="A1-311",
         stem="Close ___ door, please. It's cold.", opts=["the", "a", "an", "some"], ans="the",
         why=("We both know which door: the one in this room. So we use 'the'.",
              "Kita sama-sama tahu pintu yang mana: pintu di ruangan ini. Jadi pakai “the”.",
              "ทั้งคนพูดและคนฟังรู้ว่าประตูบานไหน คือบานในห้องนี้ จึงใช้ 'the'"),
         others=("'A' and 'an' mean 'any one', and 'some' is for more than one.",
                 "“A” dan “an” artinya “sembarang satu”, dan “some” untuk lebih dari satu.",
                 "'a' และ 'an' แปลว่า 'อันใดก็ได้หนึ่งอัน' ส่วน 'some' ใช้กับมากกว่าหนึ่ง"),
         cue=("Both people know which one? Use 'the', like the door of this room.", "Sudah jelas yang mana? Pakai “the”, seperti “the door” di ruangan ini.", "ถ้ารู้กันอยู่แล้วว่าอันไหน ให้ใช้ 'the' เช่นประตูของห้องนี้ 'the door'"),
         rsn=("identify which door is meant -> decide if both people know it -> choose the article for a known thing",
              "cari tahu pintu yang mana → putuskan sudah jelas atau belum → pilih kata sandang untuk benda yang sudah jelas",
              "ดูว่าหมายถึงประตูบานไหน → ตัดสินว่าทั้งสองคนรู้หรือไม่ → เลือกคำนำหน้านามสำหรับสิ่งที่รู้กันแล้ว"),
         d=[("a", ("first-mention article reused", "“a” dipakai untuk benda yang sudah jelas yang mana.", "ใช้ 'a' กับสิ่งที่รู้แล้วว่าหมายถึงอันไหน"),
             "'A door' means any door, but we mean the door in this room.",
             "artinya pintu mana saja, padahal yang dimaksud pintu di ruangan ini.",
             "หมายถึงประตูบานไหนก็ได้ แต่เราหมายถึงประตูในห้องนี้"),
            ("an", AN_CONS, "'An' is for a vowel sound, and 'door' starts with a consonant sound.",
             "untuk bunyi vokal, padahal “door” diawali bunyi konsonan.",
             "ใช้หน้าเสียงสระ แต่ 'door' ขึ้นต้นด้วยเสียงพยัญชนะ"),
            ("some", QUANT, "'Some' is for plural or uncountable nouns, but there is one door.",
             "untuk benda jamak atau yang nggak bisa dihitung, padahal pintunya satu.",
             "ใช้กับคำนามพหูพจน์หรือนับไม่ได้ แต่ประตูมีบานเดียว")]),
    dict(s="articles_a_an_the", id="A1-312",
         stem="My dad bought ___ new bike yesterday. The bike is red.", opts=["a", "the", "an", "some"], ans="a",
         why=("The bike is mentioned for the first time, and 'new' starts with a consonant sound: a new bike.",
              "Sepedanya baru pertama disebut, dan “new” diawali bunyi konsonan. Hasilnya “a new bike”.",
              "จักรยานเพิ่งถูกพูดถึงครั้งแรก และ 'new' ขึ้นต้นด้วยเสียงพยัญชนะ จึงได้เป็น 'a new bike'"),
         others=("'The' comes at the second mention, 'an' needs a vowel sound, and 'some' is not for one bike.",
                 "“The” dipakai saat disebut kedua kali, “an” butuh bunyi vokal, dan “some” bukan untuk satu sepeda.",
                 "'the' ใช้ตอนพูดถึงครั้งที่สอง 'an' ต้องตามด้วยเสียงสระ และ 'some' ไม่ใช้กับจักรยานคันเดียว"),
         cue=("First time: a bike. Second time: the bike.", "Pertama kali: “a bike”. Kedua kali: “the bike”.", "ครั้งแรก: 'a bike' ครั้งที่สอง: 'the bike'"),
         rsn=("check if the bike is new in the story -> identify the first sound of new -> choose the article for a first mention",
              "cek sepedanya baru disebut atau belum → dengarkan bunyi awal “new” → pilih kata sandang untuk benda yang baru disebut",
              "ดูว่าจักรยานเพิ่งถูกพูดถึงหรือไม่ → ฟังเสียงแรกของ 'new' → เลือกคำนำหน้านามสำหรับสิ่งที่เพิ่งพูดถึง"),
         d=[("the", THE_OVER, "It is for the second mention, which comes in the next sentence.",
             "baru dipakai saat sepedanya disebut kedua kali, yaitu di kalimat berikutnya.",
             "ใช้ตอนพูดถึงจักรยานครั้งที่สอง ซึ่งอยู่ในประโยคถัดไป"),
            ("an", AN_CONS, "'An' needs a vowel sound, but 'new' starts with a consonant sound.",
             "butuh bunyi vokal, padahal “new” diawali bunyi konsonan.",
             "ต้องตามด้วยเสียงสระ แต่ 'new' ขึ้นต้นด้วยเสียงพยัญชนะ"),
            ("some", QUANT, "'Some' is for plural or uncountable nouns, not for one bike.",
             "untuk benda jamak atau yang nggak bisa dihitung, bukan untuk satu sepeda.",
             "ใช้กับคำนามพหูพจน์หรือนับไม่ได้ ไม่ใช่จักรยานคันเดียว")]),
    # ---------------- 4. plural nouns ----------------
    dict(s="plural_nouns_basic", id="A1-313",
         stem="There are three ___ on the table.", opts=["boxes", "boxs", "box", "boxies"], ans="boxes",
         why=("'Box' ends in x, so the plural adds -es: boxes.",
              "“Box” berakhiran x, jadi jamaknya tambah -es. Hasilnya “boxes”.",
              "'box' ลงท้ายด้วย x พหูพจน์จึงเติม -es ได้เป็น 'boxes'"),
         others=("'Boxs' forgets the e, 'box' is singular, and 'boxies' is not a word.",
                 "“Boxs” lupa huruf e, “box” masih tunggal, dan “boxies” bukan kata.",
                 "'boxs' ขาด e 'box' ยังเป็นเอกพจน์ และ 'boxies' ไม่ใช่คำ"),
         cue=("After x, s, ch, sh: add -es. Box, boxes.", "Sesudah x, s, ch, sh: tambah -es. “Box” jadi “boxes”.", "คำที่ลงท้ายด้วย x, s, ch, sh ให้เติม -es เช่น 'boxes'"),
         rsn=("notice three before the blank -> check the last letter x -> add -es",
              "lihat “three” sebelum titik-titik → cek huruf terakhir x → tambah -es",
              "เห็น 'three' หน้าช่องว่าง → ดูตัวท้าย x → เติม -es"),
         d=[("boxs", ("simple-s-overgeneralization", "akhiran -s dipakai ke semua kata tanpa melihat huruf akhirnya.", "เติม -s ทุกคำโดยไม่ดูตัวลงท้าย"),
             "After x we add -es, not just -s.",
             "cuma diberi -s, padahal sesudah huruf x harus -es.",
             "เติมแค่ -s แต่หลัง x ต้องเติม -es"),
            ("box", KEEP_SG, "'Three' means more than one, so the noun must be plural.",
             "masih bentuk tunggal, padahal “three” berarti lebih dari satu.",
             "ยังเป็นรูปเอกพจน์ แต่ 'three' หมายถึงมากกว่าหนึ่ง"),
            ("boxies", IES_WRONG, "-ies is only for words that end in a consonant plus y.",
             "memakai -ies, padahal -ies cuma untuk kata yang berakhiran konsonan + y.",
             "เติม -ies แต่ -ies ใช้กับคำที่ลงท้ายด้วยพยัญชนะ + y เท่านั้น")]),
    dict(s="plural_nouns_basic", id="A1-314",
         stem="My aunt has two ___.", opts=["babies", "babys", "baby", "babyes"], ans="babies",
         why=("'Baby' ends in a consonant + y, so the y becomes i and we add -es: babies.",
              "“Baby” berakhiran konsonan + y, jadi y berubah jadi i lalu tambah -es. Hasilnya “babies”.",
              "'baby' ลงท้ายด้วยพยัญชนะ + y จึงเปลี่ยน y เป็น i แล้วเติม -es ได้เป็น 'babies'"),
         others=("'Babys' and 'babyes' keep the y, and 'baby' is singular.",
                 "“Babys” dan “babyes” masih menyimpan huruf y, dan “baby” masih tunggal.",
                 "'babys' และ 'babyes' ยังคง y ไว้ ส่วน 'baby' ยังเป็นเอกพจน์"),
         cue=("Consonant + y becomes -ies: baby, babies.", "Konsonan + y jadi -ies: “baby” jadi “babies”.", "พยัญชนะ + y เปลี่ยนเป็น -ies: 'baby' เป็น 'babies'"),
         rsn=("notice two before the blank -> check the ending consonant + y -> convert y to ies",
              "lihat “two” sebelum titik-titik → cek akhiran konsonan + y → ubah y jadi -ies",
              "เห็น 'two' หน้าช่องว่าง → ดูตัวท้ายพยัญชนะ + y → เปลี่ยน y เป็น -ies"),
         d=[("babys", ("simple-s-overgeneralization", "akhiran -s ditambah tanpa mengubah huruf y.", "เติม -s โดยไม่เปลี่ยน y"),
             "After a consonant + y, the y changes to i first.",
             "masih menyimpan huruf y, padahal sesudah konsonan, y harus jadi i dulu.",
             "ยังคง y ไว้ แต่หลังพยัญชนะต้องเปลี่ยน y เป็น i ก่อน"),
            ("baby", KEEP_SG, "'Two' means more than one, so the noun must be plural.",
             "masih bentuk tunggal, padahal “two” berarti lebih dari satu.",
             "ยังเป็นรูปเอกพจน์ แต่ 'two' หมายถึงมากกว่าหนึ่ง"),
            ("babyes", ("add-es-without-spelling-change", "akhiran -es ditambah tanpa mengubah y jadi i.", "เติม -es โดยไม่เปลี่ยน y เป็น i"),
             "The y must change to i before -es.",
             "lupa mengubah huruf y jadi i sebelum -es.",
             "ลืมเปลี่ยน y เป็น i ก่อนเติม -es")]),
    dict(s="plural_nouns_basic", id="A1-315",
         stem="Five ___ are playing football in the park.", opts=["men", "mans", "man", "mens"], ans="men",
         why=("'Man' is irregular: its plural is 'men', with no -s.",
              "“Man” nggak beraturan: jamaknya “men”, tanpa -s.",
              "'man' เป็นคำพิเศษ พหูพจน์คือ 'men' ไม่เติม -s"),
         others=("'Mans' and 'mens' add a wrong -s, and 'man' is singular.",
                 "“Mans” dan “mens” menambah -s yang salah, dan “man” masih tunggal.",
                 "'mans' และ 'mens' เติม -s ผิด ส่วน 'man' ยังเป็นเอกพจน์"),
         cue=("One man, two men; one woman, two women.", "Satu “man”, dua “men”; satu “woman”, dua “women”.", "หนึ่ง 'man' สอง 'men' หนึ่ง 'woman' สอง 'women'"),
         rsn=("notice five before the blank -> recall that man has a special plural -> check that no -s is added",
              "lihat “five” sebelum titik-titik → ingat “man” punya bentuk jamak khusus → pastikan nggak ada tambahan -s",
              "เห็น 'five' หน้าช่องว่าง → นึกว่า 'man' มีรูปพหูพจน์พิเศษ → ดูว่าไม่มีการเติม -s"),
         d=[("mans", ("simple-s-overgeneralization", "akhiran -s dipakai ke kata yang bentuk jamaknya khusus.", "เติม -s กับคำที่มีรูปพหูพจน์พิเศษ"),
             "'Man' does not take -s; its plural is a different word.",
             "memakai -s, padahal jamak kata ini berupa kata lain.",
             "เติม -s แต่พหูพจน์ของคำนี้เป็นอีกคำหนึ่ง"),
            ("man", KEEP_SG, "'Five' means more than one, so the noun must be plural.",
             "masih bentuk tunggal, padahal “five” berarti lebih dari satu.",
             "ยังเป็นรูปเอกพจน์ แต่ 'five' หมายถึงมากกว่าหนึ่ง"),
            ("mens", ("plural marked twice", "tanda jamak dipakai dua kali.", "ใส่เครื่องหมายพหูพจน์ซ้ำสองครั้ง"),
             "The special plural already means many; adding -s marks it twice.",
             "menambah -s ke bentuk yang sudah jamak, jadi tanda jamaknya dobel.",
             "เติม -s ให้คำที่เป็นพหูพจน์อยู่แล้ว จึงซ้ำสองครั้ง")]),
    dict(s="plural_nouns_basic", id="A1-316",
         stem="How many ___ are in your class?", opts=["students", "student", "studentes", "studenties"], ans="students",
         why=("'How many' asks about more than one, and most nouns just add -s: students.",
              "“How many” menanyakan jumlah yang lebih dari satu, dan kebanyakan kata benda cukup tambah -s. Hasilnya “students”.",
              "'How many' ถามจำนวนที่มากกว่าหนึ่ง และคำนามส่วนใหญ่แค่เติม -s จึงได้เป็น 'students'"),
         others=("'Student' is singular; 'studentes' and 'studenties' use endings this word does not take.",
                 "“Student” masih tunggal; “studentes” dan “studenties” memakai akhiran yang nggak cocok untuk kata ini.",
                 "'student' ยังเป็นเอกพจน์ ส่วน 'studentes' และ 'studenties' ใช้ตัวลงท้ายที่คำนี้ไม่ใช้"),
         cue=("How many + plural: how many students?", "“How many” + jamak: “how many students?”", "หลัง 'how many' ต้องใช้คำนามพหูพจน์เสมอ"),
         rsn=("notice how many -> check the last letter t -> add -s",
              "lihat “how many” → cek huruf terakhir t → tambah -s",
              "เห็น 'how many' → ดูตัวท้าย t → เติม -s"),
         d=[("student", KEEP_SG, "'How many' needs a plural noun.",
             "masih bentuk tunggal, padahal “how many” butuh kata benda jamak.",
             "ยังเป็นรูปเอกพจน์ แต่ 'how many' ต้องตามด้วยคำนามพหูพจน์"),
            ("studentes", ("-es added to a word that only needs -s", "akhiran -es ditambahkan ke kata yang cukup diberi -s.", "เติม -es กับคำที่แค่เติม -s ก็พอ"),
             "-es is only for words ending in s, x, ch, or sh.",
             "memakai -es, padahal -es cuma untuk kata berakhiran s, x, ch, atau sh.",
             "เติม -es แต่ -es ใช้กับคำที่ลงท้ายด้วย s, x, ch หรือ sh เท่านั้น"),
            ("studenties", IES_WRONG, "-ies is only for words that end in a consonant plus y.",
             "memakai -ies, padahal -ies cuma untuk kata yang berakhiran konsonan + y.",
             "เติม -ies แต่ -ies ใช้กับคำที่ลงท้ายด้วยพยัญชนะ + y เท่านั้น")]),
    # ---------------- 5. this / that / these / those ----------------
    dict(s="demonstrative_reference_distance_this_these_that_those", id="A1-317",
         stem="Look at ___ birds up in the sky!", opts=["those", "these", "that", "this"], ans="those",
         why=("The birds are far away in the sky, and there are many: those.",
              "Burungnya jauh di langit dan jumlahnya banyak, jadi pakai “those”.",
              "นกอยู่ไกลบนฟ้า และมีหลายตัว จึงใช้ 'those'"),
         others=("'These' is for near things, 'that' is for one far thing, and 'this' is for one near thing.",
                 "“These” untuk benda dekat, “that” untuk satu benda jauh, dan “this” untuk satu benda dekat.",
                 "'these' ใช้กับของใกล้ 'that' ใช้กับของไกลชิ้นเดียว และ 'this' ใช้กับของใกล้ชิ้นเดียว"),
         cue=("Far and many: those birds.", "Jauh dan banyak: “those birds”.", "ไกลและหลาย: 'those birds'"),
         rsn=("check near or far -> count one or many -> match the word to both answers",
              "cek dekat atau jauh → hitung satu atau banyak → pilih kata yang cocok dengan kedua jawaban tadi",
              "ดูว่าใกล้หรือไกล → นับหนึ่งหรือหลาย → เลือกคำที่ตรงกับคำตอบทั้งสองข้อ"),
         d=[("these", ("correctly matching plural but ignoring the distance cue", "sudah benar soal banyaknya, tapi lupa letaknya jauh.", "ดูจำนวนหลายชิ้นถูกแล้ว แต่ลืมดูว่าอยู่ไกล"),
             "'These' is for near things, but the birds are up in the sky.",
             "untuk benda dekat, padahal burungnya jauh di langit.",
             "ใช้กับของที่อยู่ใกล้ แต่นกอยู่ไกลบนฟ้า"),
            ("that", ("correctly matching distance but ignoring plural agreement", "sudah benar letaknya jauh, tapi lupa bendanya lebih dari satu.", "ดูระยะไกลถูกแล้ว แต่ลืมว่ามีหลายชิ้น"),
             "'That' is for one thing, but there are many birds.",
             "untuk satu benda, padahal burungnya banyak.",
             "ใช้กับสิ่งเดียว แต่มีนกหลายตัว"),
            ("this", ("using a singular near demonstrative with a plural, distant noun", "bentuk dekat untuk satu benda dipakai untuk banyak benda yang jauh.", "ใช้คำชี้แบบใกล้และเอกพจน์กับของหลายชิ้นที่อยู่ไกล"),
             "'This' is for one near thing; the birds are many and far away.",
             "untuk satu benda dekat, padahal burungnya banyak dan jauh.",
             "ใช้กับของใกล้ชิ้นเดียว แต่นกมีหลายตัวและอยู่ไกล")]),
    dict(s="demonstrative_reference_distance_this_these_that_those", id="A1-318",
         stem="___ shoes on my feet are new.", opts=["These", "Those", "This", "That"], ans="These",
         why=("The shoes are on my feet, so they are near, and there are two: these.",
              "Sepatunya ada di kakiku, jadi dekat, dan jumlahnya dua. Karena itu pakai “These”.",
              "รองเท้าอยู่ที่เท้าของฉัน จึงอยู่ใกล้ และมีสองข้าง เราจึงใช้ 'These'"),
         others=("'Those' is for far things, and 'this' and 'that' are for one thing.",
                 "“Those” untuk benda jauh, sedangkan “this” dan “that” untuk satu benda.",
                 "'those' ใช้กับของไกล ส่วน 'this' และ 'that' ใช้กับของชิ้นเดียว"),
         cue=("Near and many: these shoes.", "Dekat dan banyak: “these shoes”.", "ใกล้และหลาย: 'these shoes'"),
         rsn=("check near or far -> count one or many -> match the word to both answers",
              "cek dekat atau jauh → hitung satu atau banyak → pilih kata yang cocok dengan kedua jawaban tadi",
              "ดูว่าใกล้หรือไกล → นับหนึ่งหรือหลาย → เลือกคำที่ตรงกับคำตอบทั้งสองข้อ"),
         d=[("Those", ("correctly matching plural but ignoring the nearness cue", "sudah benar soal banyaknya, tapi lupa letaknya dekat.", "ดูจำนวนหลายชิ้นถูกแล้ว แต่ลืมดูว่าอยู่ใกล้"),
             "'Those' is for far things, but the shoes are on my feet.",
             "untuk benda jauh, padahal sepatunya ada di kakiku.",
             "ใช้กับของที่อยู่ไกล แต่รองเท้าอยู่ที่เท้าของฉัน"),
            ("This", ("correctly matching nearness but ignoring plural agreement", "sudah benar letaknya dekat, tapi lupa bendanya lebih dari satu.", "ดูระยะใกล้ถูกแล้ว แต่ลืมว่ามีหลายชิ้น"),
             "'This' is for one thing, but shoes come in a pair.",
             "untuk satu benda, padahal sepatunya sepasang.",
             "ใช้กับสิ่งเดียว แต่รองเท้ามีสองข้าง"),
            ("That", ("using a singular far demonstrative with a plural, near noun", "bentuk jauh untuk satu benda dipakai untuk banyak benda yang dekat.", "ใช้คำชี้แบบไกลและเอกพจน์กับของหลายชิ้นที่อยู่ใกล้"),
             "'That' is for one far thing; the shoes are near and there are two.",
             "untuk satu benda jauh, padahal sepatunya dekat dan ada dua.",
             "ใช้กับของไกลชิ้นเดียว แต่รองเท้าอยู่ใกล้และมีสองข้าง")]),
    dict(s="demonstrative_reference_distance_this_these_that_those", id="A1-319",
         stem="Can you see ___ house on the hill? My grandma lives there.", opts=["that", "this", "those", "these"], ans="that",
         why=("The house is far away on the hill, and there is only one: that.",
              "Rumahnya jauh di atas bukit dan cuma satu, jadi pakai “that”.",
              "บ้านอยู่ไกลบนเนินเขา และมีหลังเดียว จึงใช้ 'that'"),
         others=("'This' is for near things, and 'those' and 'these' are for many things.",
                 "“This” untuk benda dekat, sedangkan “those” dan “these” untuk banyak benda.",
                 "'this' ใช้กับของใกล้ ส่วน 'those' และ 'these' ใช้กับของหลายชิ้น"),
         cue=("Far and one: that house.", "Jauh dan satu: “that house”.", "ไกลและหนึ่ง: 'that house'"),
         rsn=("check near or far -> count one or many -> match the word to both answers",
              "cek dekat atau jauh → hitung satu atau banyak → pilih kata yang cocok dengan kedua jawaban tadi",
              "ดูว่าใกล้หรือไกล → นับหนึ่งหรือหลาย → เลือกคำที่ตรงกับคำตอบทั้งสองข้อ"),
         d=[("this", ("correctly matching singular but ignoring the distance cue", "sudah benar bendanya cuma satu, tapi lupa letaknya jauh.", "ดูถูกว่ามีชิ้นเดียว แต่ลืมดูว่าอยู่ไกล"),
             "'This' is for near things, but the house is far away on the hill.",
             "untuk benda dekat, padahal rumahnya jauh di atas bukit.",
             "ใช้กับของใกล้ แต่บ้านอยู่ไกลบนเนินเขา"),
            ("those", ("correctly matching distance but ignoring singular agreement", "sudah benar letaknya jauh, tapi lupa bendanya cuma satu.", "ดูระยะไกลถูกแล้ว แต่ลืมว่ามีชิ้นเดียว"),
             "'Those' is for many things, but there is one house.",
             "untuk banyak benda, padahal rumahnya cuma satu.",
             "ใช้กับของหลายชิ้น แต่บ้านมีหลังเดียว"),
            ("these", ("using a plural near demonstrative with a singular, distant noun", "bentuk dekat untuk banyak benda dipakai untuk satu benda yang jauh.", "ใช้คำชี้แบบใกล้และพหูพจน์กับของชิ้นเดียวที่อยู่ไกล"),
             "'These' is for many near things; the house is one and far away.",
             "untuk banyak benda dekat, padahal rumahnya satu dan jauh.",
             "ใช้กับของใกล้หลายชิ้น แต่บ้านมีหลังเดียวและอยู่ไกล")]),
    dict(s="demonstrative_reference_distance_this_these_that_those", id="A1-320",
         stem="___ pencil in my hand is broken.", opts=["This", "That", "These", "Those"], ans="This",
         why=("The pencil is in my hand, so it is near, and there is one: this.",
              "Pensilnya ada di tanganku, jadi dekat, dan cuma satu. Karena itu pakai “This”.",
              "ดินสออยู่ในมือฉัน จึงอยู่ใกล้ และมีแท่งเดียว เราจึงใช้ 'This'"),
         others=("'That' is for far things, and 'these' and 'those' are for many things.",
                 "“That” untuk benda jauh, sedangkan “these” dan “those” untuk banyak benda.",
                 "'that' ใช้กับของไกล ส่วน 'these' และ 'those' ใช้กับของหลายชิ้น"),
         cue=("Near and one: this pencil.", "Dekat dan satu: “this pencil”.", "ใกล้และหนึ่ง: 'this pencil'"),
         rsn=("check near or far -> count one or many -> match the word to both answers",
              "cek dekat atau jauh → hitung satu atau banyak → pilih kata yang cocok dengan kedua jawaban tadi",
              "ดูว่าใกล้หรือไกล → นับหนึ่งหรือหลาย → เลือกคำที่ตรงกับคำตอบทั้งสองข้อ"),
         d=[("That", ("correctly matching singular but ignoring the nearness cue", "sudah benar bendanya cuma satu, tapi lupa letaknya dekat.", "ดูถูกว่ามีชิ้นเดียว แต่ลืมดูว่าอยู่ใกล้"),
             "'That' is for far things, but the pencil is in my hand.",
             "untuk benda jauh, padahal pensilnya ada di tanganku.",
             "ใช้กับของไกล แต่ดินสออยู่ในมือฉัน"),
            ("These", ("correctly matching nearness but ignoring singular agreement", "sudah benar letaknya dekat, tapi lupa bendanya cuma satu.", "ดูระยะใกล้ถูกแล้ว แต่ลืมว่ามีชิ้นเดียว"),
             "'These' is for many things, but there is one pencil.",
             "untuk banyak benda, padahal pensilnya cuma satu.",
             "ใช้กับของหลายชิ้น แต่ดินสอมีแท่งเดียว"),
            ("Those", ("using a plural far demonstrative with a singular, near noun", "bentuk jauh untuk banyak benda dipakai untuk satu benda yang dekat.", "ใช้คำชี้แบบไกลและพหูพจน์กับของชิ้นเดียวที่อยู่ใกล้"),
             "'Those' is for many far things; the pencil is one and near.",
             "untuk banyak benda jauh, padahal pensilnya satu dan dekat.",
             "ใช้กับของไกลหลายชิ้น แต่ดินสอมีแท่งเดียวและอยู่ใกล้")]),
    # ---------------- 6. my / your / his / her / its / our / their ----------------
    dict(s="possessive_adjectives", id="A1-321",
         stem="The dog is happy. ___ tail is moving fast.", opts=["Its", "It's", "It", "Their"], ans="Its",
         why=("The owner is the dog (it), and a noun follows, so we use 'Its' with no apostrophe.",
              "Pemiliknya anjing (“it”), dan ada kata benda sesudahnya, jadi pakai “Its” tanpa apostrof.",
              "เจ้าของคือสุนัข ('it') และมีคำนามตามหลัง จึงใช้ 'Its' ที่ไม่มีอะพอสทรอฟี"),
         others=("'It's' means 'it is', 'It' is a subject form, and 'Their' is for many owners.",
                 "“It's” artinya “it is”, “It” bentuk subjek, dan “Their” untuk pemilik yang banyak.",
                 "'It's' แปลว่า 'it is' ส่วน 'It' เป็นรูปประธาน และ 'Their' ใช้กับเจ้าของหลายคน"),
         cue=("Its tail = the dog's tail. It's = it is.", "“Its tail” = ekor si anjing. “It's” = “it is”.", "'its tail' = หางของสุนัข ส่วน 'it's' = 'it is'"),
         rsn=("identify the owner -> check the noun after the blank -> select the owner form for it",
              "cari pemiliknya → cek kata benda sesudah titik-titik → pilih bentuk pemilik untuk “it”",
              "หาเจ้าของ → ดูคำนามหลังช่องว่าง → เลือกรูปแสดงความเป็นเจ้าของของ 'it'"),
         d=[("It's", ("its and it's confused", "“its” (miliknya) tertukar dengan “it's” (dia adalah).", "สับสนระหว่าง 'its' กับ 'it's'"),
             "'It's' is short for 'it is', not a word for owning.",
             "singkatan dari “it is”, bukan kata milik.",
             "เป็นคำย่อของ 'it is' ไม่ใช่คำบอกความเป็นเจ้าของ"),
            ("It", SUBJ, "'It' is a subject form; before 'tail' we need the owner form.",
             "bentuk subjek, padahal sebelum “tail” butuh bentuk pemilik.",
             "เป็นรูปประธาน แต่หน้า 'tail' ต้องใช้รูปแสดงความเป็นเจ้าของ"),
            ("Their", ("owner form does not match the number of owners", "bentuk pemilik nggak cocok dengan jumlah pemiliknya.", "รูปแสดงความเป็นเจ้าของไม่ตรงกับจำนวนเจ้าของ"),
             "'Their' is for many owners, but there is one dog.",
             "untuk pemilik yang banyak, padahal anjingnya cuma satu.",
             "ใช้กับเจ้าของหลายคน แต่สุนัขมีตัวเดียว")]),
    dict(s="possessive_adjectives", id="A1-322",
         stem="We love ___ new classroom. It is big and bright.", opts=["our", "us", "we", "ours"], ans="our",
         why=("The owners are 'we', and the noun 'classroom' follows, so we use 'our'.",
              "Pemiliknya “we”, dan sesudahnya ada kata benda “classroom”, jadi pakai “our”.",
              "เจ้าของคือ 'we' และมีคำนาม 'classroom' ตามหลัง จึงใช้ 'our'"),
         others=("'Us' is an object form, 'we' is a subject form, and 'ours' stands alone.",
                 "“Us” bentuk objek, “we” bentuk subjek, dan “ours” berdiri sendiri.",
                 "'us' เป็นรูปกรรม 'we' เป็นรูปประธาน และ 'ours' ใช้ลำพัง"),
         cue=("We becomes our: our class, our teacher.", "“We” jadi “our”: “our class”, “our teacher”.", "'we' เปลี่ยนเป็น 'our' เวลาบอกว่าเป็นของพวกเรา"),
         rsn=("identify the owner -> check the noun after the blank -> select the owner form for we",
              "cari pemiliknya → cek kata benda sesudah titik-titik → pilih bentuk pemilik untuk “we”",
              "หาเจ้าของ → ดูคำนามหลังช่องว่าง → เลือกรูปแสดงความเป็นเจ้าของของ 'we'"),
         d=[("us", OBJ, "'Us' is an object form and cannot stand before a noun.",
             "bentuk objek, nggak bisa ditaruh sebelum kata benda.",
             "เป็นรูปกรรม วางหน้าคำนามไม่ได้"),
            ("we", SUBJ, "'We' is a subject form; before a noun we need the owner form.",
             "bentuk subjek, padahal sebelum kata benda butuh bentuk pemilik.",
             "เป็นรูปประธาน แต่หน้าคำนามต้องใช้รูปแสดงความเป็นเจ้าของ"),
            ("ours", POSS_PRON, "It stands alone, never before a noun like 'classroom'.",
             "dipakai berdiri sendiri, bukan sebelum kata benda seperti “classroom”.",
             "ใช้ลำพัง ไม่ใช้หน้าคำนามอย่าง 'classroom'")]),
    dict(s="possessive_adjectives", id="A1-323",
         stem="Budi and Sari are washing ___ bikes.", opts=["their", "they", "them", "there"], ans="their",
         why=("The owners are Budi and Sari (they), so before 'bikes' we use 'their'.",
              "Pemiliknya Budi dan Sari (“they”), jadi sebelum “bikes” pakai “their”.",
              "เจ้าของคือ 'Budi' กับ 'Sari' ('they') หน้าคำว่า 'bikes' จึงใช้ 'their'"),
         others=("'They' is a subject form, 'them' is an object form, and 'there' means a place.",
                 "“They” bentuk subjek, “them” bentuk objek, dan “there” artinya “di sana”.",
                 "'they' เป็นรูปประธาน 'them' เป็นรูปกรรม และ 'there' แปลว่า 'ที่นั่น'"),
         cue=("They becomes their: their bikes.", "“They” jadi “their”: “their bikes”.", "'they' เปลี่ยนเป็น 'their' เวลาบอกว่าเป็นของพวกเขา"),
         rsn=("identify the owners -> check the noun after the blank -> select the owner form for they",
              "cari pemiliknya → cek kata benda sesudah titik-titik → pilih bentuk pemilik untuk “they”",
              "หาเจ้าของ → ดูคำนามหลังช่องว่าง → เลือกรูปแสดงความเป็นเจ้าของของ 'they'"),
         d=[("they", SUBJ, "'They' is a subject form; before 'bikes' we need the owner form.",
             "bentuk subjek, padahal sebelum “bikes” butuh bentuk pemilik.",
             "เป็นรูปประธาน แต่หน้า 'bikes' ต้องใช้รูปแสดงความเป็นเจ้าของ"),
            ("them", OBJ, "'Them' is an object form and cannot stand before a noun.",
             "bentuk objek, nggak bisa ditaruh sebelum kata benda.",
             "เป็นรูปกรรม วางหน้าคำนามไม่ได้"),
            ("there", ("their and there confused", "“their” (milik mereka) tertukar dengan “there” (di sana).", "สับสนระหว่าง 'their' กับ 'there'"),
             "'There' sounds the same but means a place, not an owner.",
             "bunyinya sama, tapi artinya tempat, bukan pemilik.",
             "ออกเสียงเหมือนกัน แต่หมายถึงสถานที่ ไม่ใช่เจ้าของ")]),
    dict(s="possessive_adjectives", id="A1-324",
         stem="Is this ___ pen, Nadia? It was on your desk.", opts=["your", "you", "yours", "you're"], ans="your",
         why=("We are asking Nadia (you), and the noun 'pen' follows, so we use the owner form for 'you'.",
              "Kita bertanya ke Nadia (“you”), dan sesudahnya ada kata benda “pen”, jadi pakai bentuk pemilik untuk “you”.",
              "เรากำลังถาม 'Nadia' ('you') และมีคำนาม 'pen' ตามหลัง จึงใช้รูปแสดงความเป็นเจ้าของของ 'you'"),
         others=("'You' is not an owner form, 'yours' stands alone, and 'you're' means 'you are'.",
                 "“You” bukan bentuk pemilik, “yours” berdiri sendiri, dan “you're” artinya “you are”.",
                 "'you' ไม่ใช่รูปแสดงความเป็นเจ้าของ 'yours' ใช้ลำพัง และ 'you're' แปลว่า 'you are'"),
         cue=("Your pen; it's yours; you're = you are.", "“Your pen”, “it's yours”, dan “you're” = “you are”.", "จำไว้ว่า 'your pen' คือปากกาของคุณ ส่วน 'you're' ย่อมาจาก 'you are'"),
         rsn=("identify the owner -> check the noun after the blank -> select the owner form for you",
              "cari pemiliknya → cek kata benda sesudah titik-titik → pilih bentuk pemilik untuk “you”",
              "หาเจ้าของ → ดูคำนามหลังช่องว่าง → เลือกรูปแสดงความเป็นเจ้าของของ 'you'"),
         d=[("you", SUBJ, "'You' does not show who owns the pen.",
             "nggak menunjukkan siapa pemilik pulpennya.",
             "ไม่ได้บอกว่าปากกาเป็นของใคร"),
            ("yours", POSS_PRON, "It stands alone at the end of a sentence, not before 'pen'.",
             "dipakai berdiri sendiri di akhir kalimat, bukan sebelum “pen”.",
             "ใช้ลำพังท้ายประโยค ไม่ใช้หน้า 'pen'"),
            ("you're", ("your and you're confused", "“your” (punyamu) tertukar dengan “you're” (kamu adalah).", "สับสนระหว่าง 'your' กับ 'you're'"),
             "'You're' is short for 'you are', not a word for owning.",
             "singkatan dari “you are”, bukan kata milik.",
             "เป็นคำย่อของ 'you are' ไม่ใช่คำบอกความเป็นเจ้าของ")]),
]
