# A1 lesson 7-12: soal latihan baru (m025-376). Format: lihat build_pack.py.
LESSONS = {
    "have_got_has_got": dict(
        obj=("Use have got or has got to say what someone owns or has.",
             "Pakai “have got” atau “has got” untuk menyebut apa yang dimiliki seseorang.",
             "ใช้ 'have got' หรือ 'has got' เพื่อบอกว่าใครมีอะไร"),
        mis=("Learner uses 'have' for every subject, or builds questions and negatives with 'do', since 'punya' and 'มี' never change.",
             "Kamu pakai “have” untuk semua subjek, atau membuat kalimat tanya dan negatifnya dengan “do”, karena kata “punya” nggak pernah berubah.",
             "คุณใช้ 'have' กับทุกประธาน หรือสร้างคำถามและประโยคปฏิเสธด้วย 'do' เพราะคำว่า 'มี' ไม่เคยเปลี่ยนรูป"),
        rule=("I, you, we, they: have got. He, she, it: has got. Question: Have or Has + subject + got? Negative: haven't got, hasn't got.",
              "“I”, “you”, “we”, “they” pakai “have got”. “He”, “she”, “it” pakai “has got”.<br><br>💡 <b>RUMUS KILAT</b>:<br>Kalau ADA kata “got” ➡️ Negatifnya pasti <b>haven't / hasn't</b>.<br>Kalau NGGAK ADA kata “got” ➡️ Negatifnya pakai <b>don't / doesn't</b>.",
              "ประธาน 'I', 'you', 'we', 'they' ใช้ 'have got' ส่วน 'he', 'she', 'it' ใช้ 'has got' ถ้าเป็นคำถามให้ย้าย 'have' หรือ 'has' ไปไว้ข้างหน้า รูปปฏิเสธคือ 'haven't got' หรือ 'hasn't got'"),
        avoid=("Find the subject first: he, she, or it takes has; the others take have. Never add do.",
               "Cari subjeknya dulu: “he”, “she”, “it” pakai “has”, yang lain pakai “have”. Jangan tambah “do”.",
               "หาประธานก่อน ถ้าเป็น 'he', 'she', 'it' ใช้ 'has' ที่เหลือใช้ 'have' และอย่าเติม 'do'"),
    ),
    "there_is_are": dict(
        obj=("Use there is for one thing and there are for many things to say that something exists.",
             "Pakai “there is” untuk satu benda dan “there are” untuk banyak benda, untuk bilang ada sesuatu di suatu tempat.",
             "ใช้ 'there is' กับสิ่งเดียว และ 'there are' กับหลายสิ่ง เพื่อบอกว่ามีอะไรอยู่ที่ไหน"),
        mis=("Learner uses 'have' to mean 'there is', copying 'ada' or 'มี', or matches the verb to 'there' instead of the noun after it.",
             "Kamu memakai “have” untuk arti “ada”, atau mencocokkan kata kerjanya dengan “there”, bukan dengan benda sesudahnya.",
             "คุณใช้ 'have' แทนความหมายว่า 'มี' หรือเลือกกริยาตามคำว่า 'there' แทนที่จะดูคำนามข้างหลัง"),
        rule=("There is + one thing, or a noun you cannot count, like milk. There are + many things. In questions, is or are moves before there.",
              "“There is” untuk satu benda atau benda yang nggak bisa dihitung, seperti “milk”. “There are” untuk banyak benda. Kalau bertanya, kata kerjanya pindah ke depan “there”.",
              "'there is' ใช้กับสิ่งเดียว หรือคำนามที่นับไม่ได้ เช่น 'milk' ส่วน 'there are' ใช้กับหลายสิ่ง ถ้าเป็นคำถามให้ย้ายกริยาไปไว้หน้า 'there'"),
        avoid=("Look at the noun after the blank: one thing or milk-type noun takes is; many things take are.",
               "Lihat benda sesudah titik-titik: satu benda atau benda seperti “milk” pakai “is”, banyak benda pakai “are”.",
               "ดูคำนามหลังช่องว่าง ถ้าเป็นสิ่งเดียวหรือคำนามแบบ 'milk' ใช้ 'is' ถ้ามีหลายสิ่งใช้ 'are'"),
    ),
    "place_prepositions_basic": dict(
        obj=("Choose in, on, under, or next to from where the thing is.",
             "Pilih “in”, “on”, “under”, atau “next to” dari letak bendanya.",
             "เลือก 'in', 'on', 'under' หรือ 'next to' จากตำแหน่งของสิ่งนั้น"),
        mis=("Learner translates every 'di' or 'ที่' with one preposition, or uses 'to' for a place where nothing moves.",
             "Kamu menerjemahkan semua “di” dengan satu kata yang sama, atau memakai “to” untuk tempat yang diam.",
             "คุณแปลคำว่า 'ที่' ด้วยคำเดียวทุกครั้ง หรือใช้ 'to' กับตำแหน่งที่ไม่มีการเคลื่อนที่"),
        rule=("In = inside (in the box). On = on a surface (on the table, on the wall). Under = below. Next to = beside.",
              "Kalau di dalam ruangan tertutup atau wilayah luas (kota, negara, wadah): Pakai “in”. Contoh: <b>in the classroom</b> (di dalam kelas), <b>in Jakarta</b>, <b>in the fridge</b> (di dalam kulkas).<br>Kalau menempel di atas permukaan, nama jalan (tanpa nomor), atau lantai gedung: Pakai “on”. Contoh: <b>on the table</b> (di atas meja), <b>on Sudirman Street</b>, <b>on the second floor</b> (di lantai dua).<br>Kalau titik lokasi tertentu, tempat kegiatan, atau alamat bernomor: Pakai “at”. Contoh: <b>at the bus stop</b> (di halte bus), <b>at school</b>, <b>at 25 Merdeka Street</b>.<br><br>💡 <b>RUMUS KILAT</b>:<br>Di dalam ruangan tertutup / area luas (kota/negara) ➡️ Pakai <b>in</b>.<br>Di atas permukaan / nama jalan tanpa nomor / lantai ➡️ Pakai <b>on</b>.<br>Titik lokasi tepat / alamat bernomor rumah ➡️ Pakai <b>at</b>.",
              "'in' แปลว่าข้างใน ('in the box') 'on' แปลว่าอยู่บนพื้นผิว ('on the table', 'on the wall') 'under' แปลว่าข้างใต้ และ 'next to' แปลว่าข้าง ๆ"),
        avoid=("Picture the scene first: inside, on a surface, below, or beside?",
               "Bayangkan dulu posisinya: di dalam, di permukaan, di bawah, atau di samping?",
               "นึกภาพก่อนว่าอยู่ข้างใน บนพื้นผิว ข้างใต้ หรือข้าง ๆ"),
    ),
    "present_simple_basics": dict(
        obj=("Use the present simple for habits: add -s or -es to the verb after he, she, or it.",
             "Pakai present simple untuk kebiasaan: tambah -s atau -es pada kata kerja sesudah “he”, “she”, atau “it”.",
             "ใช้ present simple กับกิจวัตร โดยเติม -s หรือ -es ให้คำกริยาหลัง 'he', 'she' หรือ 'it'"),
        mis=("Learner forgets the -s after he, she, or it, or adds -s after I, you, we, they, because Indonesian and Thai verbs never change.",
             "Kamu lupa -s sesudah “he”, “she”, “it”, atau malah menambah -s sesudah “I”, “you”, “we”, “they”, karena kata kerja bahasa Indonesia nggak pernah berubah.",
             "คุณลืมเติม -s หลัง 'he', 'she', 'it' หรือเติม -s หลัง 'I', 'you', 'we', 'they' เพราะคำกริยาภาษาไทยไม่เคยเปลี่ยนรูป"),
        rule=("He, she, it + verb-s (plays). After s, sh, ch, x, o add -es (watches). Consonant + y becomes -ies (cries). Other subjects use the base verb.",
              "Subjek “he”, “she”, “it” + kata kerja -s (“plays”). Akhiran s, sh, ch, x, o tambah -es (“watches”). Konsonan + y jadi -ies (“cries”). Subjek lain pakai bentuk dasar.",
              "ประธาน 'he', 'she', 'it' ให้เติม -s ที่คำกริยา ('plays') ถ้าลงท้ายด้วย s, sh, ch, x, o ให้เติม -es ('watches') ถ้าลงท้ายด้วยพยัญชนะ + y ให้เปลี่ยนเป็น -ies ('cries') ประธานอื่นใช้รูปพื้นฐาน"),
        avoid=("Find the subject first: he, she, it, or one person? Add -s. Otherwise, keep the base verb.",
               "Cari subjeknya dulu: “he”, “she”, “it”, atau satu orang? Tambah -s. Kalau bukan, pakai bentuk dasar.",
               "หาประธานก่อน ถ้าเป็น 'he', 'she', 'it' หรือคนเดียว ให้เติม -s ถ้าไม่ใช่ ให้ใช้รูปพื้นฐาน"),
    ),
    "question_words_basic": dict(
        obj=("Choose who, what, where, when, why, or how from the answer you want.",
             "Pilih “who”, “what”, “where”, “when”, “why”, atau “how” dari jawaban yang kamu cari.",
             "เลือก 'who', 'what', 'where', 'when', 'why' หรือ 'how' จากคำตอบที่ต้องการ"),
        mis=("Learner picks the first question word that comes to mind instead of looking at what the answer is about.",
             "Kamu memilih kata tanya yang pertama terlintas, bukan melihat jawabannya tentang apa.",
             "คุณเลือกคำถามคำแรกที่นึกออก แทนที่จะดูว่าคำตอบพูดถึงอะไร"),
        rule=("Who asks about a person, what about a thing, where about a place, when about a time, why about a reason, and how about a way.",
              "“Who” menanyakan orang, “what” benda, “where” tempat, “when” waktu, “why” alasan, dan “how” cara.",
              "'who' ถามถึงคน 'what' ถามถึงสิ่งของ 'where' ถามถึงสถานที่ 'when' ถามถึงเวลา 'why' ถามถึงเหตุผล และ 'how' ถามถึงวิธี"),
        avoid=("Read the answer first. Is it a person, a thing, a place, a time, a reason, or a way?",
               "Baca jawabannya dulu. Isinya orang, benda, tempat, waktu, alasan, atau cara?",
               "อ่านคำตอบก่อน แล้วถามตัวเองว่าคำตอบพูดถึงเรื่องอะไร จากนั้นจึงเลือกคำถาม"),
    ),
    "can_ability": dict(
        obj=("Use can and can't + base verb to talk about ability.",
             "Pakai “can” dan “can't” + kata kerja dasar untuk bilang bisa atau nggak bisa.",
             "ใช้ 'can' และ 'can't' + คำกริยารูปพื้นฐาน เพื่อบอกว่าทำได้หรือทำไม่ได้"),
        mis=("Learner adds to, -s, or -ing after can, or makes the negative with don't, because 'bisa' and 'ได้' never change.",
             "Kamu menambah “to”, -s, atau -ing sesudah “can”, atau membuat negatifnya dengan “don't”, karena kata “bisa” nggak pernah berubah.",
             "คุณเติม 'to', -s หรือ -ing หลัง 'can' หรือทำประโยคปฏิเสธด้วย 'don't' เพราะคำว่า 'ได้' ไม่เคยเปลี่ยนรูป"),
        rule=("Can + base verb, for every subject: I can swim, she can swim. Negative: can't swim. Question: Can you swim?",
              "Kalau bisa melakukan sesuatu: Pakai “can” + kata kerja dasar polos tanpa tambahan apa pun. Contoh: <b>My sister can swim</b> (Bukan “she cans” dan bukan “can to swim”).<br>Kalau nggak bisa melakukan sesuatu: Pakai “can't” (cannot) + kata kerja dasar. Contoh: <b>I can't ride a bike</b> (Bukan “don't can”).<br><br>💡 <b>RUMUS KILAT</b>:<br>Bisa / mampu ➡️ <b>can + kata kerja dasar</b> (polos, tanpa -s dan tanpa to).<br>Nggak bisa ➡️ <b>can't + kata kerja dasar</b>.<br>Semua subjek sama ➡️ Tetap pakai <b>can</b> tanpa ditambah akhiran apa pun.",
              "'can' + คำกริยารูปพื้นฐาน ใช้เหมือนกันกับทุกประธาน เช่น 'I can swim' และ 'she can swim' รูปปฏิเสธคือ 'can't swim' ถ้าจะถามใช้ 'Can you swim?'"),
        avoid=("After can or can't, write the verb exactly as in the dictionary: no to, no -s, no -ing.",
               "Sesudah “can” atau “can't”, tulis kata kerjanya persis seperti di kamus: tanpa “to”, tanpa -s, tanpa -ing.",
               "หลัง 'can' หรือ 'can't' ให้เขียนคำกริยาแบบในพจนานุกรม ไม่มี 'to' ไม่มี -s และไม่มี -ing"),
    ),
}

# ---- label bersama ----
HAS_PL = ("he-she-it have form used with a plural subject",
          "bentuk “has” untuk “he”, “she”, “it” dipakai untuk subjek jamak.",
          "ใช้ 'has' ของ 'he', 'she', 'it' กับประธานพหูพจน์")
HAS_I = ("he-she-it have form used with I",
         "bentuk “has” untuk “he”, “she”, “it” dipakai bersama “I”.",
         "ใช้ 'has' ซึ่งเป็นรูปของบุรุษที่สามกับ 'I'")
HAVE_EXIST = ("have used to say that something exists",
              "“have” dipakai untuk bilang ada sesuatu di suatu tempat, seperti kata “ada”.",
              "ใช้ 'have' เพื่อบอกว่ามีของอยู่ที่ไหน เหมือนคำว่า 'มี'")
PL_UNCOUNT = ("plural be used with an uncountable noun",
              "bentuk jamak dipakai untuk benda yang nggak bisa dihitung.",
              "ใช้รูปพหูพจน์กับคำนามนับไม่ได้")
DO_BE_Q = ("do added to a present be question",
           "kata bantu “do” dipakai di kalimat tanya yang butuh bentuk “be”.",
           "ใช้ 'do' ในคำถามที่ต้องใช้ 'be'")
ON_INSIDE = ("surface preposition used for something inside",
             "kata untuk “di atas permukaan” dipakai untuk benda yang ada di dalam.",
             "ใช้คำที่แปลว่าบนพื้นผิวกับของที่อยู่ข้างใน")
UNDER_INSIDE = ("below preposition used for something inside",
                "kata untuk “di bawah” dipakai untuk benda yang ada di dalam.",
                "ใช้คำที่แปลว่าข้างใต้กับของที่อยู่ข้างใน")
ON_BESIDE = ("surface preposition used for a position beside",
             "kata untuk “di atas permukaan” dipakai untuk posisi di samping.",
             "ใช้คำที่แปลว่าบนพื้นผิวกับตำแหน่งข้าง ๆ")
IN_BESIDE = ("inside preposition used for a position beside",
             "kata untuk “di dalam” dipakai untuk posisi di samping.",
             "ใช้คำที่แปลว่าข้างในกับตำแหน่งข้าง ๆ")
UNDER_BESIDE = ("below preposition used for a position beside",
                "kata untuk “di bawah” dipakai untuk posisi di samping.",
                "ใช้คำที่แปลว่าข้างใต้กับตำแหน่งข้าง ๆ")
UNDER_SURFACE = ("below preposition used for something on a surface",
                 "kata untuk “di bawah” dipakai untuk benda yang menempel di permukaan.",
                 "ใช้คำที่แปลว่าข้างใต้กับของที่ติดอยู่บนพื้นผิว")
S_NOT_ES = ("-s added where the verb needs -es",
            "akhiran -s ditambahkan, padahal kata kerja ini butuh -es.",
            "เติม -s ทั้งที่คำกริยานี้ต้องเติม -es")
S_KEEP_Y = ("-s added to a consonant + y verb without changing y",
            "kata kerja berakhiran konsonan + y diberi -s tanpa mengubah y jadi i.",
            "เติม -s กับกริยาที่ลงท้ายด้วยพยัญชนะ + y โดยไม่เปลี่ยน y เป็น i")
PROG_PL_HABIT = ("singular progressive used for a plural habit",
                 "bentuk yang sedang berlangsung dipakai untuk kebiasaan, dan bentuk satu orangnya pun nggak cocok.",
                 "ใช้รูปกำลังทำกับกิจวัตร และยังใช้รูปของคนเดียวกับหลายคนด้วย")


def QW(word, asks, answer_id, answer_th):
    """Label kata tanya: satu label per kata tanya yang salah pilih, teks per-soal menyebut jawabannya."""
    base = {
        'what': ("what used when the answer is not a thing", "kata tanya untuk benda dipakai, padahal jawabannya bukan benda.", "ใช้คำถามเรื่องสิ่งของ ทั้งที่คำตอบไม่ใช่สิ่งของ", "benda", "สิ่งของ"),
        'who': ("who used when the answer is not a person", "kata tanya untuk orang dipakai, padahal jawabannya bukan orang.", "ใช้คำถามเรื่องคน ทั้งที่คำตอบไม่ใช่คน", "orang", "คน"),
        'where': ("where used when the answer is not a place", "kata tanya untuk tempat dipakai, padahal jawabannya bukan tempat.", "ใช้คำถามเรื่องสถานที่ ทั้งที่คำตอบไม่ใช่สถานที่", "tempat", "สถานที่"),
        'when': ("when used when the answer is not a time", "kata tanya untuk waktu dipakai, padahal jawabannya bukan waktu.", "ใช้คำถามเรื่องเวลา ทั้งที่คำตอบไม่ใช่เวลา", "waktu", "เวลา"),
    }[word]
    return (base[0], base[1], base[2],
            f"kata tanya untuk {base[3]} dipakai untuk menanyakan {answer_id}.",
            f"ใช้คำถามเรื่อง{base[4]}มาถามถึง{answer_th}")


HE_BE_YOU = ("he-she-it be form used with you", "bentuk untuk “he”, “she”, “it” dipakai untuk “you”.", "ใช้รูป 'be' ของ 'he', 'she', 'it' กับ 'you'")
BE_VERB = "be verb"            # DIAG: kata kerja 'be' yang nggak menyatakan makna kemampuan
DO_AUX = "do auxiliary"        # DIAG: kata bantu 'do' yang nggak menyatakan makna kemampuan

ITEMS = [
    # ---------------- 7. have got / has got ----------------
    dict(s="have_got_has_got", id="A1-325",
         stem="My grandparents ___ got a big garden.", opts=["have", "has", "are", "do"], ans="have",
         why=("'My grandparents' are more than one person, like 'they', so we use 'have got'.",
              "“My grandparents” itu lebih dari satu orang, sama seperti “they”, jadi pakai “have got”.",
              "ปู่ย่าตายาย ('my grandparents') มีมากกว่าหนึ่งคน เหมือน 'they' จึงใช้ 'have got'"),
         others=("'Has' is only for he, she, or it; 'are' and 'do' cannot go with 'got' to show owning.",
                 "“Has” cuma untuk “he”, “she”, atau “it”. “Are” dan “do” nggak bisa dipasangkan dengan “got” untuk menyatakan punya.",
                 "'has' ใช้กับ 'he', 'she', 'it' เท่านั้น ส่วน 'are' และ 'do' ใช้คู่กับ 'got' เพื่อบอกความเป็นเจ้าของไม่ได้"),
         cue=("They have got; he has got.", "“They have got”, tapi “he has got”.", "จำไว้ว่าพวกเขาใช้ 'they have got' แต่เขาคนเดียวใช้ 'he has got'"),
         rsn=("find the subject -> count one or more people -> choose the form for more than one person",
              "cari subjeknya → hitung satu orang atau lebih → pilih bentuk untuk lebih dari satu orang",
              "หาประธาน → นับว่าคนเดียวหรือหลายคน → เลือกรูปของคนมากกว่าหนึ่งคน"),
         d=[("has", HAS_PL,
             "It is only for he, she, or it, but 'my grandparents' means 'they'.",
             "cuma untuk “he”, “she”, atau “it”, padahal “my grandparents” sama dengan “they”.",
             "ใช้กับ 'he', 'she', 'it' เท่านั้น แต่ปู่ย่าตายายมีหลายคน เท่ากับ 'they'"),
            ("are", ("be-verb substitution", "bentuk “be” dipakai untuk menyatakan punya.", "เอา 'be' มาใช้บอกความเป็นเจ้าของ"),
             "It describes a state, not owning, so it cannot go with 'got'.",
             "menyatakan keadaan, bukan punya, jadi nggak bisa dipasangkan dengan “got”.",
             "บอกสภาพ ไม่ได้บอกความเป็นเจ้าของ จึงใช้คู่กับ 'got' ไม่ได้"),
            ("do", ("double-auxiliary construction", "kata bantu “do” dipasangkan dengan “got”.", "เอา 'do' มาใช้คู่กับ 'got'"),
             "It never goes with 'got'.",
             "nggak pernah dipasangkan dengan “got”.",
             "ไม่เคยใช้คู่กับ 'got' เลย")]),
    dict(s="have_got_has_got", id="A1-326",
         stem="Dimas ___ got a bad cold today.", opts=["has", "have", "is", "does"], ans="has",
         why=("'Dimas' is one person, like 'he', so we use 'has got'.",
              "“Dimas” itu satu orang, sama seperti “he”, jadi pakai “has got”.",
              "'Dimas' เป็นคนเดียว เหมือน 'he' จึงใช้ 'has got'"),
         others=("'Have' is for I, you, we, or they; 'is' and 'does' cannot go with 'got' to show having.",
                 "“Have” untuk “I”, “you”, “we”, atau “they”. “Is” dan “does” nggak bisa dipasangkan dengan “got” untuk menyatakan punya.",
                 "'have' ใช้กับ 'I', 'you', 'we', 'they' ส่วน 'is' และ 'does' ใช้คู่กับ 'got' เพื่อบอกว่ามีไม่ได้"),
         cue=("He, she, it: has got a cold.", "“He”, “she”, “it”: “has got a cold”.", "เขาหรือเธอคนเดียวเป็นหวัด ใช้ 'has got a cold'"),
         rsn=("find the subject -> identify it as one person -> choose the form for one person",
              "cari subjeknya → pastikan itu satu orang → pilih bentuk untuk satu orang",
              "หาประธาน → ดูว่าเป็นคนเดียว → เลือกรูปของคนคนเดียว"),
         d=[("have", ("plural-form transfer", "bentuk “have” dipakai untuk satu orang.", "ใช้ 'have' กับคนเดียว"),
             "It is for I, you, we, or they, but Dimas is one person.",
             "untuk “I”, “you”, “we”, atau “they”, padahal Dimas cuma satu orang.",
             "ใช้กับ 'I', 'you', 'we', 'they' แต่ 'Dimas' เป็นคนเดียว"),
            ("is", ("be-verb substitution", "bentuk “be” dipakai untuk menyatakan punya.", "เอา 'be' มาใช้บอกความเป็นเจ้าของ"),
             "It describes a state, not having, so it cannot go with 'got'.",
             "menyatakan keadaan, bukan punya, jadi nggak bisa dipasangkan dengan “got”.",
             "บอกสภาพ ไม่ได้บอกว่ามี จึงใช้คู่กับ 'got' ไม่ได้"),
            ("does", ("double-auxiliary construction", "kata bantu “does” dipasangkan dengan “got”.", "เอา 'does' มาใช้คู่กับ 'got'"),
             "It never goes with 'got' in a statement.",
             "nggak pernah dipasangkan dengan “got” di kalimat biasa.",
             "ไม่เคยใช้คู่กับ 'got' ในประโยคบอกเล่า")]),
    dict(s="have_got_has_got", id="A1-327",
         stem="“___ your brother got a phone?” “Yes, he has.”", opts=["Has", "Have", "Does", "Is"], ans="Has",
         why=("The subject 'your brother' is he, so the question starts with 'Has'. The answer 'Yes, he has' shows it too.",
              "Subjeknya “your brother”, yaitu “he”, jadi kalimat tanyanya diawali “Has”. Jawaban “Yes, he has” juga menunjukkannya.",
              "ประธานคือ 'your brother' ซึ่งก็คือ 'he' คำถามจึงขึ้นต้นด้วย 'Has' และคำตอบ 'Yes, he has' ก็บอกเช่นกัน"),
         others=("'Have' is for you, we, or they; 'Does' and 'Is' do not make have got questions.",
                 "“Have” untuk “you”, “we”, atau “they”. “Does” dan “Is” nggak dipakai di kalimat tanya “have got”.",
                 "'have' ใช้กับ 'you', 'we', 'they' ส่วน 'does' และ 'is' ไม่ใช้ในคำถามแบบ 'have got'"),
         cue=("He has got → Has he got?", "“He has got” jadi “Has he got?”", "เปลี่ยนเป็นคำถามโดยย้าย 'has' ไปไว้หน้า: 'Has he got?'"),
         rsn=("find the subject after the blank -> identify it as he -> place the form for he before the subject",
              "cari subjek sesudah titik-titik → pastikan itu “he” → taruh bentuk untuk “he” di depan subjek",
              "หาประธานหลังช่องว่าง → ดูว่าเป็น 'he' → วางรูปของ 'he' ไว้หน้าประธาน"),
         d=[("Have", ("plural-form transfer", "bentuk “have” dipakai untuk satu orang.", "ใช้ 'have' กับคนเดียว"),
             "It is for you, we, or they, but 'your brother' is he.",
             "untuk “you”, “we”, atau “they”, padahal “your brother” itu “he”.",
             "ใช้กับ 'you', 'we', 'they' แต่พี่ชายหรือน้องชายของคุณมีคนเดียว คือ 'he'"),
            ("Does", ("do-support with have got", "“does” ditambahkan ke kalimat tanya “have got”.", "เติม 'does' ในคำถามแบบ 'have got'"),
             "Questions with 'got' do not use it.",
             "nggak dipakai di kalimat tanya yang memakai “got”.",
             "ไม่ใช้ในคำถามที่มีคำว่า 'got'"),
            ("Is", ("be-verb substitution", "bentuk “be” dipakai untuk bertanya soal punya.", "เอา 'be' มาใช้ถามเรื่องความเป็นเจ้าของ"),
             "A be word cannot ask about having with 'got'.",
             "termasuk bentuk “be”, jadi nggak bisa dipakai untuk bertanya soal punya dengan “got”.",
             "เป็นรูป 'be' จึงใช้ถามเรื่องการมีคู่กับ 'got' ไม่ได้")]),
    dict(s="have_got_has_got", id="A1-328",
         stem="Sorry, I ___ got any money with me today.", opts=["haven't", "hasn't", "don't", "am not"], ans="haven't",
         why=("The subject is 'I', and the negative of 'have got' is 'haven't got'.",
              "Subjeknya “I”, dan bentuk negatif “have got” adalah “haven't got”.",
              "ประธานคือ 'I' และรูปปฏิเสธของ 'have got' คือ 'haven't got'"),
         others=("'Hasn't' is for he, she, or it; 'don't' and 'am not' do not go with 'got'.",
                 "“Hasn't” untuk “he”, “she”, atau “it”. “Don't” dan “am not” nggak dipasangkan dengan “got”.",
                 "'hasn't' ใช้กับ 'he', 'she', 'it' ส่วน 'don't' และ 'am not' ไม่ใช้คู่กับ 'got'"),
         cue=("I haven't got; she hasn't got.", "“I haven't got”, tapi “she hasn't got”.", "ฉันใช้ 'I haven't got' แต่เธอคนเดียวใช้ 'she hasn't got'"),
         rsn=("find the subject -> identify it as I -> add not to the form for I",
              "cari subjeknya → pastikan itu “I” → tambahkan “not” pada bentuk untuk “I”",
              "หาประธาน → ดูว่าเป็น 'I' → เติม 'not' ให้รูปของ 'I'"),
         d=[("hasn't", HAS_I,
             "It is for he, she, or it, not for I.",
             "untuk “he”, “she”, atau “it”, bukan untuk “I”.",
             "ใช้กับ 'he', 'she', 'it' ไม่ใช่กับ 'I'"),
            ("don't", ("do-support with have got", "“don't” dipakai untuk membuat negatif “have got”.", "ใช้ 'don't' ทำประโยคปฏิเสธของ 'have got'"),
             "It does not go with 'got'; with 'got', the negative is made from have.",
             "nggak dipasangkan dengan “got”. Kalau ada “got”, negatifnya dibuat dari “have”.",
             "ไม่ใช้คู่กับ 'got' ถ้ามี 'got' ประโยคปฏิเสธต้องสร้างจาก 'have'"),
            ("am not", ("be-verb substitution", "bentuk “be” dipakai untuk menyatakan nggak punya.", "เอา 'be' มาใช้บอกว่าไม่มี"),
             "It describes a state, so it cannot go with 'got' to say you have nothing.",
             "menyatakan keadaan, jadi nggak bisa dipasangkan dengan “got” untuk bilang nggak punya.",
             "บอกสภาพ จึงใช้คู่กับ 'got' เพื่อบอกว่าไม่มีไม่ได้")]),
    # ---------------- 8. there is / there are ----------------
    dict(s="there_is_are", id="A1-329",
         stem="There ___ some milk in the fridge.", opts=["is", "are", "have", "be"], ans="is",
         why=("'Milk' cannot be counted, so it takes 'is', even with 'some'.",
              "“Milk” nggak bisa dihitung, jadi pakai “is”, walaupun ada “some”.",
              "'milk' นับไม่ได้ จึงใช้ 'is' ถึงจะมี 'some' ก็ตาม"),
         others=("'Are' is for many countable things, 'have' does not mean 'there is', and 'be' is the base form.",
                 "“Are” untuk banyak benda yang bisa dihitung, “have” bukan arti “ada” di sini, dan “be” bentuk dasar.",
                 "'are' ใช้กับของนับได้หลายชิ้น 'have' ไม่ได้แปลว่ามีอยู่ในที่นี้ และ 'be' เป็นรูปพื้นฐาน"),
         cue=("Milk, water, rice: there is.", "“Milk”, “water”, “rice” nggak bisa dihitung, jadi “there is”.", "ของที่นับไม่ได้อย่างนม น้ำ หรือข้าว ใช้ 'there is'"),
         rsn=("find the noun after the blank -> check if it can be counted -> choose the form for a noun you cannot count",
              "cari benda sesudah titik-titik → cek bisa dihitung atau nggak → pilih bentuk untuk benda yang nggak bisa dihitung",
              "หาคำนามหลังช่องว่าง → ดูว่านับได้หรือไม่ → เลือกรูปสำหรับคำนามนับไม่ได้"),
         d=[("are", PL_UNCOUNT,
             "It is for many countable things, but milk cannot be counted.",
             "untuk banyak benda yang bisa dihitung, padahal “milk” nggak bisa dihitung.",
             "ใช้กับของนับได้หลายชิ้น แต่ 'milk' นับไม่ได้"),
            ("have", HAVE_EXIST,
             "It is not how English says that something exists; use there + a be word.",
             "bukan cara bilang “ada” dalam bahasa Inggris. Untuk itu, pakai “there” + bentuk “be”.",
             "ไม่ใช่วิธีบอกว่ามีของอยู่ในภาษาอังกฤษ ให้ใช้ 'there' + รูป 'be'"),
            ("be", ("base form", "bentuk dasar “be” dipakai sesudah “there”.", "ใช้ 'be' รูปพื้นฐานหลัง 'there'"),
             "It is the base form; after 'there' we need a form that matches the noun.",
             "bentuk dasar, padahal sesudah “there” butuh bentuk yang cocok dengan bendanya.",
             "เป็นรูปพื้นฐาน แต่หลัง 'there' ต้องใช้รูปที่เข้ากับคำนาม")]),
    dict(s="there_is_are", id="A1-330",
         stem="There ___ five people in my family.", opts=["are", "is", "have", "am"], ans="are",
         why=("'Five people' are more than one, so we use 'are'.",
              "“Five people” lebih dari satu, jadi pakai “are”.",
              "'five people' มีมากกว่าหนึ่ง จึงใช้ 'are'"),
         others=("'Is' is for one thing, 'have' does not mean 'there is' here, and 'am' is only for I.",
                 "“Is” untuk satu benda, “have” bukan arti “ada” di sini, dan “am” cuma untuk “I”.",
                 "'is' ใช้กับสิ่งเดียว 'have' ไม่ได้แปลว่ามีอยู่ในที่นี้ และ 'am' ใช้กับ 'I' เท่านั้น"),
         cue=("Five people, many things: there are.", "Lima orang atau banyak benda: “there are”.", "ห้าคนหรือของหลายชิ้น ใช้ 'there are'"),
         rsn=("find the noun after the blank -> count one or many -> choose the form for many",
              "cari benda sesudah titik-titik → hitung satu atau banyak → pilih bentuk untuk banyak benda",
              "หาคำนามหลังช่องว่าง → นับว่าหนึ่งหรือหลาย → เลือกรูปสำหรับหลายสิ่ง"),
         d=[("is", ("singular agreement", "bentuk tunggal dipakai untuk banyak orang.", "ใช้รูปเอกพจน์กับหลายคน"),
             "It is for one thing, but there are five people.",
             "untuk satu benda, padahal orangnya lima.",
             "ใช้กับสิ่งเดียว แต่มีห้าคน"),
            ("have", HAVE_EXIST,
             "It means 'own', not 'exist'; 'ada' here is there + a be word.",
             "artinya “punya”, bukan “ada”. Arti “ada” di sini dibentuk dengan “there” + bentuk “be”.",
             "แปลว่าเป็นเจ้าของ ไม่ได้แปลว่ามีอยู่ ความหมายแบบนี้ต้องใช้ 'there' + รูป 'be'"),
            ("am", ("first-person be", "bentuk “am” dipakai sesudah “there”.", "ใช้ 'am' หลัง 'there'"),
             "It goes only with 'I'.",
             "cuma dipakai bersama “I”.",
             "ใช้คู่กับ 'I' เท่านั้น")]),
    dict(s="there_is_are", id="A1-331",
         stem="___ there a bank near here?", opts=["Is", "Are", "Have", "Does"], ans="Is",
         why=("'A bank' is one thing, so the question starts with 'Is'.",
              "“A bank” itu satu benda, jadi kalimat tanyanya diawali “Is”.",
              "'a bank' เป็นสิ่งเดียว คำถามจึงขึ้นต้นด้วย 'Is'"),
         others=("'Are' is for many things, and 'Have' and 'Does' do not make there questions.",
                 "“Are” untuk banyak benda, sedangkan “Have” dan “Does” nggak dipakai untuk kalimat tanya dengan “there”.",
                 "'are' ใช้กับหลายสิ่ง ส่วน 'have' และ 'does' ไม่ใช้ในคำถามที่มี 'there'"),
         cue=("There is a bank → Is there a bank?", "“There is a bank” jadi “Is there a bank?”", "เปลี่ยนเป็นคำถามโดยย้าย 'is' ไปไว้หน้า 'there'"),
         rsn=("find the noun after there -> count one or many -> place the singular form before there",
              "cari benda sesudah “there” → hitung satu atau banyak → taruh bentuk tunggal di depan “there”",
              "หาคำนามหลัง 'there' → นับว่าหนึ่งหรือหลาย → วางรูปเอกพจน์ไว้หน้า 'there'"),
         d=[("Are", ("plural agreement", "bentuk jamak dipakai untuk satu benda.", "ใช้รูปพหูพจน์กับสิ่งเดียว"),
             "It is for many things, but 'a bank' is one.",
             "untuk banyak benda, padahal “a bank” cuma satu.",
             "ใช้กับหลายสิ่ง แต่ 'a bank' มีแห่งเดียว"),
            ("Have", HAVE_EXIST,
             "It cannot ask whether something exists; that question moves a be word before 'there'.",
             "nggak bisa dipakai untuk bertanya “ada nggak?”. Untuk itu, bentuk “be” dipindah ke depan “there”.",
             "ใช้ถามว่ามีไหมไม่ได้ คำถามแบบนี้ต้องย้ายรูป 'be' ไปไว้หน้า 'there'"),
            ("Does", DO_BE_Q,
             "It is not used with 'there'; this question needs a be word.",
             "nggak dipakai bersama “there”. Kalimat tanya ini butuh bentuk “be”.",
             "ไม่ใช้กับ 'there' คำถามนี้ต้องใช้รูป 'be'")]),
    dict(s="there_is_are", id="A1-332",
         stem="“___ there any cookies in the jar?” “No, there aren't.”", opts=["Are", "Is", "Have", "Do"], ans="Are",
         why=("'Cookies' are many things, so the question starts with 'Are'. The answer 'there aren't' shows it too.",
              "“Cookies” itu banyak benda, jadi kalimat tanyanya diawali “Are”. Jawaban “there aren't” juga menunjukkannya.",
              "'cookies' มีหลายชิ้น คำถามจึงขึ้นต้นด้วย 'Are' และคำตอบ 'there aren't' ก็บอกเช่นกัน"),
         others=("'Is' is for one thing, and 'Have' and 'Do' do not make there questions.",
                 "“Is” untuk satu benda, sedangkan “Have” dan “Do” nggak dipakai untuk kalimat tanya dengan “there”.",
                 "'is' ใช้กับสิ่งเดียว ส่วน 'have' และ 'do' ไม่ใช้ในคำถามที่มี 'there'"),
         cue=("Many things: Are there any…?", "Banyak benda: “Are there any…?”", "ถ้าถามถึงของหลายชิ้น ให้ใช้ 'Are there any…?'"),
         rsn=("find the noun after there -> count one or many -> place the plural form before there",
              "cari benda sesudah “there” → hitung satu atau banyak → taruh bentuk jamak di depan “there”",
              "หาคำนามหลัง 'there' → นับว่าหนึ่งหรือหลาย → วางรูปพหูพจน์ไว้หน้า 'there'"),
         d=[("Is", ("singular agreement", "bentuk tunggal dipakai untuk banyak benda.", "ใช้รูปเอกพจน์กับของหลายชิ้น"),
             "It is for one thing, but 'cookies' are many.",
             "untuk satu benda, padahal “cookies” banyak.",
             "ใช้กับสิ่งเดียว แต่ 'cookies' มีหลายชิ้น"),
            ("Have", HAVE_EXIST,
             "It cannot ask whether something exists; that question uses a be word + there.",
             "nggak bisa dipakai untuk bertanya “ada nggak?”. Pertanyaan itu memakai bentuk “be” + “there”.",
             "ใช้ถามว่ามีไหมไม่ได้ คำถามแบบนี้ใช้รูป 'be' + 'there'"),
            ("Do", DO_BE_Q,
             "It is not used with 'there', and the answer uses 'there aren't', not 'don't'.",
             "nggak dipakai bersama “there”, dan jawabannya pun memakai “there aren't”, bukan “don't”.",
             "ไม่ใช้กับ 'there' และคำตอบก็ใช้ 'there aren't' ไม่ใช่ 'don't'")]),
    # ---------------- 9. in / on / under / next to ----------------
    dict(s="place_prepositions_basic", id="A1-333",
         stem="Your keys are ___ your bag. Look inside!", opts=["in", "on", "under", "to"], ans="in",
         why=("'Look inside!' tells us the keys are inside the bag, so we use 'in'.",
              "“Look inside!” menunjukkan kuncinya ada di dalam tas, jadi pakai “in”.",
              "'Look inside!' บอกว่ากุญแจอยู่ข้างในกระเป๋า จึงใช้ 'in'"),
         others=("'On' means on top, 'under' means below, and 'to' shows movement.",
                 "“On” artinya di atas permukaan, “under” artinya di bawah, dan “to” menunjukkan gerak ke suatu tempat.",
                 "'on' แปลว่าอยู่บนพื้นผิว 'under' แปลว่าอยู่ข้างใต้ และ 'to' บอกการเคลื่อนที่ไปยังที่หนึ่ง"),
         cue=("Inside a bag or a box: in.", "Di dalam tas atau kotak: “in”.", "ของที่อยู่ในกระเป๋าหรือในกล่อง ใช้ 'in'"),
         rsn=("find the clue look inside -> identify the position as inside -> choose the word for inside",
              "cari petunjuk “Look inside!” → tentukan posisinya di dalam → pilih kata untuk “di dalam”",
              "หาคำใบ้ 'Look inside!' → ระบุว่าอยู่ข้างใน → เลือกคำที่แปลว่าข้างใน"),
         d=[("on", ON_INSIDE,
             "It would mean on top of the bag, but the keys are inside.",
             "artinya di atas tas, padahal kuncinya ada di dalam.",
             "แปลว่าอยู่บนกระเป๋า แต่กุญแจอยู่ข้างใน"),
            ("under", UNDER_INSIDE,
             "It would mean below the bag, not inside it.",
             "artinya di bawah tas, bukan di dalamnya.",
             "แปลว่าอยู่ใต้กระเป๋า ไม่ใช่อยู่ข้างใน"),
            ("to", ("movement-preposition-substitution", "kata depan gerak dipakai untuk benda yang diam.", "ใช้คำบุพบทบอกการเคลื่อนที่กับของที่อยู่นิ่ง"),
             "It shows movement toward a place, but the keys are not moving.",
             "menunjukkan gerak ke suatu tempat, padahal kuncinya diam.",
             "บอกการเคลื่อนที่ไปยังที่หนึ่ง แต่กุญแจอยู่นิ่ง ๆ")]),
    dict(s="place_prepositions_basic", id="A1-334",
         stem="Sit ___ me, Rina. This chair is empty.", opts=["next to", "on", "in", "under"], ans="next to",
         why=("The empty chair is beside me, so we use 'next to'.",
              "Kursi kosongnya ada di sampingku, jadi pakai “next to”.",
              "เก้าอี้ว่างอยู่ข้าง ๆ ฉัน จึงใช้ 'next to'"),
         others=("'On me' means on my body, 'in me' means inside me, and 'under me' means below me.",
                 "“On me” artinya di atas badanku, “in me” artinya di dalam badanku, dan “under me” artinya di bawahku.",
                 "'on me' แปลว่านั่งบนตัวฉัน 'in me' แปลว่าอยู่ข้างในตัวฉัน และ 'under me' แปลว่าอยู่ใต้ตัวฉัน"),
         cue=("Beside you, on the next chair: next to.", "Di sampingmu, di kursi sebelah: “next to”.", "นั่งข้าง ๆ บนเก้าอี้ตัวถัดไป ใช้ 'next to'"),
         rsn=("find the empty chair -> identify its position beside me -> choose the words for beside",
              "cari kursi kosongnya → tentukan posisinya di sampingku → pilih kata untuk “di samping”",
              "หาเก้าอี้ว่าง → ระบุว่าอยู่ข้าง ๆ ฉัน → เลือกคำที่แปลว่าข้าง ๆ"),
         d=[("on", ON_BESIDE,
             "It would mean sitting on my body, not on the chair beside me.",
             "artinya duduk di atas badanku, bukan di kursi sebelahku.",
             "แปลว่านั่งบนตัวฉัน ไม่ใช่นั่งเก้าอี้ข้าง ๆ"),
            ("in", IN_BESIDE,
             "It would mean going inside my body, which is impossible.",
             "artinya masuk ke dalam badanku, dan itu nggak mungkin.",
             "แปลว่าเข้าไปอยู่ข้างในตัวฉัน ซึ่งเป็นไปไม่ได้"),
            ("under", UNDER_BESIDE,
             "It would mean below me, but the chair is beside me.",
             "artinya di bawahku, padahal kursinya ada di sampingku.",
             "แปลว่าอยู่ใต้ตัวฉัน แต่เก้าอี้อยู่ข้าง ๆ ฉัน")]),
    dict(s="place_prepositions_basic", id="A1-335",
         stem="There is a big picture ___ the wall.", opts=["on", "in", "under", "to"], ans="on",
         why=("A picture hangs flat against the wall's surface, so we use 'on'.",
              "Lukisan menempel di permukaan dinding, jadi pakai “on”.",
              "รูปภาพแขวนติดอยู่บนพื้นผิวของผนัง จึงใช้ 'on'"),
         others=("'In' means inside the wall, 'under' means below it, and 'to' shows movement.",
                 "“In” artinya di dalam dinding, “under” artinya di bawahnya, dan “to” menunjukkan gerak.",
                 "'in' แปลว่าอยู่ข้างในผนัง 'under' แปลว่าอยู่ข้างใต้ และ 'to' บอกการเคลื่อนที่"),
         cue=("Walls and tables are surfaces: on the wall, on the table.", "Dinding dan meja itu permukaan: “on the wall”, “on the table”.", "ผนังกับโต๊ะเป็นพื้นผิว จึงใช้ 'on the wall' และ 'on the table'"),
         rsn=("identify the wall as a surface -> check that the picture touches it -> choose the word for a surface",
              "kenali dinding sebagai permukaan → cek lukisannya menempel di situ → pilih kata untuk permukaan",
              "มองผนังเป็นพื้นผิว → ดูว่ารูปติดอยู่บนนั้น → เลือกคำสำหรับพื้นผิว"),
         d=[("in", ("container-reading", "dinding dianggap wadah, padahal lukisannya menempel di permukaan.", "มองผนังเป็นภาชนะ ทั้งที่รูปติดอยู่บนพื้นผิว"),
             "It would mean inside the wall, like a hidden safe.",
             "artinya di dalam dinding, seperti brankas yang disembunyikan.",
             "แปลว่าอยู่ข้างในผนัง เหมือนตู้เซฟที่ซ่อนไว้"),
            ("under", UNDER_SURFACE,
             "It would mean below the wall, but the picture hangs on it.",
             "artinya di bawah dinding, padahal lukisannya tergantung di dinding.",
             "แปลว่าอยู่ใต้ผนัง แต่รูปแขวนอยู่บนผนัง"),
            ("to", ("movement-preposition-substitution", "kata depan gerak dipakai untuk benda yang diam di dinding.", "ใช้คำบุพบทบอกการเคลื่อนที่กับของที่อยู่นิ่งบนผนัง"),
             "It shows movement toward a place, but the picture is not moving.",
             "menunjukkan gerak ke suatu tempat, padahal lukisannya diam.",
             "บอกการเคลื่อนที่ไปยังที่หนึ่ง แต่รูปอยู่นิ่ง ๆ")]),
    dict(s="place_prepositions_basic", id="A1-336",
         stem="Your pencil fell. Look ___ your chair!", opts=["under", "on", "in", "to"], ans="under",
         why=("A pencil that falls ends up on the floor, below the chair, so we use 'under'.",
              "Pensil yang jatuh ada di lantai, di bawah kursi, jadi pakai “under”.",
              "ดินสอที่ตกจะอยู่บนพื้น ใต้เก้าอี้ จึงใช้ 'under'"),
         others=("'On' means on the seat, 'in' means inside, and 'to' shows movement.",
                 "“On” artinya di atas dudukan kursi, “in” artinya di dalam, dan “to” menunjukkan gerak.",
                 "'on' แปลว่าอยู่บนที่นั่ง 'in' แปลว่าอยู่ข้างใน และ 'to' บอกการเคลื่อนที่"),
         cue=("It fell down? Look under.", "Barangnya jatuh? Cari di bawah: “under”.", "ของตกลงไปข้างล่าง ให้ดูข้างใต้: 'under'"),
         rsn=("notice the word fell -> identify the pencil's position below the chair -> choose the word for below",
              "perhatikan kata “fell” → tentukan letak pensilnya di bawah kursi → pilih kata untuk “di bawah”",
              "สังเกตคำว่า 'fell' → ระบุว่าดินสออยู่ใต้เก้าอี้ → เลือกคำที่แปลว่าข้างใต้"),
         d=[("on", ("surface-reading despite hidden cue", "letak di bawah kursi dibaca sebagai di atas kursi.", "อ่านตำแหน่งใต้เก้าอี้ว่าเป็นบนเก้าอี้"),
             "It would mean on the seat, but a pencil that fell is on the floor.",
             "artinya di atas dudukan kursi, padahal pensil yang jatuh ada di lantai.",
             "แปลว่าอยู่บนที่นั่ง แต่ดินสอที่ตกอยู่บนพื้น"),
            ("in", ("container-reading", "kursi dianggap wadah, padahal pensilnya jatuh ke bawah.", "มองเก้าอี้เป็นภาชนะ ทั้งที่ดินสอตกลงไปข้างล่าง"),
             "A chair has no inside; the pencil is below it.",
             "berarti di dalam, padahal kursi nggak punya bagian dalam. Pensilnya ada di bawah kursi.",
             "แปลว่าข้างใน แต่เก้าอี้ไม่มีข้างใน ดินสออยู่ใต้เก้าอี้"),
            ("to", ("movement-preposition-substitution", "kata depan gerak dipakai untuk menunjuk letak benda.", "ใช้คำบุพบทบอกการเคลื่อนที่เพื่อบอกตำแหน่ง"),
             "It shows a direction, not where the pencil is.",
             "menunjukkan arah gerak, bukan letak pensilnya.",
             "บอกทิศทางการเคลื่อนที่ ไม่ได้บอกว่าดินสออยู่ตรงไหน")]),
    # ---------------- 10. present simple ----------------
    dict(s="present_simple_basics", id="A1-337",
         stem="My dad ___ the news every evening.", opts=["watches", "watch", "watchs", "watching"], ans="watches",
         why=("'My dad' is he, and 'watch' ends in ch, so we add -es: watches.",
              "“My dad” sama dengan “he”, dan “watch” berakhiran ch, jadi tambah -es. Hasilnya “watches”.",
              "'My dad' คือ 'he' และ 'watch' ลงท้ายด้วย ch จึงเติม -es เป็น 'watches'"),
         others=("'Watch' has no ending, 'watchs' forgets the e, and 'watching' needs is before it.",
                 "“Watch” nggak ada akhirannya, “watchs” lupa huruf e, dan “watching” butuh “is” di depannya.",
                 "'watch' ไม่มีตัวลงท้าย 'watchs' ขาด e และ 'watching' ต้องมี 'is' อยู่ข้างหน้า"),
         cue=("Ch, sh, s, x, o: add -es. He watches, she goes.", "Akhiran ch, sh, s, x, o: tambah -es. “He watches”, “she goes”.", "คำกริยาที่ลงท้ายด้วย ch, sh, s, x, o ให้เติม -es เช่น 'watches'"),
         rsn=("find the subject -> check the verb ending ch -> add -es",
              "cari subjeknya → cek akhiran ch pada kata kerja → tambah -es",
              "หาประธาน → ดูว่ากริยาลงท้ายด้วย ch → เติม -es"),
         d=[("watch", ("base-form overuse", "bentuk dasar dipakai untuk “he”.", "ใช้รูปพื้นฐานกับ 'he'"),
             "'My dad' is he, so the verb needs an ending.",
             "nggak punya akhiran, padahal “my dad” sama dengan “he”.",
             "ไม่มีตัวลงท้าย แต่ 'my dad' คือ 'he'"),
            ("watchs", S_NOT_ES,
             "After ch we add -es, not just -s.",
             "cuma diberi -s, padahal sesudah ch harus -es.",
             "เติมแค่ -s แต่หลัง ch ต้องเติม -es"),
            ("watching", ("progressive confusion", "bentuk -ing dipakai tanpa “is” untuk kebiasaan.", "ใช้รูป -ing โดยไม่มี 'is' กับกิจวัตร"),
             "An -ing verb needs is before it, and 'every evening' shows a habit.",
             "bentuk -ing butuh “is” di depannya, dan “every evening” menunjukkan kebiasaan.",
             "รูป -ing ต้องมี 'is' ข้างหน้า และ 'every evening' บอกว่าเป็นกิจวัตร")]),
    dict(s="present_simple_basics", id="A1-338",
         stem="My friends ___ badminton on Saturdays.", opts=["play", "plays", "playing", "is playing"], ans="play",
         why=("'My friends' means they, so the verb stays in the base form: play.",
              "“My friends” sama dengan “they”, jadi kata kerjanya tetap bentuk dasar, yaitu “play”.",
              "'My friends' คือ 'they' คำกริยาจึงใช้รูปพื้นฐาน 'play'"),
         others=("'Plays' is for he, she, or it; 'playing' needs a be word; 'is playing' is for one person now.",
                 "“Plays” untuk “he”, “she”, atau “it”. “Playing” butuh bentuk “be”. “Is playing” untuk satu orang yang sedang bermain sekarang.",
                 "'plays' ใช้กับ 'he', 'she', 'it' ส่วน 'playing' ต้องมีรูป 'be' และ 'is playing' ใช้กับคนเดียวที่กำลังเล่นตอนนี้"),
         cue=("They play, he plays.", "“They play”, tapi “he plays”.", "พวกเขาใช้ 'they play' แต่เขาคนเดียวใช้ 'he plays'"),
         rsn=("find the subject -> count one or more people -> keep the base form",
              "cari subjeknya → hitung satu orang atau lebih → pakai bentuk dasarnya",
              "หาประธาน → นับว่าคนเดียวหรือหลายคน → ใช้รูปพื้นฐาน"),
         d=[("plays", ("adds -s to the verb although the subject is plural", "akhiran -s ditambahkan untuk subjek jamak.", "เติม -s ทั้งที่ประธานเป็นพหูพจน์"),
             "-s is only for he, she, or it, but 'my friends' are many.",
             "memakai -s, padahal -s cuma untuk “he”, “she”, atau “it”, dan “my friends” banyak.",
             "เติม -s แต่ -s ใช้กับ 'he', 'she', 'it' เท่านั้น และ 'my friends' มีหลายคน"),
            ("playing", ("progressive confusion", "bentuk -ing dipakai tanpa kata bantu untuk kebiasaan.", "ใช้รูป -ing โดยไม่มีกริยาช่วยกับกิจวัตร"),
             "An -ing verb needs are before it, and 'on Saturdays' shows a habit.",
             "bentuk -ing butuh “are” di depannya, dan “on Saturdays” menunjukkan kebiasaan.",
             "รูป -ing ต้องมี 'are' ข้างหน้า และ 'on Saturdays' บอกว่าเป็นกิจวัตร"),
            ("is playing", PROG_PL_HABIT,
             "It is for one person doing something now, but this is a habit of many friends.",
             "untuk satu orang yang sedang melakukan sesuatu sekarang, padahal ini kebiasaan banyak teman.",
             "ใช้กับคนเดียวที่กำลังทำอะไรอยู่ตอนนี้ แต่นี่เป็นกิจวัตรของเพื่อนหลายคน")]),
    dict(s="present_simple_basics", id="A1-339",
         stem="Sinta ___ to school at 6:30 every day.", opts=["goes", "go", "gos", "going"], ans="goes",
         why=("'Sinta' is she, and 'go' ends in o, so we add -es: goes.",
              "“Sinta” sama dengan “she”, dan “go” berakhiran o, jadi tambah -es. Hasilnya “goes”.",
              "'Sinta' คือ 'she' และ 'go' ลงท้ายด้วย o จึงเติม -es เป็น 'goes'"),
         others=("'Go' has no ending, 'gos' forgets the e, and 'going' needs is before it.",
                 "“Go” nggak ada akhirannya, “gos” lupa huruf e, dan “going” butuh “is” di depannya.",
                 "'go' ไม่มีตัวลงท้าย 'gos' ขาด e และ 'going' ต้องมี 'is' ข้างหน้า"),
         cue=("Go becomes goes, do becomes does.", "“Go” jadi “goes”, “do” jadi “does”.", "จำไว้ว่า 'go' เปลี่ยนเป็น 'goes' และ 'do' เปลี่ยนเป็น 'does'"),
         rsn=("find the subject -> check the verb ending o -> add -es",
              "cari subjeknya → cek akhiran o pada kata kerja → tambah -es",
              "หาประธาน → ดูว่ากริยาลงท้ายด้วย o → เติม -es"),
         d=[("go", ("base-form overuse", "bentuk dasar dipakai untuk “she”.", "ใช้รูปพื้นฐานกับ 'she'"),
             "Sinta is she, so the verb needs an ending.",
             "nggak punya akhiran, padahal Sinta sama dengan “she”.",
             "ไม่มีตัวลงท้าย แต่ 'Sinta' คือ 'she'"),
            ("gos", S_NOT_ES,
             "After o we add -es, not just -s.",
             "cuma diberi -s, padahal sesudah o harus -es.",
             "เติมแค่ -s แต่หลัง o ต้องเติม -es"),
            ("going", ("progressive confusion", "bentuk -ing dipakai tanpa “is” untuk kebiasaan.", "ใช้รูป -ing โดยไม่มี 'is' กับกิจวัตร"),
             "An -ing verb needs is before it, and 'every day' shows a habit.",
             "bentuk -ing butuh “is” di depannya, dan “every day” menunjukkan kebiasaan.",
             "รูป -ing ต้องมี 'is' ข้างหน้า และ 'every day' บอกว่าเป็นกิจวัตร")]),
    dict(s="present_simple_basics", id="A1-340",
         stem="The baby ___ a lot at night.", opts=["cries", "crys", "cry", "crying"], ans="cries",
         why=("'The baby' is one person, and 'cry' ends in consonant + y, so we write 'cries'.",
              "“The baby” itu satu orang, dan “cry” berakhiran konsonan + y, jadi tulisannya “cries”.",
              "'The baby' เป็นคนเดียว และ 'cry' ลงท้ายด้วยพยัญชนะ + y จึงเขียนเป็น 'cries'"),
         others=("'Crys' keeps the y, 'cry' has no ending, and 'crying' needs is before it.",
                 "“Crys” masih menyimpan huruf y, “cry” nggak ada akhirannya, dan “crying” butuh “is” di depannya.",
                 "'crys' ยังคง y ไว้ 'cry' ไม่มีตัวลงท้าย และ 'crying' ต้องมี 'is' ข้างหน้า"),
         cue=("Consonant + y: cry, cries; study, studies.", "Konsonan + y: “cry” jadi “cries”, “study” jadi “studies”.", "ถ้าลงท้ายด้วยพยัญชนะ + y ให้เปลี่ยนเป็น -ies เช่น 'cries'"),
         rsn=("find the subject -> check the ending consonant + y -> convert y to ies",
              "cari subjeknya → cek akhiran konsonan + y → ubah y jadi -ies",
              "หาประธาน → ดูตัวท้ายพยัญชนะ + y → เปลี่ยน y เป็น -ies"),
         d=[("crys", S_KEEP_Y,
             "After a consonant + y, the y changes to i first.",
             "masih menyimpan huruf y, padahal sesudah konsonan, y harus jadi i dulu.",
             "ยังคง y ไว้ แต่หลังพยัญชนะต้องเปลี่ยน y เป็น i ก่อน"),
            ("cry", ("base-form overuse", "bentuk dasar dipakai untuk satu orang.", "ใช้รูปพื้นฐานกับคนเดียว"),
             "'The baby' is one person, so the verb needs an ending.",
             "nggak punya akhiran, padahal “the baby” itu satu orang.",
             "ไม่มีตัวลงท้าย แต่ 'the baby' เป็นคนเดียว"),
            ("crying", ("progressive confusion", "bentuk -ing dipakai tanpa “is” untuk kebiasaan.", "ใช้รูป -ing โดยไม่มี 'is' กับกิจวัตร"),
             "An -ing verb needs is before it, and 'a lot at night' shows a habit.",
             "bentuk -ing butuh “is” di depannya, dan “a lot at night” menunjukkan kebiasaan.",
             "รูป -ing ต้องมี 'is' ข้างหน้า และ 'a lot at night' บอกว่าเกิดขึ้นเป็นประจำ")]),
    # ---------------- 11. question words ----------------
    dict(s="question_words_basic", id="A1-341",
         stem="“___ is your English teacher?” “Mr. Budi.”", opts=["Who", "What", "Where", "When"], ans="Who",
         why=("The answer 'Mr. Budi' is a person, so we ask with 'Who'.",
              "Jawabannya “Mr. Budi”, yaitu orang, jadi bertanya dengan “Who”.",
              "คำตอบคือ 'Mr. Budi' ซึ่งเป็นคน จึงถามด้วย 'Who'"),
         others=("'What' asks about a thing, 'Where' about a place, and 'When' about a time.",
                 "“What” menanyakan benda, “Where” menanyakan tempat, dan “When” menanyakan waktu.",
                 "'what' ถามถึงสิ่งของ 'where' ถามถึงสถานที่ และ 'when' ถามถึงเวลา"),
         cue=("The answer is a person? Ask 'Who'.", "Jawabannya orang? Tanya dengan “Who”.", "ถ้าคำตอบเป็นคน ให้ถามด้วย 'Who'"),
         rsn=("check the answer Mr. Budi -> identify it as a person -> choose the question word for a person",
              "lihat jawabannya, “Mr. Budi” → pastikan itu orang → pilih kata tanya untuk orang",
              "ดูคำตอบ 'Mr. Budi' → ดูว่าเป็นคน → เลือกคำถามสำหรับคน"),
         d=[("What", QW('what', 'person', 'orang', 'คน'),
             "It asks about a thing, but the answer is a person.",
             "menanyakan benda, padahal jawabannya orang.",
             "ใช้ถามถึงสิ่งของ แต่คำตอบเป็นคน"),
            ("Where", QW('where', 'person', 'orang', 'คน'),
             "It asks about a place, but the answer is a person.",
             "menanyakan tempat, padahal jawabannya orang.",
             "ใช้ถามถึงสถานที่ แต่คำตอบเป็นคน"),
            ("When", QW('when', 'person', 'orang', 'คน'),
             "It asks about a time, but the answer is a person.",
             "menanyakan waktu, padahal jawabannya orang.",
             "ใช้ถามถึงเวลา แต่คำตอบเป็นคน")]),
    dict(s="question_words_basic", id="A1-342",
         stem="“___ are you sad?” “Because my cat is sick.”", opts=["Why", "What", "Where", "When"], ans="Why",
         why=("The answer starts with 'Because', which gives a reason, so we ask with 'Why'.",
              "Jawabannya diawali “Because”, yaitu alasan, jadi bertanya dengan “Why”.",
              "คำตอบขึ้นต้นด้วย 'Because' ซึ่งบอกเหตุผล จึงถามด้วย 'Why'"),
         others=("'What', 'Where', and 'When' ask about a thing, a place, and a time, not a reason.",
                 "“What”, “Where”, dan “When” menanyakan benda, tempat, dan waktu, bukan alasan.",
                 "'what', 'where' และ 'when' ถามถึงสิ่งของ สถานที่ และเวลา ไม่ใช่เหตุผล"),
         cue=("Because in the answer? Ask 'Why'.", "Ada “because” di jawabannya? Tanya dengan “Why”.", "ถ้าคำตอบมีคำว่า 'because' ให้ถามด้วย 'Why'"),
         rsn=("check the answer -> notice the word because -> choose the question word for a reason",
              "lihat jawabannya → perhatikan kata “Because” → pilih kata tanya untuk alasan",
              "ดูคำตอบ → สังเกตคำว่า 'Because' → เลือกคำถามสำหรับเหตุผล"),
         d=[("What", QW('what', 'reason', 'alasan', 'เหตุผล'),
             "It asks about a thing, but the answer is a reason.",
             "menanyakan benda, padahal jawabannya alasan.",
             "ใช้ถามถึงสิ่งของ แต่คำตอบเป็นเหตุผล"),
            ("Where", QW('where', 'reason', 'alasan', 'เหตุผล'),
             "It asks about a place, but the answer is a reason.",
             "menanyakan tempat, padahal jawabannya alasan.",
             "ใช้ถามถึงสถานที่ แต่คำตอบเป็นเหตุผล"),
            ("When", QW('when', 'reason', 'alasan', 'เหตุผล'),
             "It asks about a time, but the answer is a reason.",
             "menanyakan waktu, padahal jawabannya alasan.",
             "ใช้ถามถึงเวลา แต่คำตอบเป็นเหตุผล")]),
    dict(s="question_words_basic", id="A1-343",
         stem="“___ do you go to school?” “By bus.”", opts=["How", "What", "Where", "When"], ans="How",
         why=("'By bus' tells the way you travel, so we ask with 'How'.",
              "“By bus” menjelaskan caranya pergi, jadi bertanya dengan “How”.",
              "'By bus' บอกวิธีเดินทาง จึงถามด้วย 'How'"),
         others=("'What' asks about a thing, 'Where' about a place, and 'When' about a time; none asks about a way.",
                 "“What” menanyakan benda, “Where” tempat, dan “When” waktu. Nggak ada yang menanyakan cara.",
                 "'what' ถามถึงสิ่งของ 'where' ถามถึงสถานที่ 'when' ถามถึงเวลา ไม่มีคำไหนถามถึงวิธี"),
         cue=("By bus, by bike, on foot: ask 'How'.", "“By bus”, “by bike”, “on foot”: tanya dengan “How”.", "คำตอบแบบนั่งรถเมล์หรือเดินไป ให้ถามด้วย 'How'"),
         rsn=("check the answer By bus -> identify it as a way to travel -> choose the question word for a way",
              "lihat jawaban “By bus” → pastikan itu cara bepergian → pilih kata tanya untuk cara",
              "ดูคำตอบ 'By bus' → ดูว่าเป็นวิธีเดินทาง → เลือกคำถามสำหรับวิธี"),
         d=[("What", QW('what', 'way', 'cara', 'วิธี'),
             "It asks about a thing, but the answer is a way to travel.",
             "menanyakan benda, padahal jawabannya cara pergi.",
             "ใช้ถามถึงสิ่งของ แต่คำตอบเป็นวิธีเดินทาง"),
            ("Where", QW('where', 'way', 'cara', 'วิธี'),
             "It asks about a place, but the answer is a way to travel, not the place.",
             "menanyakan tempat, padahal jawabannya cara pergi, bukan tujuannya.",
             "ใช้ถามถึงสถานที่ แต่คำตอบเป็นวิธีเดินทาง ไม่ใช่จุดหมาย"),
            ("When", QW('when', 'way', 'cara', 'วิธี'),
             "It asks about a time, but the answer is a way to travel.",
             "menanyakan waktu, padahal jawabannya cara pergi.",
             "ใช้ถามถึงเวลา แต่คำตอบเป็นวิธีเดินทาง")]),
    dict(s="question_words_basic", id="A1-344",
         stem="“___ is in your bag?” “My lunch box.”", opts=["What", "Who", "Where", "When"], ans="What",
         why=("'My lunch box' is a thing, so we ask with 'What'.",
              "“My lunch box” itu benda, jadi bertanya dengan “What”.",
              "'My lunch box' เป็นสิ่งของ จึงถามด้วย 'What'"),
         others=("'Who' asks about a person, 'Where' about a place, and 'When' about a time.",
                 "“Who” menanyakan orang, “Where” menanyakan tempat, dan “When” menanyakan waktu.",
                 "'who' ถามถึงคน 'where' ถามถึงสถานที่ และ 'when' ถามถึงเวลา"),
         cue=("The answer is a thing? Ask 'What'.", "Jawabannya benda? Tanya dengan “What”.", "ถ้าคำตอบเป็นสิ่งของ ให้ถามด้วย 'What'"),
         rsn=("check the answer My lunch box -> identify it as a thing -> choose the question word for a thing",
              "lihat jawaban “My lunch box” → pastikan itu benda → pilih kata tanya untuk benda",
              "ดูคำตอบ 'My lunch box' → ดูว่าเป็นสิ่งของ → เลือกคำถามสำหรับสิ่งของ"),
         d=[("Who", QW('who', 'thing', 'benda', 'สิ่งของ'),
             "It asks about a person, but the answer is a thing.",
             "menanyakan orang, padahal jawabannya benda.",
             "ใช้ถามถึงคน แต่คำตอบเป็นสิ่งของ"),
            ("Where", QW('where', 'thing', 'benda', 'สิ่งของ'),
             "It asks about a place, but the answer is a thing.",
             "menanyakan tempat, padahal jawabannya benda.",
             "ใช้ถามถึงสถานที่ แต่คำตอบเป็นสิ่งของ"),
            ("When", QW('when', 'thing', 'benda', 'สิ่งของ'),
             "It asks about a time, but the answer is a thing.",
             "menanyakan waktu, padahal jawabannya benda.",
             "ใช้ถามถึงเวลา แต่คำตอบเป็นสิ่งของ")]),
    # ---------------- 12. can / can't ----------------
    dict(s="can_ability", id="A1-345",
         stem="My little brother can ___ to ten in English.", opts=["count", "counts", "to count", "counting"], ans="count",
         why=("After 'can' we use the base verb, with no ending: can count.",
              "Sesudah “can”, kata kerjanya bentuk dasar tanpa tambahan, jadi “can count”.",
              "หลัง 'can' ใช้คำกริยารูปพื้นฐานที่ไม่เติมอะไร จึงได้เป็น 'can count'"),
         others=("'Counts' adds -s, 'to count' adds to, and 'counting' adds -ing; can takes none of them.",
                 "“Counts” menambah -s, “to count” menambah “to”, dan “counting” menambah -ing. Sesudah “can”, semuanya nggak boleh.",
                 "'counts' เติม -s 'to count' เติม 'to' และ 'counting' เติม -ing หลัง 'can' ห้ามใช้ทั้งหมดนี้"),
         cue=("Can + plain verb: can count, can swim.", "“Can” + kata kerja bentuk dasar: “can count”, “can swim”.", "หลัง 'can' ใช้คำกริยาเปล่า ๆ เช่น 'can count'"),
         rsn=("notice can before the blank -> recall that can takes the base verb -> choose the verb with no ending",
              "lihat “can” sebelum titik-titik → ingat “can” butuh bentuk dasar → pilih kata kerja tanpa tambahan apa pun",
              "เห็น 'can' หน้าช่องว่าง → นึกว่า 'can' ตามด้วยรูปพื้นฐาน → เลือกคำกริยาที่ไม่เติมอะไรเลย"),
         d=[("counts", ("-s added to the verb after can", "akhiran -s ditambahkan ke kata kerja sesudah “can”.", "เติม -s ให้คำกริยาหลัง 'can'"),
             "There is no -s after 'can', even when the subject is he or she.",
             "memakai -s, padahal sesudah “can” nggak ada -s, walaupun subjeknya “he” atau “she”.",
             "เติม -s แต่หลัง 'can' ไม่เติม -s ถึงประธานจะเป็น 'he' หรือ 'she' ก็ตาม"),
            ("to count", ("adds 'to' after the modal can", "kata “to” ditambahkan sesudah “can”.", "เติม 'to' หลัง 'can'"),
             "'Can' never takes 'to' before the verb.",
             "memakai “to”, padahal “can” nggak pernah diikuti “to”.",
             "มี 'to' แต่ 'can' ไม่เคยตามด้วย 'to'"),
            ("counting", ("-ing form used after can", "bentuk -ing dipakai sesudah “can”.", "ใช้รูป -ing หลัง 'can'"),
             "After 'can' the verb has no -ing.",
             "memakai -ing, padahal sesudah “can” kata kerjanya harus bentuk dasar.",
             "เติม -ing แต่หลัง 'can' คำกริยาต้องเป็นรูปพื้นฐาน")]),
    dict(s="can_ability", id="A1-346",
         stem="“___ you ride a horse?” “No, I can't.”", opts=["Can", "Are", "Does", "Is"], ans="Can",
         why=("The answer 'No, I can't' shows the question is about ability, so it starts with 'Can'.",
              "Jawabannya “No, I can't”, jadi pertanyaannya soal kemampuan dan diawali “Can”.",
              "คำตอบคือ 'No, I can't' คำถามจึงถามเรื่องความสามารถ และขึ้นต้นด้วย 'Can'"),
         others=("'Are' and 'Is' do not go with 'ride', and 'Does' is for he, she, or it.",
                 "“Are” dan “Is” nggak bisa dipasangkan dengan “ride”, dan “Does” untuk “he”, “she”, atau “it”.",
                 "'are' และ 'is' ใช้คู่กับ 'ride' ไม่ได้ ส่วน 'does' ใช้กับ 'he', 'she', 'it'"),
         cue=("You can ride → Can you ride?", "“You can ride” jadi “Can you ride?”", "เปลี่ยนเป็นคำถามโดยย้าย 'can' ไปไว้หน้า 'you'"),
         rsn=("check the answer No, I can't -> identify the question as one about ability -> place the ability word before you",
              "lihat jawaban “No, I can't” → pastikan pertanyaannya soal kemampuan → taruh kata bantu kemampuan di depan “you”",
              "ดูคำตอบ 'No, I can't' → ดูว่าถามเรื่องความสามารถ → วางคำช่วยบอกความสามารถไว้หน้า 'you'"),
         d=[("Are", (BE_VERB, "“are” dipakai untuk bertanya soal kemampuan.", "ใช้ 'are' ถามเรื่องความสามารถ"),
             "It is a be word, and be words do not go with an action verb like 'ride'.",
             "termasuk bentuk “be”, dan bentuk “be” nggak dipasangkan dengan kata kerja aksi seperti “ride”.",
             "เป็นรูป 'be' และรูป 'be' ใช้คู่กับคำกริยาแสดงการกระทำอย่าง 'ride' ไม่ได้"),
            ("Does", (DO_AUX, "“does” dipakai untuk “you” dan untuk bertanya soal kemampuan.", "ใช้ 'does' กับ 'you' และใช้ถามเรื่องความสามารถ"),
             "It is for he, she, or it, and the answer is about ability.",
             "untuk “he”, “she”, atau “it”, padahal subjeknya “you” dan yang ditanya kemampuan.",
             "ใช้กับ 'he', 'she', 'it' แต่ประธานคือ 'you' และถามเรื่องความสามารถ"),
            ("Is", HE_BE_YOU,
             "It does not go with 'you', and it cannot go with 'ride'.",
             "nggak cocok dengan “you”, dan nggak bisa dipasangkan dengan “ride”.",
             "ไม่เข้ากับ 'you' และใช้คู่กับ 'ride' ไม่ได้")]),
    dict(s="can_ability", id="A1-347",
         stem="Nadia ___ play the guitar, but she can sing.", opts=["can't", "doesn't can", "can't to", "not can"], ans="can't",
         why=("Nadia is not able to play, so we use 'can't' + the base verb: can't play.",
              "Nadia nggak bisa main gitar, jadi pakai “can't” + kata kerja dasar. Hasilnya “can't play”.",
              "นาเดียเล่นกีตาร์ไม่เป็น จึงใช้ 'can't' + คำกริยารูปพื้นฐาน ได้เป็น 'can't play'"),
         others=("'Doesn't can' and 'not can' are not English, and 'can't to' adds a wrong 'to'.",
                 "“Doesn't can” dan “not can” bukan bahasa Inggris, sedangkan “can't to” menambah “to” yang salah.",
                 "'doesn't can' และ 'not can' ไม่มีในภาษาอังกฤษ ส่วน 'can't to' เติม 'to' ผิด"),
         cue=("Not able? Just add n't: can't play.", "Nggak bisa? Cukup tambah n't: “can't play”.", "ถ้าทำไม่ได้ แค่เติม n't เป็น 'can't play'"),
         rsn=("notice but she can sing -> identify the missing ability -> choose the negative ability form",
              "perhatikan “but she can sing” → temukan kemampuan yang nggak dia punya → pilih bentuk negatif untuk kemampuan",
              "สังเกต 'but she can sing' → หาสิ่งที่เธอทำไม่ได้ → เลือกรูปปฏิเสธของความสามารถ"),
         d=[("doesn't can", (DO_AUX, "“doesn't” dipakai untuk membuat negatif “can”.", "ใช้ 'doesn't' ทำประโยคปฏิเสธของ 'can'"),
             "'Can' makes its own negative; it never takes 'doesn't'.",
             "salah karena “can” membuat negatifnya sendiri, tanpa bantuan “doesn't”.",
             "ผิด เพราะ 'can' ทำรูปปฏิเสธเองได้ โดยไม่ต้องใช้ 'doesn't'"),
            ("can't to", ("adds 'to' after the modal can", "kata “to” ditambahkan sesudah bentuk negatif “can”.", "เติม 'to' หลังรูปปฏิเสธของ 'can'"),
             "There is no 'to' after the negative of 'can'; the verb comes right after.",
             "menambah “to”, padahal sesudah bentuk negatif “can” kata kerjanya langsung menyusul.",
             "เติม 'to' แต่หลังรูปปฏิเสธของ 'can' คำกริยาตามมาทันที"),
            ("not can", ("not placed before can", "kata “not” ditaruh sebelum “can”.", "วาง 'not' ไว้หน้า 'can'"),
             "'Not' goes after 'can', and the two join as one word.",
             "menaruh “not” di depan, padahal “not” harus sesudah “can” dan menyatu jadi satu kata.",
             "วาง 'not' ไว้ข้างหน้า แต่ 'not' ต้องอยู่หลัง 'can' และรวมเป็นคำเดียว")]),
    dict(s="can_ability", id="A1-348",
         stem="My grandmother is 80, but she ___ still ride a bike.", opts=["can", "cans", "can to", "is can"], ans="can",
         why=("She is still able to ride, so we use 'can' + base verb, and 'can' never changes.",
              "Nenek masih mampu naik sepeda, jadi pakai “can” + kata kerja dasar. “Can” nggak pernah berubah bentuk.",
              "คุณยายยังขี่จักรยานได้ จึงใช้ 'can' + คำกริยารูปพื้นฐาน และ 'can' ไม่เคยเปลี่ยนรูป"),
         others=("'Cans' adds -s, 'can to' adds 'to', and 'is can' adds an extra 'is'.",
                 "“Cans” menambah -s, “can to” menambah “to”, dan “is can” menambah “is” yang nggak perlu.",
                 "'cans' เติม -s 'can to' เติม 'to' และ 'is can' เติม 'is' ที่ไม่จำเป็น"),
         cue=("Can never changes: I can, she can, they can.", "“Can” nggak pernah berubah: “I can”, “she can”, “they can”.", "'can' ไม่เคยเปลี่ยนรูป ใช้เหมือนกันทุกประธาน"),
         rsn=("find the subject she -> recall that the ability word never changes -> choose the form with no change",
              "cari subjeknya, “she” → ingat kata bantu kemampuan nggak pernah berubah → pilih bentuk yang nggak berubah",
              "หาประธาน 'she' → นึกว่าคำช่วยบอกความสามารถไม่เคยเปลี่ยนรูป → เลือกรูปที่ไม่เปลี่ยน"),
         d=[("cans", ("-s added to can", "akhiran -s ditambahkan ke kata bantu “can”.", "เติม -s ให้ 'can'"),
             "This helper word never takes -s, even with 'she'.",
             "memakai -s, padahal kata bantu kemampuan nggak pernah diberi -s, walaupun subjeknya “she”.",
             "เติม -s แต่คำช่วยบอกความสามารถไม่เคยเติม -s ถึงประธานจะเป็น 'she' ก็ตาม"),
            ("can to", ("adds 'to' after the modal can", "kata “to” ditambahkan sesudah “can”.", "เติม 'to' หลัง 'can'"),
             "There is no 'to' after this helper word; the verb comes right after.",
             "menambah “to”, padahal sesudah kata bantu kemampuan kata kerjanya langsung menyusul.",
             "เติม 'to' แต่หลังคำช่วยบอกความสามารถ คำกริยาตามมาทันที"),
            ("is can", ("be added before can", "bentuk “be” ditambahkan di depan “can”.", "เติม 'be' ไว้หน้า 'can'"),
             "It uses two helper words at once; the be word must go.",
             "memakai dua kata bantu sekaligus, jadi bentuk “be”-nya harus dibuang.",
             "ใช้กริยาช่วยสองตัวพร้อมกัน ต้องตัดรูป 'be' ออก")]),
]
