# A2 lesson 25-31: soal latihan baru (m025-376). Format: lihat build_pack.py.
LESSONS = {
    "zero_vs_first_conditional": dict(
        obj=("Use if + present, present for things that are always true, and if + present, will + verb for one real future result.",
             "Pakai “if” + present, present untuk hal yang selalu benar, dan “if” + present, “will” + kata kerja untuk satu akibat nyata di masa depan.",
             "ใช้ 'if' + ปัจจุบัน ตามด้วยปัจจุบัน กับสิ่งที่จริงเสมอ และใช้ 'if' + ปัจจุบัน ตามด้วย 'will' + คำกริยา กับผลที่จะเกิดจริงในอนาคต"),
        mis=("Learner puts will after if because the event is in the future, or uses the past for a fact that is always true.",
             "Kamu menaruh “will” sesudah “if” karena kejadiannya nanti, atau memakai bentuk lampau untuk fakta yang selalu benar.",
             "คุณใส่ 'will' หลัง 'if' เพราะเป็นเรื่องในอนาคต หรือใช้รูปอดีตกับความจริงที่เป็นจริงเสมอ"),
        rule=("Always true: If + present, present (If you heat ice, it melts). One future result: If + present, will + verb. No will after if.",
              "Selalu benar: “If” + present, present (“If you heat ice, it melts”). Akibat di masa depan: “If” + present, “will” + kata kerja. Sesudah “if” jangan pakai “will”.",
              "ถ้าจริงเสมอ ใช้ 'If' + ปัจจุบัน แล้วตามด้วยปัจจุบัน ('If you heat ice, it melts') ถ้าเป็นผลในอนาคต ใช้ 'If' + ปัจจุบัน แล้วตามด้วย 'will' + คำกริยา และห้ามใช้ 'will' หลัง 'if'"),
        avoid=("Ask: is it always true, or one future event? Then check that no will follows if.",
               "Tanya: ini selalu benar, atau satu kejadian nanti? Lalu pastikan nggak ada “will” sesudah “if”.",
               "ถามตัวเองว่าจริงเสมอหรือเป็นเหตุการณ์ในอนาคตครั้งเดียว แล้วดูว่าไม่มี 'will' หลัง 'if'"),
    ),
    "first_vs_subsequent_mention": dict(
        obj=("Use a or an when you mention something for the first time, and the when you mention it again.",
             "Pakai “a” atau “an” saat sesuatu pertama kali disebut, dan “the” saat disebut lagi.",
             "ใช้ 'a' หรือ 'an' ตอนพูดถึงสิ่งหนึ่งครั้งแรก และใช้ 'the' ตอนพูดถึงอีกครั้ง"),
        mis=("Learner uses the for everything or forgets the article, since 'itu' and 'นั้น' can be left out.",
             "Kamu memakai “the” untuk semuanya atau lupa kata sandang, karena kata “itu” sering boleh dihilangkan.",
             "คุณใช้ 'the' กับทุกอย่าง หรือลืมใส่คำนำหน้านาม เพราะคำว่า 'นั้น' จะใส่หรือไม่ใส่ก็ได้"),
        rule=("First mention: a or an (I bought a hat). Second mention: the (The hat is blue), because the listener now knows which one.",
              "Pertama kali disebut: “a” atau “an” (“I bought a hat”). Disebut lagi: “the” (“The hat is blue”), karena pendengar sudah tahu yang mana.",
              "พูดถึงครั้งแรกใช้ 'a' หรือ 'an' ('I bought a hat') พูดถึงอีกครั้งใช้ 'the' ('The hat is blue') เพราะผู้ฟังรู้แล้วว่าหมายถึงอันไหน"),
        avoid=("Look back: has this thing appeared before? No: a or an. Yes: the.",
               "Lihat kalimat sebelumnya: benda ini sudah muncul? Belum: “a/an”. Sudah: “the”.",
               "ย้อนดูประโยคก่อนหน้า ถ้ายังไม่เคยพูดถึงใช้ 'a/an' ถ้าพูดถึงแล้วใช้ 'the'"),
    ),
    "comparative_vs_superlative_scope": dict(
        obj=("Use a comparative + than for two things and the + superlative for one thing in a group of three or more.",
             "Pakai bentuk “lebih” + “than” untuk dua hal, dan “the” + bentuk “paling” untuk satu hal di kelompok tiga atau lebih.",
             "ใช้รูปขั้นกว่า + 'than' กับสองสิ่ง และใช้ 'the' + ขั้นสูงสุดกับสิ่งเดียวในกลุ่มตั้งแต่สามขึ้นไป"),
        mis=("Learner uses the superlative for two things, or forgets the before it, since 'paling' and 'ที่สุด' need no article.",
             "Kamu memakai bentuk “paling” untuk dua hal, atau lupa “the” sebelum bentuk “paling”.",
             "คุณใช้ขั้นสูงสุดกับสองสิ่ง หรือลืมใส่ 'the' หน้าขั้นสูงสุด"),
        rule=("Two things: -er or more + than. The winner of a bigger group: the + -est or the most.",
              "Dua hal: -er atau “more” + “than”. Juara dari satu kelompok yang lebih besar: “the” + -est atau “the most”.",
              "สองสิ่งใช้ -er หรือ 'more' + 'than' ส่วนที่หนึ่งของกลุ่มใหญ่ใช้ 'the' + -est หรือ 'the most'"),
        avoid=("Count what is compared: two things, or a whole group?",
               "Hitung yang dibandingkan: dua hal, atau satu kelompok?",
               "นับสิ่งที่เปรียบเทียบว่าเป็นแค่สองสิ่ง หรือทั้งกลุ่ม"),
    ),
    "past_continuous_vs_past_simple_interrupted_action": dict(
        obj=("Use was or were + -ing for a longer action in the past, and the past simple for the short event that interrupts it.",
             "Pakai “was/were” + -ing untuk kegiatan panjang di masa lalu, dan past simple untuk kejadian singkat yang memotongnya.",
             "ใช้ 'was/were' + -ing กับการกระทำที่ยาวกว่าในอดีต และใช้ past simple กับเหตุการณ์สั้นที่มาขัดจังหวะ"),
        mis=("Learner uses the same form for both actions, since 'sedang' and 'กำลัง' are often left out.",
             "Kamu memakai bentuk yang sama untuk kedua kejadian, karena kata “sedang” sering dihilangkan.",
             "คุณใช้รูปเดียวกันกับทั้งสองเหตุการณ์ เพราะมักละคำว่า 'กำลัง'"),
        rule=("A long action in progress: was or were + -ing. The short event that cuts in: past simple.",
              "Kegiatan panjang yang sedang berlangsung pakai “was/were” + -ing. Kejadian singkat yang memotongnya pakai past simple.",
              "การกระทำที่ยาวและกำลังดำเนินอยู่ใช้ 'was/were' + -ing ส่วนเหตุการณ์สั้นที่มาขัดจังหวะใช้ past simple"),
        avoid=("Find the two actions: which was already happening, and which happened suddenly?",
               "Cari dua kejadiannya: mana yang sedang berlangsung, dan mana yang terjadi tiba-tiba?",
               "หาสองเหตุการณ์ว่าอันไหนกำลังเกิดอยู่ และอันไหนเกิดขึ้นทันที"),
    ),
    "much_many_little_few_countability": dict(
        obj=("Use many and few with countable plural nouns, and much and little with uncountable nouns.",
             "Pakai “many” dan “few” untuk benda jamak yang bisa dihitung, serta “much” dan “little” untuk benda yang nggak bisa dihitung.",
             "ใช้ 'many' และ 'few' กับคำนามพหูพจน์ที่นับได้ และใช้ 'much' และ 'little' กับคำนามนับไม่ได้"),
        mis=("Learner uses one word for every noun, since 'banyak' and 'sedikit' work with both kinds of nouns.",
             "Kamu memakai satu kata untuk semua benda, karena “banyak” dan “sedikit” bisa dipakai untuk benda apa saja.",
             "คุณใช้คำเดียวกับคำนามทุกแบบ เพราะคำว่า 'มาก' และ 'น้อย' ใช้ได้กับทุกอย่าง"),
        rule=("Countable plural (books, friends): many, few. Uncountable (water, money, time): much, little.",
              "Benda jamak yang bisa dihitung (“books”, “friends”): “many”, “few”. Benda yang nggak bisa dihitung (“water”, “money”, “time”): “much”, “little”.",
              "คำนามพหูพจน์ที่นับได้ ('books', 'friends') ใช้ 'many' กับ 'few' ส่วนคำนามนับไม่ได้ ('water', 'money', 'time') ใช้ 'much' กับ 'little'"),
        avoid=("Can you count the noun one by one? Yes: many or few. No: much or little.",
               "Bendanya bisa dihitung satu per satu? Bisa: “many/few”. Nggak bisa: “much/little”.",
               "ถ้านับคำนามทีละชิ้นได้ ใช้ 'many' หรือ 'few' ถ้านับไม่ได้ ใช้ 'much' หรือ 'little'"),
    ),
    "place_prepositions_at_in_on": dict(
        obj=("Choose at for a point or a place for an activity, in for inside an area, and on for a surface or a floor.",
             "Pilih “at” untuk titik atau tempat kegiatan, “in” untuk di dalam suatu area, dan “on” untuk permukaan atau lantai gedung.",
             "เลือก 'at' สำหรับจุดหรือสถานที่ทำกิจกรรม 'in' สำหรับข้างในพื้นที่ และ 'on' สำหรับพื้นผิวหรือชั้นของอาคาร"),
        mis=("Learner uses one preposition for every place, since 'di' and 'ที่' cover them all.",
             "Kamu memakai satu kata depan untuk semua tempat, karena kata “di” bisa dipakai untuk semuanya.",
             "คุณใช้คำบุพบทคำเดียวกับทุกสถานที่ เพราะคำว่า 'ที่' ใช้ได้กับทุกแบบ"),
        rule=("At: a point or a place for an activity (at the bus stop, at home). In: inside an area (in Jakarta). On: a surface or a floor (on the second floor).",
              "“At”: titik atau tempat kegiatan (“at the bus stop”, “at home”). “In”: di dalam area (“in Jakarta”). “On”: permukaan atau lantai gedung (“on the second floor”).",
              "'at' ใช้กับจุดหรือสถานที่ทำกิจกรรม ('at the bus stop', 'at home') 'in' ใช้กับข้างในพื้นที่ ('in Jakarta') และ 'on' ใช้กับพื้นผิวหรือชั้นของอาคาร ('on the second floor')"),
        avoid=("Ask: a point, an area, or a surface or floor?",
               "Tanya: titik, area, atau permukaan dan lantai?",
               "ถามตัวเองว่าเป็นจุด พื้นที่ หรือพื้นผิวและชั้นของอาคาร"),
    ),
    "as_as_equality_vs_comparative": dict(
        obj=("Use as + adjective + as when two things are the same, and not as … as when one is less.",
             "Pakai “as” + kata sifat + “as” kalau dua hal sama, dan “not as … as” kalau yang satu kalah.",
             "ใช้ 'as' + คำคุณศัพท์ + 'as' เมื่อสองสิ่งเท่ากัน และใช้ 'not as … as' เมื่ออันหนึ่งน้อยกว่า"),
        mis=("Learner mixes as with than or like, or adds -er or more inside as … as.",
             "Kamu mencampur “as” dengan “than” atau “like”, atau menambah -er atau “more” di dalam “as … as”.",
             "คุณผสม 'as' กับ 'than' หรือ 'like' หรือเติม -er หรือ 'more' ไว้ใน 'as … as'"),
        rule=("Same: as + plain adjective + as (as tall as). Less: not as … as. Never than, and no -er or more inside.",
              "Sama: “as” + kata sifat bentuk dasar + “as” (“as tall as”). Kalah: “not as … as”. Jangan pakai “than”, -er, atau “more” di dalamnya.",
              "เท่ากันใช้ 'as' + คำคุณศัพท์รูปพื้นฐาน + 'as' ('as tall as') ถ้าน้อยกว่าใช้ 'not as … as' และห้ามใช้ 'than' หรือเติม -er และ 'more' ข้างใน"),
        avoid=("Same or different? Same: as … as. Then check both as words and the plain adjective.",
               "Sama atau beda? Kalau sama: “as … as”. Lalu cek kedua “as” dan kata sifat bentuk dasarnya.",
               "เท่ากันหรือไม่ ถ้าเท่ากันใช้ 'as … as' แล้วตรวจว่ามี 'as' ครบสองตัวและคำคุณศัพท์เป็นรูปพื้นฐาน"),
    ),
}

# ---- label bersama ----
WILL_IF = ("will used after if", "“will” dipakai di bagian “if”.", "ใช้ 'will' ในส่วนที่มี 'if'")
ING_WILL = ("-ing form used after will", "bentuk -ing dipakai sesudah “will”.", "ใช้คำกริยารูป -ing หลัง 'will'")
DOESNT_PL = ("doesn't used with a plural subject", "“doesn't” dipakai untuk subjek jamak.", "ใช้ 'doesn't' กับประธานพหูพจน์")
PAST_FUT = "uses simple past for an explicitly future consequence"
BARE_AGR = "missing subject-verb agreement / bare form"
ING_ALONE = "reduces the sentence to a fragment: an -ing form with no finite verb to carry the tense"
REAL_HYP = "real condition treated as hypothetical"
PAST_FACT = "past tense used for a timeless fact"
ART_REUSE = "indefinite article reused for an already-identified noun"
ART_VOWEL = "wrong article form regardless of identifiability (vowel-sound rule misapplied)"
QUANT_SG = "quantifier substituted for a singular countable reference"
THE_FIRST = "specific-article overuse"
A_PL = "applies a singular indefinite article to a plural noun"
AN_PL_KNOWN = "applies a singular indefinite article to a plural noun and ignores that the noun is already specific"
ANY_POS = ("negative quantifier used in a positive sentence", "kata jumlah untuk kalimat negatif dipakai di kalimat positif.", "ใช้คำบอกปริมาณของประโยคปฏิเสธในประโยคบอกเล่า")
A_VOWEL = ("a used before a vowel sound", "“a” dipakai sebelum kata yang diawali bunyi vokal.", "ใช้ 'a' หน้าคำที่ขึ้นต้นด้วยเสียงสระ")
AN_KNOWN = ("an used for something the listener can already identify", "“an” dipakai untuk benda yang sudah jelas yang mana.", "ใช้ 'an' กับสิ่งที่ผู้ฟังรู้แล้วว่าอันไหน")
SOME_KNOWN = ("some reused for things already mentioned", "“some” dipakai lagi untuk benda yang sudah disebut.", "ใช้ 'some' ซ้ำกับสิ่งที่พูดถึงแล้ว")
SUP_TWO = "superlative used for a two-item comparison"
MORE_SHORT = "applies the periphrastic 'more + adjective' pattern to a short one-syllable adjective that takes '-er'"
COMP_GROUP = "comparative used for a ranking within a group of three or more"
BASE_THAN = "base adjective used without comparative marking"
DOUBLE_COMP = "doubles the comparative marking by putting 'more' before an adjective already ending in '-er'"
NO_DOUBLE_ER = ("final consonant not doubled before -er", "huruf mati terakhir nggak digandakan sebelum -er.", "ไม่เพิ่มพยัญชนะตัวท้ายก่อนเติม -er")
THE_DROP = ("the dropped before a superlative", "'the' hilang sebelum bentuk 'paling'.", "ขาด 'the' หน้าขั้นสูงสุด")
THE_COMP = ("the used with a comparative for a group", "'the' dipasangkan dengan bentuk 'lebih' untuk satu kelompok.", "ใช้ 'the' คู่กับขั้นกว่าเมื่อเปรียบเทียบทั้งกลุ่ม")
EST_LONG = ("-est added to a long adjective", "akhiran -est ditambahkan ke kata sifat panjang.", "เติม -est ให้คำคุณศัพท์ยาว")
BOTH_DONE = "treats both clauses as sequential completed events"
PRES_SUB = "present-tense substitution"
PROG_SHORT = "aspect confusion (progressive for a single completed trip)"
PERF_PAST = "confuses interrupted past action with present perfect result"
SG_PAST = "singular-past transfer"
IRREG_ED = ("regular -ed added to an irregular verb", "akhiran -ed dipakai untuk kata kerja yang bentuk lampaunya khusus.", "เติม -ed ให้คำกริยาที่มีรูปอดีตพิเศษ")
WAS_YOU = ("singular past be used with you", "bentuk lampau 'was' dipakai untuk 'you'.", "ใช้รูปอดีต 'was' กับประธาน 'you'")
STATEMENT_Q = ("statement order used for a question", "susunan kalimat berita dipakai untuk kalimat tanya.", "ใช้ลำดับของประโยคบอกเล่ากับคำถาม")
MUCH_COUNT = "applies the uncountable-noun quantifier to a countable plural noun"
LITTLE_COUNT = "applies the uncountable-noun quantifier ('little') to a countable plural noun, and also confuses scarcity type"
MANY_UNCOUNT = "countable-quantity-substitution"
FEW_BIG = ("few used when the meaning needs a large number", "“few” (sedikit) dipakai padahal maksudnya jumlah yang banyak.", "ใช้ 'few' ที่แปลว่าน้อย ทั้งที่ความหมายต้องการจำนวนมาก")
FEW_UNCOUNT = ("few or a few used with an uncountable noun", "“few” atau “a few” dipakai untuk benda yang nggak bisa dihitung.", "ใช้ 'few' หรือ 'a few' กับคำนามนับไม่ได้")
OF_DROP = ("of dropped after a lot", "kata “of” hilang sesudah “a lot”.", "ลืมใส่ 'of' หลัง 'a lot'")
A_MANY = ("a placed before many", "“a” ditaruh sebelum “many”.", "วาง 'a' ไว้หน้า 'many'")
MOVE_STATIC = "movement preposition used for a static location"
AT_AREA = ("at used for a city or country", "kata depan untuk titik dipakai untuk kota atau negara.", "ใช้คำบุพบทของจุดกับเมืองหรือประเทศ")
ON_AREA = ("on used for a city or country", "kata depan untuk permukaan dipakai untuk kota atau negara.", "ใช้คำบุพบทของพื้นผิวกับเมืองหรือประเทศ")
IN_POINT = ("in used for a meeting point", "kata depan untuk di dalam dipakai untuk titik pertemuan.", "ใช้คำบุพบทของข้างในกับจุดนัดพบ")
ON_POINT = ("on used for a meeting point", "kata depan untuk permukaan dipakai untuk titik pertemuan.", "ใช้คำบุพบทของพื้นผิวกับจุดนัดพบ")
IN_FLOOR = ("in used for a floor of a building", "kata depan untuk di dalam dipakai untuk lantai gedung.", "ใช้คำบุพบทของข้างในกับชั้นของอาคาร")
AT_FLOOR = ("at used for a floor of a building", "kata depan untuk titik dipakai untuk lantai gedung.", "ใช้คำบุพบทของจุดกับชั้นของอาคาร")
IN_HOME = ("in used instead of the fixed phrase at home", "“in” dipakai untuk frasa tetap “at home”.", "ใช้ 'in' แทนสำนวนตายตัว 'at home'")
ON_HOME = ("on used instead of the fixed phrase at home", "“on” dipakai untuk frasa tetap “at home”.", "ใช้ 'on' แทนสำนวนตายตัว 'at home'")
COMP_EQUAL = "defaults to the comparative form even though the context implies equality, not difference"
AS_THAN = "mixes the equality frame 'as ... as' with comparative 'than'"
COMP_INSIDE = ("comparative form used inside as ... as", "bentuk -er atau “more” dipakai di dalam “as … as”.", "ใช้รูปขั้นกว่า (-er หรือ 'more') ไว้ข้างใน 'as … as'")
LIKE_CLOSE = ("like used to close an as ... as comparison", "“like” dipakai untuk menutup perbandingan “as … as”.", "ใช้ 'like' ปิดการเปรียบเทียบแบบ 'as … as'")
ER_AS = ("comparative -er closed with as instead of than", "bentuk -er ditutup dengan “as”, bukan dengan “than”.", "ใช้รูป -er แล้วปิดด้วย 'as' แทน 'than'")
FIRST_AS = ("first as dropped in an as ... as comparison", "“as” yang pertama hilang dalam perbandingan “as … as”.", "ขาด 'as' ตัวแรกในการเปรียบเทียบแบบ 'as … as'")


def N(label, item_id, item_th):
    """label baru dengan teks khusus untuk soal ini"""
    return label + (item_id, item_th)


def L(name, item_id, item_th):
    return (name, item_id, item_th)


ITEMS = [
    # ---------------- 25. zero vs first conditional ----------------
    dict(s="zero_vs_first_conditional", id="A2-329",
         stem="If it ___ tomorrow, we won't go to the beach.", opts=["rains", "will rain", "rained", "rain"], ans="rains",
         why=("After if we use the present simple, even for tomorrow, so: rains.",
              "Sesudah “if” pakai present simple, walaupun kejadiannya besok, jadi “rains”.",
              "หลัง 'if' ใช้ present simple แม้จะพูดถึงพรุ่งนี้ จึงใช้ 'rains'"),
         others=("'Will rain' puts will after if, 'rained' is past, and 'rain' forgets -s for it.",
                 "“Will rain” menaruh “will” sesudah “if”, “rained” bentuk lampau, dan “rain” lupa -s untuk “it”.",
                 "'will rain' ใส่ 'will' หลัง 'if' ส่วน 'rained' เป็นรูปอดีต และ 'rain' ลืมเติม -s ให้ 'it'"),
         cue=("If + present, will + verb: If it rains, we will stay.", "“If” + present, “will” + kata kerja: “If it rains, we will stay”.", "หลัง 'if' ใช้ปัจจุบัน แล้วค่อยใช้ 'will' ในอีกครึ่งประโยค"),
         rsn=("find the if part -> recall that the if part uses the present -> add -s for it",
              "cari bagian “if” → ingat bagian “if” pakai present → tambah -s untuk “it”",
              "หาส่วนที่มี 'if' → นึกว่าส่วน 'if' ใช้ปัจจุบัน → เติม -s ให้ 'it'"),
         d=[("will rain", WILL_IF,
             "It puts will after if, but the if part uses the present.",
             "menaruh “will” sesudah “if”, padahal bagian “if” memakai present.",
             "ใส่ 'will' หลัง 'if' แต่ส่วนที่มี 'if' ต้องใช้ปัจจุบัน"),
            ("rained", L(PAST_FUT, "bentuk lampau dipakai untuk hari esok.", "ใช้รูปอดีตกับพรุ่งนี้"),
             "It is past, but tomorrow is in the future.",
             "bentuk lampau, padahal “tomorrow” masih di masa depan.",
             "เป็นรูปอดีต แต่ 'tomorrow' ยังเป็นอนาคต"),
            ("rain", L(BARE_AGR, "bentuk dasar dipakai untuk “it”.", "ใช้รูปพื้นฐานกับ 'it'"),
             "It forgets -s, but the subject is it.",
             "lupa -s, padahal subjeknya “it”.",
             "ลืมเติม -s แต่ประธานคือ 'it'")]),
    dict(s="zero_vs_first_conditional", id="A2-330",
         stem="If you mix red and blue, you ___ purple.", opts=["get", "got", "would get", "getting"], ans="get",
         why=("Red and blue always make purple. A fact that is always true uses the present, so: get.",
              "Merah dicampur biru selalu jadi ungu. Fakta yang selalu benar pakai present, jadi “get”.",
              "สีแดงผสมสีน้ำเงินได้สีม่วงเสมอ ความจริงแบบนี้ใช้ปัจจุบัน จึงใช้ 'get'"),
         others=("'Got' is past, 'would get' is for imagined situations, and 'getting' cannot stand alone as the verb.",
                 "“Got” bentuk lampau, “would get” untuk hal yang cuma diandaikan, dan “getting” nggak bisa berdiri sendiri sebagai kata kerja.",
                 "'got' เป็นรูปอดีต ส่วน 'would get' ใช้กับเรื่องสมมุติ และ 'getting' ใช้เป็นคำกริยาตามลำพังไม่ได้"),
         cue=("Always true? Present + present.", "Selalu benar? Present ketemu present.", "ถ้าจริงเสมอ ให้ใช้ปัจจุบันทั้งสองส่วน"),
         rsn=("identify the sentence as a fact that is always true -> recall present + present for facts -> keep the verb in the present",
              "pastikan kalimatnya fakta yang selalu benar → ingat fakta memakai present + present → pakai kata kerja bentuk present",
              "ดูว่าเป็นความจริงที่จริงเสมอ → นึกว่าความจริงใช้ปัจจุบันทั้งสองส่วน → ใช้คำกริยารูปปัจจุบัน"),
         d=[
            ("would get", L(REAL_HYP, "fakta yang nyata diperlakukan sebagai andai-andai.", "มองเงื่อนไขที่จริงเป็นการสมมุติ"),
             "It is for imagined situations, but this really happens.",
             "untuk hal yang cuma diandaikan, padahal ini benar-benar terjadi.",
             "ใช้กับเรื่องสมมุติ แต่นี่เกิดขึ้นจริง"),
            ("got", L(PAST_FACT, "bentuk lampau dipakai untuk fakta yang selalu benar.", "ใช้รูปอดีตกับความจริงที่จริงเสมอ"),
             "It is past, but this fact is true at any time.",
             "bentuk lampau, padahal fakta ini benar kapan saja.",
             "เป็นรูปอดีต แต่ความจริงนี้จริงทุกเวลา"),
            ("getting", L(ING_ALONE, "bentuk -ing dipakai sendirian sebagai kata kerja kalimat.", "ใช้รูป -ing ตามลำพังเป็นคำกริยาของประโยค"),
             "It cannot stand alone as the verb of the sentence.",
             "nggak bisa berdiri sendiri sebagai kata kerja kalimat.",
             "ใช้เป็นคำกริยาหลักของประโยคตามลำพังไม่ได้")]),
    dict(s="zero_vs_first_conditional", id="A2-331",
         stem="Hurry up! If you don't leave now, you ___ the bus.", opts=["will miss", "miss", "missed", "will missing"], ans="will miss",
         why=("This is a warning about one future result, so the result part uses will + the base verb.",
              "Ini peringatan tentang satu akibat nanti, jadi bagian akibatnya pakai “will” + kata kerja dasar.",
              "นี่เป็นคำเตือนถึงผลที่จะเกิดในอนาคต ส่วนผลจึงใช้ 'will' + คำกริยารูปพื้นฐาน"),
         others=("'Miss' sounds like a general fact, 'missed' is past, and 'will missing' adds -ing after will.",
                 "“Miss” terdengar seperti fakta umum, “missed” bentuk lampau, dan “will missing” menambah -ing sesudah “will”.",
                 "'miss' ฟังเหมือนความจริงทั่วไป ส่วน 'missed' เป็นรูปอดีต และ 'will missing' เติม -ing หลัง 'will'"),
         cue=("A warning about later: If you…, you will…", "Peringatan untuk nanti: “If you…, you will…”", "คำเตือนเรื่องอนาคตใช้ 'If you…, you will…'"),
         rsn=("notice hurry up and now -> identify the result as one future event -> combine will with the base verb",
              "perhatikan “Hurry up!” dan “now” → pastikan akibatnya satu kejadian nanti → gabungkan “will” dengan kata kerja dasar",
              "สังเกต 'Hurry up!' และ 'now' → ดูว่าผลเป็นเหตุการณ์ในอนาคต → รวม 'will' กับคำกริยารูปพื้นฐาน"),
         d=[("miss", L("drops the future marker entirely, defaulting to present simple", "penanda masa depan hilang dari bagian akibatnya.", "ส่วนผลไม่มีคำบอกอนาคต"),
             "It has no will, so it sounds like a general fact, not a warning about this bus.",
             "nggak punya “will”, jadi terdengar seperti fakta umum, bukan peringatan soal bus ini.",
             "ไม่มี 'will' จึงฟังเหมือนความจริงทั่วไป ไม่ใช่คำเตือนเรื่องรถคันนี้"),
            ("missed", L(PAST_FUT, "bentuk lampau dipakai untuk akibat yang belum terjadi.", "ใช้รูปอดีตกับผลที่ยังไม่เกิด"),
             "It is past, but the bus has not left yet.",
             "bentuk lampau, padahal busnya belum berangkat.",
             "เป็นรูปอดีต แต่รถยังไม่ออก"),
            ("will missing", ING_WILL,
             "It adds -ing, but after will the verb stays in its base form.",
             "memakai -ing, padahal sesudah “will” kata kerjanya tetap bentuk dasar.",
             "เติม -ing แต่หลัง 'will' คำกริยาต้องเป็นรูปพื้นฐาน")]),
    dict(s="zero_vs_first_conditional", id="A2-332",
         stem="Plants die if they ___ water.", opts=["don't get", "won't get", "didn't get", "doesn't get"], ans="don't get",
         why=("This is always true, so both parts use the present, and they takes don't.",
              "Ini selalu benar, jadi kedua bagiannya pakai present, dan “they” pakai “don't”.",
              "นี่เป็นความจริงเสมอ ทั้งสองส่วนจึงใช้ปัจจุบัน และ 'they' ใช้ 'don't'"),
         others=("'Won't get' puts will after if, 'didn't get' is past, and 'doesn't get' is for he, she, or it.",
                 "“Won't get” menaruh bentuk “will” sesudah “if”, “didn't get” bentuk lampau, dan “doesn't get” untuk “he”, “she”, atau “it”.",
                 "'won't get' ใส่รูปของ 'will' หลัง 'if' ส่วน 'didn't get' เป็นรูปอดีต และ 'doesn't get' ใช้กับประธานเอกพจน์"),
         cue=("Science facts use the present in both parts.", "Fakta ilmiah pakai present di kedua bagian.", "ความจริงทางวิทยาศาสตร์ใช้ปัจจุบันทั้งสองส่วน"),
         rsn=("identify the sentence as a science fact -> recall present + present for facts -> choose the present negative for they",
              "pastikan kalimatnya fakta ilmiah → ingat fakta memakai present + present → pilih bentuk negatif present untuk “they”",
              "ดูว่าเป็นความจริงทางวิทยาศาสตร์ → นึกว่าความจริงใช้ปัจจุบันทั้งสองส่วน → เลือกรูปปฏิเสธปัจจุบันของ 'they'"),
         d=[("won't get", WILL_IF,
             "It puts won't (will not) in the if part, but that part uses the present.",
             "menaruh “won't” (will not) di bagian “if”, padahal bagian itu memakai present.",
             "ใส่ 'won't' ในส่วนที่มี 'if' แต่ส่วนนั้นต้องใช้ปัจจุบัน"),
            ("didn't get", L(PAST_FACT, "bentuk lampau dipakai untuk fakta ilmiah.", "ใช้รูปอดีตกับความจริงทางวิทยาศาสตร์"),
             "It is past, but this fact is always true.",
             "bentuk lampau, padahal fakta ini selalu benar.",
             "เป็นรูปอดีต แต่ความจริงนี้จริงเสมอ"),
            ("doesn't get", DOESNT_PL,
             "It is for he, she, or it, but they means the plants.",
             "untuk “he”, “she”, atau “it”, padahal “they” artinya tanaman-tanaman itu.",
             "ใช้กับประธานเอกพจน์ แต่ 'they' หมายถึงต้นไม้หลายต้น")]),
    # ---------------- 26. first vs second mention ----------------
    dict(s="first_vs_subsequent_mention", id="A2-333",
         stem="Rina has a cat and a rabbit. ___ rabbit is white.", opts=["The", "A", "An", "Some"], ans="The",
         why=("The rabbit was mentioned in the first sentence, so now it takes The.",
              "Kelincinya sudah disebut di kalimat pertama, jadi sekarang pakai “The”.",
              "กระต่ายถูกพูดถึงแล้วในประโยคแรก ตอนนี้จึงใช้ 'The'"),
         others=("'A' and 'An' introduce something new, and 'Some' is for more than one.",
                 "“A” dan “An” untuk memperkenalkan benda baru, dan “Some” untuk lebih dari satu.",
                 "'a' และ 'an' ใช้แนะนำสิ่งใหม่ ส่วน 'some' ใช้กับมากกว่าหนึ่ง"),
         cue=("Said before? Use the.", "Sudah disebut? Pakai “the”.", "ถ้าพูดถึงไปแล้ว ให้ใช้ 'the'"),
         rsn=("check the first sentence -> notice the rabbit is already mentioned -> choose the article for a known thing",
              "lihat kalimat pertama → perhatikan kelincinya sudah disebut → pilih kata sandang untuk benda yang sudah dikenal",
              "ดูประโยคแรก → สังเกตว่าพูดถึงกระต่ายไปแล้ว → เลือกคำนำหน้านามสำหรับสิ่งที่รู้แล้ว"),
         d=[("A", L(ART_REUSE, "“a” dipakai lagi untuk kelinci yang sudah disebut.", "ใช้ 'a' ซ้ำกับกระต่ายที่พูดถึงแล้ว"),
             "It introduces a new rabbit, but we already know this one.",
             "memperkenalkan kelinci baru, padahal kelinci ini sudah kita kenal.",
             "เหมือนแนะนำกระต่ายตัวใหม่ แต่เรารู้จักตัวนี้แล้ว"),
            ("An", L(ART_VOWEL, "“an” dipakai sebelum bunyi konsonan.", "ใช้ 'an' หน้าเสียงพยัญชนะ"),
             "It is for a vowel sound, and the rabbit is already known anyway.",
             "untuk bunyi vokal, dan kelincinya pun sudah dikenal.",
             "ใช้หน้าเสียงสระ และกระต่ายตัวนี้ก็รู้จักแล้ว"),
            ("Some", L(QUANT_SG, "kata jumlah dipakai untuk satu kelinci tertentu.", "ใช้คำบอกปริมาณกับกระต่ายตัวเดียวที่เจาะจง"),
             "It is for more than one, but there is one rabbit.",
             "untuk lebih dari satu, padahal kelincinya cuma satu.",
             "ใช้กับมากกว่าหนึ่ง แต่มีกระต่ายตัวเดียว")]),
    dict(s="first_vs_subsequent_mention", id="A2-334",
         stem="Yesterday I found ___ old photo in a box. The photo shows my grandma.", opts=["an", "the", "a", "any"], ans="an",
         why=("The photo is new in the story, and old starts with a vowel sound, so we say an old photo.",
              "Fotonya baru pertama disebut, dan “old” diawali bunyi vokal. Hasilnya “an old photo”.",
              "รูปเพิ่งถูกพูดถึงครั้งแรก และ 'old' ขึ้นต้นด้วยเสียงสระ จึงได้เป็น 'an old photo'"),
         others=("'The' comes at the second mention, 'a' needs a consonant sound, and 'any' is for questions and negatives.",
                 "“The” dipakai saat disebut kedua kali, “a” butuh bunyi konsonan, dan “any” untuk kalimat tanya atau negatif.",
                 "'the' ใช้ตอนพูดถึงครั้งที่สอง ส่วน 'a' ต้องตามด้วยเสียงพยัญชนะ และ 'any' ใช้ในคำถามหรือประโยคปฏิเสธ"),
         cue=("First time + vowel sound: an old photo. Next time: the photo.", "Pertama + bunyi vokal: “an old photo”. Berikutnya: “the photo”.", "ครั้งแรกและขึ้นต้นด้วยเสียงสระใช้ 'an old photo' ครั้งต่อไปใช้ 'the photo'"),
         rsn=("check if the photo is new in the story -> identify the first sound of old -> choose the article for a first mention",
              "cek fotonya baru disebut atau belum → dengarkan bunyi awal “old” → pilih kata sandang untuk benda yang baru disebut",
              "ดูว่ารูปเพิ่งถูกพูดถึงหรือไม่ → ฟังเสียงแรกของ 'old' → เลือกคำนำหน้านามสำหรับสิ่งที่เพิ่งพูดถึง"),
         d=[("the", L(THE_FIRST, "“the” dipakai untuk foto yang baru pertama disebut.", "ใช้ 'the' กับรูปที่เพิ่งพูดถึงครั้งแรก"),
             "It is for the second mention, which comes in the next sentence.",
             "baru dipakai saat fotonya disebut kedua kali, yaitu di kalimat berikutnya.",
             "ใช้ตอนพูดถึงรูปครั้งที่สอง ซึ่งอยู่ในประโยคถัดไป"),
            ("a", A_VOWEL,
             "It needs a consonant sound, but old starts with a vowel sound.",
             "butuh bunyi konsonan, padahal “old” diawali bunyi vokal.",
             "ต้องตามด้วยเสียงพยัญชนะ แต่ 'old' ขึ้นต้นด้วยเสียงสระ"),
            ("any", N(ANY_POS, "“any” dipakai untuk memperkenalkan satu foto di kalimat positif.", "ใช้ 'any' แนะนำรูปหนึ่งใบในประโยคบอกเล่า"),
             "It is for questions and negatives, and it does not introduce one new photo.",
             "dipakai di kalimat tanya dan negatif, bukan untuk memperkenalkan satu foto baru.",
             "ใช้ในคำถามและประโยคปฏิเสธ ไม่ได้ใช้แนะนำรูปใบใหม่หนึ่งใบ")]),
    dict(s="first_vs_subsequent_mention", id="A2-335",
         stem="We watched a film last night. ___ ending was very sad.", opts=["The", "A", "An", "Some"], ans="The",
         why=("We know which ending: the ending of the film we just mentioned, so we use The.",
              "Kita tahu akhir cerita yang mana, yaitu akhir film yang baru disebut, jadi pakai “The”.",
              "เรารู้ว่าตอนจบไหน คือตอนจบของหนังที่เพิ่งพูดถึง จึงใช้ 'The'"),
         others=("'A' and 'An' mean any ending, and 'Some' is for more than one.",
                 "“A” dan “An” artinya akhir cerita yang mana saja, dan “Some” untuk lebih dari satu.",
                 "'a' และ 'an' หมายถึงตอนจบไหนก็ได้ ส่วน 'some' ใช้กับมากกว่าหนึ่ง"),
         cue=("Part of something already mentioned? Use the: the ending, the actors.", "Bagian dari benda yang sudah disebut? Pakai “the”: “the ending”, “the actors”.", "ถ้าเป็นส่วนหนึ่งของสิ่งที่พูดถึงแล้ว ให้ใช้ 'the' เช่น 'the actors'"),
         rsn=("check the first sentence -> match the ending to the film -> choose the article for a known thing",
              "lihat kalimat pertama → cocokkan akhir cerita dengan filmnya → pilih kata sandang untuk benda yang sudah dikenal",
              "ดูประโยคแรก → จับคู่ตอนจบกับหนังเรื่องนั้น → เลือกคำนำหน้านามสำหรับสิ่งที่รู้แล้ว"),
         d=[("A", L(ART_REUSE, "“a” dipakai untuk akhir film yang sudah jelas yang mana.", "ใช้ 'a' กับตอนจบของหนังที่รู้แล้วว่าตอนไหน"),
             "It means any ending, but we mean the ending of this film.",
             "artinya akhir cerita yang mana saja, padahal yang dimaksud akhir film ini.",
             "หมายถึงตอนจบไหนก็ได้ แต่เราหมายถึงตอนจบของหนังเรื่องนี้"),
            ("An", AN_KNOWN,
             "It fits the vowel sound, but it still means any ending, not this film's.",
             "cocok dengan bunyi vokal, tapi tetap berarti akhir cerita yang mana saja.",
             "เข้ากับเสียงสระ แต่ยังหมายถึงตอนจบไหนก็ได้ ไม่ใช่ของหนังเรื่องนี้"),
            ("Some", L(QUANT_SG, "kata jumlah dipakai untuk satu akhir cerita.", "ใช้คำบอกปริมาณกับตอนจบเดียว"),
             "It is for more than one, but a film has one ending.",
             "untuk lebih dari satu, padahal filmnya punya satu akhir cerita.",
             "ใช้กับมากกว่าหนึ่ง แต่หนังมีตอนจบเดียว")]),
    dict(s="first_vs_subsequent_mention", id="A2-336",
         stem="My mum bought some apples yesterday. ___ apples were all sweet.", opts=["The", "Some", "A", "An"], ans="The",
         why=("The apples were already mentioned, so we use The, also for plural nouns.",
              "Apelnya sudah disebut, jadi pakai “The”, termasuk untuk benda jamak.",
              "แอปเปิลถูกพูดถึงไปแล้ว จึงใช้ 'The' แม้เป็นคำนามพหูพจน์"),
         others=("'Some' would mean other apples or only some of them, and 'A' and 'An' are for one new thing.",
                 "“Some” berarti apel lain atau cuma sebagian, sedangkan “A” dan “An” untuk satu benda baru.",
                 "'some' หมายถึงแอปเปิลอื่นหรือแค่บางลูก ส่วน 'a' และ 'an' ใช้กับสิ่งใหม่ชิ้นเดียว"),
         cue=("Mentioned before, one or many: the.", "Sudah disebut, satu atau banyak: “the”.", "ถ้าพูดถึงแล้ว ไม่ว่าหนึ่งหรือหลาย ให้ใช้ 'the'"),
         rsn=("check the first sentence -> notice the apples are already mentioned -> choose the article for known things",
              "lihat kalimat pertama → perhatikan apelnya sudah disebut → pilih kata sandang untuk benda yang sudah dikenal",
              "ดูประโยคแรก → สังเกตว่าพูดถึงแอปเปิลไปแล้ว → เลือกคำนำหน้านามสำหรับสิ่งที่รู้แล้ว"),
         d=[("Some", SOME_KNOWN,
             "It means other apples or only part of them, but all shows we mean every apple Mum bought.",
             "berarti apel lain atau cuma sebagian, padahal “all” menunjuk semua apel yang tadi dibeli Ibu.",
             "หมายถึงแอปเปิลอื่นหรือแค่บางลูก แต่ 'all' บอกว่าหมายถึงแอปเปิลทุกลูกที่แม่ซื้อมา"),
            ("A", L(A_PL, "“a” dipakai sebelum “apples” yang jamak.", "ใช้ 'a' หน้า 'apples' ซึ่งเป็นพหูพจน์"),
             "It is for one thing, but apples are many.",
             "untuk satu benda, padahal “apples” banyak.",
             "ใช้กับสิ่งเดียว แต่ 'apples' มีหลายลูก"),
            ("An", L(AN_PL_KNOWN, "“an” dipakai sebelum “apples” yang jamak dan sudah disebut.", "ใช้ 'an' หน้า 'apples' ที่เป็นพหูพจน์และพูดถึงไปแล้ว"),
             "It fits the vowel sound, but it is for one thing and apples are many.",
             "cocok dengan bunyi vokal, tapi untuk satu benda, padahal apelnya banyak.",
             "เข้ากับเสียงสระ แต่ใช้กับสิ่งเดียว ขณะที่แอปเปิลมีหลายลูก")]),
    # ---------------- 27. comparative vs superlative ----------------
    dict(s="comparative_vs_superlative_scope", id="A2-337",
         stem="Which is ___, a cat or a dog?", opts=["bigger", "the biggest", "biger", "more big"], ans="bigger",
         why=("Only two animals are compared, so we use the comparative, bigger.",
              "Cuma dua hewan yang dibandingkan, jadi pakai bentuk “lebih”, yaitu “bigger”.",
              "เปรียบเทียบสัตว์แค่สองตัว จึงใช้ขั้นกว่า คือ 'bigger'"),
         others=("'The biggest' is for a group of three or more, 'biger' forgets to double the g, and 'more big' is wrong for a short word.",
                 "“The biggest” untuk kelompok tiga atau lebih, “biger” lupa menggandakan huruf g, dan “more big” salah untuk kata pendek.",
                 "'the biggest' ใช้กับกลุ่มตั้งแต่สามขึ้นไป ส่วน 'biger' ลืมเพิ่ม g อีกตัว และ 'more big' ผิดสำหรับคำสั้น"),
         cue=("A or B? Use -er: big becomes bigger, fast becomes faster.", "Pilih A atau B? Pakai -er: “big” jadi “bigger”, “fast” jadi “faster”.", "ถ้าเลือกระหว่างสองอย่าง ให้ใช้ -er เช่น 'fast' กลายเป็น 'faster'"),
         rsn=("count the things compared -> identify two animals -> choose the comparative form",
              "hitung yang dibandingkan → temukan dua hewan → pilih bentuk “lebih”",
              "นับสิ่งที่เปรียบเทียบ → เห็นว่ามีสัตว์สองตัว → เลือกรูปขั้นกว่า"),
         d=[("the biggest", L(SUP_TWO, "bentuk “paling” dipakai untuk dua hewan.", "ใช้ขั้นสูงสุดกับสัตว์สองตัว"),
             "It is for a group of three or more, but only two animals are compared.",
             "untuk kelompok tiga atau lebih, padahal yang dibandingkan cuma dua hewan.",
             "ใช้กับกลุ่มตั้งแต่สามขึ้นไป แต่เปรียบเทียบสัตว์แค่สองตัว"),
            ("biger", NO_DOUBLE_ER,
             "It forgets to double the g before -er.",
             "lupa menggandakan huruf g sebelum -er.",
             "ลืมเพิ่ม g อีกตัวก่อนเติม -er"),
            ("more big", L(MORE_SHORT, "pola “more” dipakai untuk kata sifat pendek.", "ใช้ 'more' กับคำคุณศัพท์สั้น"),
             "Short words like big take -er, not more.",
             "memakai “more”, padahal kata pendek seperti “big” cukup diberi -er.",
             "ใช้ 'more' แต่คำสั้นอย่าง 'big' ใช้ -er")]),
    dict(s="comparative_vs_superlative_scope", id="A2-338",
         stem="Andi is ___ student in our class. He always gets 100!", opts=["the smartest", "smarter", "smartest", "the smarter"], ans="the smartest",
         why=("Andi is compared with the whole class, so we use the + -est, the smartest.",
              "Andi dibandingkan dengan seluruh kelas, jadi pakai “the” + -est, yaitu “the smartest”.",
              "เปรียบเทียบแอนดี้กับทั้งห้อง จึงใช้ 'the' + -est คือ 'the smartest'"),
         others=("'Smarter' is for two people, 'smartest' needs the, and 'the smarter' mixes the with a two-thing form.",
                 "“Smarter” untuk dua orang, “smartest” butuh “the”, dan “the smarter” mencampur “the” dengan bentuk untuk dua hal.",
                 "'smarter' ใช้กับสองคน ส่วน 'smartest' ต้องมี 'the' และ 'the smarter' ผสม 'the' กับรูปที่ใช้กับสองสิ่ง"),
         cue=("In our class, in the world: the + -est.", "Di kelas, di dunia: “the” + -est.", "ถ้าเปรียบในห้องหรือในโลก ให้ใช้ 'the' + -est"),
         rsn=("notice in our class -> identify a group of many students -> choose the superlative with the",
              "perhatikan “in our class” → pastikan yang dibandingkan satu kelompok → pilih bentuk “paling” dengan “the”",
              "สังเกต 'in our class' → ดูว่าเปรียบเทียบทั้งกลุ่ม → เลือกขั้นสูงสุดที่มี 'the'"),
         d=[("smarter", L(COMP_GROUP, "bentuk “lebih” dipakai untuk satu kelas.", "ใช้ขั้นกว่ากับทั้งห้อง"),
             "It compares two people, but Andi is compared with the whole class.",
             "membandingkan dua orang, padahal Andi dibandingkan dengan seluruh kelas.",
             "เปรียบเทียบคนสองคน แต่แอนดี้ถูกเปรียบกับทั้งห้อง"),
            ("smartest", THE_DROP,
             "It forgets the; a superlative always needs it.",
             "lupa “the”, padahal bentuk “paling” selalu butuh “the”.",
             "ลืม 'the' แต่ขั้นสูงสุดต้องมี 'the' เสมอ"),
            ("the smarter", THE_COMP,
             "It mixes the with a two-thing form; a group needs -est.",
             "mencampur “the” dengan bentuk untuk dua hal, padahal kelompok butuh -est.",
             "ผสม 'the' กับรูปที่ใช้กับสองสิ่ง แต่ทั้งกลุ่มต้องใช้ -est")]),
    dict(s="comparative_vs_superlative_scope", id="A2-339",
         stem="My phone is ___ than yours, but Dita's is the cheapest.", opts=["cheaper", "the cheapest", "cheap", "more cheaper"], ans="cheaper",
         why=("'Than' compares two phones, so we use cheaper.",
              "“Than” membandingkan dua ponsel, jadi pakai “cheaper”.",
              "'than' เปรียบเทียบโทรศัพท์สองเครื่อง จึงใช้ 'cheaper'"),
         others=("'The cheapest' is for a group, 'cheap' does not compare, and 'more cheaper' marks the comparison twice.",
                 "“The cheapest” untuk satu kelompok, “cheap” nggak membandingkan, dan “more cheaper” menandai perbandingan dua kali.",
                 "'the cheapest' ใช้กับทั้งกลุ่ม ส่วน 'cheap' ไม่ได้เปรียบเทียบ และ 'more cheaper' บอกการเปรียบเทียบซ้ำสองครั้ง"),
         cue=("Than = two things = -er.", "Ada “than” = dua hal = -er.", "มี 'than' แปลว่าเปรียบเทียบสองสิ่ง จึงใช้ -er"),
         rsn=("notice than after the blank -> count two phones -> choose the comparative form",
              "perhatikan “than” sesudah titik-titik → hitung dua ponsel → pilih bentuk “lebih”",
              "สังเกต 'than' หลังช่องว่าง → นับว่ามีโทรศัพท์สองเครื่อง → เลือกรูปขั้นกว่า"),
         d=[("the cheapest", L(SUP_TWO, "bentuk “paling” dipakai untuk dua ponsel.", "ใช้ขั้นสูงสุดกับโทรศัพท์สองเครื่อง"),
             "It ranks a group, but than compares only two phones.",
             "untuk juara satu kelompok, padahal “than” cuma membandingkan dua ponsel.",
             "ใช้จัดอันดับทั้งกลุ่ม แต่ 'than' เปรียบเทียบแค่สองเครื่อง"),
            ("cheap", L(BASE_THAN, "kata sifat bentuk dasar dipakai sebelum “than”.", "ใช้คำคุณศัพท์รูปพื้นฐานหน้า 'than'"),
             "It does not compare, but than needs a comparative.",
             "nggak membandingkan, padahal “than” butuh bentuk “lebih”.",
             "ไม่ได้เปรียบเทียบ แต่ 'than' ต้องใช้รูปขั้นกว่า"),
            ("more cheaper", L(DOUBLE_COMP, "“more” ditumpuk di depan kata sifat yang sudah ber-er.", "ใช้ 'more' ซ้อนหน้าคำที่เติม -er แล้ว"),
             "It marks the comparison twice; -er alone is enough.",
             "menandai perbandingan dua kali, padahal -er saja sudah cukup.",
             "บอกการเปรียบเทียบซ้ำสองครั้ง ทั้งที่ใช้ -er อย่างเดียวก็พอ")]),
    dict(s="comparative_vs_superlative_scope", id="A2-340",
         stem="This is ___ book in the library.", opts=["the most interesting", "more interesting", "the interestingest", "most interesting"], ans="the most interesting",
         why=("The book is compared with all the books in the library, and interesting is a long word, so: the most interesting.",
              "Bukunya dibandingkan dengan semua buku di perpustakaan, dan “interesting” kata panjang, jadi “the most interesting”.",
              "หนังสือเล่มนี้เปรียบกับหนังสือทั้งห้องสมุด และ 'interesting' เป็นคำยาว จึงใช้ 'the most interesting'"),
         others=("'More interesting' is for two things, 'the interestingest' adds -est to a long word, and 'most interesting' forgets the.",
                 "“More interesting” untuk dua hal, “the interestingest” menambah -est ke kata panjang, dan “most interesting” lupa “the”.",
                 "ตัวเลือกที่มี 'more' ใช้เปรียบเทียบแค่สองสิ่ง ตัวเลือกที่เติม -est ผิดเพราะคำยาวต้องใช้ 'most' และตัวเลือกที่ไม่มี 'the' ก็ขาดคำที่ขั้นสูงสุดต้องมี"),
         cue=("Long word + group: the most + the word.", "Kata panjang + satu kelompok: “the most” + kata sifat.", "ถ้าเป็นคำยาวและเปรียบทั้งกลุ่ม ให้ใช้ 'the most' + คำคุณศัพท์"),
         rsn=("notice in the library -> identify a big group of books -> choose the superlative for a long word",
              "perhatikan “in the library” → pastikan yang dibandingkan banyak buku → pilih bentuk “paling” untuk kata panjang",
              "สังเกต 'in the library' → ดูว่าเปรียบกับหนังสือจำนวนมาก → เลือกขั้นสูงสุดของคำยาว"),
         d=[("more interesting", L(COMP_GROUP, "bentuk “lebih” dipakai untuk semua buku di perpustakaan.", "ใช้ขั้นกว่ากับหนังสือทั้งห้องสมุด"),
             "It compares two things, but here the book is compared with the whole library.",
             "membandingkan dua hal, padahal bukunya dibandingkan dengan seisi perpustakaan.",
             "เปรียบเทียบสองสิ่ง แต่เล่มนี้ถูกเปรียบกับทั้งห้องสมุด"),
            ("the interestingest", EST_LONG,
             "Long words take most, not -est.",
             "memakai -est, padahal kata sifat panjang memakai “most”.",
             "เติม -est แต่คำยาวต้องใช้ 'most'"),
            ("most interesting", THE_DROP,
             "It forgets the before most.",
             "lupa “the” sebelum “most”.",
             "ลืมใส่ 'the' หน้า 'most'")]),
    # ---------------- 28. past continuous vs past simple ----------------
    dict(s="past_continuous_vs_past_simple_interrupted_action", id="A2-341",
         stem="We ___ TV when the lights went out.", opts=["were watching", "watched", "was watching", "are watching"], ans="were watching",
         why=("Watching TV was the longer action already happening, and we takes were, so: were watching.",
              "Menonton TV adalah kegiatan panjang yang sedang berlangsung, dan “we” pakai “were”, jadi “were watching”.",
              "การดูทีวีเป็นการกระทำที่ยาวและกำลังเกิดอยู่ และ 'we' ใช้ 'were' จึงเป็น 'were watching'"),
         others=("'Watched' makes it a short finished action, 'was watching' is for I, he, she, or it, and 'are watching' is present.",
                 "“Watched” membuatnya jadi kejadian singkat yang selesai, “was watching” untuk “I”, “he”, “she”, atau “it”, dan “are watching” bentuk sekarang.",
                 "'watched' ทำให้เป็นเหตุการณ์สั้นที่จบแล้ว ส่วน 'was watching' ใช้กับประธานเอกพจน์ และ 'are watching' เป็นรูปปัจจุบัน"),
         cue=("Long action: were + -ing. Short event: went out.", "Kegiatan panjang: “were” + -ing. Kejadian singkat: “went out”.", "การกระทำที่ยาวใช้ 'were' + -ing ส่วนเหตุการณ์สั้นคือ 'went out'"),
         rsn=("find the short event the lights went out -> identify watching TV as the long action -> combine were with -ing",
              "cari kejadian singkatnya, yaitu lampu padam → pastikan menonton TV kegiatan yang panjang → gabungkan “were” dengan -ing",
              "หาเหตุการณ์สั้นซึ่งก็คือไฟดับ → ดูว่าการดูทีวีเป็นการกระทำที่ยาว → รวม 'were' กับ -ing"),
         d=[("watched", L(BOTH_DONE, "kegiatan panjang ditulis sebagai kejadian singkat yang selesai.", "เขียนการกระทำที่ยาวเป็นเหตุการณ์สั้นที่จบแล้ว"),
             "It makes watching a short finished action, so the idea of being interrupted is lost.",
             "membuat kegiatan menonton jadi kejadian singkat yang selesai, jadi makna terpotongnya hilang.",
             "ทำให้การดูทีวีกลายเป็นเหตุการณ์สั้นที่จบแล้ว ความหมายว่าถูกขัดจังหวะจึงหายไป"),
            ("was watching", L(SG_PAST, "bentuk tunggal “was” dipakai untuk “we”.", "ใช้ 'was' รูปเอกพจน์กับ 'we'"),
             "It is for I, he, she, or it, but the subject is we.",
             "untuk “I”, “he”, “she”, atau “it”, padahal subjeknya “we”.",
             "ใช้กับ 'I', 'he', 'she', 'it' แต่ประธานคือ 'we'"),
            ("are watching", L(PRES_SUB, "bentuk sekarang dipakai untuk cerita masa lalu.", "ใช้รูปปัจจุบันกับเรื่องในอดีต"),
             "It is present, but went out shows the story is in the past.",
             "bentuk sekarang, padahal “went out” menunjukkan ceritanya di masa lalu.",
             "เป็นรูปปัจจุบัน แต่ 'went out' บอกว่าเรื่องนี้เกิดในอดีต")]),
    dict(s="past_continuous_vs_past_simple_interrupted_action", id="A2-342",
         stem="I was sleeping when my phone suddenly ___.", opts=["rang", "was ringing", "rings", "ringed"], ans="rang",
         why=("'Suddenly' shows a short event that cut into my sleep, so it takes the past simple, rang.",
              "“Suddenly” menunjukkan kejadian singkat yang memotong tidurku, jadi pakai past simple, yaitu “rang”.",
              "'suddenly' บอกว่าเป็นเหตุการณ์สั้นที่มาขัดตอนหลับ จึงใช้ past simple คือ 'rang'"),
         others=("'Was ringing' makes it a long action, 'rings' is present, and 'ringed' is not the past of ring.",
                 "“Was ringing” membuatnya jadi kegiatan panjang, “rings” bentuk sekarang, dan “ringed” bukan bentuk lampau dari “ring”.",
                 "'was ringing' ทำให้เป็นการกระทำที่ยาว ส่วน 'rings' เป็นรูปปัจจุบัน และ 'ringed' ไม่ใช่รูปอดีตของ 'ring'"),
         cue=("Suddenly = a short event = past simple.", "“Suddenly” = kejadian singkat = past simple.", "'suddenly' คือเหตุการณ์สั้น จึงใช้ past simple"),
         rsn=("notice the word suddenly -> identify the ringing as the short event -> choose the past simple form of ring",
              "perhatikan kata “suddenly” → pastikan dering ponsel kejadian singkat → pilih bentuk past simple dari “ring”",
              "สังเกตคำว่า 'suddenly' → ดูว่าเสียงโทรศัพท์ดังเป็นเหตุการณ์สั้น → เลือกรูป past simple ของ 'ring'"),
         d=[("was ringing", L(PROG_SHORT, "bentuk sedang berlangsung dipakai untuk kejadian singkat.", "ใช้รูปกำลังเกิดกับเหตุการณ์สั้น"),
             "It makes the ringing a long action, but suddenly shows a short one.",
             "membuat deringnya jadi kegiatan panjang, padahal “suddenly” menunjukkan kejadian singkat.",
             "ทำให้เสียงดังเป็นการกระทำที่ยาว แต่ 'suddenly' บอกว่าเป็นเหตุการณ์สั้น"),
            ("rings", L(PRES_SUB, "bentuk sekarang dipakai untuk cerita masa lalu.", "ใช้รูปปัจจุบันกับเรื่องในอดีต"),
             "It is present, but was sleeping shows the past.",
             "bentuk sekarang, padahal “was sleeping” menunjukkan masa lalu.",
             "เป็นรูปปัจจุบัน แต่ 'was sleeping' บอกว่าเป็นอดีต"),
            ("ringed", IRREG_ED,
             "Ring is irregular; its past form is not made with -ed.",
             "memakai -ed, padahal “ring” punya bentuk lampau khusus.",
             "เติม -ed แต่ 'ring' มีรูปอดีตพิเศษ")]),
    dict(s="past_continuous_vs_past_simple_interrupted_action", id="A2-343",
         stem="What ___ when the teacher came in?", opts=["were you doing", "was you doing", "you were doing", "are you doing"], ans="were you doing",
         why=("The question asks about an action in progress when the teacher came in, and you takes were: were you doing.",
              "Pertanyaannya menanyakan kegiatan yang sedang berlangsung saat guru masuk, dan “you” pakai “were”, jadi “were you doing”.",
              "คำถามถามถึงสิ่งที่กำลังทำอยู่ตอนครูเข้ามา และ 'you' ใช้ 'were' จึงเป็น 'were you doing'"),
         others=("'Was you doing' uses the wrong be for you, 'you were doing' keeps statement order, and 'are you doing' is present.",
                 "“Was you doing” memakai bentuk “be” yang salah untuk “you”, “you were doing” memakai susunan kalimat berita, dan “are you doing” bentuk sekarang.",
                 "'was you doing' ใช้รูป 'be' ผิดกับ 'you' ส่วน 'you were doing' ใช้ลำดับประโยคบอกเล่า และ 'are you doing' เป็นรูปปัจจุบัน"),
         cue=("In progress in the past? Were you + -ing?", "Sedang berlangsung di masa lalu? “Were you” + -ing?", "ถ้าถามว่ากำลังทำอะไรอยู่ในอดีต ให้ใช้ 'Were you' + -ing"),
         rsn=("notice the word when -> identify the question as asking about an action in progress -> place were before you",
              "perhatikan kata “when” → pastikan yang ditanya kegiatan yang sedang berlangsung → taruh “were” sebelum “you”",
              "สังเกตคำว่า 'when' → ดูว่าถามถึงสิ่งที่กำลังทำอยู่ → วาง 'were' ไว้หน้า 'you'"),
         d=[("was you doing", WAS_YOU,
             "It is wrong for you, because you always takes were, even for one person.",
             "salah untuk “you”, karena “you” selalu memakai “were”, walaupun cuma satu orang.",
             "ผิดสำหรับ 'you' เพราะ 'you' ใช้ 'were' เสมอ แม้เป็นคนเดียว"),
            ("you were doing", STATEMENT_Q,
             "It keeps statement order, so it is not a question.",
             "memakai susunan kalimat berita, jadi belum jadi pertanyaan.",
             "ใช้ลำดับของประโยคบอกเล่า จึงยังไม่เป็นคำถาม"),
            ("are you doing", L(PRES_SUB, "bentuk sekarang dipakai untuk pertanyaan tentang masa lalu.", "ใช้รูปปัจจุบันถามเรื่องในอดีต"),
             "It is present, but came in shows the past.",
             "bentuk sekarang, padahal “came in” menunjukkan masa lalu.",
             "เป็นรูปปัจจุบัน แต่ 'came in' บอกว่าเป็นอดีต")]),
    dict(s="past_continuous_vs_past_simple_interrupted_action", id="A2-344",
         stem="Rani ___ her arm while she was playing basketball.", opts=["broke", "was breaking", "breaked", "has broken"], ans="broke",
         why=("Breaking an arm is a short event during the longer game, so it takes the past simple, broke.",
              "Patah tangan itu kejadian singkat di tengah permainan yang panjang, jadi pakai past simple, yaitu “broke”.",
              "แขนหักเป็นเหตุการณ์สั้นระหว่างการเล่นที่ยาวกว่า จึงใช้ past simple คือ 'broke'"),
         others=("'Was breaking' makes it a long action, 'breaked' is not a real past form, and 'has broken' does not go with a finished past time.",
                 "“Was breaking” membuatnya jadi kegiatan panjang, “breaked” bukan bentuk lampau yang benar, dan “has broken” nggak cocok dengan waktu lampau yang sudah selesai.",
                 "'was breaking' ทำให้เป็นการกระทำที่ยาว ส่วน 'breaked' ไม่ใช่รูปอดีตที่ถูก และ 'has broken' ใช้กับเวลาในอดีตที่จบแล้วไม่ได้"),
         cue=("A short event inside a long one: past simple.", "Kejadian singkat di tengah kegiatan panjang: past simple.", "เหตุการณ์สั้นที่เกิดระหว่างการกระทำที่ยาว ใช้ past simple"),
         rsn=("find the long action was playing -> identify breaking as the short event -> choose the irregular past form of break",
              "cari kegiatan panjangnya, “was playing” → pastikan patahnya kejadian singkat → pilih bentuk lampau khusus dari “break”",
              "หาการกระทำที่ยาว 'was playing' → ดูว่าแขนหักเป็นเหตุการณ์สั้น → เลือกรูปอดีตพิเศษของ 'break'"),
         d=[("was breaking", L(PROG_SHORT, "bentuk sedang berlangsung dipakai untuk kejadian singkat.", "ใช้รูปกำลังเกิดกับเหตุการณ์สั้น"),
             "It makes the break a long action, but it happened in a moment.",
             "membuat patahnya jadi kegiatan panjang, padahal terjadi dalam sekejap.",
             "ทำให้แขนหักกลายเป็นการกระทำที่ยาว แต่มันเกิดขึ้นในพริบตา"),
            ("breaked", IRREG_ED,
             "Break is irregular; its past form is not made with -ed.",
             "memakai -ed, padahal “break” punya bentuk lampau khusus.",
             "เติม -ed แต่ 'break' มีรูปอดีตพิเศษ"),
            ("has broken", L(PERF_PAST, "bentuk “has” + kata kerja bentuk ketiga dipakai untuk kejadian lampau yang jelas waktunya.", "ใช้ 'has' + กริยาช่อง 3 กับเหตุการณ์ในอดีตที่รู้เวลาชัดเจน"),
             "It does not go with while she was playing, a finished past time.",
             "nggak cocok dengan “while she was playing”, waktu lampau yang sudah selesai.",
             "ใช้ไม่ได้กับ 'while she was playing' ซึ่งเป็นเวลาในอดีตที่จบแล้ว")]),
    # ---------------- 29. much / many / little / few ----------------
    dict(s="much_many_little_few_countability", id="A2-345",
         stem="There are too ___ people on this bus. I can't sit down.", opts=["many", "much", "little", "few"], ans="many",
         why=("People can be counted, and the bus is full, so we use many.",
              "“People” bisa dihitung, dan busnya penuh, jadi pakai “many”.",
              "'people' นับได้ และรถเมล์เต็ม จึงใช้ 'many'"),
         others=("'Much' and 'little' are for things you cannot count, and 'few' would mean the bus is almost empty.",
                 "“Much” dan “little” untuk benda yang nggak bisa dihitung, dan “few” berarti busnya hampir kosong.",
                 "'much' และ 'little' ใช้กับสิ่งที่นับไม่ได้ ส่วน 'few' จะแปลว่ารถเกือบว่าง"),
         cue=("People can be counted: too many people.", "Orang bisa dihitung: “too many people”.", "คนนับได้ จึงใช้ 'too many people'"),
         rsn=("check if people can be counted -> decide if there are a lot or a few -> choose the word for a lot of countable things",
              "cek “people” bisa dihitung atau nggak → putuskan jumlahnya banyak atau sedikit → pilih kata untuk banyak benda yang bisa dihitung",
              "ดูว่า 'people' นับได้หรือไม่ → ตัดสินว่ามีมากหรือน้อย → เลือกคำสำหรับของนับได้จำนวนมาก"),
         d=[("much", L(MUCH_COUNT, "“much” dipakai untuk “people”.", "ใช้ 'much' กับ 'people'"),
             "It is for things you cannot count, but people can be counted.",
             "untuk benda yang nggak bisa dihitung, padahal orang bisa dihitung.",
             "ใช้กับสิ่งที่นับไม่ได้ แต่คนนับได้"),
            ("little", L(LITTLE_COUNT, "“little” dipakai untuk “people”.", "ใช้ 'little' กับ 'people'"),
             "It is for things you cannot count, and it means 'not much'.",
             "untuk benda yang nggak bisa dihitung, dan artinya “sedikit”.",
             "ใช้กับสิ่งที่นับไม่ได้ และแปลว่าน้อย"),
            ("few", FEW_BIG,
             "It fits countable nouns, but it means the bus is almost empty.",
             "cocok untuk benda yang bisa dihitung, tapi artinya busnya hampir kosong.",
             "ใช้กับของนับได้ก็จริง แต่แปลว่ารถเกือบว่าง")]),
    dict(s="much_many_little_few_countability", id="A2-346",
         stem="My brother doesn't drink ___ water. He only drinks soda.", opts=["much", "many", "few", "a lot"], ans="much",
         why=("Water cannot be counted, and in negative sentences we use much.",
              "“Water” nggak bisa dihitung, dan di kalimat negatif kita pakai “much”.",
              "'water' นับไม่ได้ และในประโยคปฏิเสธใช้ 'much'"),
         others=("'Many' and 'few' are for countable nouns, and 'a lot' needs of before a noun.",
                 "“Many” dan “few” untuk benda yang bisa dihitung, dan “a lot” butuh “of” sebelum kata benda.",
                 "'many' และ 'few' ใช้กับคำนามนับได้ ส่วน 'a lot' ต้องมี 'of' หน้าคำนาม"),
         cue=("Not much water, not many bottles.", "“Not much water”, “not many bottles”.", "น้ำใช้ 'not much' ส่วนขวดใช้ 'not many'"),
         rsn=("check if water can be counted -> notice the negative doesn't -> choose the word for uncountable nouns",
              "cek “water” bisa dihitung atau nggak → perhatikan kalimat negatif “doesn't” → pilih kata untuk benda yang nggak bisa dihitung",
              "ดูว่า 'water' นับได้หรือไม่ → สังเกตรูปปฏิเสธ 'doesn't' → เลือกคำสำหรับคำนามนับไม่ได้"),
         d=[("many", L(MANY_UNCOUNT, "“many” dipakai untuk “water”.", "ใช้ 'many' กับ 'water'"),
             "It is for things you can count, but water cannot be counted.",
             "untuk benda yang bisa dihitung, padahal “water” nggak bisa dihitung.",
             "ใช้กับของที่นับได้ แต่ 'water' นับไม่ได้"),
            ("few", N(FEW_UNCOUNT, "“few” dipakai untuk “water” yang nggak bisa dihitung.", "ใช้ 'few' กับ 'water' ซึ่งนับไม่ได้"),
             "It is for countable plural nouns, not for water.",
             "untuk benda jamak yang bisa dihitung, bukan untuk “water”.",
             "ใช้กับคำนามพหูพจน์ที่นับได้ ไม่ใช่กับ 'water'"),
            ("a lot", OF_DROP,
             "It needs of before the noun.",
             "kurang “of”, padahal ungkapan ini butuh “of” sebelum kata benda.",
             "ขาด 'of' เพราะสำนวนนี้ต้องมี 'of' ก่อนคำนาม")]),
    dict(s="much_many_little_few_countability", id="A2-347",
         stem="There are only a ___ cookies left. Take one!", opts=["few", "little", "many", "much"], ans="few",
         why=("Cookies can be counted, so a small number is a few.",
              "“Cookies” bisa dihitung, jadi jumlah yang sedikit pakai “a few”.",
              "'cookies' นับได้ จำนวนน้อยจึงใช้ 'a few'"),
         others=("'Little' is for things you cannot count, and a never comes before many or much.",
                 "“Little” untuk benda yang nggak bisa dihitung, sedangkan “a” nggak pernah ditaruh sebelum “many” atau “much”.",
                 "'little' ใช้กับสิ่งที่นับไม่ได้ ส่วน 'a' ไม่เคยวางหน้า 'many' หรือ 'much'"),
         cue=("A few cookies, a little milk.", "“A few cookies”, “a little milk”.", "ขนมใช้ 'a few' ส่วนนมใช้ 'a little'"),
         rsn=("check if cookies can be counted -> notice only a -> choose the word for a small number",
              "cek “cookies” bisa dihitung atau nggak → perhatikan “only a” → pilih kata untuk jumlah yang sedikit",
              "ดูว่า 'cookies' นับได้หรือไม่ → สังเกต 'only a' → เลือกคำที่บอกจำนวนน้อย"),
         d=[("little", L(LITTLE_COUNT, "“a little” dipakai untuk “cookies” yang bisa dihitung.", "ใช้ 'a little' กับ 'cookies' ซึ่งนับได้"),
             "It is for things you cannot count, like milk, but cookies can be counted.",
             "untuk benda yang nggak bisa dihitung seperti susu, padahal kue bisa dihitung.",
             "ใช้กับสิ่งที่นับไม่ได้อย่างนม แต่ขนมนับได้"),
            ("many", A_MANY,
             "It cannot follow a, and it means a lot, not a few.",
             "nggak bisa didahului “a”, dan artinya banyak, bukan sedikit.",
             "ใช้หลัง 'a' ไม่ได้ และแปลว่ามาก ไม่ใช่น้อย"),
            ("much", L(MUCH_COUNT, "“much” dipakai untuk “cookies” yang bisa dihitung.", "ใช้ 'much' กับ 'cookies' ซึ่งนับได้"),
             "It cannot follow a, and it is for things you cannot count.",
             "nggak bisa didahului “a”, dan untuk benda yang nggak bisa dihitung.",
             "ใช้หลัง 'a' ไม่ได้ และใช้กับสิ่งที่นับไม่ได้")]),
    dict(s="much_many_little_few_countability", id="A2-348",
         stem="Can I have a ___ sugar in my tea, please?", opts=["little", "few", "many", "lot"], ans="little",
         why=("Sugar cannot be counted, so a small amount is a little.",
              "“Sugar” nggak bisa dihitung, jadi jumlah yang sedikit pakai “a little”.",
              "'sugar' นับไม่ได้ ปริมาณน้อยจึงใช้ 'a little'"),
         others=("'A few' is for countable nouns, 'a many' is not English, and 'a lot' needs of.",
                 "“A few” untuk benda yang bisa dihitung, “a many” bukan bahasa Inggris, dan “a lot” butuh “of”.",
                 "'a few' ใช้กับคำนามนับได้ ส่วน 'a many' ไม่มีในภาษาอังกฤษ และ 'a lot' ต้องมี 'of'"),
         cue=("A little sugar, a little milk, a little time.", "“A little sugar”, “a little milk”, “a little time”.", "ของที่นับไม่ได้อย่างน้ำตาลหรือนมใช้ 'a little'"),
         rsn=("check if sugar can be counted -> notice a before the blank -> choose the word for a small amount",
              "cek “sugar” bisa dihitung atau nggak → perhatikan “a” sebelum titik-titik → pilih kata untuk jumlah yang sedikit",
              "ดูว่า 'sugar' นับได้หรือไม่ → สังเกต 'a' หน้าช่องว่าง → เลือกคำที่บอกปริมาณน้อย"),
         d=[("few", N(FEW_UNCOUNT, "“a few” dipakai untuk “sugar” yang nggak bisa dihitung.", "ใช้ 'a few' กับ 'sugar' ซึ่งนับไม่ได้"),
             "It is for countable plural nouns, but sugar cannot be counted.",
             "untuk benda jamak yang bisa dihitung, padahal gula nggak bisa dihitung.",
             "ใช้กับคำนามพหูพจน์ที่นับได้ แต่น้ำตาลนับไม่ได้"),
            ("many", A_MANY,
             "It cannot follow a, and it is for countable nouns.",
             "nggak bisa didahului “a”, dan untuk benda yang bisa dihitung.",
             "ใช้หลัง 'a' ไม่ได้ และใช้กับของที่นับได้"),
            ("lot", OF_DROP,
             "It needs of after it, and it means much, not a small amount.",
             "butuh “of” sesudahnya, dan artinya pun banyak, bukan sedikit.",
             "ต้องมี 'of' ตามหลัง และยังแปลว่ามาก ไม่ใช่น้อย")]),
    # ---------------- 30. at / in / on (place) ----------------
    dict(s="place_prepositions_at_in_on", id="A2-349",
         stem="My uncle lives ___ Surabaya.", opts=["in", "at", "on", "to"], ans="in",
         why=("A city is a big area, so we use in.",
              "Kota itu area yang luas, jadi pakai “in”.",
              "เมืองเป็นพื้นที่กว้าง จึงใช้ 'in'"),
         others=("'At' is for a point, 'on' is for a surface, and 'to' shows movement.",
                 "“At” untuk titik, “on” untuk permukaan, dan “to” menunjukkan gerak.",
                 "'at' ใช้กับจุด ส่วน 'on' ใช้กับพื้นผิว และ 'to' บอกการเคลื่อนที่"),
         cue=("Cities and countries: in Surabaya, in Thailand.", "Kota dan negara: “in Surabaya”, “in Thailand”.", "เมืองและประเทศใช้ 'in' เช่น 'in Thailand'"),
         rsn=("identify Surabaya as a city -> recall the word for inside a big area -> apply it before Surabaya",
              "kenali Surabaya sebagai kota → ingat kata depan untuk di dalam area yang luas → pakai kata itu sebelum “Surabaya”",
              "ดูว่า 'Surabaya' เป็นเมือง → นึกถึงคำบุพบทของพื้นที่กว้าง → ใช้คำนั้นหน้า 'Surabaya'"),
         d=[("at", AT_AREA,
             "It is for a point, like a bus stop, not for a whole city.",
             "untuk satu titik, seperti halte, bukan untuk seluruh kota.",
             "ใช้กับจุดหนึ่งอย่างป้ายรถเมล์ ไม่ใช่ทั้งเมือง"),
            ("on", ON_AREA,
             "It is for a surface, but a city is an area we live in.",
             "untuk permukaan, padahal kota adalah area tempat kita tinggal.",
             "ใช้กับพื้นผิว แต่เมืองเป็นพื้นที่ที่เราอยู่ข้างใน"),
            ("to", L(MOVE_STATIC, "kata depan gerak dipakai untuk tempat tinggal.", "ใช้คำบุพบทบอกการเคลื่อนที่กับที่อยู่"),
             "It shows movement, but living somewhere is not moving.",
             "menunjukkan gerak, padahal tinggal di suatu tempat bukan gerakan.",
             "บอกการเคลื่อนที่ แต่การอาศัยอยู่ไม่ใช่การเคลื่อนที่")]),
    dict(s="place_prepositions_at_in_on", id="A2-350",
         stem="Let's meet ___ the bus stop at five.", opts=["at", "in", "on", "to"], ans="at",
         why=("A bus stop is a point where we meet, so we use at.",
              "Halte itu titik tempat kita bertemu, jadi pakai “at”.",
              "ป้ายรถเมล์เป็นจุดนัดพบ จึงใช้ 'at'"),
         others=("'In' means inside, 'on' means on a surface, and 'to' shows movement.",
                 "“In” artinya di dalam, “on” artinya di atas permukaan, dan “to” menunjukkan gerak.",
                 "'in' แปลว่าข้างใน ส่วน 'on' แปลว่าบนพื้นผิว และ 'to' บอกการเคลื่อนที่"),
         cue=("Meeting points: at the bus stop, at the gate.", "Titik pertemuan: “at the bus stop”, “at the gate”.", "จุดนัดพบใช้ 'at' เช่น 'at the gate'"),
         rsn=("identify the bus stop as a meeting point -> recall the word for a point -> apply it before the bus stop",
              "kenali halte sebagai titik bertemu → ingat kata depan untuk titik → pakai kata itu sebelum “the bus stop”",
              "ดูว่าป้ายรถเมล์เป็นจุดนัดพบ → นึกถึงคำบุพบทของจุด → ใช้คำนั้นหน้า 'the bus stop'"),
         d=[("in", IN_POINT,
             "It means inside the bus stop, but we meet at a point.",
             "artinya di dalam halte, padahal kita bertemu di satu titik.",
             "แปลว่าอยู่ข้างในป้ายรถเมล์ แต่เรานัดเจอกันที่จุดหนึ่ง"),
            ("on", ON_POINT,
             "It means on top of the bus stop, which is not where we meet.",
             "artinya di atas halte, padahal bukan di situ kita bertemu.",
             "แปลว่าอยู่บนหลังคาป้ายรถเมล์ ซึ่งไม่ใช่ที่นัดเจอ"),
            ("to", L(MOVE_STATIC, "kata depan gerak dipakai untuk tempat bertemu.", "ใช้คำบุพบทบอกการเคลื่อนที่กับจุดนัดพบ"),
             "It shows a direction, but meet needs a place.",
             "menunjukkan arah gerak, padahal “meet” butuh tempat, bukan arah.",
             "บอกทิศทาง แต่ 'meet' ต้องการสถานที่ ไม่ใช่ทิศทาง")]),
    dict(s="place_prepositions_at_in_on", id="A2-351",
         stem="Our classroom is ___ the second floor.", opts=["on", "in", "at", "to"], ans="on",
         why=("Floors of a building take on, so: on the second floor.",
              "Lantai gedung pakai “on”, jadi “on the second floor”.",
              "ชั้นของอาคารใช้ 'on' จึงเป็น 'on the second floor'"),
         others=("'In' is for inside an area, 'at' is for a point, and 'to' shows movement.",
                 "“In” untuk di dalam area, “at” untuk titik, dan “to” menunjukkan gerak.",
                 "'in' ใช้กับข้างในพื้นที่ ส่วน 'at' ใช้กับจุด และ 'to' บอกการเคลื่อนที่"),
         cue=("Floors: on the first floor, on the second floor.", "Lantai gedung: “on the first floor”, “on the second floor”.", "ชั้นของอาคารใช้ 'on' เช่น 'on the first floor'"),
         rsn=("identify the second floor as a floor of a building -> recall the word for floors -> apply it before the second floor",
              "kenali “the second floor” sebagai lantai gedung → ingat kata depan untuk lantai → pakai kata itu sebelum “the second floor”",
              "ดูว่า 'the second floor' เป็นชั้นของอาคาร → นึกถึงคำบุพบทของชั้น → ใช้คำนั้นหน้า 'the second floor'"),
         d=[("in", IN_FLOOR,
             "It copies 'di lantai dua', but English uses a different word for floors.",
             "meniru “di lantai dua”, padahal bahasa Inggris memakai kata lain untuk lantai.",
             "ใช้กับข้างในพื้นที่ แต่ภาษาอังกฤษใช้อีกคำหนึ่งกับชั้นของอาคาร"),
            ("at", AT_FLOOR,
             "It is for a point, but a floor is a level of the building.",
             "untuk satu titik, padahal lantai adalah tingkat di dalam gedung.",
             "ใช้กับจุดหนึ่ง แต่ชั้นคือระดับหนึ่งของอาคาร"),
            ("to", L(MOVE_STATIC, "kata depan gerak dipakai untuk letak kelas.", "ใช้คำบุพบทบอกการเคลื่อนที่กับตำแหน่งของห้องเรียน"),
             "It shows movement, but the classroom does not move.",
             "menunjukkan gerak, padahal kelasnya diam di tempat.",
             "บอกการเคลื่อนที่ แต่ห้องเรียนอยู่กับที่")]),
    dict(s="place_prepositions_at_in_on", id="A2-352",
         stem="Sorry, I can't come out. I'm ___ home with my little sister.", opts=["at", "in", "on", "to"], ans="at",
         why=("We always say at home, with no the.",
              "Kita selalu bilang “at home”, tanpa “the”.",
              "เราพูดว่า 'at home' เสมอ โดยไม่มี 'the'"),
         others=("'In home' and 'on home' are not English, and 'to home' shows movement.",
                 "“In home” dan “on home” bukan bahasa Inggris, dan “to home” menunjukkan gerak.",
                 "'in home' และ 'on home' ไม่มีในภาษาอังกฤษ ส่วน 'to home' บอกการเคลื่อนที่"),
         cue=("Fixed phrases: at home, at school, at work.", "Frasa tetap: “at home”, “at school”, “at work”.", "สำนวนที่ใช้ตายตัวคือ 'at home', 'at school' และ 'at work'"),
         rsn=("notice the word home -> recall the fixed phrase for being at home -> apply the fixed word before home",
              "perhatikan kata “home” → ingat frasa tetap untuk berada di rumah → pakai kata depan tetapnya sebelum “home”",
              "สังเกตคำว่า 'home' → นึกถึงสำนวนตายตัวเวลาอยู่บ้าน → ใช้คำบุพบทที่ตายตัวหน้า 'home'"),
         d=[("in", IN_HOME,
             "It is not used for being home; English has a fixed phrase for this.",
             "nggak dipakai untuk “di rumah”, karena bahasa Inggris punya frasa tetap untuk itu.",
             "ไม่ใช่สำนวนที่ภาษาอังกฤษใช้เมื่ออยู่บ้าน"),
            ("on", ON_HOME,
             "It means on top of something, not being at home.",
             "artinya di atas sesuatu, bukan berada di rumah.",
             "แปลว่าอยู่บนบางอย่าง ไม่ใช่อยู่บ้าน"),
            ("to", L(MOVE_STATIC, "kata depan gerak dipakai untuk posisi di rumah.", "ใช้คำบุพบทบอกการเคลื่อนที่กับการอยู่บ้าน"),
             "It shows movement, but I am already home.",
             "menunjukkan gerak, padahal aku sudah di rumah.",
             "บอกการเคลื่อนที่ แต่ฉันอยู่บ้านแล้ว")]),
    # ---------------- 31. as ... as ----------------
    dict(s="as_as_equality_vs_comparative", id="A2-353",
         stem="Nina is 150 cm, and Tari is 150 cm too. Nina is ___ Tari.", opts=["as tall as", "taller than", "as taller as", "as tall than"], ans="as tall as",
         why=("They are the same height, so we use as + plain adjective + as.",
              "Tinggi mereka sama, jadi pakai “as” + kata sifat bentuk dasar + “as”.",
              "ทั้งสองคนสูงเท่ากัน จึงใช้ 'as' + คำคุณศัพท์รูปพื้นฐาน + 'as'"),
         others=("'Taller than' shows a difference, 'as taller as' adds -er inside, and 'as tall than' mixes as with than.",
                 "“Taller than” menunjukkan perbedaan, “as taller as” menambah -er di dalamnya, dan “as tall than” mencampur “as” dengan “than”.",
                 "'taller than' บอกว่าคนหนึ่งสูงกว่า ตัวเลือกที่เติม -er ไว้ข้างใน 'as … as' ผิดรูปแบบ และตัวเลือกที่ปิดด้วย 'than' ก็ผสมสองรูปแบบเข้าด้วยกัน"),
         cue=("Same height: as tall as.", "Tingginya sama: “as tall as”.", "สูงเท่ากันใช้ 'as tall as'"),
         rsn=("compare the two heights -> identify them as the same -> choose as with the plain adjective and as",
              "bandingkan kedua tinggi badannya → pastikan sama → pilih “as” + kata sifat bentuk dasar + “as”",
              "เปรียบเทียบความสูงทั้งสอง → ดูว่าเท่ากัน → เลือก 'as' + คำคุณศัพท์รูปพื้นฐาน + 'as'"),
         d=[("taller than", L(COMP_EQUAL, "bentuk “lebih” dipakai untuk dua tinggi yang sama.", "ใช้ขั้นกว่ากับความสูงที่เท่ากัน"),
             "It says Nina is taller, but they are the same height.",
             "menyatakan Nina lebih tinggi, padahal tinggi mereka sama.",
             "บอกว่านีนาสูงกว่า แต่ทั้งสองสูงเท่ากัน"),
            ("as taller as", N(COMP_INSIDE, "akhiran -er ditambahkan di dalam “as … as”.", "เติม -er ไว้ข้างใน 'as … as'"),
             "It adds -er inside the frame; as … as takes the plain adjective.",
             "menambah -er di dalamnya, padahal “as … as” memakai kata sifat bentuk dasar.",
             "เติม -er ข้างใน แต่ 'as … as' ใช้คำคุณศัพท์รูปพื้นฐาน"),
            ("as tall than", L(AS_THAN, "bingkai “as … as” ditutup dengan “than”.", "ปิดรูปแบบ 'as … as' ด้วย 'than'"),
             "It mixes as with than; the frame closes with as.",
             "mencampur “as” dengan “than”, padahal bingkainya ditutup dengan “as”.",
             "ผสม 'as' กับ 'than' แต่รูปแบบนี้ต้องปิดด้วย 'as'")]),
    dict(s="as_as_equality_vs_comparative", id="A2-354",
         stem="The train is fast, but it isn't ___ a plane.", opts=["as fast as", "as fast than", "as fast like", "faster as"], ans="as fast as",
         why=("In a negative sentence we still use as … as, so: isn't as fast as.",
              "Di kalimat negatif tetap pakai “as … as”, jadi “isn't as fast as”.",
              "ในประโยคปฏิเสธยังใช้ 'as … as' จึงเป็น 'isn't as fast as'"),
         others=("'As fast than' and 'as fast like' close the frame with the wrong word, and 'faster as' mixes -er with as.",
                 "“As fast than” dan “as fast like” menutup bingkainya dengan kata yang salah, dan “faster as” mencampur -er dengan “as”.",
                 "ตัวเลือกที่ปิดด้วย 'than' หรือ 'like' ใช้คำปิดผิด ส่วน 'faster as' ผสม -er กับ 'as'"),
         cue=("Less than? not as … as: not as fast as.", "Kalah? “not as … as”: “not as fast as”.", "ถ้าน้อยกว่าใช้ 'not as … as' เช่น 'not as fast as'"),
         rsn=("notice the negative isn't -> recall that the frame stays as … as -> check that both parts use as",
              "perhatikan bentuk negatif “isn't” → ingat bingkainya tetap “as … as” → cek kedua bagiannya memakai “as”",
              "สังเกตรูปปฏิเสธ 'isn't' → นึกว่ารูปแบบยังเป็น 'as … as' → ดูว่าทั้งสองส่วนใช้ 'as'"),
         d=[("as fast than", L(AS_THAN, "bingkai “as … as” ditutup dengan “than”.", "ปิดรูปแบบ 'as … as' ด้วย 'than'"),
             "It opens with as but closes with than; the two cannot be mixed.",
             "dibuka dengan “as” tapi ditutup dengan “than”, padahal keduanya nggak bisa dicampur.",
             "เปิดด้วย 'as' แต่ปิดด้วย 'than' ซึ่งผสมกันไม่ได้"),
            ("as fast like", LIKE_CLOSE,
             "It closes the frame with like (seperti), but as … as must close with as.",
             "menutup bingkainya dengan “like” (seperti), padahal “as … as” harus ditutup dengan “as” juga.",
             "ปิดด้วย 'like' (เหมือน) แต่ 'as … as' ต้องปิดด้วย 'as' เหมือนกัน"),
            ("faster as", ER_AS,
             "It mixes -er with as; choose faster than or the as … as frame.",
             "mencampur -er dengan “as”, padahal pilihannya “faster than” atau bentuk “as … as”.",
             "ผสม -er กับ 'as' แต่ต้องเลือกใช้ 'faster than' หรือรูป 'as … as'")]),
    dict(s="as_as_equality_vs_comparative", id="A2-355",
         stem="My room isn't ___ my sister's room. Hers is bigger.", opts=["as big as", "as big than", "as bigger as", "big as"], ans="as big as",
         why=("In the negative frame we keep as + plain adjective + as, so: isn't as big as.",
              "Di bingkai negatif tetap “as” + kata sifat bentuk dasar + “as”, jadi “isn't as big as”.",
              "ในรูปปฏิเสธยังใช้ 'as' + คำคุณศัพท์รูปพื้นฐาน + 'as' จึงเป็น 'isn't as big as'"),
         others=("'As big than' mixes as with than, 'as bigger as' adds -er inside, and 'big as' forgets the first as.",
                 "“As big than” mencampur “as” dengan “than”, “as bigger as” menambah -er di dalamnya, dan “big as” lupa “as” yang pertama.",
                 "ตัวเลือกที่ปิดด้วย 'than' ผสมสองรูปแบบ ตัวเลือกที่เติม -er ไว้ข้างในผิดรูปแบบ และ 'big as' ลืม 'as' ตัวแรก"),
         cue=("as … as is a twin pair: open with as, close with as.", "“as … as” itu pasangan kembar: buka dengan “as”, tutup dengan “as”.", "'as … as' เป็นคู่แฝด เปิดด้วย 'as' และปิดด้วย 'as'"),
         rsn=("notice isn't and hers is bigger -> recall the frame not as … as -> check both as words and the plain adjective",
              "perhatikan “isn't” dan “Hers is bigger” → ingat bingkai “not as … as” → cek kedua “as” dan kata sifat bentuk dasarnya",
              "สังเกต 'isn't' และ 'Hers is bigger' → นึกถึงรูปแบบ 'not as … as' → ตรวจ 'as' ทั้งสองตัวและคำคุณศัพท์รูปพื้นฐาน"),
         d=[("as big than", L(AS_THAN, "bingkai “as … as” ditutup dengan “than”.", "ปิดรูปแบบ 'as … as' ด้วย 'than'"),
             "It closes with than, but a frame that opens with as must close with as.",
             "ditutup dengan “than”, padahal bingkai yang dibuka dengan “as” harus ditutup dengan “as” juga.",
             "ปิดด้วย 'than' แต่ถ้าเปิดด้วย 'as' ก็ต้องปิดด้วย 'as'"),
            ("as bigger as", N(COMP_INSIDE, "akhiran -er ditambahkan di dalam “as … as”.", "เติม -er ไว้ข้างใน 'as … as'"),
             "It adds -er inside the frame; as … as takes the plain adjective.",
             "menambah -er di dalamnya, padahal “as … as” memakai kata sifat bentuk dasar.",
             "เติม -er ข้างใน แต่ 'as … as' ใช้คำคุณศัพท์รูปพื้นฐาน"),
            ("big as", FIRST_AS,
             "It forgets the first as; the frame needs as on both sides.",
             "lupa “as” yang pertama, padahal bingkainya butuh “as” di kedua sisi.",
             "ลืม 'as' ตัวแรก แต่รูปแบบนี้ต้องมี 'as' ทั้งสองข้าง")]),
    dict(s="as_as_equality_vs_comparative", id="A2-356",
         stem="Both bikes cost the same. The red one is ___ the blue one.", opts=["as expensive as", "more expensive than", "as more expensive as", "expensive as"], ans="as expensive as",
         why=("They cost the same, so we use as + plain adjective + as, with no more.",
              "Harganya sama, jadi pakai “as” + kata sifat bentuk dasar + “as”, tanpa “more”.",
              "ราคาเท่ากัน จึงใช้ 'as' + คำคุณศัพท์รูปพื้นฐาน + 'as' โดยไม่มี 'more'"),
         others=("'More expensive than' shows a difference, 'as more expensive as' adds more inside, and 'expensive as' forgets the first as.",
                 "“More expensive than” menunjukkan perbedaan, “as more expensive as” menambah “more” di dalamnya, dan “expensive as” lupa “as” yang pertama.",
                 "'more expensive than' บอกว่าคันหนึ่งแพงกว่า ตัวเลือกที่เติม 'more' ไว้ข้างในผิดรูปแบบ และ 'expensive as' ลืม 'as' ตัวแรก"),
         cue=("Same price: as expensive as. Long words stay plain inside.", "Harga sama: “as expensive as”. Kata sifat panjang pun tetap bentuk dasar di dalamnya.", "ราคาเท่ากันใช้ 'as expensive as' และคำยาวก็ไม่ต้องเติม 'more'"),
         rsn=("notice cost the same -> identify the two bikes as equal -> keep the adjective plain between as and as",
              "perhatikan “cost the same” → pastikan kedua sepeda setara → pakai kata sifat bentuk dasar di antara “as” dan “as”",
              "สังเกต 'cost the same' → ดูว่าจักรยานสองคันเท่ากัน → ใช้คำคุณศัพท์รูปพื้นฐานระหว่าง 'as' กับ 'as'"),
         d=[("more expensive than", L(COMP_EQUAL, "bentuk “lebih” dipakai untuk dua harga yang sama.", "ใช้ขั้นกว่ากับราคาที่เท่ากัน"),
             "It says the red one costs more, but both cost the same.",
             "menyatakan sepeda merah lebih mahal, padahal harganya sama.",
             "บอกว่าคันสีแดงแพงกว่า แต่ราคาเท่ากัน"),
            ("as more expensive as", N(COMP_INSIDE, "kata “more” ditambahkan di dalam “as … as”.", "เติม 'more' ไว้ข้างใน 'as … as'"),
             "It adds more inside the frame; as … as takes the plain adjective.",
             "menambah “more” di dalamnya, padahal “as … as” memakai kata sifat bentuk dasar.",
             "เติม 'more' ข้างใน แต่ 'as … as' ใช้คำคุณศัพท์รูปพื้นฐาน"),
            ("expensive as", FIRST_AS,
             "It forgets the first as; the frame needs as on both sides.",
             "lupa “as” yang pertama, padahal bingkainya butuh “as” di kedua sisi.",
             "ลืม 'as' ตัวแรก แต่รูปแบบนี้ต้องมี 'as' ทั้งสองข้าง")]),
]
