# A2 lesson 39-46: soal latihan baru (m025-377). Format: lihat ../README.md.
LESSONS = {
    "present_perfect_experience_ever_never": dict(
        obj=("Use have or has + past participle with ever and never to talk about experiences in your life so far.",
             "Pakai “have/has” + bentuk ketiga dengan “ever” dan “never” untuk menceritakan pengalaman sampai sekarang.",
             "ใช้ 'have/has' + กริยาช่อง 3 กับ 'ever' และ 'never' เพื่อพูดถึงประสบการณ์จนถึงตอนนี้"),
        mis=("Learner uses the past simple or the base verb after have, since 'pernah' and 'เคย' need no change to the verb.",
             "Kamu memakai bentuk lampau atau bentuk dasar sesudah “have”, karena kata “pernah” nggak mengubah kata kerjanya.",
             "คุณใช้รูปอดีตหรือรูปพื้นฐานหลัง 'have' เพราะคำว่า 'เคย' ไม่ทำให้คำกริยาเปลี่ยนรูป"),
        rule=("Experience: have or has + third form (been, eaten, seen). Ever in questions (Have you ever…?), never for 'not once' (I have never…).",
              "Pengalaman: “have/has” + bentuk ketiga (“been”, “eaten”, “seen”). “Ever” untuk bertanya, “never” untuk “belum pernah”.",
              "พูดถึงประสบการณ์ใช้ 'have/has' + กริยาช่อง 3 เช่น 'been', 'eaten' ใช้ 'ever' ในคำถาม และใช้ 'never' เมื่อหมายถึงไม่เคยเลย"),
        avoid=("After have or has, check the verb: is it the third form?",
               "Sesudah “have/has”, cek kata kerjanya: sudah bentuk ketiga?",
               "หลัง 'have/has' ให้ดูว่าคำกริยาเป็นช่อง 3 แล้วหรือยัง"),
    ),
    "present_perfect_with_for_since_duration": dict(
        obj=("Use have or has + past participle with for or since for something that started in the past and is still true now.",
             "Pakai “have/has” + bentuk ketiga dengan “for” atau “since” untuk hal yang mulai di masa lalu dan masih berlaku sekarang.",
             "ใช้ 'have/has' + กริยาช่อง 3 กับ 'for' หรือ 'since' สำหรับสิ่งที่เริ่มในอดีตและยังเป็นอยู่ตอนนี้"),
        mis=("Learner uses the present simple, since 'sudah … sejak' and 'มา … แล้ว' keep the verb as it is.",
             "Kamu memakai present simple, karena kalimat seperti “aku tinggal di sini sejak 2020” nggak mengubah kata kerjanya.",
             "คุณใช้ present simple เพราะประโยคอย่าง 'อยู่ที่นี่มาห้าปีแล้ว' ไม่ต้องเปลี่ยนรูปคำกริยา"),
        rule=("Started in the past and still true: have or has + third form + for (a length of time) or since (a starting point).",
              "Mulai di masa lalu dan masih berlaku: “have/has” + bentuk ketiga + “for” (lamanya) atau “since” (titik mulai).",
              "สิ่งที่เริ่มในอดีตและยังเป็นอยู่ใช้ 'have/has' + กริยาช่อง 3 ตามด้วย 'for' (ระยะเวลา) หรือ 'since' (จุดเริ่มต้น)"),
        avoid=("See for or since? Check that the verb is have or has + third form.",
               "Ada “for” atau “since”? Cek kata kerjanya sudah “have/has” + bentuk ketiga.",
               "ถ้ามี 'for' หรือ 'since' ให้ดูว่าคำกริยาเป็น 'have/has' + ช่อง 3 แล้ว"),
    ),
    "comparative_formation_er_vs_more_no_double_marking": dict(
        obj=("Make comparatives with -er for short adjectives (hotter, easier) and more for long ones (more expensive), never both.",
             "Bentuk perbandingan dengan -er untuk kata sifat pendek (“hotter”, “easier”) dan “more” untuk kata sifat panjang (“more expensive”), jangan keduanya.",
             "สร้างขั้นกว่าด้วย -er สำหรับคำคุณศัพท์สั้น ('hotter', 'easier') และใช้ 'more' กับคำยาว ('more expensive') โดยไม่ใช้ทั้งสองอย่างพร้อมกัน"),
        mis=("Learner uses more with a short word, -er with a long word, or both, since 'lebih' and 'กว่า' work the same for every word.",
             "Kamu memakai “more” untuk kata pendek, -er untuk kata panjang, atau keduanya sekaligus, karena kata “lebih” bisa dipakai untuk semua kata.",
             "คุณใช้ 'more' กับคำสั้น ใช้ -er กับคำยาว หรือใช้ทั้งสองอย่าง เพราะคำว่า 'กว่า' ใช้ได้กับทุกคำ"),
        rule=("Short words: -er (hot → hotter, easy → easier). Long words: more (more beautiful). Never more + -er.",
              "Kata pendek: -er (“hot” → “hotter”, “easy” → “easier”). Kata panjang: “more” (“more beautiful”). Jangan “more” + -er.",
              "คำสั้นเติม -er ('hot' เป็น 'hotter', 'easy' เป็น 'easier') ส่วนคำยาวใช้ 'more' และห้ามใช้ 'more' กับ -er พร้อมกัน"),
        avoid=("Count the beats: one beat or ending in -y, add -er; longer, use more.",
               "Hitung suku katanya: satu suku kata atau berakhiran -y pakai -er; lebih panjang pakai “more”.",
               "นับพยางค์ ถ้ามีพยางค์เดียวหรือลงท้ายด้วย -y ให้เติม -er ถ้ายาวกว่านั้นให้ใช้ 'more'"),
    ),
    "adverb_of_manner_ly_vs_adjective_after_verb": dict(
        obj=("Use an adjective after be, look, and feel, and an -ly adverb to say how someone does an action.",
             "Pakai kata sifat sesudah “be”, “look”, dan “feel”, dan kata keterangan -ly untuk menjelaskan cara seseorang melakukan sesuatu.",
             "ใช้คำคุณศัพท์หลัง 'be', 'look' และ 'feel' และใช้คำกริยาวิเศษณ์ -ly เพื่อบอกว่าทำอย่างไร"),
        mis=("Learner uses the adjective after an action verb, since one word in Indonesian and Thai can describe both a thing and an action.",
             "Kamu memakai kata sifat sesudah kata kerja aksi, karena “baju yang indah” dan “bernyanyi dengan indah” memakai kata yang sama.",
             "คุณใช้คำคุณศัพท์หลังคำกริยาที่เป็นการกระทำ เพราะในภาษาไทย 'ร้องเพลงเพราะ' กับ 'เสียงเพราะ' ใช้คำเดียวกัน"),
        rule=("Action verb + -ly adverb: sings beautifully. Be, look, feel + adjective: looks beautiful. Some adverbs have no -ly: fast, well.",
              "Kata kerja aksi + kata keterangan -ly: “sings beautifully”. “Be”, “look”, “feel” + kata sifat: “looks beautiful”. Ada yang tanpa -ly: “fast”, “well”.",
              "คำกริยาที่เป็นการกระทำใช้ -ly เช่น 'sings beautifully' ส่วน 'be', 'look', 'feel' ตามด้วยคำคุณศัพท์ และบางคำไม่มี -ly เช่น 'fast'"),
        avoid=("Ask: does the word describe the person or thing, or how the action is done?",
               "Tanya: kata itu menjelaskan orang atau bendanya, atau cara kegiatannya dilakukan?",
               "ถามว่าคำนั้นบอกลักษณะของคนหรือสิ่งของ หรือบอกวิธีทำ"),
    ),
    "how_much_vs_how_many_quantity_questions": dict(
        obj=("Ask How many + plural countable noun, and How much + uncountable noun or price.",
             "Tanya “How many” + benda jamak yang bisa dihitung, dan “How much” + benda yang nggak bisa dihitung atau harga.",
             "ถาม 'How many' + คำนามพหูพจน์ที่นับได้ และ 'How much' + คำนามนับไม่ได้หรือราคา"),
        mis=("Learner uses one question word for every noun, since 'berapa' and 'เท่าไร' fit all of them.",
             "Kamu memakai satu kata tanya untuk semua benda, karena kata “berapa” bisa dipakai untuk apa saja.",
             "คุณใช้คำถามแบบเดียวกับทุกคำนาม เพราะคำว่า 'เท่าไร' ใช้ได้กับทุกอย่าง"),
        rule=("How many + plural noun you can count (How many eggs?). How much + noun you can't count (How much milk?) or a price (How much is it?).",
              "Kalau menanyakan jumlah benda yang bisa dihitung satu-satu: Pakai “How many” yang selalu diikuti kata benda jamak berakhiran -s. Contoh: <b>How many pens do you have?</b> (Berapa banyak pulpen yang kamu punya?).<br>Kalau menanyakan jumlah benda yang tidak bisa dihitung atau menanyakan harga barang: Pakai “How much”. Contoh: <b>How much water do you drink?</b> (Berapa banyak air yang kamu minum?) atau <b>How much is this shirt?</b> (Berapa harga baju ini?).<br><br>💡 <b>RUMUS KILAT</b>:<br>Setelah titik-titik ada kata jamak (berakhiran <b>-s</b>) ➡️ Tanya pakai <b>How many</b>.<br>Setelah titik-titik benda tak bisa dihitung (tanpa -s) atau tanya harga ➡️ Tanya pakai <b>How much</b>.",
              "'How many' ใช้กับคำนามพหูพจน์ที่นับได้ ส่วน 'How much' ใช้กับคำนามนับไม่ได้ ('How much milk?') หรือใช้ถามราคา"),
        avoid=("Look at the noun after the gap: can you count it one by one?",
               "Lihat kata benda sesudah titik-titik: bisa dihitung satu per satu?",
               "ดูคำนามหลังช่องว่างว่านับทีละชิ้นได้ไหม"),
    ),
    "indefinite_compounds_something_anything_nothing": dict(
        obj=("Use something in positive sentences, anything after a negative verb, and nothing with a positive verb to mean 'not anything'.",
             "Pakai “something” di kalimat positif, “anything” sesudah kata kerja negatif, dan “nothing” dengan kata kerja positif untuk arti “tidak ada apa-apa”.",
             "ใช้ 'something' ในประโยคบอกเล่า 'anything' หลังคำกริยาปฏิเสธ และ 'nothing' กับคำกริยาบอกเล่าเพื่อหมายถึงไม่มีอะไรเลย"),
        mis=("Learner uses anything in positive sentences or puts nothing after a negative verb, since 'apa-apa' and 'อะไร' fit both.",
             "Kamu memakai “anything” di kalimat positif atau “nothing” sesudah kata kerja negatif, karena kata “apa-apa” cocok untuk keduanya.",
             "คุณใช้ 'anything' ในประโยคบอกเล่า หรือใช้ 'nothing' หลังคำกริยาปฏิเสธ เพราะคำว่า 'อะไร' ใช้ได้ทั้งสองแบบ"),
        rule=("Positive: something (I see something). Negative verb: anything (I can't see anything). Positive verb meaning 'not any': nothing (There is nothing).",
              "Positif: “something”. Kata kerja negatif: “anything” (“I can't see anything”). Kata kerja positif dengan arti “tidak ada”: “nothing” (“There is nothing”).",
              "ประโยคบอกเล่าใช้ 'something' กริยาปฏิเสธใช้ 'anything' และถ้ากริยาเป็นบอกเล่าแต่หมายถึงไม่มีเลยให้ใช้ 'nothing'"),
        avoid=("Find the verb: negative? Use anything. Positive but meaning none? Use nothing.",
               "Cari kata kerjanya: negatif? Pakai “anything”. Positif tapi artinya “tidak ada”? Pakai “nothing”.",
               "หาคำกริยาก่อน ถ้าเป็นปฏิเสธใช้ 'anything' ถ้าเป็นบอกเล่าแต่หมายถึงไม่มีให้ใช้ 'nothing'"),
    ),
    "cause_result_connectors_because_vs_so": dict(
        obj=("Use because before a reason, so before a result, and because of before a noun.",
             "Pakai “because” sebelum alasan, “so” sebelum akibat, dan “because of” sebelum kata benda.",
             "ใช้ 'because' หน้าเหตุผล 'so' หน้าผลลัพธ์ และ 'because of' หน้าคำนาม"),
        mis=("Learner mixes up reason and result, since 'karena … maka' and 'เพราะ … จึง' can be used together.",
             "Kamu tertukar antara alasan dan akibat, karena dalam bahasa Indonesia “karena … maka” boleh dipakai bersamaan.",
             "คุณสับสนระหว่างเหตุผลกับผลลัพธ์ เพราะในภาษาไทยใช้ 'เพราะ … จึง' พร้อมกันได้"),
        rule=("Because + reason (because it rained). So + result (so I stayed home). Because of + noun (because of the rain).",
              "Membedakan ALASAN (sebab) vs AKIBAT (hasil):<br>1. Alasan / Sebab: Pakai “Because” di depan penyebabnya. Contoh: <b>We stayed home because it rained</b>.<br>2. Akibat / Hasil: Pakai “so” di depan kejadian akibatnya (posisinya di tengah kalimat, diawali koma). Contoh: <b>It rained, so we stayed home</b>.<br><br>💡 <b>RUMUS KILAT</b>:<br>Di depan penyebab kejadian ➡️ Pakai <b>because</b>.<br>Di depan dampak / hasil kejadian ➡️ Pakai <b>, so</b>.<br>Pantangan ➡️ Dilarang menggabungkan keduanya dalam satu kalimat (salah: <i>Because it rained so we stayed home</i> ❌).",
              "'because' ตามด้วยเหตุผล ส่วน 'so' ตามด้วยผลลัพธ์ และ 'because of' ตามด้วยคำนาม"),
        avoid=("Ask: does the next part give the reason or the result? Is it a whole sentence or just a noun?",
               "Tanya: bagian sesudahnya alasan atau akibat? Kalimat utuh atau cuma kata benda?",
               "ถามว่าส่วนที่ตามมาเป็นเหตุผลหรือผลลัพธ์ และเป็นประโยคเต็มหรือแค่คำนาม"),
    ),
    "irregular_comparative_better_worse_forms": dict(
        obj=("Use the special forms better, best, worse, and worst for good and bad, never gooder or more good.",
             "Pakai bentuk khusus “better”, “best”, “worse”, dan “worst” untuk “good” dan “bad”, bukan “gooder” atau “more good”.",
             "ใช้รูปพิเศษของ 'good' และ 'bad' เมื่อเปรียบเทียบ โดยไม่เติม -er และไม่ใช้ 'more'"),
        mis=("Learner adds -er or more to good and bad, like other adjectives.",
             "Kamu menambah -er atau “more” pada “good” dan “bad”, seperti kata sifat lain.",
             "คุณเติม -er หรือใช้ 'more' กับ 'good' และ 'bad' เหมือนคำคุณศัพท์อื่น"),
        rule=("good → better → the best; bad → worse → the worst. No -er, no more.",
              "“good” → “better” → “the best”; “bad” → “worse” → “the worst”. Tanpa -er, tanpa “more”.",
              "คำว่า 'good' และ 'bad' มีรูปเปรียบเทียบพิเศษของตัวเอง ('better' และ 'worse') จึงไม่เติม -er และไม่ใช้ 'more'"),
        avoid=("Before adding -er or more, check: is it good or bad?",
               "Sebelum menambah -er atau “more”, cek: kata sifatnya “good” atau “bad”?",
               "ก่อนเติม -er หรือใช้ 'more' ให้ดูว่าเป็น 'good' หรือ 'bad' หรือเปล่า"),
    ),
}

# ---- label lama (nama persis di grammar-misconception-id.json) ----
PAST_IN_PP = "using the past-simple form inside a present perfect question frame"
BARE_AFTER_HAVE = "leaving the bare verb although 'have' needs the past participle after it"
PAST_FOR_EXP = "uses the past simple for a life experience without a time"
PRESENT_SPAN = "using the plain present as a habit statement, ignoring the stretch of time that began in the past"
PROG_SPAN = "choosing the present progressive for right now, though the span from 2019 needs a past-to-present link"
PERIOD_SEALED = "sealing the period off as a completed event, though the family still lives there"
PRES_CONT_ALWAYS = "Assumes present time always requires present continuous."
MORE_SHORT = "applies the periphrastic 'more + adjective' pattern to a short one-syllable adjective that takes '-er'"
DOUBLE_COMP = "doubles the comparative marking by putting 'more' before an adjective already ending in '-er'"
ER_LONG = "adds -er to a long adjective"
SUP_TWO = "superlative used for a two-item comparison"
BASE_THAN = "base adjective used without comparative marking"
ADV_AFTER_BE = "uses the adverb where an adjective after 'be' is needed"
ADJ_AFTER_ACTION = "uses the bare adjective after an action verb where a manner adverb in '-ly' is required"
WITH_ADJ = "builds the manner phrase as 'with' plus a bare adjective, copying Indonesian 'dengan hati-hati'"
COMP_NO_COMPARE = "switches to a comparative adjective although nothing is being compared and the slot needs an adverb"
MUCH_COUNTABLE = "asks about a countable plural noun with 'how much'"
MANY_UNCOUNTABLE = "asks about an uncountable noun with 'how many'"
BARE_HOW = "asks quantity with bare 'how' and drops the quantity word entirely"
PARTITIVE_OF = "adds a partitive 'of' straight after 'how much' before a bare noun"
REMOVE_PL = "removes the article correctly but incorrectly pluralizes the uncountable noun"
ANYTHING_POS = "uses 'anything' in a positive clause that has no negative word to license it"
POS_IN_NEG = "using a positive indefinite pronoun that contradicts the negative context"
DOUBLE_NEG = "combining a negated verb ('didn't') with a negative pronoun, creating a non-standard double negative"
SPLIT_NEG = "incorrectly splitting the compound negative pronoun into two words"
NO_AFTER_NOT = "uses 'no' before a verb already negated with 'not'"
SO_REASON = "introduces the reason clause with the result connector 'so'"
BECAUSE_OF_CLAUSE = "puts 'because of' before a full clause although it only takes a noun phrase"
SO_THAT = "uses the purpose connector 'so that' where a plain reason connector is needed"
BECAUSE_RESULT = "introduces the result clause with 'because'"
ER_IRREG = "regular -er ending forced onto an irregular adjective"
MORE_IRREG = "regular 'more + adjective' pattern applied to an irregular adjective"
BEST_THAN = "superlative 'best' used where 'than' demands a comparative"

# ---- label baru dari paket g/h (teks harus sama persis) ----
HAS_I = ("he-she-it have form used with I", "bentuk “has” untuk “he”, “she”, “it” dipakai bersama “I”.", "ใช้ 'has' ซึ่งเป็นรูปของบุรุษที่สามกับ 'I'")
NO_DOUBLE_ER = ("final consonant not doubled before -er", "huruf mati terakhir nggak digandakan sebelum -er.", "ไม่เพิ่มพยัญชนะตัวท้ายก่อนเติม -er")
THE_COMP = ("the used with a comparative for a group", "'the' dipasangkan dengan bentuk 'lebih' untuk satu kelompok.", "ใช้ 'the' คู่กับขั้นกว่าเมื่อเปรียบเทียบทั้งกลุ่ม")

# ---- label baru ----
ING_HAVE = ("-ing form used after have in the present perfect", "bentuk -ing dipakai sesudah “have” untuk pengalaman.", "ใช้รูป -ing หลัง 'have' เมื่อพูดถึงประสบการณ์")
HAVE_3SG = ("have used with he, she, or it", "“have” dipakai untuk “he”, “she”, atau “it”.", "ใช้ 'have' กับประธานเอกพจน์อย่าง 'he', 'she', 'it'")
DID_PP = ("did used with a past participle", "“did” dipasangkan dengan kata kerja bentuk ketiga.", "ใช้ 'did' คู่กับกริยาช่อง 3")
BE_PP = ("be used instead of have for an experience", "bentuk “be” dipakai sebagai pengganti “have” untuk pengalaman.", "ใช้ 'be' แทน 'have' เมื่อพูดถึงประสบการณ์")
EVER_POS = ("ever used in a positive statement", "“ever” dipakai di kalimat pernyataan positif.", "ใช้ 'ever' ในประโยคบอกเล่า")
NO_VERB = ("no used to make a verb negative", "“no” dipakai untuk menegatifkan kata kerja.", "ใช้ 'no' ทำให้คำกริยาเป็นปฏิเสธ")
YET_MID = ("yet placed in the middle before the verb", "“yet” ditaruh di tengah kalimat, sebelum kata kerja.", "วาง 'yet' ไว้กลางประโยคหน้าคำกริยา")
HAVE_NO_PP = ("have used without a past participle", "“have” dipakai tanpa kata kerja bentuk ketiga sesudahnya.", "ใช้ 'have' โดยไม่มีกริยาช่อง 3 ตามหลัง")
Y_KEPT_ER = ("-er added to a consonant + y adjective without changing y", "kata sifat berakhiran konsonan + y diberi -er tanpa mengubah y jadi i.", "เติม -er ให้คำคุณศัพท์ที่ลงท้ายด้วยพยัญชนะ + y โดยไม่เปลี่ยน y เป็น i")
LY_IRREG = ("-ly added to an adverb that has no -ly form", "akhiran -ly ditambahkan ke kata keterangan yang nggak memakai -ly.", "เติม -ly ให้คำกริยาวิเศษณ์ที่ไม่มีรูป -ly")
NOUN_FOR_ADV = ("noun used where an adverb is needed", "kata benda dipakai di tempat kata keterangan cara.", "ใช้คำนามในตำแหน่งของคำกริยาวิเศษณ์")
NOUN_FOR_ADJ = ("noun used where an adjective is needed", "kata benda dipakai di tempat kata sifat.", "ใช้คำนามในตำแหน่งของคำคุณศัพท์")
LOOK_LIKE_ADJ = ("like added before an adjective after look", "“like” ditambahkan sebelum kata sifat sesudah “look”.", "เติม 'like' หน้าคำคุณศัพท์หลัง 'look'")
QUIET_QUITE = ("quite confused with quiet", "“quite” (cukup) tertukar dengan “quiet” (tenang).", "สับสน 'quite' (ค่อนข้าง) กับ 'quiet' (เงียบ)")
HOW_LONG_AMOUNT = ("how long used to ask about an amount", "“how long” (berapa lama) dipakai untuk menanyakan jumlah atau harga.", "ใช้ 'how long' (นานเท่าไร) ถามจำนวนหรือราคา")
HOW_OFTEN_AMOUNT = ("how often used to ask about a number", "“how often” (seberapa sering) dipakai untuk menanyakan jumlah.", "ใช้ 'how often' (บ่อยแค่ไหน) ถามจำนวน")
HOW_MANY_PRICE = ("how many used to ask a price", "“how many” dipakai untuk menanyakan harga.", "ใช้ 'how many' ถามราคา")
HOW_PRICE = ("price used after how instead of much", "“how price” dipakai untuk menanyakan harga, meniru “berapa harganya”.", "ใช้ 'how price' ถามราคาแบบแปลคำต่อคำ")
CONTAINER_SG = ("container noun left singular after how many", "kata wadah dibiarkan tunggal sesudah “how many”.", "ใช้คำบอกภาชนะแบบเอกพจน์หลัง 'how many'")
SPLIT_COMPOUND = ("compound word split into two", "satu kata gabungan dipecah jadi dua kata.", "แยกคำประสมคำเดียวออกเป็นสองคำ")
NOTHING_CONTRA = ("nothing used for something that is there", "“nothing” dipakai padahal ada sesuatu di sana.", "ใช้ 'nothing' ทั้งที่มีบางอย่างอยู่จริง")
NONE_THING = ("none used instead of nothing", "“none” dipakai sebagai pengganti “nothing”.", "ใช้ 'none' แทนคำว่า 'nothing'")
BECAUSE_NP = ("because used directly before a noun", "'because' dipakai langsung sebelum kata benda.", "ใช้ 'because' หน้าคำนามโดยตรง")
SO_NP = ("so used before a noun as a reason", "“so” dipakai sebelum kata benda untuk menyebut alasan.", "ใช้ 'so' หน้าคำนามเพื่อบอกเหตุผล")
BUT_RESULT = ("but used to link a result", "“but” dipakai untuk menyambung akibat, padahal “but” menandai pertentangan.", "ใช้ 'but' เชื่อมผลลัพธ์ ทั้งที่ 'but' ใช้บอกความขัดแย้ง")
SO_START = ("so used to open a reason at the start", "“so” dipakai di awal kalimat untuk membuka alasan.", "ใช้ 'so' ขึ้นต้นประโยคเพื่อบอกเหตุผล")
GOODEST = ("regular -est ending forced onto an irregular adjective", "akhiran -est dipaksakan ke kata sifat yang bentuknya khusus.", "เติม -est ให้คำคุณศัพท์ที่มีรูปพิเศษ")


def L(name, item_id, item_th):
    return (name, item_id, item_th)


def N(label, item_id, item_th):
    """label baru dengan teks khusus untuk soal ini"""
    return label + (item_id, item_th)


ITEMS = [
    # ---------------- 39. present perfect: ever / never ----------------
    dict(s="present_perfect_experience_ever_never", id="A2-385",
         stem="Have you ever ___ sushi? It's really good!", opts=["eaten", "ate", "eat", "eating"], ans="eaten",
         why=("After have, an experience uses the third form of the verb, eaten.",
              "Sesudah “have”, pengalaman memakai kata kerja bentuk ketiga, yaitu “eaten”.",
              "หลัง 'have' ประสบการณ์ใช้กริยาช่อง 3 คือ 'eaten'"),
         others=("'Ate' is the past simple, 'eat' is the base form, and 'eating' is the -ing form.",
                 "“Ate” bentuk lampau, “eat” bentuk dasar, dan “eating” bentuk -ing.",
                 "'ate' เป็นรูปอดีต ส่วน 'eat' เป็นรูปพื้นฐาน และ 'eating' เป็นรูป -ing"),
         cue=("eat, ate, eaten: after have, take the third one.", "“eat”, “ate”, “eaten”: sesudah “have”, ambil yang ketiga.", "จำสามช่อง 'eat', 'ate', 'eaten' และหลัง 'have' ให้ใช้ช่องที่สามเสมอ"),
         rsn=("notice have and ever -> recall that experiences use have + the third form -> choose the third form of eat",
              "perhatikan “have” dan “ever” → ingat pengalaman memakai “have” + bentuk ketiga → pilih bentuk ketiga dari “eat”",
              "สังเกต 'have' และ 'ever' → นึกว่าประสบการณ์ใช้ 'have' + กริยาช่อง 3 → เลือกช่อง 3 ของ 'eat'"),
         d=[("ate", L(PAST_IN_PP, "bentuk lampau dipakai sesudah “have”.", "ใช้รูปอดีตหลัง 'have'"),
             "It is the past simple; after have, use the third form.",
             "bentuk lampau, padahal sesudah “have” kata kerjanya bentuk ketiga.",
             "เป็นรูปอดีต แต่หลัง 'have' ต้องใช้กริยาช่อง 3"),
            ("eat", L(BARE_AFTER_HAVE, "bentuk dasar dipakai sesudah “have”.", "ใช้รูปพื้นฐานหลัง 'have'"),
             "It is the base form; after have, the verb changes to the third form.",
             "bentuk dasar, padahal sesudah “have” kata kerjanya berubah jadi bentuk ketiga.",
             "เป็นรูปพื้นฐาน แต่หลัง 'have' คำกริยาต้องเปลี่ยนเป็นช่อง 3"),
            ("eating", ING_HAVE,
             "It is the -ing form; have + -ing is not how English talks about experiences.",
             "bentuk -ing, padahal “have” + -ing bukan pola untuk pengalaman.",
             "เป็นรูป -ing แต่ 'have' + -ing ไม่ใช่รูปที่ใช้บอกประสบการณ์")]),
    dict(s="present_perfect_experience_ever_never", id="A2-386",
         stem="I ___ to Bali, but I'd love to go one day.", opts=["have never been", "never went", "have never go", "has never been"], ans="have never been",
         why=("It is a life experience with no time given, and I takes have.",
              "Ini pengalaman hidup tanpa waktu tertentu, dan “I” pakai “have”, jadi “have never been”.",
              "นี่เป็นประสบการณ์ชีวิตที่ไม่ระบุเวลา และ 'I' ใช้ 'have' จึงเป็น 'have never been'"),
         others=("'Never went' needs a finished time, 'have never go' keeps the base form, and 'has never been' is for he, she, or it.",
                 "“Never went” butuh waktu lampau yang jelas, “have never go” masih bentuk dasar, dan “has never been” untuk “he”, “she”, atau “it”.",
                 "'never went' ต้องมีเวลาในอดีตที่ชัดเจน ส่วน 'have never go' ยังเป็นรูปพื้นฐาน และ 'has never been' ใช้กับประธานเอกพจน์บุรุษที่สาม"),
         cue=("Never in my life: I have never been.", "Belum pernah seumur hidup: “I have never been”.", "ไม่เคยเลยในชีวิตใช้ 'I have never been'"),
         rsn=("notice that no time is given -> choose have for the subject I -> keep never before the third form",
              "perhatikan nggak ada waktu yang disebut → pilih “have” untuk subjek “I” → taruh “never” sebelum bentuk ketiga",
              "สังเกตว่าไม่มีการบอกเวลา → เลือก 'have' ให้ประธาน 'I' → วาง 'never' ไว้หน้ากริยาช่อง 3"),
         d=[("never went", L(PAST_FOR_EXP, "bentuk lampau dipakai untuk pengalaman tanpa waktu.", "ใช้รูปอดีตกับประสบการณ์ที่ไม่ระบุเวลา"),
             "It is the past simple, which needs a finished time like last year.",
             "bentuk lampau, padahal tanpa waktu lampau yang jelas, pengalaman memakai “have”.",
             "เป็นรูปอดีต แต่ถ้าไม่มีเวลาในอดีตที่ชัดเจน ประสบการณ์ต้องใช้ 'have'"),
            ("have never go", L(BARE_AFTER_HAVE, "bentuk dasar “go” dipakai sesudah “have never”.", "ใช้รูปพื้นฐาน 'go' หลัง 'have never'"),
             "It keeps the base form; after have, use the third form.",
             "masih bentuk dasar, padahal sesudah “have” kata kerjanya bentuk ketiga.",
             "ยังเป็นรูปพื้นฐาน แต่หลัง 'have' ต้องใช้กริยาช่อง 3"),
            ("has never been", N(HAS_I, "“has” dipakai untuk “I”.", "ใช้ 'has' กับ 'I'"),
             "It is for he, she, or it, but the subject is I.",
             "untuk “he”, “she”, atau “it”, padahal subjeknya “I”.",
             "ใช้กับประธานเอกพจน์บุรุษที่สาม แต่ประธานคือ 'I'")]),
    dict(s="present_perfect_experience_ever_never", id="A2-387",
         stem="___ your brother ever ridden a horse?", opts=["Has", "Have", "Did", "Is"], ans="Has",
         why=("Your brother is he, and ridden is the third form, so the question starts with Has.",
              "“Your brother” sama dengan “he”, dan “ridden” bentuk ketiga, jadi pertanyaannya diawali “Has”.",
              "'your brother' คือ 'he' และ 'ridden' เป็นกริยาช่อง 3 คำถามจึงขึ้นต้นด้วย 'Has'"),
         others=("'Have' is for I, you, we, and they, 'Did' goes with the base form, and 'Is' cannot go with ridden.",
                 "“Have” untuk “I”, “you”, “we”, “they”, “Did” dipasangkan dengan bentuk dasar, dan “Is” nggak bisa dipasangkan dengan “ridden”.",
                 "'have' ใช้กับประธานพหูพจน์หรือ 'I' และ 'you' ส่วน 'did' ใช้คู่กับรูปพื้นฐาน และ 'is' ใช้คู่กับ 'ridden' ไม่ได้"),
         cue=("He, she, it + ever: Has he ever…?", "“He”, “she”, “it” + “ever”: “Has he ever…?”", "ประธานเอกพจน์บุรุษที่สามใช้ 'Has' เช่น 'Has he ever…?'"),
         rsn=("identify your brother as he -> notice the third form ridden -> choose the helper for he in this tense",
              "kenali “your brother” sebagai “he” → perhatikan bentuk ketiga “ridden” → pilih kata bantu untuk “he” di bentuk ini",
              "ดูว่า 'your brother' คือ 'he' → สังเกตกริยาช่อง 3 'ridden' → เลือกกริยาช่วยของ 'he' ในรูปนี้"),
         d=[("Have", HAVE_3SG,
             "It is for I, you, we, and they, but your brother is he.",
             "untuk “I”, “you”, “we”, dan “they”, padahal “your brother” sama dengan “he”.",
             "ใช้กับประธานพหูพจน์หรือ 'I' และ 'you' แต่พี่ชายเป็นคนเดียว ซึ่งใช้เหมือน 'he'"),
            ("Did", DID_PP,
             "It only goes with the base form, but here the verb is the third form.",
             "hanya dipasangkan dengan bentuk dasar, padahal di sini kata kerjanya bentuk ketiga.",
             "ใช้คู่กับรูปพื้นฐานเท่านั้น แต่ในที่นี้คำกริยาเป็นช่อง 3"),
            ("Is", BE_PP,
             "It cannot go with ridden; experiences use a different helper verb.",
             "nggak bisa dipasangkan dengan “ridden”; pengalaman memakai kata bantu lain.",
             "ใช้คู่กับ 'ridden' ไม่ได้ ประสบการณ์ต้องใช้กริยาช่วยตัวอื่น")]),
    dict(s="present_perfect_experience_ever_never", id="A2-388",
         stem="My dad has ___ been on a plane. He is scared of flying.", opts=["never", "ever", "no", "yet"], ans="never",
         why=("He is scared of flying, so he has not flown even once. The word for that is never.",
              "Ayah takut naik pesawat, jadi maksudnya belum pernah sekali pun. Kata untuk itu adalah “never”.",
              "พ่อกลัวการนั่งเครื่องบิน จึงหมายความว่าไม่เคยเลยสักครั้ง คำที่ใช้คือ 'never'"),
         others=("'Ever' is for questions, 'no' cannot go before a verb like been, and 'yet' goes at the end of negatives and questions.",
                 "“Ever” untuk kalimat tanya, “no” nggak bisa ditaruh sebelum kata kerja seperti “been”, dan “yet” ditaruh di akhir kalimat negatif atau tanya.",
                 "'ever' ใช้ในคำถาม ส่วน 'no' วางหน้าคำกริยาอย่าง 'been' ไม่ได้ และ 'yet' อยู่ท้ายประโยคปฏิเสธหรือคำถาม"),
         cue=("Not once in your life: never.", "Belum pernah sekali pun: “never”.", "ไม่เคยเลยสักครั้งใช้ 'never'"),
         rsn=("notice scared of flying -> identify the meaning as not even once -> choose the word for not once in your life",
              "perhatikan “scared of flying” → pastikan maksudnya belum pernah sekali pun → pilih kata untuk “belum pernah”",
              "สังเกต 'scared of flying' → ดูว่าหมายถึงไม่เคยเลยสักครั้ง → เลือกคำที่แปลว่าไม่เคย"),
         d=[("ever", EVER_POS,
             "It is for questions about experiences, and it doesn't mean 'not once'.",
             "dipakai di kalimat tanya tentang pengalaman, dan artinya bukan “belum pernah”.",
             "ใช้ในคำถามเรื่องประสบการณ์ และไม่ได้แปลว่าไม่เคย"),
            ("no", NO_VERB,
             "It goes before nouns, not before a verb like been.",
             "dipakai sebelum kata benda, bukan sebelum kata kerja seperti “been”.",
             "ใช้หน้าคำนาม ไม่ใช่หน้าคำกริยาอย่าง 'been'"),
            ("yet", YET_MID,
             "It goes at the end of negatives and questions, and it means 'so far', not 'not once'.",
             "ditaruh di akhir kalimat negatif atau tanya, dan artinya “sampai sekarang”, bukan “belum pernah”.",
             "อยู่ท้ายประโยคปฏิเสธหรือคำถาม และแปลว่าจนถึงตอนนี้ ไม่ได้แปลว่าไม่เคย")]),
    # ---------------- 40. present perfect + for / since ----------------
    dict(s="present_perfect_with_for_since_duration", id="A2-389",
         stem="My parents ___ married for twenty years, and they are still happy.", opts=["have been", "are", "were", "have"], ans="have been",
         why=("They married twenty years ago and are still married, so we use have been with for.",
              "Mereka menikah dua puluh tahun lalu dan masih menikah sampai sekarang, jadi pakai “have been” bersama “for”.",
              "พ่อแม่แต่งงานมายี่สิบปีและยังอยู่ด้วยกัน จึงใช้ 'have been' คู่กับ 'for'"),
         others=("'Are' ignores the twenty years, 'were' sounds finished, and 'have' needs been after it.",
                 "“Are” mengabaikan rentang dua puluh tahun, “were” terdengar sudah selesai, dan “have” butuh “been” sesudahnya.",
                 "'are' ไม่สนใจช่วงยี่สิบปี ส่วน 'were' ฟังเหมือนจบไปแล้ว และ 'have' ต้องมี 'been' ตามหลัง"),
         cue=("for + a time that reaches now: have been.", "“For” + rentang sampai sekarang: “have been”.", "'for' + ช่วงเวลาที่ต่อเนื่องถึงตอนนี้ใช้ 'have been'"),
         rsn=("notice for twenty years -> check that they are still married now -> combine have with the third form of be",
              "perhatikan “for twenty years” → cek mereka masih menikah sekarang → gabungkan “have” dengan bentuk ketiga dari “be”",
              "สังเกต 'for twenty years' → ดูว่ายังแต่งงานกันอยู่ตอนนี้ → รวม 'have' กับกริยาช่อง 3 ของ 'be'"),
         d=[("are", L(PRESENT_SPAN, "bentuk sekarang dipakai untuk rentang dua puluh tahun.", "ใช้รูปปัจจุบันกับช่วงเวลายี่สิบปี"),
             "It only describes now; for twenty years needs a verb that reaches back into the past.",
             "cuma menggambarkan sekarang, padahal “for twenty years” butuh kata kerja yang menjangkau masa lalu.",
             "พูดถึงแค่ตอนนี้ แต่ 'for twenty years' ต้องใช้คำกริยาที่ย้อนไปถึงอดีต"),
            ("were", L(PERIOD_SEALED, "bentuk lampau dipakai untuk pernikahan yang masih berlangsung.", "ใช้รูปอดีตกับการแต่งงานที่ยังดำเนินอยู่"),
             "It sounds finished, but they are still married and happy.",
             "terdengar sudah selesai, padahal mereka masih menikah dan bahagia.",
             "ฟังเหมือนจบไปแล้ว แต่ทั้งสองยังแต่งงานและมีความสุขอยู่"),
            ("have", HAVE_NO_PP,
             "It is missing a verb; the state married still needs been.",
             "kurang satu kata kerja; keadaan “married” masih butuh “been”.",
             "ขาดคำกริยาไปหนึ่งคำ สภาพ 'married' ยังต้องมี 'been'")]),
    dict(s="present_perfect_with_for_since_duration", id="A2-390",
         stem="I ___ this phone for two years, and it still works well.", opts=["have had", "have", "am having", "had"], ans="have had",
         why=("I got the phone two years ago and still own it, so we use have had.",
              "Ponselnya kumiliki sejak dua tahun lalu dan masih kupakai, jadi pakai “have had”.",
              "ฉันมีโทรศัพท์นี้มาสองปีแล้วและยังใช้อยู่ จึงใช้ 'have had'"),
         others=("'Have' ignores the two years, 'am having' uses -ing for owning, and 'had' sounds finished.",
                 "“Have” mengabaikan rentang dua tahun, “am having” memakai -ing untuk kepemilikan, dan “had” terdengar sudah selesai.",
                 "'have' ไม่สนใจช่วงสองปี ส่วน 'am having' ใช้ -ing กับการเป็นเจ้าของ และ 'had' ฟังเหมือนจบไปแล้ว"),
         cue=("Owned from then until now: have had.", "Dimiliki dari dulu sampai sekarang: “have had”.", "มีมาตั้งแต่ตอนนั้นจนถึงตอนนี้ใช้ 'have had'"),
         rsn=("notice for two years -> check that I still own the phone -> combine have with the third form of have",
              "perhatikan “for two years” → cek ponselnya masih kupunya → gabungkan “have” dengan bentuk ketiga dari “have”",
              "สังเกต 'for two years' → ดูว่ายังมีโทรศัพท์อยู่ → รวม 'have' กับกริยาช่อง 3 ของ 'have'"),
         d=[("have", L(PRESENT_SPAN, "bentuk sekarang dipakai untuk rentang dua tahun.", "ใช้รูปปัจจุบันกับช่วงเวลาสองปี"),
             "It only talks about now; for two years needs a helper verb + the third form.",
             "cuma membicarakan sekarang, padahal “for two years” butuh kata bantu + bentuk ketiga.",
             "พูดถึงแค่ตอนนี้ แต่ 'for two years' ต้องใช้กริยาช่วยกับกริยาช่อง 3"),
            ("am having", L(PRES_CONT_ALWAYS, "bentuk -ing dipakai untuk memiliki ponsel.", "ใช้รูป -ing กับการเป็นเจ้าของโทรศัพท์"),
             "It uses -ing, but owning is a state, and for two years reaches back into the past.",
             "memakai -ing, padahal memiliki itu keadaan, dan “for two years” menjangkau masa lalu.",
             "ใช้ -ing แต่การมีเป็นสภาพ และ 'for two years' ย้อนไปถึงอดีต"),
            ("had", L(PERIOD_SEALED, "bentuk lampau dipakai untuk ponsel yang masih dimiliki.", "ใช้รูปอดีตกับโทรศัพท์ที่ยังมีอยู่"),
             "It sounds finished, but the phone still works and I still use it.",
             "terdengar sudah selesai, padahal ponselnya masih dipakai sampai sekarang.",
             "ฟังเหมือนจบไปแล้ว แต่ยังใช้โทรศัพท์เครื่องนี้อยู่")]),
    dict(s="present_perfect_with_for_since_duration", id="A2-391",
         stem="“How long ___ here?” “Since last year.”", opts=["have you lived", "do you live", "are you living", "did you live"], ans="have you lived",
         why=("The answer since last year shows a stretch until now, so the question uses have you lived.",
              "Jawaban “Since last year” menunjukkan rentang sampai sekarang, jadi pertanyaannya “have you lived”.",
              "คำตอบ 'Since last year' บอกช่วงเวลาที่ต่อเนื่องถึงตอนนี้ คำถามจึงใช้ 'have you lived'"),
         others=("'Do you live' asks only about now, 'are you living' uses -ing, and 'did you live' sounds finished.",
                 "“Do you live” cuma menanyakan sekarang, “are you living” memakai -ing, dan “did you live” terdengar sudah selesai.",
                 "'do you live' ถามถึงแค่ตอนนี้ ส่วน 'are you living' ใช้ -ing และ 'did you live' ฟังเหมือนจบไปแล้ว"),
         cue=("How long until now? How long have you…?", "Berapa lama sampai sekarang? “How long have you…?”", "ถามว่านานเท่าไรจนถึงตอนนี้ใช้ 'How long have you…?'"),
         rsn=("notice the answer since last year -> identify a stretch of time until now -> place have before you and the third form after it",
              "perhatikan jawaban “Since last year” → pastikan rentangnya sampai sekarang → taruh “have” sebelum “you” dan bentuk ketiga sesudahnya",
              "สังเกตคำตอบ 'Since last year' → ดูว่าเป็นช่วงเวลาที่ต่อเนื่องถึงตอนนี้ → วาง 'have' หน้า 'you' และกริยาช่อง 3 ตามหลัง"),
         d=[("do you live", L(PRESENT_SPAN, "bentuk sekarang dipakai untuk pertanyaan “How long”.", "ใช้รูปปัจจุบันในคำถาม 'How long'"),
             "It asks only about now, but since last year stretches back into the past.",
             "cuma menanyakan sekarang, padahal “since last year” menjangkau masa lalu.",
             "ถามถึงแค่ตอนนี้ แต่ 'since last year' ย้อนไปถึงอดีต"),
            ("are you living", L(PROG_SPAN, "bentuk -ing dipakai untuk rentang sejak tahun lalu.", "ใช้รูป -ing กับช่วงเวลาตั้งแต่ปีที่แล้ว"),
             "It is about right now only; a stretch since last year needs have + the third form.",
             "cuma soal saat ini, padahal rentang sejak tahun lalu butuh “have” + bentuk ketiga.",
             "พูดถึงแค่ตอนนี้ แต่ช่วงเวลาตั้งแต่ปีที่แล้วต้องใช้ 'have' + กริยาช่อง 3"),
            ("did you live", L(PERIOD_SEALED, "bentuk lampau dipakai untuk rentang yang masih berlangsung.", "ใช้รูปอดีตกับช่วงเวลาที่ยังดำเนินอยู่"),
             "It sounds finished, but the person still lives here.",
             "terdengar sudah selesai, padahal orangnya masih tinggal di sini.",
             "ฟังเหมือนจบไปแล้ว แต่คนนั้นยังอยู่ที่นี่")]),
    dict(s="present_perfect_with_for_since_duration", id="A2-392",
         stem="I ___ swimming since I was six.", opts=["have loved", "love", "am loving", "loved"], ans="have loved",
         why=("The love started when I was six and is still true, so we use have loved with since.",
              "Rasa suka itu mulai waktu umur enam tahun dan masih ada sampai sekarang, jadi pakai “have loved” bersama “since”.",
              "ความชอบนี้เริ่มตอนอายุหกขวบและยังมีอยู่ จึงใช้ 'have loved' คู่กับ 'since'"),
         others=("'Love' ignores since, 'am loving' uses -ing for a feeling, and 'loved' sounds finished.",
                 "“Love” mengabaikan “since”, “am loving” memakai -ing untuk perasaan, dan “loved” terdengar sudah selesai.",
                 "'love' ไม่สนใจ 'since' ส่วน 'am loving' ใช้ -ing กับความรู้สึก และ 'loved' ฟังเหมือนจบไปแล้ว"),
         cue=("since + a start that reaches now: have loved, have known.", "“Since” + titik mulai sampai sekarang: “have loved”, “have known”.", "'since' + จุดเริ่มต้นที่ต่อเนื่องถึงตอนนี้ใช้ 'have' + ช่อง 3"),
         rsn=("notice since I was six -> check that the feeling is still true -> combine have with the third form of love",
              "perhatikan “since I was six” → cek perasaannya masih ada → gabungkan “have” dengan bentuk ketiga dari “love”",
              "สังเกต 'since I was six' → ดูว่ายังรู้สึกอย่างนั้นอยู่ → รวม 'have' กับกริยาช่อง 3 ของ 'love'"),
         d=[("love", L(PRESENT_SPAN, "bentuk sekarang dipakai bersama “since”.", "ใช้รูปปัจจุบันคู่กับ 'since'"),
             "It only talks about now; since needs have + the third form.",
             "cuma membicarakan sekarang, padahal “since” butuh “have” + bentuk ketiga.",
             "พูดถึงแค่ตอนนี้ แต่ 'since' ต้องใช้ 'have' + กริยาช่อง 3"),
            ("am loving", L(PRES_CONT_ALWAYS, "bentuk -ing dipakai untuk perasaan “love”.", "ใช้รูป -ing กับความรู้สึก 'love'"),
             "It uses -ing, but love is a feeling and takes no -ing.",
             "memakai -ing, padahal “love” itu perasaan dan nggak memakai -ing.",
             "ใช้ -ing แต่ 'love' เป็นความรู้สึกที่ไม่ใช้ -ing"),
            ("loved", L(PERIOD_SEALED, "bentuk lampau dipakai untuk perasaan yang masih ada.", "ใช้รูปอดีตกับความรู้สึกที่ยังมีอยู่"),
             "It sounds finished, but I still love swimming.",
             "terdengar sudah selesai, padahal sampai sekarang aku masih suka berenang.",
             "ฟังเหมือนจบไปแล้ว แต่ตอนนี้ฉันยังชอบว่ายน้ำอยู่")]),
    # ---------------- 41. -er or more ----------------
    dict(s="comparative_formation_er_vs_more_no_double_marking", id="A2-393",
         stem="Today is ___ than yesterday. Let's go swimming!", opts=["hotter", "hoter", "more hot", "more hotter"], ans="hotter",
         why=("Hot is a short word, so add -er and double the t.",
              "“Hot” kata pendek, jadi tambah -er dan gandakan huruf t, yaitu “hotter”.",
              "'hot' เป็นคำสั้น จึงเติม -er และเพิ่ม t อีกตัว เป็น 'hotter'"),
         others=("'Hoter' forgets to double the t, 'more hot' uses more for a short word, and 'more hotter' marks the comparison twice.",
                 "“Hoter” lupa menggandakan huruf t, “more hot” memakai “more” untuk kata pendek, dan “more hotter” menandai perbandingan dua kali.",
                 "'hoter' ลืมเพิ่ม t ส่วน 'more hot' ใช้ 'more' กับคำสั้น และ 'more hotter' บอกการเปรียบเทียบซ้ำสองครั้ง"),
         cue=("hot → hotter, big → bigger: double the last letter.", "“hot” → “hotter”, “big” → “bigger”: gandakan huruf terakhirnya.", "'hot' เป็น 'hotter' และ 'big' เป็น 'bigger' โดยเพิ่มพยัญชนะตัวท้าย"),
         rsn=("notice than -> identify hot as a short word -> add one more t before -er",
              "perhatikan “than” → kenali “hot” sebagai kata pendek → tambahkan satu huruf t lagi sebelum -er",
              "สังเกต 'than' → ดูว่า 'hot' เป็นคำสั้น → เพิ่ม t อีกตัวก่อนเติม -er"),
         d=[("hoter", NO_DOUBLE_ER,
             "It forgets to double the t before -er.",
             "lupa menggandakan huruf t sebelum -er.",
             "ลืมเพิ่ม t อีกตัวก่อนเติม -er"),
            ("more hot", L(MORE_SHORT, "pola “more” dipakai untuk kata pendek “hot”.", "ใช้ 'more' กับคำสั้น 'hot'"),
             "It uses more, but short words like hot take -er.",
             "memakai “more”, padahal kata pendek seperti “hot” cukup diberi -er.",
             "ใช้ 'more' แต่คำสั้นอย่าง 'hot' ใช้ -er"),
            ("more hotter", L(DOUBLE_COMP, "“more” ditumpuk di depan bentuk -er.", "ใช้ 'more' ซ้อนหน้ารูป -er"),
             "It marks the comparison twice; -er alone is enough.",
             "menandai perbandingan dua kali, padahal -er saja sudah cukup.",
             "บอกการเปรียบเทียบซ้ำสองครั้ง ทั้งที่ใช้ -er อย่างเดียวก็พอ")]),
    dict(s="comparative_formation_er_vs_more_no_double_marking", id="A2-394",
         stem="This test is ___ than the last one. I finished it in ten minutes!", opts=["easier", "easyer", "more easy", "more easier"], ans="easier",
         why=("Easy ends in a consonant + y, so y changes to i before -er.",
              "“Easy” berakhiran konsonan + y, jadi y diganti i lalu ditambah -er, yaitu “easier”.",
              "'easy' ลงท้ายด้วยพยัญชนะ + y จึงเปลี่ยน y เป็น i แล้วเติม -er เป็น 'easier'"),
         others=("'Easyer' keeps the y, 'more easy' uses more for a short word, and 'more easier' marks the comparison twice.",
                 "“Easyer” mempertahankan huruf y, “more easy” memakai “more” untuk kata pendek, dan “more easier” menandai perbandingan dua kali.",
                 "'easyer' ยังคง y ไว้ ส่วน 'more easy' ใช้ 'more' กับคำสั้น และ 'more easier' บอกการเปรียบเทียบซ้ำสองครั้ง"),
         cue=("easy → easier: y becomes i before -er.", "“easy” → “easier”: y berubah jadi i sebelum -er.", "'easy' เป็น 'easier' โดยเปลี่ยน y เป็น i ก่อนเติม -er"),
         rsn=("notice than -> check the y at the end of easy -> convert y to i before -er",
              "perhatikan “than” → cek huruf y di akhir “easy” → ubah y jadi i sebelum -er",
              "สังเกต 'than' → ดูตัว y ท้าย 'easy' → เปลี่ยน y เป็น i ก่อนเติม -er"),
         d=[("easyer", Y_KEPT_ER,
             "It keeps the y; after a consonant, y becomes i before -er.",
             "mempertahankan huruf y, padahal sesudah konsonan huruf y berubah jadi i sebelum -er.",
             "ยังคง y ไว้ แต่หลังพยัญชนะ y ต้องเปลี่ยนเป็น i ก่อนเติม -er"),
            ("more easy", L(MORE_SHORT, "pola “more” dipakai untuk “easy”.", "ใช้ 'more' กับ 'easy'"),
             "It uses more, but easy takes -er.",
             "memakai “more”, padahal “easy” cukup diberi -er.",
             "ใช้ 'more' ทั้งที่คำสั้นอย่าง 'easy' ต้องเติม -er"),
            ("more easier", L(DOUBLE_COMP, "“more” ditumpuk di depan bentuk -er.", "ใช้ 'more' ซ้อนหน้ารูป -er"),
             "It marks the comparison twice; the -er form alone is enough.",
             "menandai perbandingan dua kali, padahal bentuk -er saja sudah cukup.",
             "บอกการเปรียบเทียบซ้ำสองครั้ง ทั้งที่ใช้รูป -er อย่างเดียวก็พอ")]),
    dict(s="comparative_formation_er_vs_more_no_double_marking", id="A2-395",
         stem="This dress is ___ than that one. I'll buy it!", opts=["more beautiful", "beautifuller", "more beautifuller", "most beautiful"], ans="more beautiful",
         why=("Beautiful is a long word, so we put more before it.",
              "“Beautiful” kata panjang, jadi pakai “more” di depannya.",
              "'beautiful' เป็นคำยาว จึงใช้ 'more' ข้างหน้า"),
         others=("'Beautifuller' adds -er to a long word, 'more beautifuller' uses both, and 'most beautiful' is for a group.",
                 "“Beautifuller” menambah -er ke kata panjang, “more beautifuller” memakai keduanya, dan “most beautiful” untuk satu kelompok.",
                 "ตัวเลือกที่เติม -er ให้คำยาวผิด ตัวเลือกที่ใช้ทั้ง 'more' และ -er ก็ผิด และ 'most' ใช้กับทั้งกลุ่ม"),
         cue=("Long words: more beautiful, more expensive.", "Kata panjang: “more beautiful”, “more expensive”.", "คำยาวที่มีหลายพยางค์ต้องใช้ 'more' ข้างหน้า"),
         rsn=("notice than -> count the parts of beautiful -> apply more before a long word",
              "perhatikan “than” → hitung suku kata “beautiful” → pakai “more” sebelum kata panjang",
              "สังเกต 'than' → นับพยางค์ของ 'beautiful' → ใช้ 'more' หน้าคำยาว"),
         d=[("beautifuller", L(ER_LONG, "akhiran -er ditambahkan ke “beautiful”.", "เติม -er ให้ 'beautiful'"),
             "It adds -er, but long words take more.",
             "memakai -er, padahal kata panjang memakai “more”.",
             "เติม -er แต่คำยาวต้องใช้ 'more'"),
            ("more beautifuller", L(DOUBLE_COMP, "“more” dan -er dipakai bersamaan.", "ใช้ 'more' กับ -er พร้อมกัน"),
             "It uses more and -er together; use only one.",
             "memakai “more” dan -er sekaligus, padahal cukup salah satu.",
             "ใช้ 'more' กับ -er พร้อมกัน ทั้งที่ใช้อย่างเดียวก็พอ"),
            ("most beautiful", L(SUP_TWO, "bentuk “paling” dipakai untuk dua baju.", "ใช้ขั้นสูงสุดกับชุดสองตัว"),
             "It is for the top of a group, but than compares two dresses.",
             "untuk juara satu kelompok, padahal “than” membandingkan dua baju.",
             "ใช้กับอันดับหนึ่งของกลุ่ม แต่ 'than' เปรียบเทียบชุดสองตัว")]),
    dict(s="comparative_formation_er_vs_more_no_double_marking", id="A2-396",
         stem="Taking a taxi is ___ than taking the bus.", opts=["more expensive", "expensiver", "the most expensive", "expensive"], ans="more expensive",
         why=("Expensive is a long word, so its comparative is more expensive.",
              "“Expensive” kata panjang, jadi bentuk “lebih”-nya “more expensive”.",
              "'expensive' เป็นคำยาว ขั้นกว่าจึงเป็น 'more expensive'"),
         others=("'Expensiver' adds -er to a long word, 'the most expensive' is for a group, and 'expensive' does not compare.",
                 "“Expensiver” menambah -er ke kata panjang, “the most expensive” untuk satu kelompok, dan “expensive” nggak membandingkan.",
                 "'expensiver' เติม -er ให้คำยาว ส่วน 'the most expensive' ใช้กับทั้งกลุ่ม และ 'expensive' ไม่ได้เปรียบเทียบ"),
         cue=("Three beats or more: more + adjective.", "Tiga suku kata atau lebih: “more” + kata sifat.", "คำที่มีสามพยางค์ขึ้นไปใช้ 'more' + คำคุณศัพท์"),
         rsn=("notice than and the two ways to travel -> identify expensive as a long word -> apply more before it",
              "perhatikan “than” dan dua cara bepergian → kenali “expensive” sebagai kata panjang → pakai “more” di depannya",
              "สังเกต 'than' และการเดินทางสองแบบ → ดูว่า 'expensive' เป็นคำยาว → ใช้ 'more' ข้างหน้า"),
         d=[("expensiver", L(ER_LONG, "akhiran -er ditambahkan ke “expensive”.", "เติม -er ให้ 'expensive'"),
             "It adds -er to a long word; long words take more.",
             "menambah -er ke kata panjang, padahal kata panjang memakai “more”.",
             "เติม -er ให้คำยาว แต่คำยาวต้องใช้ 'more'"),
            ("the most expensive", L(SUP_TWO, "bentuk “paling” dipakai untuk dua cara bepergian.", "ใช้ขั้นสูงสุดกับการเดินทางสองแบบ"),
             "It is for the top of a group, but than compares only two ways to travel.",
             "untuk juara satu kelompok, padahal “than” cuma membandingkan dua cara bepergian.",
             "ใช้กับอันดับหนึ่งของกลุ่ม แต่ 'than' เปรียบเทียบการเดินทางแค่สองแบบ"),
            ("expensive", L(BASE_THAN, "kata sifat bentuk dasar dipakai sebelum “than”.", "ใช้คำคุณศัพท์รูปพื้นฐานหน้า 'than'"),
             "It does not compare, but than needs a comparative.",
             "nggak membandingkan, padahal “than” butuh bentuk “lebih”.",
             "ไม่ได้เปรียบเทียบ แต่ 'than' ต้องใช้รูปขั้นกว่า")]),
    # ---------------- 42. adjective or -ly adverb ----------------
    dict(s="adverb_of_manner_ly_vs_adjective_after_verb", id="A2-397",
         stem="My brother drives very ___. I'm always scared!", opts=["fast", "fastly", "faster", "speed"], ans="fast",
         why=("Fast is both an adjective and an adverb, so how he drives is simply fast, with no -ly.",
              "“Fast” bisa jadi kata sifat sekaligus kata keterangan, jadi cara menyetirnya cukup “fast”, tanpa -ly.",
              "'fast' เป็นได้ทั้งคำคุณศัพท์และคำกริยาวิเศษณ์ วิธีขับรถจึงใช้ 'fast' โดยไม่เติม -ly"),
         others=("'Fastly' is not an English word, 'faster' compares when nothing is compared, and 'speed' is a noun.",
                 "“Fastly” bukan kata bahasa Inggris, “faster” membandingkan padahal nggak ada yang dibandingkan, dan “speed” kata benda.",
                 "'fastly' ไม่มีในภาษาอังกฤษ ส่วน 'faster' ใช้เปรียบเทียบทั้งที่ไม่มีการเปรียบเทียบ และ 'speed' เป็นคำนาม"),
         cue=("fast stays fast, good becomes well: no -ly.", "“fast” tetap “fast”, “good” jadi “well”: tanpa -ly.", "'fast' ยังเป็น 'fast' และ 'good' เป็น 'well' โดยไม่เติม -ly"),
         rsn=("identify the word as describing how he drives -> recall that some adverbs have no -ly -> check that nothing is compared",
              "kenali katanya menjelaskan cara menyetir → ingat ada kata keterangan yang tanpa -ly → cek nggak ada yang dibandingkan",
              "ดูว่าคำนี้บอกวิธีขับรถ → นึกว่าคำกริยาวิเศษณ์บางคำไม่มี -ly → ดูว่าไม่มีการเปรียบเทียบ"),
         d=[("fastly", LY_IRREG,
             "It is not an English word; this adverb never takes -ly.",
             "bukan kata bahasa Inggris, karena kata keterangan ini nggak pernah diberi -ly.",
             "ไม่มีในภาษาอังกฤษ เพราะคำกริยาวิเศษณ์คำนี้ไม่เคยเติม -ly"),
            ("faster", L(COMP_NO_COMPARE, "bentuk “lebih” dipakai tanpa ada yang dibandingkan.", "ใช้ขั้นกว่าทั้งที่ไม่มีการเปรียบเทียบ"),
             "It compares, but there is no than and nothing is compared.",
             "membandingkan, padahal nggak ada “than” dan nggak ada yang dibandingkan.",
             "ใช้เปรียบเทียบ แต่ไม่มี 'than' และไม่มีการเปรียบเทียบ"),
            ("speed", N(NOUN_FOR_ADV, "kata benda “speed” dipakai untuk menjelaskan cara menyetir.", "ใช้คำนาม 'speed' บอกวิธีขับรถ"),
             "It is a noun, but after drives very we need a word for how.",
             "kata benda, padahal sesudah “drives very” dibutuhkan kata yang menjelaskan cara.",
             "เป็นคำนาม แต่หลัง 'drives very' ต้องใช้คำที่บอกวิธีทำ")]),
    dict(s="adverb_of_manner_ly_vs_adjective_after_verb", id="A2-398",
         stem="You look ___ today! Is that a new dress?", opts=["beautiful", "beautifully", "beauty", "like beautiful"], ans="beautiful",
         why=("Look here means 'seem', so it takes an adjective.",
              "“Look” di sini artinya “kelihatan”, jadi diikuti kata sifat, yaitu “beautiful”.",
              "'look' ในที่นี้แปลว่าดูเหมือน จึงตามด้วยคำคุณศัพท์ คือ 'beautiful'"),
         others=("'Beautifully' describes how an action is done, 'beauty' is a noun, and 'like beautiful' adds like before an adjective.",
                 "“Beautifully” menjelaskan cara melakukan kegiatan, “beauty” kata benda, dan “like beautiful” menambah “like” sebelum kata sifat.",
                 "'beautifully' บอกวิธีทำ ส่วน 'beauty' เป็นคำนาม และ 'like beautiful' เติม 'like' หน้าคำคุณศัพท์"),
         cue=("look, feel, be + adjective: you look beautiful.", "“Look”, “feel”, “be” + kata sifat: “you look beautiful”.", "หลังคำกริยาอย่าง 'look' และ 'feel' ให้ใช้คำคุณศัพท์"),
         rsn=("identify look as meaning seem -> recall that look takes an adjective -> choose the adjective form",
              "kenali “look” sebagai “kelihatan” → ingat “look” diikuti kata sifat → pilih bentuk kata sifat",
              "ดูว่า 'look' แปลว่าดูเหมือน → นึกว่า 'look' ตามด้วยคำคุณศัพท์ → เลือกรูปคำคุณศัพท์"),
         d=[("beautifully", L(ADV_AFTER_BE, "kata keterangan -ly dipakai sesudah “look”.", "ใช้คำกริยาวิเศษณ์ -ly หลัง 'look'"),
             "It describes how an action is done, but look here needs an adjective.",
             "menjelaskan cara melakukan kegiatan, padahal “look” di sini butuh kata sifat.",
             "บอกวิธีทำ แต่ 'look' ในที่นี้ต้องใช้คำคุณศัพท์"),
            ("beauty", NOUN_FOR_ADJ,
             "It is a noun; after look we need an adjective.",
             "kata benda, padahal sesudah “look” dibutuhkan kata sifat.",
             "เป็นคำนาม แต่หลัง 'look' ต้องใช้คำคุณศัพท์"),
            ("like beautiful", LOOK_LIKE_ADJ,
             "It adds like, but look like is followed by a noun, like look like a princess.",
             "menambah “like”, padahal “look like” diikuti kata benda, seperti “look like a princess”.",
             "เติม 'like' เข้ามา แต่ถ้ามี 'like' ต้องตามด้วยคำนาม เช่น เจ้าหญิง ไม่ใช่คำคุณศัพท์")]),
    dict(s="adverb_of_manner_ly_vs_adjective_after_verb", id="A2-399",
         stem="Sinta sings ___. Everyone loves her voice.", opts=["beautifully", "beautiful", "beauty", "with beautiful"], ans="beautifully",
         why=("The word tells how Sinta sings, and sings is an action verb, so we use the -ly adverb.",
              "Kata ini menjelaskan cara Sinta bernyanyi, dan “sings” kata kerja aksi, jadi pakai kata keterangan -ly, yaitu “beautifully”.",
              "คำนี้บอกว่าซินต้าร้องเพลงอย่างไร และ 'sings' เป็นคำกริยาที่เป็นการกระทำ จึงใช้รูป -ly คือ 'beautifully'"),
         others=("'Beautiful' describes a thing, not an action, 'beauty' is a noun, and 'with beautiful' copies 'dengan indah'.",
                 "“Beautiful” menjelaskan benda, bukan kegiatan, “beauty” kata benda, dan “with beautiful” meniru “dengan indah”.",
                 "'beautiful' ใช้บอกลักษณะของสิ่งของ ไม่ใช่การกระทำ ส่วน 'beauty' เป็นคำนาม และ 'with beautiful' ไม่ใช่รูปที่ภาษาอังกฤษใช้บอกวิธีทำ"),
         cue=("Action verb + -ly: sings beautifully, drives carefully.", "Kata kerja aksi + -ly: “sings beautifully”, “drives carefully”.", "คำกริยาที่เป็นการกระทำ + -ly เช่น 'drives carefully'"),
         rsn=("identify sings as an action verb -> recall that how an action is done takes -ly -> add -ly to beautiful",
              "kenali “sings” sebagai kata kerja aksi → ingat cara melakukan kegiatan memakai -ly → tambahkan -ly ke “beautiful”",
              "ดูว่า 'sings' เป็นคำกริยาที่เป็นการกระทำ → นึกว่าวิธีทำใช้ -ly → เติม -ly ให้ 'beautiful'"),
         d=[("beautiful", L(ADJ_AFTER_ACTION, "kata sifat dipakai sesudah “sings”.", "ใช้คำคุณศัพท์หลัง 'sings'"),
             "It describes a thing, like a nice song; after sings, use -ly.",
             "menjelaskan benda, seperti lagu yang indah; sesudah “sings” pakai -ly.",
             "ใช้บอกลักษณะของสิ่งของ เช่น เพลงที่ไพเราะ แต่หลัง 'sings' ต้องใช้ -ly"),
            ("beauty", N(NOUN_FOR_ADV, "kata benda “beauty” dipakai sesudah “sings”.", "ใช้คำนาม 'beauty' หลัง 'sings'"),
             "It is a noun; after sings we need a word for how.",
             "kata benda, padahal sesudah “sings” dibutuhkan kata yang menjelaskan cara.",
             "เป็นคำนาม แต่หลัง 'sings' ต้องใช้คำที่บอกวิธีทำ"),
            ("with beautiful", L(WITH_ADJ, "pola “with” + kata sifat meniru “dengan indah”.", "ใช้ 'with' + คำคุณศัพท์แบบแปลคำต่อคำ"),
             "It copies 'dengan indah'; English uses one word with -ly.",
             "meniru “dengan indah”, padahal bahasa Inggris cukup memakai satu kata ber-ly.",
             "แปลคำต่อคำจากภาษาแม่ แต่ภาษาอังกฤษใช้คำเดียวที่เติม -ly")]),
    dict(s="adverb_of_manner_ly_vs_adjective_after_verb", id="A2-400",
         stem="Please close the door ___. The baby is sleeping.", opts=["quietly", "quiet", "quite", "quietness"], ans="quietly",
         why=("The word tells how to close the door, so we use the -ly adverb.",
              "Kata ini menjelaskan cara menutup pintu, jadi pakai kata keterangan -ly, yaitu “quietly”.",
              "คำนี้บอกวิธีปิดประตู จึงใช้รูป -ly คือ 'quietly'"),
         others=("'Quiet' describes a thing, 'quite' means 'fairly', and 'quietness' is a noun.",
                 "“Quiet” menjelaskan benda, “quite” artinya “cukup”, dan “quietness” kata benda.",
                 "'quiet' ใช้บอกลักษณะของสิ่งของ ส่วน 'quite' แปลว่าค่อนข้าง และ 'quietness' เป็นคำนาม"),
         cue=("How do you do it? Add -ly: quietly, slowly, carefully.", "Bagaimana caranya? Tambah -ly: “quietly”, “slowly”, “carefully”.", "ถ้าบอกว่าทำอย่างไรให้เติม -ly เช่น 'slowly'"),
         rsn=("identify close as an action verb -> recall that how an action is done takes -ly -> check the spelling of quiet",
              "kenali “close” sebagai kata kerja aksi → ingat cara melakukan kegiatan memakai -ly → cek ejaan “quiet”",
              "ดูว่า 'close' เป็นคำกริยาที่เป็นการกระทำ → นึกว่าวิธีทำใช้ -ly → ดูการสะกดคำว่า 'quiet'"),
         d=[("quiet", L(ADJ_AFTER_ACTION, "kata sifat dipakai sesudah “close the door”.", "ใช้คำคุณศัพท์หลัง 'close the door'"),
             "It describes a thing, like a calm room; for how you close the door, use -ly.",
             "menjelaskan benda, seperti ruangan yang tenang; untuk cara menutup pintu pakai -ly.",
             "ใช้บอกลักษณะของสิ่งของ เช่น ห้องที่เงียบ แต่ถ้าบอกวิธีปิดประตูต้องใช้ -ly"),
            ("quite", QUIET_QUITE,
             "It means 'fairly'; it is only spelled like quiet.",
             "artinya “cukup”, seperti “cukup besar”; tulisannya cuma mirip dengan “quiet”.",
             "แปลว่าค่อนข้าง เช่น ค่อนข้างใหญ่ แค่สะกดคล้ายกับ 'quiet'"),
            ("quietness", N(NOUN_FOR_ADV, "kata benda “quietness” dipakai untuk menjelaskan cara.", "ใช้คำนาม 'quietness' บอกวิธีทำ"),
             "It is a noun; for how you close the door, use the -ly form.",
             "kata benda, padahal untuk menjelaskan cara menutup pintu dibutuhkan bentuk -ly.",
             "เป็นคำนาม แต่ถ้าบอกวิธีปิดประตูต้องใช้รูป -ly")]),
    # ---------------- 43. how much / how many ----------------
    dict(s="how_much_vs_how_many_quantity_questions", id="A2-401",
         stem="“___ eggs do we need?” “Six.”", opts=["How many", "How much", "How long", "How often"], ans="How many",
         why=("Eggs can be counted and the answer is a number, so we ask How many.",
              "Telur bisa dihitung dan jawabannya angka, jadi bertanya dengan “How many”.",
              "ไข่นับได้และคำตอบเป็นตัวเลข จึงถามด้วย 'How many'"),
         others=("'How much' is for things you can't count, 'how long' asks about time, and 'how often' asks how many times.",
                 "“How much” untuk benda yang nggak bisa dihitung, “how long” menanyakan lama waktu, dan “how often” menanyakan seberapa sering.",
                 "'how much' ใช้กับสิ่งที่นับไม่ได้ ส่วน 'how long' ถามระยะเวลา และ 'how often' ถามความถี่"),
         cue=("Count them? How many eggs, how many books.", "Bisa dihitung? “How many eggs”, “how many books”.", "ถ้านับเป็นชิ้นได้ให้ถามด้วย 'how many'"),
         rsn=("notice the answer six -> check that eggs can be counted -> choose the question for a number of things",
              "perhatikan jawaban “Six” → cek telur bisa dihitung → pilih kata tanya untuk jumlah benda",
              "สังเกตคำตอบ 'Six' → ดูว่าไข่นับได้ → เลือกคำถามที่ถามจำนวนสิ่งของ"),
         d=[("How much", L(MUCH_COUNTABLE, "“how much” dipakai untuk “eggs”.", "ใช้ 'how much' กับ 'eggs'"),
             "It is for things you can't count, but eggs can be counted.",
             "untuk benda yang nggak bisa dihitung, padahal telur bisa dihitung.",
             "ใช้กับสิ่งที่นับไม่ได้ แต่ไข่นับได้"),
            ("How long", HOW_LONG_AMOUNT,
             "It asks about time, not about a number of eggs.",
             "menanyakan lama waktu, bukan jumlah telur.",
             "ใช้ถามระยะเวลา ไม่ใช่จำนวนไข่"),
            ("How often", HOW_OFTEN_AMOUNT,
             "It asks how many times something happens, not how many eggs we need.",
             "menanyakan seberapa sering sesuatu terjadi, bukan berapa telur yang dibutuhkan.",
             "ใช้ถามว่าเกิดขึ้นบ่อยแค่ไหน ไม่ใช่ต้องใช้ไข่กี่ฟอง")]),
    dict(s="how_much_vs_how_many_quantity_questions", id="A2-402",
         stem="“___ is this T-shirt?” “Ten dollars.”", opts=["How much", "How many", "How price", "How long"], ans="How much",
         why=("The answer is a price, and we ask about prices with How much.",
              "Jawabannya harga, dan harga ditanyakan dengan “How much”.",
              "คำตอบเป็นราคา และการถามราคาใช้ 'How much'"),
         others=("'How many' is for counting things, 'how price' copies 'berapa harganya', and 'how long' asks about time.",
                 "“How many” untuk menghitung benda, “how price” meniru “berapa harganya”, dan “how long” menanyakan lama waktu.",
                 "'how many' ใช้นับสิ่งของ ส่วน 'how price' แปลคำต่อคำ และ 'how long' ใช้ถามระยะเวลา"),
         cue=("Asking the price: How much is it?", "Menanyakan harga: “How much is it?”", "เวลาถามราคาให้ใช้ 'how much' เสมอ"),
         rsn=("notice the answer ten dollars -> identify the question as asking a price -> choose the phrase for prices",
              "perhatikan jawaban “Ten dollars” → pastikan yang ditanyakan harga → pilih kata tanya untuk harga",
              "สังเกตคำตอบ 'Ten dollars' → ดูว่าคำถามถามราคา → เลือกคำถามที่ใช้ถามราคา"),
         d=[("How many", HOW_MANY_PRICE,
             "It counts things, but here we want the price.",
             "dipakai untuk menghitung benda, padahal di sini yang ditanya harga.",
             "ใช้นับสิ่งของ แต่ในที่นี้ถามราคา"),
            ("How price", HOW_PRICE,
             "It copies 'berapa harganya' word by word; English doesn't say it this way.",
             "meniru “berapa harganya” kata per kata, padahal bahasa Inggris nggak berkata begitu.",
             "แปลคำต่อคำ แต่ภาษาอังกฤษไม่พูดแบบนี้"),
            ("How long", N(HOW_LONG_AMOUNT, "“how long” dipakai untuk menanyakan harga.", "ใช้ 'how long' ถามราคา"),
             "It asks about time, not about a price.",
             "menanyakan lama waktu, bukan harga.",
             "ใช้ถามระยะเวลา ไม่ใช่ราคา")]),
    dict(s="how_much_vs_how_many_quantity_questions", id="A2-403",
         stem="___ milk do you want in your coffee?", opts=["How much", "How many", "How", "How much of"], ans="How much",
         why=("Milk cannot be counted, so we ask How much.",
              "Susu nggak bisa dihitung, jadi bertanya dengan “How much”.",
              "นมนับไม่ได้ จึงถามด้วย 'How much'"),
         others=("'How many' is for countable plurals, 'how' alone loses the idea of amount, and 'how much of' adds an extra of.",
                 "“How many” untuk benda jamak yang bisa dihitung, “how” saja kehilangan makna jumlah, dan “how much of” menambah “of” yang berlebihan.",
                 "'how many' ใช้กับคำนามพหูพจน์ที่นับได้ ส่วน 'how' อย่างเดียวไม่บอกปริมาณ และ 'how much of' เติม 'of' เกินมา"),
         cue=("Milk, water, sugar: How much?", "Susu, air, gula: “How much?”", "ของที่นับไม่ได้อย่างนมหรือน้ำตาลใช้ 'How much'"),
         rsn=("check if milk can be counted -> recall the question for amounts you can't count -> keep no extra word before milk",
              "cek susu bisa dihitung atau nggak → ingat kata tanya untuk jumlah yang nggak bisa dihitung → jangan tambah kata lain sebelum “milk”",
              "ดูว่านมนับได้หรือไม่ → นึกถึงคำถามของปริมาณที่นับไม่ได้ → ไม่เติมคำอื่นหน้า 'milk'"),
         d=[("How many", L(MANY_UNCOUNTABLE, "“how many” dipakai untuk “milk”.", "ใช้ 'how many' กับ 'milk'"),
             "It is for things you can count, but milk cannot be counted.",
             "untuk benda yang bisa dihitung, padahal susu nggak bisa dihitung.",
             "ใช้กับสิ่งที่นับได้ แต่นมนับไม่ได้"),
            ("How", L(BARE_HOW, "“how” saja dipakai untuk menanyakan jumlah susu.", "ใช้ 'how' อย่างเดียวถามปริมาณนม"),
             "It asks in what way, so the idea of amount is lost.",
             "menanyakan bagaimana caranya, jadi makna jumlahnya hilang.",
             "ถามว่าอย่างไร ความหมายเรื่องปริมาณจึงหายไป"),
            ("How much of", L(PARTITIVE_OF, "“of” diselipkan sebelum “milk”.", "ใส่ 'of' หน้า 'milk'"),
             "It adds of, but of needs a word like the after it.",
             "menambah “of”, padahal “of” butuh kata seperti “the” sesudahnya.",
             "เติม 'of' แต่ 'of' ต้องตามด้วยคำอย่าง 'the'")]),
    dict(s="how_much_vs_how_many_quantity_questions", id="A2-404",
         stem="How many ___ do you drink every day?", opts=["glasses of water", "water", "waters", "glass of water"], ans="glasses of water",
         why=("Water cannot be counted, so we count the glasses, and how many needs a plural.",
              "Air nggak bisa dihitung, jadi yang dihitung gelasnya, dan “how many” butuh bentuk jamak.",
              "น้ำนับไม่ได้ จึงนับเป็นแก้ว และ 'how many' ต้องใช้พหูพจน์"),
         others=("'Water' cannot follow how many, 'waters' adds -s to an uncountable noun, and 'glass of water' is singular.",
                 "“Water” nggak bisa dipakai sesudah “how many”, “waters” menambah -s ke benda yang nggak bisa dihitung, dan “glass of water” masih tunggal.",
                 "'water' ใช้หลัง 'how many' ไม่ได้ ส่วน 'waters' เติม -s ให้คำนามนับไม่ได้ และ 'glass of water' ยังเป็นเอกพจน์"),
         cue=("Count the containers: glasses of water, cups of tea.", "Hitung wadahnya: “glasses of water”, “cups of tea”.", "นับเป็นภาชนะ เช่น 'cups of tea'"),
         rsn=("notice how many -> check that water itself cannot be counted -> convert the container word into the plural",
              "perhatikan “how many” → cek air sendiri nggak bisa dihitung → buat kata wadahnya jadi jamak",
              "สังเกต 'how many' → ดูว่าน้ำนับเองไม่ได้ → ทำคำบอกภาชนะให้เป็นพหูพจน์"),
         d=[("water", L(MANY_UNCOUNTABLE, "“how many” dipakai langsung untuk “water”.", "ใช้ 'how many' กับ 'water' โดยตรง"),
             "It cannot be counted, so it can't come straight after how many.",
             "nggak bisa dihitung, jadi nggak bisa langsung dipakai sesudah “how many”.",
             "นับไม่ได้ จึงใช้หลัง 'how many' โดยตรงไม่ได้"),
            ("waters", L(REMOVE_PL, "“water” diberi -s supaya bisa dihitung.", "เติม -s ให้ 'water' เพื่อให้นับได้"),
             "It adds -s to an uncountable noun; count the glasses instead.",
             "menambah -s ke benda yang nggak bisa dihitung, padahal yang dihitung gelasnya.",
             "เติม -s ให้คำนามนับไม่ได้ แต่ต้องนับเป็นแก้วแทน"),
            ("glass of water", CONTAINER_SG,
             "It is singular, but how many needs a plural like glasses.",
             "masih tunggal, padahal “how many” butuh bentuk jamak seperti “glasses”.",
             "ยังเป็นเอกพจน์ แต่ 'how many' ต้องใช้รูปพหูพจน์อย่าง 'glasses'")]),
    # ---------------- 44. something / anything / nothing ----------------
    dict(s="indefinite_compounds_something_anything_nothing", id="A2-405",
         stem="There is ___ under my bed. I can hear it moving!", opts=["something", "anything", "nothing", "some thing"], ans="something",
         why=("The sentence is positive and I can hear it, so there really is a thing: something.",
              "Kalimatnya positif dan suaranya terdengar, jadi memang ada sesuatu, yaitu “something”.",
              "ประโยคเป็นบอกเล่าและได้ยินเสียง จึงมีบางอย่างอยู่จริง คือ 'something'"),
         others=("'Anything' needs a negative or a question, 'nothing' says there is no thing, and 'some thing' should be one word.",
                 "“Anything” butuh kalimat negatif atau tanya, “nothing” menyatakan nggak ada apa-apa, dan “some thing” seharusnya satu kata.",
                 "'anything' ต้องใช้ในประโยคปฏิเสธหรือคำถาม ส่วน 'nothing' บอกว่าไม่มีอะไร และ 'some thing' ต้องเขียนเป็นคำเดียว"),
         cue=("Positive and real: something.", "Positif dan benar-benar ada: “something”.", "ประโยคบอกเล่าและมีอยู่จริงใช้ 'something'"),
         rsn=("notice the positive verb is -> check that I can hear it moving -> choose the one-word positive form",
              "perhatikan kata kerja positif “is” → cek suaranya memang terdengar → pilih bentuk positif satu kata",
              "สังเกตคำกริยาบอกเล่า 'is' → ดูว่าได้ยินเสียงจริง → เลือกรูปบอกเล่าที่เป็นคำเดียว"),
         d=[("anything", L(ANYTHING_POS, "“anything” dipakai di kalimat positif.", "ใช้ 'anything' ในประโยคบอกเล่า"),
             "It needs a negative verb or a question, but this sentence is positive.",
             "butuh kata kerja negatif atau kalimat tanya, padahal kalimat ini positif.",
             "ต้องใช้กับคำกริยาปฏิเสธหรือคำถาม แต่ประโยคนี้เป็นบอกเล่า"),
            ("nothing", NOTHING_CONTRA,
             "It says there is no thing, but I can hear it moving.",
             "menyatakan nggak ada apa-apa, padahal suaranya terdengar bergerak.",
             "บอกว่าไม่มีอะไร แต่ได้ยินเสียงบางอย่างขยับอยู่"),
            ("some thing", SPLIT_COMPOUND,
             "It splits one word into two; English writes it as one word.",
             "memecah satu kata jadi dua, padahal bahasa Inggris menulisnya sebagai satu kata.",
             "แยกคำเดียวเป็นสองคำ แต่ภาษาอังกฤษเขียนเป็นคำเดียว")]),
    dict(s="indefinite_compounds_something_anything_nothing", id="A2-406",
         stem="She hasn't eaten ___ today. She must be very hungry.", opts=["anything", "nothing", "something", "no"], ans="anything",
         why=("Hasn't is already negative, so we use anything.",
              "“Hasn't” sudah negatif, jadi pakai “anything”.",
              "'hasn't' เป็นรูปปฏิเสธอยู่แล้ว จึงใช้ 'anything'"),
         others=("'Nothing' adds a second negative, 'something' is for positive sentences, and 'no' needs a noun after it.",
                 "“Nothing” menambah negatif kedua, “something” untuk kalimat positif, dan “no” butuh kata benda sesudahnya.",
                 "'nothing' เติมคำปฏิเสธคำที่สอง ส่วน 'something' ใช้ในประโยคบอกเล่า และ 'no' ต้องมีคำนามตามหลัง"),
         cue=("hasn't … anything = has … nothing.", "“hasn't … anything” = “has … nothing”.", "ประโยคที่มี 'hasn't' ใช้คู่กับ 'anything' ไม่ใช้ 'nothing'"),
         rsn=("notice the negative hasn't -> recall that one negative is enough -> choose the word for negative sentences",
              "perhatikan bentuk negatif “hasn't” → ingat satu negatif sudah cukup → pilih kata untuk kalimat negatif",
              "สังเกตรูปปฏิเสธ 'hasn't' → นึกว่าคำปฏิเสธคำเดียวก็พอ → เลือกคำที่ใช้ในประโยคปฏิเสธ"),
         d=[("nothing", L(DOUBLE_NEG, "“hasn't” dan “nothing” dipakai bersamaan.", "ใช้ 'hasn't' กับ 'nothing' พร้อมกัน"),
             "It adds a second negative; hasn't is already negative.",
             "menambah negatif kedua, padahal “hasn't” sudah negatif.",
             "เติมคำปฏิเสธคำที่สอง ทั้งที่ 'hasn't' เป็นปฏิเสธอยู่แล้ว"),
            ("something", L(POS_IN_NEG, "“something” dipakai di kalimat negatif.", "ใช้ 'something' ในประโยคปฏิเสธ"),
             "It is for positive sentences, but hasn't makes this one negative.",
             "untuk kalimat positif, padahal “hasn't” membuat kalimat ini negatif.",
             "ใช้ในประโยคบอกเล่า แต่ 'hasn't' ทำให้ประโยคนี้เป็นปฏิเสธ"),
            ("no", L(NO_AFTER_NOT, "“no” dipakai sesudah “hasn't” tanpa kata benda.", "ใช้ 'no' หลัง 'hasn't' โดยไม่มีคำนาม"),
             "It adds a second negative and needs a noun after it.",
             "menambah negatif kedua dan butuh kata benda sesudahnya.",
             "เติมคำปฏิเสธคำที่สองและต้องมีคำนามตามหลัง")]),
    dict(s="indefinite_compounds_something_anything_nothing", id="A2-407",
         stem="___ happened at school today. It was a boring day.", opts=["Nothing", "Anything", "Something", "None"], ans="Nothing",
         why=("The day was boring, so no event happened, and the verb happened is positive.",
              "Harinya membosankan, jadi nggak ada kejadian apa-apa, dan kata kerja “happened” berbentuk positif.",
              "วันนั้นน่าเบื่อ จึงไม่มีอะไรเกิดขึ้น และคำกริยา 'happened' เป็นรูปบอกเล่า"),
         others=("'Anything' can't start a positive sentence like this, 'something' says an event happened, and 'none' is not used this way for things.",
                 "“Anything” nggak bisa jadi subjek kalimat positif seperti ini, “something” berarti ada kejadian, dan “none” nggak dipakai begini untuk benda.",
                 "'anything' ใช้เป็นประธานของประโยคบอกเล่าแบบนี้ไม่ได้ ส่วน 'something' แปลว่ามีเรื่องเกิดขึ้น และ 'none' ไม่ใช้แบบนี้กับสิ่งของ"),
         cue=("No event at all + positive verb: Nothing happened.", "Nggak ada kejadian + kata kerja positif: “Nothing happened”.", "ไม่มีอะไรเกิดขึ้นและกริยาเป็นบอกเล่าใช้ 'Nothing happened'"),
         rsn=("notice a boring day -> identify the meaning as no event -> check that happened is positive",
              "perhatikan “a boring day” → pastikan maksudnya nggak ada kejadian → cek “happened” berbentuk positif",
              "สังเกต 'a boring day' → ดูว่าหมายถึงไม่มีอะไรเกิดขึ้น → ดูว่า 'happened' เป็นรูปบอกเล่า"),
         d=[("Anything", L(ANYTHING_POS, "“anything” dipakai sebagai subjek kalimat positif.", "ใช้ 'anything' เป็นประธานของประโยคบอกเล่า"),
             "It needs a negative verb or a question, but happened is positive.",
             "butuh kata kerja negatif atau kalimat tanya, padahal “happened” positif.",
             "ต้องใช้กับคำกริยาปฏิเสธหรือคำถาม แต่ 'happened' เป็นบอกเล่า"),
            ("Something", L(POS_IN_NEG, "“something” dipakai padahal harinya membosankan.", "ใช้ 'something' ทั้งที่วันนั้นน่าเบื่อ"),
             "It says an event happened, but the day was boring.",
             "berarti ada kejadian, padahal harinya membosankan.",
             "แปลว่ามีเรื่องเกิดขึ้น แต่วันนั้นน่าเบื่อ"),
            ("None", NONE_THING,
             "It points back to people or things already named, not to events in general.",
             "merujuk ke orang atau benda yang sudah disebut, bukan ke kejadian secara umum.",
             "ใช้กับคนหรือสิ่งของที่พูดถึงไปแล้ว ไม่ใช่เหตุการณ์ทั่วไป")]),
    dict(s="indefinite_compounds_something_anything_nothing", id="A2-408",
         stem="I can't see ___. It's too dark in here.", opts=["anything", "nothing", "something", "no thing"], ans="anything",
         why=("Can't is already negative, so we use anything, not a second negative.",
              "“Can't” sudah negatif, jadi pakai “anything”, bukan negatif kedua.",
              "'can't' เป็นรูปปฏิเสธอยู่แล้ว จึงใช้ 'anything' ไม่ใช้คำปฏิเสธคำที่สอง"),
         others=("'Nothing' adds a second negative, 'something' is for positive sentences, and 'no thing' splits one word.",
                 "“Nothing” menambah negatif kedua, “something” untuk kalimat positif, dan “no thing” memecah satu kata.",
                 "'nothing' เติมคำปฏิเสธคำที่สอง ส่วน 'something' ใช้ในประโยคบอกเล่า และ 'no thing' แยกคำเดียวเป็นสองคำ"),
         cue=("can't see anything = can see nothing.", "“can't see anything” = “can see nothing”.", "ประโยคที่มี 'can't' ใช้คู่กับ 'anything' เพราะปฏิเสธไปแล้ว"),
         rsn=("notice the negative can't -> recall that one negative is enough -> choose the one-word form for negative sentences",
              "perhatikan bentuk negatif “can't” → ingat satu negatif sudah cukup → pilih bentuk satu kata untuk kalimat negatif",
              "สังเกตรูปปฏิเสธ 'can't' → นึกว่าคำปฏิเสธคำเดียวก็พอ → เลือกคำเดียวที่ใช้ในประโยคปฏิเสธ"),
         d=[("nothing", L(DOUBLE_NEG, "“can't” dan “nothing” dipakai bersamaan.", "ใช้ 'can't' กับ 'nothing' พร้อมกัน"),
             "It adds a second negative; can't is already negative.",
             "menambah negatif kedua, padahal “can't” sudah negatif.",
             "เติมคำปฏิเสธคำที่สอง ทั้งที่ 'can't' เป็นปฏิเสธอยู่แล้ว"),
            ("something", L(POS_IN_NEG, "“something” dipakai sesudah “can't”.", "ใช้ 'something' หลัง 'can't'"),
             "It is for positive sentences, but can't makes this one negative.",
             "untuk kalimat positif, padahal “can't” membuat kalimat ini negatif.",
             "ใช้ในประโยคบอกเล่า แต่ 'can't' ทำให้ประโยคนี้เป็นปฏิเสธ"),
            ("no thing", L(SPLIT_NEG, "kata negatif dipecah jadi dua kata.", "แยกคำปฏิเสธเป็นสองคำ"),
             "It splits one word into two and adds a second negative.",
             "memecah satu kata jadi dua dan menambah negatif kedua.",
             "แยกคำเดียวเป็นสองคำและเติมคำปฏิเสธคำที่สอง")]),
    # ---------------- 45. because / so / because of ----------------
    dict(s="cause_result_connectors_because_vs_so", id="A2-409",
         stem="We stayed inside ___ it was raining.", opts=["because", "so", "because of", "so that"], ans="because",
         why=("It was raining is the reason for staying inside, so we use because.",
              "“It was raining” adalah alasan kami tetap di dalam, jadi pakai “because”.",
              "'it was raining' เป็นเหตุผลที่อยู่ข้างใน จึงใช้ 'because'"),
         others=("'So' comes before a result, 'because of' needs a noun, and 'so that' gives a purpose.",
                 "“So” dipakai sebelum akibat, “because of” butuh kata benda, dan “so that” menyatakan tujuan.",
                 "'so' ใช้หน้าผลลัพธ์ ส่วน 'because of' ต้องตามด้วยคำนาม และ 'so that' บอกจุดประสงค์"),
         cue=("Result + because + reason.", "Akibat + “because” + alasan.", "ผลลัพธ์ + 'because' + เหตุผล"),
         rsn=("identify it was raining as the reason -> notice that it is a whole sentence -> choose the word that brings a reason",
              "kenali “it was raining” sebagai alasan → perhatikan bagian itu kalimat utuh → pilih kata yang membawa alasan",
              "ดูว่า 'it was raining' เป็นเหตุผล → สังเกตว่าเป็นประโยคเต็ม → เลือกคำที่นำเหตุผล"),
         d=[("so", L(SO_REASON, "“so” dipakai sebelum alasan.", "ใช้ 'so' หน้าเหตุผล"),
             "It comes before a result, but the rain is the reason.",
             "dipakai sebelum akibat, padahal hujan itu alasannya.",
             "ใช้หน้าผลลัพธ์ แต่ฝนตกเป็นเหตุผล"),
            ("because of", L(BECAUSE_OF_CLAUSE, "“because of” dipakai sebelum kalimat utuh.", "ใช้ 'because of' หน้าประโยคเต็ม"),
             "It needs a noun, like the rain, not a whole sentence.",
             "butuh kata benda, seperti “the rain”, bukan kalimat utuh.",
             "ต้องตามด้วยคำนาม เช่น 'the rain' ไม่ใช่ประโยคเต็ม"),
            ("so that", L(SO_THAT, "“so that” dipakai untuk alasan.", "ใช้ 'so that' บอกเหตุผล"),
             "It gives a purpose, something you want to happen, not a reason.",
             "menyatakan tujuan, yaitu hal yang ingin dicapai, bukan alasan.",
             "บอกจุดประสงค์ซึ่งเป็นสิ่งที่อยากให้เกิด ไม่ใช่เหตุผล")]),
    dict(s="cause_result_connectors_because_vs_so", id="A2-410",
         stem="The shop was closed, ___ we went home.", opts=["so", "because", "because of", "but"], ans="so",
         why=("We went home is the result of the closed shop, so we use so.",
              "“We went home” adalah akibat dari toko yang tutup, jadi pakai “so”.",
              "'we went home' เป็นผลจากร้านที่ปิด จึงใช้ 'so'"),
         others=("'Because' comes before a reason, 'because of' needs a noun, and 'but' shows a contrast.",
                 "Pilihan “because” membawa alasan, “because of” butuh kata benda, dan “but” menandai pertentangan.",
                 "'because' ใช้หน้าเหตุผล ส่วน 'because of' ต้องตามด้วยคำนาม และ 'but' ใช้บอกความขัดแย้ง"),
         cue=("Reason + so + result.", "Alasan + “so” + akibat.", "เหตุผล + 'so' + ผลลัพธ์"),
         rsn=("identify the shop was closed as the reason -> identify we went home as the result -> choose the word that brings a result",
              "kenali “the shop was closed” sebagai alasan → kenali “we went home” sebagai akibat → pilih kata yang membawa akibat",
              "ดูว่า 'the shop was closed' เป็นเหตุผล → ดูว่า 'we went home' เป็นผลลัพธ์ → เลือกคำที่นำผลลัพธ์"),
         d=[("because", L(BECAUSE_RESULT, "“because” dipakai sebelum akibat.", "ใช้ 'because' หน้าผลลัพธ์"),
             "It comes before a reason, but going home is the result.",
             "dipakai sebelum alasan, padahal pulang itu akibatnya.",
             "ใช้หน้าเหตุผล แต่การกลับบ้านเป็นผลลัพธ์"),
            ("because of", L(BECAUSE_OF_CLAUSE, "“because of” dipakai sebelum kalimat utuh.", "ใช้ 'because of' หน้าประโยคเต็ม"),
             "It needs a noun and brings a reason, but here a whole sentence gives a result.",
             "butuh kata benda dan membawa alasan, padahal di sini kalimat utuhnya berisi akibat.",
             "ต้องตามด้วยคำนามและใช้บอกเหตุผล แต่ในที่นี้เป็นประโยคเต็มที่บอกผลลัพธ์"),
            ("but", BUT_RESULT,
             "It shows a contrast, but going home is the natural result of the closed shop.",
             "menandai pertentangan, padahal pulang justru akibat wajar dari toko yang tutup.",
             "ใช้บอกความขัดแย้ง แต่การกลับบ้านเป็นผลที่ตามมาจากร้านที่ปิด")]),
    dict(s="cause_result_connectors_because_vs_so", id="A2-411",
         stem="The football match was cancelled ___ the heavy rain.", opts=["because of", "because", "so", "so that"], ans="because of",
         why=("The heavy rain is a noun, not a whole sentence, so we use because of.",
              "“The heavy rain” kata benda, bukan kalimat utuh, jadi pakai “because of”.",
              "'the heavy rain' เป็นคำนาม ไม่ใช่ประโยคเต็ม จึงใช้ 'because of'"),
         others=("'Because' needs a subject and verb after it, 'so' brings a result, and 'so that' gives a purpose.",
                 "“Because” butuh subjek dan kata kerja sesudahnya, “so” membawa akibat, dan “so that” menyatakan tujuan.",
                 "'because' ต้องตามด้วยประธานและคำกริยา ส่วน 'so' ใช้บอกผลลัพธ์ และ 'so that' บอกจุดประสงค์"),
         cue=("Noun after it? because of the rain.", "Sesudahnya kata benda? “because of the rain”.", "ถ้าข้างหลังเป็นคำนามให้ใช้ 'because of'"),
         rsn=("identify the heavy rain as the reason -> notice that it is a noun, not a sentence -> choose the reason word that goes before a noun",
              "kenali “the heavy rain” sebagai alasan → perhatikan itu kata benda, bukan kalimat → pilih kata alasan yang dipakai sebelum kata benda",
              "ดูว่า 'the heavy rain' เป็นเหตุผล → สังเกตว่าเป็นคำนาม ไม่ใช่ประโยค → เลือกคำบอกเหตุผลที่ใช้หน้าคำนาม"),
         d=[("because", BECAUSE_NP,
             "It needs a subject and verb after it, but here there is only a noun.",
             "butuh subjek dan kata kerja sesudahnya, padahal di sini cuma ada kata benda.",
             "ต้องตามด้วยประธานและคำกริยา แต่ในที่นี้มีแค่คำนาม"),
            ("so", SO_NP,
             "It brings a result, but the rain is the reason.",
             "membawa akibat, padahal hujan itu alasannya.",
             "ใช้บอกผลลัพธ์ แต่ฝนเป็นเหตุผล"),
            ("so that", L(SO_THAT, "“so that” dipakai sebelum kata benda untuk alasan.", "ใช้ 'so that' หน้าคำนามเพื่อบอกเหตุผล"),
             "It gives a purpose, and nobody wanted the rain.",
             "menyatakan tujuan, padahal hujan bukan sesuatu yang diinginkan.",
             "บอกจุดประสงค์ แต่ไม่มีใครอยากให้ฝนตก")]),
    dict(s="cause_result_connectors_because_vs_so", id="A2-412",
         stem="___ it was very hot, we went swimming.", opts=["Because", "So", "Because of", "So that"], ans="Because",
         why=("It was very hot is the reason, and a reason can come first with Because.",
              "“It was very hot” adalah alasan, dan alasan boleh ditaruh di depan dengan “Because”.",
              "'it was very hot' เป็นเหตุผล และเหตุผลขึ้นต้นประโยคได้ด้วย 'Because'"),
         others=("'So' cannot open a reason, 'because of' needs a noun, and 'so that' gives a purpose.",
                 "“So” nggak bisa membuka alasan, “because of” butuh kata benda, dan “so that” menyatakan tujuan.",
                 "'so' ใช้ขึ้นต้นเหตุผลไม่ได้ ส่วน 'because of' ต้องตามด้วยคำนาม และ 'so that' บอกจุดประสงค์"),
         cue=("Reason first: Because it was hot, we swam.", "Alasan di depan: “Because it was hot, we swam”.", "ขึ้นต้นด้วยเหตุผลได้ เช่น 'Because it was hot, we swam'"),
         rsn=("identify it was very hot as the reason -> notice that the reason comes first -> choose the word that brings a reason",
              "kenali “it was very hot” sebagai alasan → perhatikan alasannya ada di depan → pilih kata yang membawa alasan",
              "ดูว่า 'it was very hot' เป็นเหตุผล → สังเกตว่าเหตุผลอยู่ต้นประโยค → เลือกคำที่นำเหตุผล"),
         d=[("So", SO_START,
             "It brings a result, so it cannot open the reason at the start.",
             "membawa akibat, jadi nggak bisa membuka alasan di awal kalimat.",
             "ใช้บอกผลลัพธ์ จึงใช้ขึ้นต้นเหตุผลไม่ได้"),
            ("Because of", L(BECAUSE_OF_CLAUSE, "“because of” dipakai sebelum kalimat utuh.", "ใช้ 'because of' หน้าประโยคเต็ม"),
             "It needs a noun, like the heat, not a whole sentence.",
             "butuh kata benda, seperti “the heat”, bukan kalimat utuh.",
             "ต้องตามด้วยคำนาม เช่น 'the heat' ไม่ใช่ประโยคเต็ม"),
            ("So that", L(SO_THAT, "“so that” dipakai untuk alasan di awal kalimat.", "ใช้ 'so that' บอกเหตุผลที่ต้นประโยค"),
             "It gives a purpose, but the hot weather is a reason.",
             "menyatakan tujuan, padahal cuaca panas itu alasan.",
             "บอกจุดประสงค์ แต่อากาศร้อนเป็นเหตุผล")]),
    # ---------------- 46. better / best / worse ----------------
    dict(s="irregular_comparative_better_worse_forms", id="A2-413",
         stem="My English is ___ now than last year. I practise every day.", opts=["better", "gooder", "more better", "best"], ans="better",
         why=("Good has a special comparative form, better, and than needs a comparative.",
              "“Good” punya bentuk “lebih” yang khusus, yaitu “better”, dan “than” butuh bentuk “lebih”.",
              "'good' มีรูปขั้นกว่าพิเศษ คือ 'better' และ 'than' ต้องใช้รูปขั้นกว่า"),
         others=("'Gooder' is not a word, 'more better' marks the comparison twice, and 'best' is for a group.",
                 "“Gooder” bukan kata bahasa Inggris, “more better” menandai perbandingan dua kali, dan “best” untuk satu kelompok.",
                 "'gooder' ไม่มีในภาษาอังกฤษ ส่วน 'more better' บอกการเปรียบเทียบซ้ำสองครั้ง และ 'best' ใช้กับทั้งกลุ่ม"),
         cue=("good → better → the best.", "“good” → “better” → “the best”.", "คำว่า 'good' เปลี่ยนรูปเป็น 'better' และ 'the best' ไม่ได้เติม -er"),
         rsn=("notice than -> recall that good has a special form -> check that nothing is added before it",
              "perhatikan “than” → ingat “good” punya bentuk khusus → cek nggak ada kata tambahan di depannya",
              "สังเกต 'than' → นึกว่า 'good' มีรูปพิเศษ → ดูว่าไม่มีคำอื่นเติมข้างหน้า"),
         d=[("gooder", L(ER_IRREG, "akhiran -er ditempel ke “good”.", "เติม -er ให้ 'good'"),
             "It is not an English word; good has its own special form.",
             "bukan kata bahasa Inggris, karena “good” punya bentuk khusus sendiri.",
             "ไม่มีในภาษาอังกฤษ เพราะ 'good' มีรูปพิเศษของตัวเอง"),
            ("more better", L(DOUBLE_COMP, "“more” ditumpuk di depan bentuk khusus.", "ใช้ 'more' ซ้อนหน้ารูปพิเศษ"),
             "It marks the comparison twice; the special form alone is enough.",
             "menandai perbandingan dua kali, padahal bentuk khususnya saja sudah cukup.",
             "บอกการเปรียบเทียบซ้ำสองครั้ง ทั้งที่ใช้รูปพิเศษอย่างเดียวก็พอ"),
            ("best", L(BEST_THAN, "bentuk “paling” dipakai sebelum “than”.", "ใช้ขั้นสูงสุดหน้า 'than'"),
             "It is for the top of a group, but than compares two things.",
             "untuk juara satu kelompok, padahal “than” membandingkan dua hal.",
             "ใช้กับอันดับหนึ่งของกลุ่ม แต่ 'than' เปรียบเทียบสองสิ่ง")]),
    dict(s="irregular_comparative_better_worse_forms", id="A2-414",
         stem="This is the ___ day of my life! I got a new puppy!", opts=["best", "better", "most good", "goodest"], ans="best",
         why=("The day is number one of all the days in my life, so we use the best.",
              "Hari ini nomor satu di antara semua hari dalam hidupku, jadi pakai “the best”.",
              "วันนี้เป็นวันที่ดีที่สุดในบรรดาทุกวันในชีวิต จึงใช้ 'the best'"),
         others=("'Better' compares two things, 'most good' uses most with good, and 'goodest' is not a word.",
                 "“Better” membandingkan dua hal, “most good” memakai “most” untuk “good”, dan “goodest” bukan kata bahasa Inggris.",
                 "'better' ใช้เปรียบเทียบสองสิ่ง ส่วน 'most good' ใช้ 'most' กับ 'good' และ 'goodest' ไม่มีในภาษาอังกฤษ"),
         cue=("Number one of all: the best.", "Nomor satu dari semuanya: “the best”.", "อันดับหนึ่งของทั้งหมดใช้ 'the best'"),
         rsn=("notice the and of my life -> identify the day as number one of all -> recall the special form of good for a group",
              "perhatikan “the” dan “of my life” → pastikan harinya nomor satu dari semuanya → ingat bentuk khusus “good” untuk satu kelompok",
              "สังเกต 'the' และ 'of my life' → ดูว่าวันนี้เป็นอันดับหนึ่งของทั้งหมด → นึกถึงรูปพิเศษของ 'good' เมื่อเทียบทั้งกลุ่ม"),
         d=[("better", N(THE_COMP, "bentuk “lebih” dipakai untuk semua hari dalam hidup.", "ใช้ขั้นกว่ากับทุกวันในชีวิต"),
             "It compares two things, but here the day is compared with all the days of my life.",
             "membandingkan dua hal, padahal di sini harinya dibandingkan dengan semua hari dalam hidupku.",
             "ใช้เปรียบเทียบสองสิ่ง แต่ในที่นี้เทียบกับทุกวันในชีวิต"),
            ("most good", L(MORE_IRREG, "“most” dipakai untuk “good”.", "ใช้ 'most' กับ 'good'"),
             "It uses most, but good has its own special form.",
             "memakai “most”, padahal “good” punya bentuk khusus sendiri.",
             "ใช้ 'most' แต่ 'good' มีรูปพิเศษของตัวเอง"),
            ("goodest", GOODEST,
             "It is not an English word; good has a special form for a group.",
             "bukan kata bahasa Inggris, karena “good” punya bentuk khusus untuk satu kelompok.",
             "ไม่มีในภาษาอังกฤษ เพราะ 'good' มีรูปพิเศษเมื่อเทียบทั้งกลุ่ม")]),
    dict(s="irregular_comparative_better_worse_forms", id="A2-415",
         stem="My cold is ___ today. I feel terrible!", opts=["worse", "badder", "more bad", "more worse"], ans="worse",
         why=("I feel terrible, so my cold is more bad than before, and the special form of bad is worse.",
              "Aku merasa sangat nggak enak badan, jadi pilek hari ini lebih parah dari sebelumnya, dan bentuk khusus “bad” adalah “worse”.",
              "ฉันรู้สึกแย่มาก ไข้หวัดวันนี้จึงแย่กว่าเดิม และรูปพิเศษของ 'bad' คือ 'worse'"),
         others=("'Badder' is not a word, 'more bad' uses more with bad, and 'more worse' marks the comparison twice.",
                 "“Badder” bukan kata bahasa Inggris, “more bad” memakai “more” untuk “bad”, dan “more worse” menandai perbandingan dua kali.",
                 "'badder' ไม่มีในภาษาอังกฤษ ส่วน 'more bad' ใช้ 'more' กับ 'bad' และ 'more worse' บอกการเปรียบเทียบซ้ำสองครั้ง"),
         cue=("bad → worse → the worst.", "“bad” → “worse” → “the worst”.", "คำว่า 'bad' เปลี่ยนรูปเป็น 'worse' และ 'the worst' ไม่ได้เติม -er"),
         rsn=("notice today and I feel terrible -> identify a comparison with before -> recall the special form of bad",
              "perhatikan “today” dan “I feel terrible” → pastikan ada perbandingan dengan sebelumnya → ingat bentuk khusus “bad”",
              "สังเกต 'today' และ 'I feel terrible' → ดูว่ามีการเทียบกับก่อนหน้า → นึกถึงรูปพิเศษของ 'bad'"),
         d=[("badder", L(ER_IRREG, "akhiran -er ditempel ke “bad”.", "เติม -er ให้ 'bad'"),
             "It is not an English word; bad has its own special form.",
             "bukan kata bahasa Inggris, karena “bad” punya bentuk khusus sendiri.",
             "ไม่มีในภาษาอังกฤษ เพราะ 'bad' มีรูปพิเศษของตัวเอง"),
            ("more bad", L(MORE_IRREG, "“more” dipakai untuk “bad”.", "ใช้ 'more' กับ 'bad'"),
             "It uses more, but bad has its own special form.",
             "memakai “more”, padahal “bad” punya bentuk khusus sendiri.",
             "ใช้ 'more' แต่ 'bad' มีรูปพิเศษของตัวเอง"),
            ("more worse", L(DOUBLE_COMP, "“more” ditumpuk di depan bentuk khusus.", "ใช้ 'more' ซ้อนหน้ารูปพิเศษ"),
             "It marks the comparison twice; the special form alone is enough.",
             "menandai perbandingan dua kali, padahal bentuk khususnya saja sudah cukup.",
             "บอกการเปรียบเทียบซ้ำสองครั้ง ทั้งที่ใช้รูปพิเศษอย่างเดียวก็พอ")]),
    dict(s="irregular_comparative_better_worse_forms", id="A2-416",
         stem="Walking is ___ for your health than taking the bus.", opts=["better", "more good", "best", "good"], ans="better",
         why=("Two things are compared with than, and the comparative of good is better.",
              "Dua hal dibandingkan dengan “than”, dan bentuk “lebih” dari “good” adalah “better”.",
              "เปรียบเทียบสองสิ่งด้วย 'than' และขั้นกว่าของ 'good' คือ 'better'"),
         others=("'More good' uses more with good, 'best' is for a group, and 'good' does not compare.",
                 "“More good” memakai “more” untuk “good”, “best” untuk satu kelompok, dan “good” nggak membandingkan.",
                 "'more good' ใช้ 'more' กับ 'good' ส่วน 'best' ใช้กับทั้งกลุ่ม และ 'good' ไม่ได้เปรียบเทียบ"),
         cue=("good + than? better than.", "“good” + “than”? “better than”.", "'good' ที่ตามด้วย 'than' ต้องเป็น 'better than'"),
         rsn=("notice than and the two choices -> recall that good has a special comparative -> check that nothing is added before it",
              "perhatikan “than” dan dua pilihannya → ingat “good” punya bentuk “lebih” yang khusus → cek nggak ada kata tambahan di depannya",
              "สังเกต 'than' และสองทางเลือก → นึกว่า 'good' มีขั้นกว่าแบบพิเศษ → ดูว่าไม่มีคำอื่นเติมข้างหน้า"),
         d=[("more good", L(MORE_IRREG, "“more” dipakai untuk “good”.", "ใช้ 'more' กับ 'good'"),
             "It uses more, but good has its own special comparative.",
             "memakai “more”, padahal “good” punya bentuk “lebih” yang khusus.",
             "ใช้ 'more' แต่ 'good' มีขั้นกว่าแบบพิเศษของตัวเอง"),
            ("best", L(BEST_THAN, "bentuk “paling” dipakai sebelum “than”.", "ใช้ขั้นสูงสุดหน้า 'than'"),
             "It is for the top of a group, but than compares only two ways to travel.",
             "untuk juara satu kelompok, padahal “than” cuma membandingkan dua cara bepergian.",
             "ใช้กับอันดับหนึ่งของกลุ่ม แต่ 'than' เปรียบเทียบการเดินทางแค่สองแบบ"),
            ("good", L(BASE_THAN, "kata sifat bentuk dasar dipakai sebelum “than”.", "ใช้คำคุณศัพท์รูปพื้นฐานหน้า 'than'"),
             "It does not compare, but than needs a comparative.",
             "nggak membandingkan, padahal “than” butuh bentuk “lebih”.",
             "ไม่ได้เปรียบเทียบ แต่ 'than' ต้องใช้รูปขั้นกว่า")]),
]
