# A2 lesson 18-24: soal latihan baru (m025-376). Format: lihat build_pack.py.
LESSONS = {
    "imperative_commands_base_form": dict(
        obj=("Give instructions with the base verb, use Don't + base verb to stop someone, and Let's + base verb to suggest.",
             "Beri perintah dengan kata kerja bentuk dasar, pakai “Don't” + bentuk dasar untuk melarang, dan “Let's” + bentuk dasar untuk mengajak.",
             "ให้คำสั่งด้วยคำกริยารูปพื้นฐาน ใช้ 'Don't' + รูปพื้นฐานเพื่อห้าม และใช้ 'Let's' + รูปพื้นฐานเพื่อชวน"),
        mis=("Learner adds a subject, -s, -ing, or to to the command, or uses 'not' alone to stop someone.",
             "Kamu menambahkan subjek, -s, -ing, atau “to” pada kalimat perintah, atau memakai “not” saja untuk melarang.",
             "คุณเติมประธาน เติม -s เติม -ing หรือใส่ 'to' ในประโยคคำสั่ง หรือใช้แค่ 'not' เพื่อห้าม"),
        rule=("Command: base verb (Open, Sit). Warning: Don't + base verb (Don't run). Suggestion: Let's + base verb (Let's go).",
              "Kalimat perintah, ajakan, atau instruksi langsung:<br>• Kalimat perintah positif diawali langsung dengan kata kerja dasar polos (Verb 1), tanpa subjek, tanpa to, tanpa -ing atau -s.<br>• Kalimat larangan diawali dengan “Don't” + kata kerja dasar.<br><br>💡 <b>RUMUS KILAT</b>:<br>Perintah / suruhan ➡️ Langsung <b>Verb 1 polos</b> di awal (contoh: <i>Open the door!</i>, bukan <i>To open</i> atau <i>Opening</i> ❌).<br>Larangan ➡️ Awali dengan <b>Don't + Verb 1</b> (contoh: <i>Don't touch!</i>).",
              "คำสั่งใช้คำกริยารูปพื้นฐาน ('Open', 'Sit') คำห้ามใช้ 'Don't' + รูปพื้นฐาน ('Don't run') และคำชวนใช้ 'Let's' + รูปพื้นฐาน ('Let's go')"),
        avoid=("Start with the verb itself: no subject, no -s, no -ing, no to.",
               "Mulai langsung dari kata kerjanya: tanpa subjek, tanpa -s, tanpa -ing, tanpa “to”.",
               "เริ่มประโยคด้วยคำกริยาเลย ไม่มีประธาน ไม่เติม -s ไม่เติม -ing และไม่มี 'to'"),
    ),
    "adverbs_of_frequency_mid_position": dict(
        obj=("Put always, usually, often, sometimes, and never before the main verb but after be.",
             "Taruh “always”, “usually”, “often”, “sometimes”, dan “never” sebelum kata kerja utama, tapi sesudah “be”.",
             "วาง 'always', 'usually', 'often', 'sometimes' และ 'never' ไว้หน้าคำกริยาหลัก แต่ไว้หลัง 'be'"),
        mis=("Learner puts the frequency word after the verb or at the end, or forgets that the verb still matches the subject.",
             "Kamu menaruh kata frekuensi sesudah kata kerja atau di akhir kalimat, atau lupa kata kerjanya tetap harus cocok dengan subjek.",
             "คุณวางคำบอกความถี่ไว้หลังคำกริยาหรือท้ายประโยค หรือลืมว่าคำกริยายังต้องเข้ากับประธาน"),
        rule=("Frequency word before the main verb (She often reads), after am, is, are (He is always late). In questions: Do you usually…?",
              "Posisi kata keterangan frekuensi (always, usually, often, sometimes, rarely, never):<br>• Diletakkan SEBELUM kata kerja aksi biasa (contoh: <i>I always drink milk</i>).<br>• Diletakkan SETELAH to be (am, is, are, was, were) (contoh: <i>He is always late</i>).<br><br>💡 <b>RUMUS KILAT</b>:<br>Ada kata kerja aksi biasa ➡️ Taruh keterangan <b>SEBELUM</b> kata kerja (contoh: <i>She never eats meat</i>).<br>Ada to be (am/is/are) ➡️ Taruh keterangan <b>SETELAH</b> to be (contoh: <i>She is never angry</i>).",
              "คำบอกความถี่อยู่หน้าคำกริยาหลัก ('She often reads') แต่อยู่หลัง 'am/is/are' ('He is always late') ส่วนคำถามใช้ 'Do you usually…?'"),
        avoid=("Find the verb. Is it be? Put the frequency word after it. Any other verb? Put it before.",
               "Cari kata kerjanya. Kalau “be”, taruh kata frekuensi sesudahnya. Kalau kata kerja lain, taruh sebelumnya.",
               "หาคำกริยาก่อน ถ้าเป็น 'be' ให้วางคำบอกความถี่ไว้ข้างหลัง ถ้าเป็นกริยาอื่นให้วางไว้ข้างหน้า"),
    ),
    "possessive_s_noun_ownership": dict(
        obj=("Show who owns something with 's for one owner and s' for plural owners ending in s.",
             "Tunjukkan pemilik dengan 's untuk satu pemilik dan s' untuk pemilik jamak yang berakhiran s.",
             "บอกความเป็นเจ้าของด้วย 's สำหรับเจ้าของคนเดียว และ s' สำหรับเจ้าของหลายคนที่ลงท้ายด้วย s"),
        mis=("Learner puts two nouns side by side as in 'tas Sinta', writes -s without an apostrophe, or adds his or her after the name.",
             "Kamu menempelkan dua kata benda seperti “tas Sinta”, menulis -s tanpa apostrof, atau menambah “his/her” sesudah nama.",
             "คุณวางคำนามสองคำติดกันเหมือน 'กระเป๋าสินตา' เขียน -s โดยไม่มีอะพอสทรอฟี หรือเติม 'his/her' หลังชื่อ"),
        rule=("Owner + 's + thing (Sinta's bag). Plural owner ending in s: add only an apostrophe (my parents' car). Plural without s: 's (children's).",
              "Dalam bahasa Inggris, menyatakan kepemilikan orang TIDAK BISA cuma menggabungkan dua kata seperti bahasa Indonesia (salah: <i>Sinta bag</i> ❌ atau <i>Sinta her bag</i> ❌).<br>Kalau pemiliknya orang tunggal: Tambahkan tanda petik dan s (<b>'s</b>) pada nama pemiliknya sebelum barang yang dimiliki. Contoh: <b>Sinta's bag</b> (tas milik Sinta), <b>my father's car</b> (mobil ayahku).<br>Kalau pemiliknya jamak dan sudah berakhiran huruf -s: Cukup tambahkan tanda petik di paling ujung (<b>s'</b>). Contoh: <b>the students' books</b> (buku-buku para murid).<br><br>💡 <b>RUMUS KILAT</b>:<br>Pemilik tunggal ➡️ Beri akhiran <b>'s</b> pada nama pemilik (contoh: <i>Budi's phone</i>).<br>Pemilik jamak berakhiran -s ➡️ Cukup beri tanda petik di ujung kata <b>-s'</b> (contoh: <i>the teachers' room</i>).<br>Pantangan ➡️ Dilarang menempelkan nama langsung (<i>Budi phone</i> ❌) atau mendobelkan kata ganti (<i>Budi his phone</i> ❌).",
              "เจ้าของ + 's + สิ่งของ ('Sinta's bag') ถ้าเจ้าของเป็นพหูพจน์ที่ลงท้ายด้วย s ให้เติมแค่อะพอสทรอฟี ส่วนพหูพจน์ที่ไม่มี s ยังใช้ 's ('children's')"),
        avoid=("Find the owner first. One owner? Add 's. More than one and ending in s? Add only the apostrophe.",
               "Cari pemiliknya dulu. Satu pemilik? Tambah 's. Lebih dari satu dan berakhiran s? Cukup tambah apostrof.",
               "หาเจ้าของก่อน ถ้ามีคนเดียวให้เติม 's ถ้ามีหลายคนและลงท้ายด้วย s ให้เติมแค่อะพอสทรอฟี"),
    ),
    "would_like_polite_requests": dict(
        obj=("Use would like to ask for things politely and Would you like…? to offer.",
             "Pakai “would like” untuk meminta dengan sopan dan “Would you like…?” untuk menawarkan.",
             "ใช้ 'would like' เพื่อขออย่างสุภาพ และใช้ 'Would you like…?' เพื่อเสนอ"),
        mis=("Learner asks about taste with 'Do you like' when offering, or puts -ing or no to after would like.",
             "Kamu menawarkan dengan “Do you like” yang sebenarnya menanyakan selera, atau memakai -ing atau lupa “to” sesudah “would like”.",
             "คุณใช้ 'Do you like' ซึ่งถามเรื่องความชอบเวลาจะเสนอ หรือใช้ -ing หรือลืม 'to' หลัง 'would like'"),
        rule=("Ask politely: I would like + thing, or + to + verb. Offer: Would you like + thing or to + verb? Someone else: would like me to + verb.",
              "Meminta: “I would like” + benda, atau + “to” + kata kerja. Menawarkan: “Would you like…?”. Menyuruh orang lain: “would like me to” + kata kerja.",
              "ขออย่างสุภาพใช้ 'I would like' + สิ่งของ หรือ + 'to' + คำกริยา ถ้าจะเสนอใช้ 'Would you like…?' ถ้าอยากให้คนอื่นทำใช้ 'would like me to' + คำกริยา"),
        avoid=("Ordering or offering? Use would like. If a verb comes next, put to before it.",
               "Lagi memesan atau menawarkan? Pakai “would like”. Kalau sesudahnya kata kerja, taruh “to” di depannya.",
               "ถ้ากำลังสั่งหรือเสนอ ให้ใช้ 'would like' และถ้าตามด้วยคำกริยา ให้ใส่ 'to' ข้างหน้า"),
    ),
    "like_love_hate_plus_gerund_preferences": dict(
        obj=("Use like, love, hate, and enjoy + verb-ing to talk about activities you like or dislike.",
             "Pakai “like”, “love”, “hate”, dan “enjoy” + kata kerja -ing untuk membicarakan kegiatan yang kamu suka atau nggak suka.",
             "ใช้ 'like', 'love', 'hate' และ 'enjoy' + คำกริยาเติม -ing เพื่อพูดถึงกิจกรรมที่ชอบหรือไม่ชอบ"),
        mis=("Learner puts the base verb right after like or enjoy, as in 'suka main', or spells the -ing form wrongly.",
             "Kamu menaruh kata kerja dasar langsung sesudah “like” atau “enjoy”, seperti “suka main”, atau salah mengeja bentuk -ing-nya.",
             "คุณวางคำกริยารูปพื้นฐานต่อจาก 'like' หรือ 'enjoy' ทันที เหมือนพูดว่า 'ชอบเล่น' หรือสะกดรูป -ing ผิด"),
        rule=("Like, love, hate, enjoy + verb-ing (I love swimming). Enjoy always takes -ing. Spelling: swim, swimming; dance, dancing.",
              "“Like”, “love”, “hate”, “enjoy” + kata kerja -ing (“I love swimming”). “Enjoy” selalu diikuti -ing. Ejaan: “swim” jadi “swimming”, “dance” jadi “dancing”.",
              "คำกริยาบอกความรู้สึกอย่าง 'like', 'love', 'hate' และ 'enjoy' ต้องตามด้วยคำกริยาเติม -ing เสมอ และต้องระวังการสะกด เช่น 'swimming' กับ 'dancing'"),
        avoid=("After a feeling verb, give the next verb -ing and check the spelling.",
               "Sesudah kata kerja perasaan, beri kata kerja berikutnya -ing dan periksa ejaannya.",
               "หลังคำกริยาที่บอกความรู้สึก ให้เติม -ing ให้คำกริยาตัวถัดไปและตรวจการสะกด"),
    ),
    "present_simple_vs_continuous": dict(
        obj=("Choose the present simple for habits and the present continuous for things happening now.",
             "Pilih present simple untuk kebiasaan dan present continuous untuk kejadian yang sedang berlangsung.",
             "เลือก present simple สำหรับกิจวัตร และ present continuous สำหรับสิ่งที่กำลังเกิดขึ้นตอนนี้"),
        mis=("Learner picks the verb form without looking at the time words, since 'setiap hari' and 'sekarang' do not change the verb.",
             "Kamu memilih bentuk kata kerja tanpa melihat kata waktunya, karena “setiap hari” dan “sekarang” nggak mengubah kata kerja dalam bahasa Indonesia.",
             "คุณเลือกรูปคำกริยาโดยไม่ดูคำบอกเวลา เพราะคำว่า 'ทุกวัน' กับ 'ตอนนี้' ไม่ได้เปลี่ยนรูปคำกริยาในภาษาไทย"),
        rule=("Habit (every day, usually): present simple. Happening now (now, look!): a be form + -ing.",
              "Bedakan RUTINITAS vs SEDANG BERLANGSUNG:<br>1. Rutinitas / kebiasaan berulang: Pakai Present Simple (Verb 1). Ditandai kata: every day, always, usually.<br>2. Sedang berlangsung saat ini: Pakai Present Continuous (am/is/are + Verb-ing). Ditandai kata: right now, at the moment, Look!, Listen!<br><br>💡 <b>RUMUS KILAT</b>:<br>Sedang terjadi SEKARANG ➡️ Pakai <b>am/is/are + Verb-ing</b> (contoh: <i>is eating right now</i>).<br>Kebiasaan / jadwal rutin ➡️ Pakai <b>Verb 1 (-s/-es)</b> (contoh: <i>eats every day</i>).<br>State verbs (know, like, want, understand) ➡️ Selalu pakai Present Simple, tidak boleh pakai -ing!",
              "ถ้าเป็นกิจวัตรที่ทำเป็นประจำ เช่นมีคำว่า 'every day' ให้ใช้ present simple ถ้ากำลังเกิดขึ้นตอนนี้ เช่นมีคำว่า 'now' ให้ใช้รูป 'be' + -ing"),
        avoid=("Circle the time word first: a habit word or a now word?",
               "Lingkari kata waktunya dulu: kata kebiasaan atau kata “sekarang”?",
               "วงคำบอกเวลาก่อนว่าเป็นคำบอกกิจวัตรหรือคำที่บอกว่าตอนนี้"),
    ),
    "obligation_vs_permission": dict(
        obj=("Choose must or have to for rules, can for permission, mustn't for 'not allowed', and don't have to for 'not necessary'.",
             "Pilih “must”/“have to” untuk aturan, “can” untuk izin, “mustn't” untuk larangan, dan “don't have to” untuk “nggak perlu”.",
             "เลือก 'must' หรือ 'have to' สำหรับกฎ 'can' สำหรับการอนุญาต 'mustn't' สำหรับข้อห้าม และ 'don't have to' สำหรับสิ่งที่ไม่จำเป็น"),
        mis=("Learner mixes up mustn't (not allowed) and don't have to (not necessary), since 'nggak harus' and 'nggak boleh' sound close.",
             "Kamu tertukar antara “mustn't” (dilarang) dan “don't have to” (nggak perlu), karena “nggak harus” dan “nggak boleh” terdengar mirip.",
             "คุณสับสนระหว่าง 'mustn't' ที่แปลว่าห้าม กับ 'don't have to' ที่แปลว่าไม่จำเป็น"),
        rule=("Must, have to = necessary. Can = allowed. Mustn't = not allowed. Don't have to = not necessary, you may choose.",
              "“Must”/“have to” = wajib. “Can” = boleh. “Mustn't” = dilarang. “Don't have to” = nggak wajib, boleh memilih.",
              "'must' หรือ 'have to' แปลว่าต้องทำ 'can' แปลว่าทำได้ 'mustn't' แปลว่าห้ามทำ และ 'don't have to' แปลว่าไม่จำเป็นต้องทำ"),
        avoid=("Ask yourself: is it a rule, a permission, a ban, or a free choice?",
               "Tanya dirimu: ini aturan, izin, larangan, atau pilihan bebas?",
               "ถามตัวเองว่านี่เป็นกฎ การอนุญาต ข้อห้าม หรือทางเลือก"),
    ),
}

# ---- label bersama ----
CMD_S = "adding -s as if the command needed subject-verb agreement with a singular subject"
CMD_ING = "using the -ing form on its own, which describes an activity instead of telling someone to act"
CMD_TO = "using a to-infinitive where a direct command is required"
ADV_AFTER = "moves the adverb between the verb and its object, copying Indonesian word order"
ADV_BEFORE_BE = "puts the frequency adverb before the verb be"
BARE_3SG = "leaving the bare verb with no third-person marking after a singular subject"
IS_BEFORE_VERB = "inserting 'is' before a main verb, blending the 'be' pattern with the present simple"
POSS_NONE = "drops the marker of ownership entirely, lining up two nouns as Indonesian does"
POSS_NOAPOS = "writes a plain -s ending that superficially resembles the possessive but loses the apostrophe"
POSS_DOUBLE = "inserting a duplicate owner pronoun after the name, marking possession twice"
TO_ING = "mixes the to-infinitive and the -ing ending into one broken shape"
FEEL_BARE = "following the feeling verb with a bare infinitive, chaining verbs directly as Indonesian does"
STATEMENT_Q = ("statement order used for a question",
               "susunan kalimat berita dipakai untuk kalimat tanya.",
               "ใช้ลำดับของประโยคบอกเล่ากับคำถาม")
ING_WOULD = ("-ing form used after would like",
             "bentuk -ing dipakai sesudah 'would like'.",
             "ใช้รูป -ing หลังคำขออย่างสุภาพ 'would like'")
S_SECOND = ("-s added to the second verb",
            "akhiran -s ditambahkan ke kata kerja kedua.",
            "เติม -s ให้คำกริยาตัวที่สอง")
PC_SG_PL = ("singular be used in present continuous with a plural subject",
            "bentuk “be” tunggal dipakai untuk banyak orang yang sedang melakukan sesuatu.",
            "ใช้รูป 'be' เอกพจน์กับหลายคนที่กำลังทำอะไรอยู่")
ING_MISSING = ("-ing missing after am, is, or are",
               "akhiran -ing lupa ditambahkan sesudah bentuk “be”.",
               "ลืมเติม -ing หลังรูป 'be'")


def L(name, item_id, item_th):
    """Label lama (sudah ada di bank) dengan teks per-soal."""
    return (name, item_id, item_th)


ITEMS = [
    # ---------------- 18. imperative ----------------
    dict(s="imperative_commands_base_form", id="A2-301",
         stem="It's cold outside. ___ your jacket!", opts=["Put on", "Puts on", "Putting on", "To put on"], ans="Put on",
         why=("This is an instruction to you, so it starts with the base verb, Put on.",
              "Ini perintah untuk kamu, jadi langsung dimulai dengan kata kerja bentuk dasar, yaitu “Put on”.",
              "นี่เป็นคำสั่งถึงคุณ จึงขึ้นต้นด้วยคำกริยารูปพื้นฐาน คือ 'Put on'"),
         others=("'Puts on' adds -s, 'Putting on' only names an activity, and 'To put on' is not a command.",
                 "“Puts on” menambah -s, “Putting on” cuma menyebut kegiatan, dan “To put on” bukan kalimat perintah.",
                 "'Puts on' เติม -s ส่วน 'Putting on' แค่บอกกิจกรรม และ 'To put on' ไม่ใช่ประโยคคำสั่ง"),
         cue=("Commands start with the plain verb: Put on, Sit down, Look.", "Perintah dimulai dengan kata kerja bentuk dasar: “Put on”, “Sit down”, “Look”.", "ประโยคคำสั่งขึ้นต้นด้วยคำกริยาเปล่า ๆ เช่น 'Put on' หรือ 'Sit down'"),
         rsn=("identify the sentence as an instruction -> check that there is no subject -> choose the plain verb",
              "pastikan kalimatnya perintah → cek nggak ada subjeknya → pilih kata kerja bentuk dasar",
              "ดูว่าเป็นประโยคคำสั่ง → ดูว่าไม่มีประธาน → เลือกคำกริยาเปล่า ๆ"),
         d=[("Puts on", L(CMD_S, "akhiran -s ditambahkan ke kata perintah.", "เติม -s ให้คำสั่ง"),
             "It adds -s, but a command has no subject to match.",
             "memakai -s, padahal kalimat perintah nggak punya subjek yang perlu dicocokkan.",
             "เติม -s แต่ประโยคคำสั่งไม่มีประธานให้ต้องเข้าคู่"),
            ("Putting on", L(CMD_ING, "bentuk -ing dipakai untuk memberi perintah.", "ใช้รูป -ing ออกคำสั่ง"),
             "It only names an activity; it does not tell anyone to act.",
             "cuma menyebut kegiatan, bukan menyuruh orang melakukannya.",
             "แค่บอกชื่อกิจกรรม ไม่ได้สั่งให้ใครทำ"),
            ("To put on", L(CMD_TO, "“to” + kata kerja dipakai untuk memberi perintah.", "ใช้ 'to' + คำกริยาออกคำสั่ง"),
             "It starts with to, but a command starts with the verb itself.",
             "memakai “to”, padahal perintah dimulai langsung dari kata kerjanya.",
             "มี 'to' แต่คำสั่งต้องขึ้นต้นด้วยคำกริยาเลย")]),
    dict(s="imperative_commands_base_form", id="A2-302",
         stem="Please ___ quiet in the library.", opts=["be", "are", "to be", "being"], ans="be",
         why=("A command with an adjective like 'quiet' needs the base form of be, so: be quiet.",
              "Perintah dengan kata sifat seperti “quiet” butuh bentuk dasar “be”, jadi “be quiet”.",
              "คำสั่งที่มีคำคุณศัพท์อย่าง 'quiet' ต้องใช้ 'be' รูปพื้นฐาน จึงเป็น 'be quiet'"),
         others=("'Are' needs a subject like you, 'to be' is not a command, and 'being' only names a state.",
                 "“Are” butuh subjek seperti “you”, “to be” bukan kalimat perintah, dan “being” cuma menyebut keadaan.",
                 "'are' ต้องมีประธานอย่าง 'you' ส่วน 'to be' ไม่ใช่ประโยคคำสั่ง และ 'being' แค่บอกสภาพ"),
         cue=("Commands with adjectives use be: Be quiet! Be careful!", "Perintah dengan kata sifat pakai “be”: “Be quiet!”, “Be careful!”", "คำสั่งที่มีคำคุณศัพท์ใช้ 'be' เช่น 'Be quiet!' หรือ 'Be careful!'"),
         rsn=("notice please -> identify quiet as an adjective -> choose the base form that goes with an adjective",
              "perhatikan kata “please” → kenali “quiet” sebagai kata sifat → pilih bentuk dasar yang cocok untuk kata sifat",
              "สังเกตคำว่า 'please' → ดูว่า 'quiet' เป็นคำคุณศัพท์ → เลือกรูปพื้นฐานที่ใช้กับคำคุณศัพท์"),
         d=[("are", ("be form with a subject used in a command", "bentuk “be” yang butuh subjek dipakai di kalimat perintah.", "ใช้รูป 'be' ที่ต้องมีประธานในประโยคคำสั่ง"),
             "It needs a subject like you, but a command has none.",
             "butuh subjek seperti “you”, padahal kalimat perintah nggak punya subjek.",
             "ต้องมีประธานอย่าง 'you' แต่ประโยคคำสั่งไม่มีประธาน"),
            ("to be", L(CMD_TO, "“to” + kata kerja dipakai untuk memberi perintah.", "ใช้ 'to' + คำกริยาออกคำสั่ง"),
             "It starts with to, but a command starts with the verb itself.",
             "memakai “to”, padahal perintah dimulai langsung dari kata kerjanya.",
             "มี 'to' แต่คำสั่งต้องขึ้นต้นด้วยคำกริยาเลย"),
            ("being", L(CMD_ING, "bentuk -ing dipakai untuk memberi perintah.", "ใช้รูป -ing ออกคำสั่ง"),
             "It only names a state; it does not tell anyone what to do.",
             "cuma menyebut keadaan, bukan menyuruh orang melakukan sesuatu.",
             "แค่บอกสภาพ ไม่ได้สั่งให้ใครทำอะไร")]),
    dict(s="imperative_commands_base_form", id="A2-303",
         stem="The soup is very hot. ___ it yet!", opts=["Don't eat", "Not eat", "Doesn't eat", "Don't eating"], ans="Don't eat",
         why=("To tell someone not to do something, we use Don't + the base verb, so: Don't eat.",
              "Untuk melarang, pakai “Don't” + bentuk dasar, jadi “Don't eat”.",
              "ถ้าจะห้าม ให้ใช้ 'Don't' + รูปพื้นฐาน จึงเป็น 'Don't eat'"),
         others=("'Not eat' has no helper word, 'Doesn't eat' is for he, she, or it, and 'Don't eating' adds -ing.",
                 "“Not eat” nggak punya kata bantu, “Doesn't eat” untuk “he”, “she”, atau “it”, dan “Don't eating” menambah -ing.",
                 "'Not eat' ไม่มีกริยาช่วย ส่วน 'Doesn't eat' ใช้กับเขาหรือเธอคนเดียว และ 'Don't eating' เติม -ing เกินมา"),
         cue=("Stop someone? Don't + verb: Don't eat, Don't touch.", "Mau melarang? “Don't” + kata kerja: “Don't eat”, “Don't touch”.", "ถ้าจะห้าม ใช้ 'Don't' + คำกริยา เช่น 'Don't touch'"),
         rsn=("notice the warning very hot -> identify the sentence as a warning -> add don't before the base verb",
              "perhatikan peringatan “very hot” → pastikan kalimatnya larangan → taruh “don't” sebelum kata kerja dasar",
              "สังเกตคำเตือน 'very hot' → ดูว่าเป็นประโยคห้าม → วาง 'don't' ไว้หน้าคำกริยารูปพื้นฐาน"),
         d=[("Not eat", ("not used without do in a negative command", "“not” dipakai tanpa “do” untuk melarang.", "ใช้ 'not' โดยไม่มี 'do' เพื่อห้าม"),
             "It has no helper word; a negative command needs Don't.",
             "nggak punya kata bantu, padahal larangan butuh “Don't”.",
             "ไม่มีกริยาช่วย แต่คำห้ามต้องใช้ 'Don't'"),
            ("Doesn't eat", L(CMD_S, "“doesn't” dipakai di kalimat larangan.", "ใช้ 'doesn't' ในประโยคห้าม"),
             "It is for he, she, or it, but a command has no subject.",
             "untuk “he”, “she”, atau “it”, padahal kalimat perintah nggak punya subjek.",
             "ใช้กับ 'he', 'she', 'it' แต่ประโยคคำสั่งไม่มีประธาน"),
            ("Don't eating", ("-ing form used after don't in a command", "bentuk -ing dipakai sesudah “don't” di kalimat larangan.", "ใช้รูป -ing หลัง 'don't' ในประโยคห้าม"),
             "It adds -ing, but after Don't the verb stays in its base form.",
             "memakai -ing, padahal sesudah “Don't” kata kerjanya tetap bentuk dasar.",
             "เติม -ing แต่หลัง 'Don't' คำกริยาต้องเป็นรูปพื้นฐาน")]),
    dict(s="imperative_commands_base_form", id="A2-304",
         stem="I'm hungry. Let's ___ to the canteen together!", opts=["go", "goes", "going", "to go"], ans="go",
         why=("After Let's, the verb stays in its base form, so: go.",
              "Sesudah “Let's”, kata kerjanya tetap bentuk dasar, jadi “go”.",
              "หลัง 'Let's' คำกริยาต้องเป็นรูปพื้นฐาน จึงใช้ 'go'"),
         others=("'Goes' adds -s, 'going' adds -ing, and 'to go' adds to; after Let's, none of them fit.",
                 "“Goes” menambah -s, “going” menambah -ing, dan “to go” menambah “to”. Sesudah “Let's”, semuanya nggak cocok.",
                 "'goes' เติม -s 'going' เติม -ing และ 'to go' เติม 'to' หลัง 'Let's' จึงใช้ไม่ได้ทั้งหมด"),
         cue=("Let's + plain verb: Let's go, Let's eat.", "“Let's” + kata kerja bentuk dasar: “Let's go”, “Let's eat”.", "หลัง 'Let's' ใช้คำกริยาเปล่า ๆ เช่น 'Let's eat'"),
         rsn=("notice let's before the blank -> recall that let's takes the base verb -> choose the verb with no ending",
              "lihat “Let's” sebelum titik-titik → ingat “Let's” butuh bentuk dasar → pilih kata kerja tanpa tambahan",
              "เห็น 'Let's' หน้าช่องว่าง → นึกว่า 'Let's' ตามด้วยรูปพื้นฐาน → เลือกคำกริยาที่ไม่เติมอะไร"),
         d=[("goes", ("-s added to the verb after let's", "akhiran -s ditambahkan ke kata kerja sesudah “let's”.", "เติม -s ให้คำกริยาหลัง 'let's'"),
             "It adds -s, but after Let's the verb stays in its base form.",
             "memakai -s, padahal sesudah “Let's” kata kerjanya tetap bentuk dasar.",
             "เติม -s แต่หลัง 'Let's' คำกริยาต้องเป็นรูปพื้นฐาน"),
            ("going", ("-ing form used after let's", "bentuk -ing dipakai sesudah “let's”.", "ใช้รูป -ing หลัง 'let's'"),
             "It adds -ing, but after Let's the verb stays in its base form.",
             "memakai -ing, padahal sesudah “Let's” kata kerjanya tetap bentuk dasar.",
             "เติม -ing แต่หลัง 'Let's' คำกริยาต้องเป็นรูปพื้นฐาน"),
            ("to go", ("to added after let's", "kata “to” ditambahkan sesudah “let's”.", "เติม 'to' หลัง 'let's'"),
             "It adds to, but Let's is followed directly by the verb.",
             "memakai “to”, padahal “Let's” langsung diikuti kata kerja.",
             "มี 'to' แต่หลัง 'Let's' ต้องตามด้วยคำกริยาทันที")]),
    # ---------------- 19. frequency adverbs ----------------
    dict(s="adverbs_of_frequency_mid_position", id="A2-305",
         stem="I ___ my teeth before bed.", opts=["always brush", "brush always", "always brushes", "am always brush"], ans="always brush",
         why=("'Always' goes before the main verb, and 'I' takes the base form, so: always brush.",
              "“Always” ditaruh sebelum kata kerja utama, dan subjek “I” pakai bentuk dasar. Hasilnya “always brush”.",
              "'always' อยู่หน้าคำกริยาหลัก และ 'I' ใช้รูปพื้นฐาน จึงได้เป็น 'always brush'"),
         others=("'Brush always' puts always after the verb, 'always brushes' adds -s for I, and 'am always brush' adds an extra am.",
                 "“Brush always” menaruh “always” sesudah kata kerja, “always brushes” menambah -s untuk “I”, dan “am always brush” menambah “am” yang nggak perlu.",
                 "'brush always' วาง 'always' ไว้หลังคำกริยา ส่วน 'always brushes' เติม -s ให้ 'I' และ 'am always brush' เติม 'am' ที่ไม่จำเป็น"),
         cue=("Always before the action: I always brush, I never eat.", "“Always” sebelum aksinya: “I always brush”, “I never eat”.", "'always' ต้องอยู่หน้าการกระทำ เช่น 'I always brush'"),
         rsn=("find the main verb brush -> place always before it -> keep the base form for I",
              "cari kata kerja utamanya, “brush” → taruh “always” di depannya → pakai bentuk dasar untuk “I”",
              "หาคำกริยาหลัก 'brush' → วาง 'always' ไว้ข้างหน้า → ใช้รูปพื้นฐานกับ 'I'"),
         d=[("brush always", L(ADV_AFTER, "kata frekuensi ditaruh sesudah kata kerja.", "วางคำบอกความถี่ไว้หลังคำกริยา"),
             "It puts always after the verb, but it belongs before it.",
             "menaruh “always” sesudah kata kerja, padahal tempatnya sebelum kata kerja.",
             "วาง 'always' ไว้หลังคำกริยา แต่ต้องอยู่หน้าคำกริยา"),
            ("always brushes", ("-s added to the verb after I", "akhiran -s ditambahkan ke kata kerja untuk subjek “I”.", "เติม -s ให้คำกริยาของ 'I'"),
             "It adds -s, but 'I' never takes -s.",
             "memakai -s, padahal subjek “I” nggak pernah pakai -s.",
             "เติม -s แต่ 'I' ไม่เคยเติม -s"),
            ("am always brush", ("am inserted before a main verb", "“am” diselipkan di depan kata kerja utama.", "แทรก 'am' ไว้หน้าคำกริยาหลัก"),
             "It adds am, but brush is already the main verb.",
             "menambah “am”, padahal “brush” sudah jadi kata kerja utamanya.",
             "เติม 'am' แต่ 'brush' เป็นคำกริยาหลักอยู่แล้ว")]),
    dict(s="adverbs_of_frequency_mid_position", id="A2-306",
         stem="My little sister ___ scared of the dark.", opts=["is often", "often is", "often", "often be"], ans="is often",
         why=("'Scared' needs the verb be, and the frequency word comes after be, so: is often.",
              "“Scared” butuh “be”, dan kata frekuensi ditaruh sesudah “be”, jadi “is often”.",
              "'scared' ต้องใช้ 'be' และคำบอกความถี่อยู่หลัง 'be' จึงเป็น 'is often'"),
         others=("'Often is' puts often before be, 'often' has no be at all, and 'often be' uses the base form.",
                 "“Often is” menaruh “often” sebelum “be”, “often” sama sekali nggak punya “be”, dan “often be” memakai bentuk dasar.",
                 "'often is' วาง 'often' ไว้หน้า 'be' ส่วน 'often' ไม่มี 'be' เลย และ 'often be' ใช้รูปพื้นฐาน"),
         cue=("With be, the frequency word comes after: is often, are never.", "Dengan “be”, kata frekuensi di belakangnya: “is often”, “are never”.", "ถ้ามี 'be' คำบอกความถี่จะอยู่ข้างหลัง เช่น 'is often'"),
         rsn=("notice the adjective scared -> recall that it needs be -> place often after be",
              "perhatikan kata sifat “scared” → ingat kata sifat butuh “be” → taruh “often” sesudah “be”",
              "สังเกตคำคุณศัพท์ 'scared' → นึกว่าต้องใช้ 'be' → วาง 'often' ไว้หลัง 'be'"),
         d=[("often is", L(ADV_BEFORE_BE, "kata frekuensi ditaruh sebelum “be”.", "วางคำบอกความถี่ไว้หน้า 'be'"),
             "It puts often before be, but with be it comes after.",
             "menaruh “often” sebelum “be”, padahal dengan “be” tempatnya sesudahnya.",
             "วาง 'often' ไว้หน้า 'be' แต่ถ้ามี 'be' ต้องวางไว้ข้างหลัง"),
            ("often", L("missing-be-auxiliary", "“be” dihilangkan sebelum kata sifat “scared”.", "ตัด 'be' ที่ต้องอยู่หน้าคำคุณศัพท์ 'scared' ออก"),
             "It has no be, but scared is an adjective and needs one.",
             "nggak punya “be”, padahal “scared” kata sifat dan butuh “be”.",
             "ไม่มี 'be' แต่ 'scared' เป็นคำคุณศัพท์และต้องมี 'be'"),
            ("often be", L("base form", "bentuk dasar “be” dipakai untuk “my little sister”.", "ใช้ 'be' รูปพื้นฐานกับ 'my little sister'"),
             "It uses the base form be, but my little sister needs is.",
             "memakai bentuk dasar “be”, padahal “my little sister” butuh “is”.",
             "ใช้ 'be' รูปพื้นฐาน แต่ 'my little sister' ต้องใช้ 'is'")]),
    dict(s="adverbs_of_frequency_mid_position", id="A2-307",
         stem="Budi ___ his homework on time. The teacher is angry.", opts=["never does", "does never", "never do", "is never do"], ans="never does",
         why=("'Never' goes before the main verb, and Budi needs the -s form, so: never does.",
              "“Never” ditaruh sebelum kata kerja utama, dan Budi butuh bentuk -s. Hasilnya “never does”.",
              "'never' อยู่หน้าคำกริยาหลัก และ 'Budi' ต้องใช้รูปเติม -s จึงเป็น 'never does'"),
         others=("'Does never' puts never after the verb, 'never do' forgets -s, and 'is never do' adds an extra is.",
                 "“Does never” menaruh “never” sesudah kata kerja, “never do” lupa -s, dan “is never do” menambah “is” yang nggak perlu.",
                 "'does never' วาง 'never' ไว้หลังคำกริยา ส่วน 'never do' ลืมเติม -s และ 'is never do' เติม 'is' ที่ไม่จำเป็น"),
         cue=("Never before the action: he never does, she never eats.", "“Never” sebelum aksinya: “he never does”, “she never eats”.", "'never' ต้องอยู่หน้าการกระทำ เช่น 'he never does'"),
         rsn=("find the main verb -> place never before it -> add -s for Budi",
              "cari kata kerja utamanya → taruh “never” di depannya → tambah -s untuk Budi",
              "หาคำกริยาหลัก → วาง 'never' ไว้ข้างหน้า → เติม -s ให้ 'Budi'"),
         d=[("does never", L(ADV_AFTER, "kata frekuensi ditaruh sesudah kata kerja.", "วางคำบอกความถี่ไว้หลังคำกริยา"),
             "It puts never after the verb, but it belongs before it.",
             "menaruh “never” sesudah kata kerja, padahal tempatnya sebelum kata kerja.",
             "วาง 'never' ไว้หลังคำกริยา แต่ต้องอยู่หน้าคำกริยา"),
            ("never do", L(BARE_3SG, "bentuk dasar dipakai untuk Budi.", "ใช้รูปพื้นฐานกับ 'Budi'"),
             "It forgets -s, but Budi is he.",
             "lupa -s, padahal Budi sama dengan “he”.",
             "ลืมเติม -s แต่ 'Budi' คือ 'he'"),
            ("is never do", L(IS_BEFORE_VERB, "“is” diselipkan di depan kata kerja utama.", "แทรก 'is' ไว้หน้าคำกริยาหลัก"),
             "It adds is, but do is already the main verb.",
             "menambah “is”, padahal “do” sudah jadi kata kerja utamanya.",
             "เติม 'is' แต่ 'do' เป็นคำกริยาหลักอยู่แล้ว")]),
    dict(s="adverbs_of_frequency_mid_position", id="A2-308",
         stem="“___ ride your bike to school?” “Yes, almost every day.”", opts=["Do you usually", "Usually do you", "Do usually you", "You usually do"], ans="Do you usually",
         why=("In a question the order is Do + subject + frequency word + verb, so: Do you usually ride.",
              "Di kalimat tanya urutannya “Do” + subjek + kata frekuensi + kata kerja, jadi “Do you usually ride”.",
              "ในคำถามลำดับคือ 'Do' + ประธาน + คำบอกความถี่ + คำกริยา จึงเป็น 'Do you usually ride'"),
         others=("The other orders put usually in front, put it before the subject, or keep statement order.",
                 "Susunan lain menaruh “usually” di depan, menaruhnya sebelum subjek, atau memakai susunan kalimat berita.",
                 "ลำดับอื่นวาง 'usually' ไว้ข้างหน้า วางไว้หน้าประธาน หรือใช้ลำดับประโยคบอกเล่า"),
         cue=("Question: Do you usually…? Does she often…?", "Kalimat tanya: “Do you usually…?”, “Does she often…?”", "ในคำถามให้วางคำบอกความถี่ไว้หลังประธาน เช่น 'Do you usually…?'"),
         rsn=("notice the question mark -> place do before the subject -> place usually after the subject",
              "perhatikan tanda tanya → taruh “Do” sebelum subjek → taruh “usually” sesudah subjek",
              "สังเกตเครื่องหมายคำถาม → วาง 'Do' ไว้หน้าประธาน → วาง 'usually' ไว้หลังประธาน"),
         d=[("Usually do you", ("frequency word moved to the front of a question", "kata frekuensi dipindah ke awal kalimat tanya.", "ย้ายคำบอกความถี่ไปไว้ต้นคำถาม"),
             "It moves usually to the front, but in a question it comes after the subject.",
             "memindah “usually” ke depan, padahal di kalimat tanya tempatnya sesudah subjek.",
             "ย้าย 'usually' ไปข้างหน้า แต่ในคำถามต้องอยู่หลังประธาน"),
            ("Do usually you", ("frequency word placed before the subject in a question", "kata frekuensi ditaruh sebelum subjek di kalimat tanya.", "วางคำบอกความถี่ไว้หน้าประธานในคำถาม"),
             "It puts usually before you, but it goes after the subject.",
             "menaruh “usually” sebelum “you”, padahal tempatnya sesudah subjek.",
             "วาง 'usually' ไว้หน้า 'you' แต่ต้องอยู่หลังประธาน"),
            ("You usually do", STATEMENT_Q,
             "It keeps statement order, so it does not sound like a question.",
             "memakai susunan kalimat berita, jadi nggak terdengar seperti pertanyaan.",
             "ใช้ลำดับของประโยคบอกเล่า จึงฟังไม่เป็นคำถาม")]),
    # ---------------- 20. possessive 's ----------------
    dict(s="possessive_s_noun_ownership", id="A2-309",
         stem="The ___ bowl is empty. Can you feed it?", opts=["cat's", "cat", "cats", "cat its"], ans="cat's",
         why=("The bowl belongs to the cat, one owner, so we add 's to cat.",
              "Mangkuknya milik si kucing, satu pemilik, jadi “cat” ditambah 's.",
              "ชามเป็นของแมวตัวเดียว จึงเติม 's ให้ 'cat'"),
         others=("'Cat' has no owner marker, 'cats' looks like a plural, and 'cat its' marks the owner twice.",
                 "“Cat” nggak punya tanda pemilik, “cats” terbaca seperti bentuk jamak, dan “cat its” menandai pemilik dua kali.",
                 "'cat' ไม่มีเครื่องหมายเจ้าของ 'cats' อ่านเหมือนพหูพจน์ และ 'cat its' บอกเจ้าของซ้ำสองครั้ง"),
         cue=("Owner + 's + thing: the cat's bowl.", "Pemilik + 's + barang: “the cat's bowl”.", "เจ้าของ + 's + สิ่งของ เช่น 'the cat's bowl'"),
         rsn=("identify the owner -> count one owner -> add 's to the owner",
              "cari pemiliknya → hitung pemiliknya satu → tambah 's pada pemiliknya",
              "หาเจ้าของ → นับว่ามีเจ้าของตัวเดียว → เติม 's ให้เจ้าของ"),
         d=[("cat", L(POSS_NONE, "tanda pemilik hilang, dua kata benda ditempel begitu saja.", "ไม่มีเครื่องหมายเจ้าของ วางคำนามสองคำติดกันเฉย ๆ"),
             "It has no owner marker, so it reads like two nouns stuck together.",
             "nggak punya tanda pemilik, jadi terbaca seperti dua kata benda yang ditempel.",
             "ไม่มีเครื่องหมายเจ้าของ จึงอ่านเหมือนคำนามสองคำวางติดกัน"),
            ("cats", L(POSS_NOAPOS, "akhiran -s ditulis tanpa apostrof.", "เขียน -s โดยไม่มีอะพอสทรอฟี"),
             "Without an apostrophe it looks like 'many cats', not the owner.",
             "tanpa apostrof terbaca seperti “banyak kucing”, bukan pemiliknya.",
             "ไม่มีอะพอสทรอฟี จึงอ่านเหมือนแมวหลายตัว ไม่ใช่เจ้าของ"),
            ("cat its", L(POSS_DOUBLE, "kata pemilik ditambahkan sesudah kata bendanya.", "เติมคำบอกความเป็นเจ้าของหลังคำนาม"),
             "It marks the owner twice; 's alone is enough.",
             "menandai pemilik dua kali, padahal 's saja sudah cukup.",
             "บอกเจ้าของซ้ำสองครั้ง ทั้งที่ใช้แค่ 's ก็พอ")]),
    dict(s="possessive_s_noun_ownership", id="A2-310",
         stem="My two ___ room is next to mine.", opts=["brothers'", "brother's", "brother", "brothers's"], ans="brothers'",
         why=("'Two brothers' is plural and already ends in s, so we add only an apostrophe after the s.",
              "“Two brothers” jamak dan sudah berakhiran s, jadi cukup tambah apostrof sesudah huruf s.",
              "'two brothers' เป็นพหูพจน์ที่ลงท้ายด้วย s แล้ว จึงเติมแค่อะพอสทรอฟีหลัง s"),
         others=("'Brother's' is for one brother, 'brother' has no plural or owner marker, and 'brothers's' adds an extra s.",
                 "“Brother's” untuk satu saudara, “brother” nggak punya tanda jamak maupun tanda pemilik, dan “brothers's” menambah s yang berlebihan.",
                 "“brother's” ใช้กับพี่หรือน้องคนเดียว ส่วน “brother” ไม่มีทั้งเครื่องหมายพหูพจน์และเจ้าของ และ “brothers's” เติม s เกินมา"),
         cue=("Many owners ending in s: just add the apostrophe.", "Pemilik jamak berakhiran s cukup ditambah apostrof.", "เจ้าของหลายคนที่ลงท้ายด้วย s ให้เติมแค่อะพอสทรอฟี"),
         rsn=("count the owners -> check the s ending -> add only an apostrophe",
              "hitung pemiliknya → cek akhiran s → tambah apostrof saja",
              "นับจำนวนเจ้าของ → ดูตัว s ท้ายคำ → เติมแค่อะพอสทรอฟี"),
         d=[("brother's", ("singular owner form used for plural owners", "bentuk pemilik untuk satu orang dipakai untuk pemilik yang banyak.", "ใช้รูปเจ้าของคนเดียวกับเจ้าของหลายคน"),
             "It is for one brother, but there are two.",
             "untuk satu saudara, padahal jumlahnya dua.",
             "ใช้กับพี่หรือน้องคนเดียว แต่มีสองคน"),
            ("brother", L(POSS_NONE, "tanda jamak dan tanda pemilik sama-sama hilang.", "ไม่มีทั้งเครื่องหมายพหูพจน์และเครื่องหมายเจ้าของ"),
             "It has no plural -s and no apostrophe, so it doesn't show two owners.",
             "nggak punya -s jamak dan apostrof, jadi nggak menunjukkan dua pemilik.",
             "ไม่มีทั้ง -s พหูพจน์และอะพอสทรอฟี จึงไม่ได้บอกว่าเป็นของสองคน"),
            ("brothers's", ("'s added to a plural that already ends in s", "akhiran 's ditambahkan ke bentuk jamak yang sudah berakhiran s.", "เติม 's ให้คำพหูพจน์ที่ลงท้ายด้วย s อยู่แล้ว"),
             "It adds another s; after a plural s, the apostrophe alone is enough.",
             "menambah s lagi, padahal sesudah s jamak cukup apostrof saja.",
             "เติม s ซ้ำ ทั้งที่หลัง s ของพหูพจน์ใช้แค่อะพอสทรอฟีก็พอ")]),
    dict(s="possessive_s_noun_ownership", id="A2-311",
         stem="The ___ toys are all over the floor!", opts=["children's", "childrens'", "children", "childs'"], ans="children's",
         why=("'Children' is already plural but does not end in s, so we still add 's.",
              "“Children” sudah jamak tapi nggak berakhiran s, jadi tetap ditambah 's.",
              "'children' เป็นพหูพจน์อยู่แล้วแต่ไม่ได้ลงท้ายด้วย s จึงยังต้องเติม 's"),
         others=("'Childrens'' adds a wrong s, 'children' has no owner marker, and 'childs'' is not a word.",
                 "“Childrens'” menambah s yang salah, “children” nggak punya tanda pemilik, dan “childs'” bukan kata.",
                 "“childrens'” เติม s ผิด “children” ไม่มีเครื่องหมายเจ้าของ และ “childs'” ไม่ใช่คำ"),
         cue=("Plural without s? Still add 's: children's, men's.", "Jamak tanpa akhiran s tetap ditambah 's: “children's”, “men's”.", "พหูพจน์ที่ไม่ได้ลงท้ายด้วย s ยังต้องเติม 's เช่น 'men's'"),
         rsn=("identify the owners as children -> check that the word does not end in s -> add 's",
              "kenali pemiliknya, yaitu anak-anak → cek katanya nggak berakhiran s → tambah 's",
              "ดูว่าเจ้าของคือเด็ก ๆ → ดูว่าคำนี้ไม่ได้ลงท้ายด้วย s → เติม 's"),
         d=[("childrens'", ("s added to a plural that does not take s", "huruf s ditambahkan ke bentuk jamak yang nggak memakai s.", "เติม s ให้คำพหูพจน์ที่ไม่ใช้ s"),
             "It adds an s that 'children' never takes.",
             "menambah s, padahal “children” nggak pernah memakai s.",
             "เติม s ทั้งที่ 'children' ไม่เคยเติม s"),
            ("children", L(POSS_NONE, "tanda pemilik hilang.", "ไม่มีเครื่องหมายเจ้าของ"),
             "It has no owner marker, so we cannot tell whose toys they are.",
             "nggak punya tanda pemilik, jadi mainannya nggak jelas milik siapa.",
             "ไม่มีเครื่องหมายเจ้าของ จึงไม่รู้ว่าของเล่นเป็นของใคร"),
            ("childs'", ("regular plural rule used for an irregular plural", "aturan jamak biasa dipakai untuk kata yang jamaknya khusus.", "ใช้กฎพหูพจน์ทั่วไปกับคำที่มีรูปพหูพจน์พิเศษ"),
             "It is not a real word; the plural of child is children.",
             "bukan kata yang benar, karena jamak dari “child” adalah “children”.",
             "ไม่มีคำนี้ในภาษาอังกฤษ เพราะพหูพจน์ของ 'child' คือ 'children'")]),
    dict(s="possessive_s_noun_ownership", id="A2-312",
         stem="“Whose bag is this?” “It's ___.”", opts=["Maya's", "Maya", "Mayas", "of Maya"], ans="Maya's",
         why=("The answer names the owner, Maya, so we add 's to her name, even with no noun after it.",
              "Jawabannya menyebut pemiliknya, Maya, jadi namanya ditambah 's walaupun nggak ada kata benda sesudahnya.",
              "คำตอบบอกชื่อเจ้าของคือมายา จึงเติม 's ให้ชื่อ แม้ไม่มีคำนามตามหลัง"),
         others=("'Maya' has no owner marker, 'Mayas' has no apostrophe, and 'of Maya' is not how English shows a person's things.",
                 "“Maya” nggak punya tanda pemilik, “Mayas” nggak punya apostrof, dan “of Maya” bukan cara bahasa Inggris menyebut barang milik orang.",
                 "'Maya' ไม่มีเครื่องหมายเจ้าของ 'Mayas' ไม่มีอะพอสทรอฟี และ 'of Maya' ไม่ใช่วิธีบอกของของคนในภาษาอังกฤษ"),
         cue=("It's Maya's = it belongs to Maya.", "“It's Maya's” = barang itu milik Maya.", "'It's Maya's' แปลว่าเป็นของมายา"),
         rsn=("check the question word whose -> identify the owner Maya -> add 's to the name",
              "lihat kata tanya “Whose” → temukan pemiliknya, Maya → tambah 's pada namanya",
              "ดูคำถาม 'Whose' → หาเจ้าของซึ่งก็คือมายา → เติม 's ให้ชื่อ"),
         d=[("Maya", ("owner named without any ownership marker", "nama pemilik disebut tanpa tanda kepemilikan.", "บอกชื่อเจ้าของโดยไม่มีเครื่องหมายความเป็นเจ้าของ"),
             "It just names the person; it does not say the bag is hers.",
             "cuma menyebut orangnya, bukan menyatakan tas itu miliknya.",
             "บอกแค่ชื่อคน ไม่ได้บอกว่ากระเป๋าเป็นของเธอ"),
            ("Mayas", L(POSS_NOAPOS, "akhiran -s ditulis tanpa apostrof.", "เขียน -s โดยไม่มีอะพอสทรอฟี"),
             "Without the apostrophe it is not an owner form.",
             "tanpa apostrof, jadi belum jadi bentuk pemilik.",
             "ไม่มีอะพอสทรอฟี จึงยังไม่ใช่รูปแสดงความเป็นเจ้าของ"),
            ("of Maya", ("of + name used for a person's belongings", "pola “of” + nama dipakai untuk barang milik seseorang.", "ใช้ 'of' + ชื่อคนเพื่อบอกของที่เป็นของคนนั้น"),
             "It copies 'punya Maya'; English uses 's for a person's things.",
             "meniru “punya Maya”, padahal bahasa Inggris memakai 's untuk barang milik orang.",
             "แปลตรงจาก 'ของมายา' แต่ภาษาอังกฤษใช้ 's กับของของคน")]),
    # ---------------- 21. would like ----------------
    dict(s="would_like_polite_requests", id="A2-313",
         stem="I would like ___ a table for four, please.", opts=["to book", "book", "booking", "to booking"], ans="to book",
         why=("After would like, another verb needs to, so: would like to book.",
              "Sesudah “would like”, kata kerja berikutnya butuh “to”, jadi “would like to book”.",
              "หลัง 'would like' คำกริยาตัวต่อไปต้องมี 'to' จึงเป็น 'would like to book'"),
         others=("'Book' has no to, 'booking' adds -ing, and 'to booking' mixes to with -ing.",
                 "“Book” nggak pakai “to”, “booking” menambah -ing, dan “to booking” mencampur “to” dengan -ing.",
                 "คำว่า 'book' ขาด 'to' ส่วน 'booking' เติม -ing และ 'to booking' เอา 'to' กับ -ing มาผสมกันซึ่งผิด"),
         cue=("Would like + to + verb: I'd like to book, I'd like to go.", "“Would like” + “to” + kata kerja: “I'd like to book”.", "เวลาขออย่างสุภาพแล้วตามด้วยคำกริยา ให้ใส่ 'to' เสมอ เช่น 'I'd like to go'"),
         rsn=("notice would like before the blank -> check that a verb follows -> add to before the base verb",
              "lihat “would like” sebelum titik-titik → cek bahwa sesudahnya kata kerja → tambah “to” sebelum bentuk dasar",
              "เห็น 'would like' หน้าช่องว่าง → ดูว่าตามด้วยคำกริยา → เติม 'to' หน้ารูปพื้นฐาน"),
         d=[("book", ("to dropped after would like", "kata “to” hilang sesudah 'would like'.", "ลืมใส่ 'to' หลังคำขออย่างสุภาพ 'would like'"),
             "It has no to, but a verb after would like needs to.",
             "nggak memakai “to”, padahal kata kerja sesudah “would like” butuh “to”.",
             "ไม่มี 'to' แต่คำกริยาหลัง 'would like' ต้องมี 'to'"),
            ("booking", ING_WOULD,
             "It adds -ing, but would like takes to + the base verb.",
             "memakai -ing, padahal “would like” diikuti “to” + bentuk dasar.",
             "เติม -ing แต่ 'would like' ต้องตามด้วย 'to' + รูปพื้นฐาน"),
            ("to booking", L(TO_ING, "“to” dicampur dengan -ing.", "ผสม 'to' กับ -ing"),
             "It mixes to with -ing; after to, the verb stays in its base form.",
             "mencampur “to” dengan -ing, padahal sesudah “to” kata kerjanya tetap bentuk dasar.",
             "ผสม 'to' กับ -ing แต่หลัง 'to' คำกริยาต้องเป็นรูปพื้นฐาน")]),
    dict(s="would_like_polite_requests", id="A2-314",
         stem="___ you like some cake? I made it myself!", opts=["Would", "Do", "Are", "Will"], ans="Would",
         why=("It is an offer, and polite offers use Would you like…?",
              "Ini tawaran, dan tawaran sopan memakai “Would you like…?”",
              "นี่เป็นการเสนอ และการเสนออย่างสุภาพใช้ 'Would you like…?'"),
         others=("'Do you like' asks about taste in general, 'Are' cannot go with like, and 'Will' is not used for offers like this.",
                 "“Do you like” menanyakan selera secara umum, “Are” nggak bisa dipasangkan dengan “like”, dan “Will” nggak dipakai untuk tawaran seperti ini.",
                 "'Do you like' ถามเรื่องความชอบทั่วไป ส่วน 'Are' ใช้คู่กับ 'like' ไม่ได้ และ 'Will' ไม่ใช้กับการเสนอแบบนี้"),
         cue=("Offering something? Would you like…?", "Mau menawarkan sesuatu? “Would you like…?”", "ถ้าจะเสนออะไรให้ ใช้ 'Would you like…?'"),
         rsn=("notice I made it myself -> identify the question as an offer -> choose the word for a polite offer",
              "perhatikan “I made it myself” → pastikan pertanyaannya tawaran → pilih kata untuk tawaran sopan",
              "สังเกต 'I made it myself' → ดูว่าเป็นการเสนอ → เลือกคำที่ใช้เสนออย่างสุภาพ"),
         d=[("Do", L("stating a general preference in casual flat form instead of the polite request formula", "“do you like” dipakai untuk menawarkan.", "ใช้ 'do you like' เพื่อเสนอ"),
             "It asks what you like in general, not whether you want cake now.",
             "menanyakan selera secara umum, bukan menawarkan kue sekarang.",
             "ถามเรื่องความชอบทั่วไป ไม่ได้เสนอเค้กให้ตอนนี้"),
            ("Are", ("be used with like in an offer", "bentuk “be” dipasangkan dengan “like” untuk menawarkan.", "ใช้ 'be' คู่กับ 'like' เพื่อเสนอ"),
             "It is a be word, and be words cannot go with like.",
             "termasuk bentuk “be”, padahal bentuk “be” nggak bisa dipasangkan dengan “like”.",
             "เป็นรูป 'be' ซึ่งใช้คู่กับ 'like' ไม่ได้"),
            ("Will", ("will used for a polite offer", "“will” dipakai untuk tawaran sopan.", "ใช้ 'will' เพื่อเสนออย่างสุภาพ"),
             "It talks about the future, but polite offers use a different word.",
             "membicarakan masa depan, padahal tawaran sopan memakai kata lain.",
             "พูดถึงอนาคต แต่การเสนออย่างสุภาพใช้อีกคำหนึ่ง")]),
    dict(s="would_like_polite_requests", id="A2-315",
         stem="My mum would like me ___ my room today.", opts=["to clean", "clean", "cleaning", "cleaned"], ans="to clean",
         why=("The pattern is would like + person + to + verb, so: would like me to clean.",
              "Polanya “would like” + orang + “to” + kata kerja, jadi “would like me to clean”.",
              "ถ้าอยากให้คนอื่นทำอะไร รูปแบบคือ 'would like' + คน + 'to' + คำกริยา จึงเป็น 'me to clean'"),
         others=("'Clean' has no to, 'cleaning' adds -ing, and 'cleaned' is a past form.",
                 "“Clean” nggak pakai “to”, “cleaning” menambah -ing, dan “cleaned” bentuk lampau.",
                 "'clean' ไม่มี 'to' ส่วน 'cleaning' เติม -ing และ 'cleaned' เป็นรูปอดีต"),
         cue=("Want someone to act? would like + me or you + to + verb.", "Mau orang lain melakukan sesuatu? “would like” + “me/you” + “to” + kata kerja.", "ถ้าอยากให้คนอื่นทำอะไร ใช้ 'would like' + 'me/you' + 'to' + คำกริยา"),
         rsn=("notice the person me after would like -> recall that the next verb needs to -> add to before the base verb",
              "perhatikan “me” sesudah “would like” → ingat kata kerja berikutnya butuh “to” → tambah “to” sebelum bentuk dasar",
              "สังเกต 'me' หลัง 'would like' → นึกว่าคำกริยาตัวต่อไปต้องมี 'to' → เติม 'to' หน้ารูปพื้นฐาน"),
         d=[("clean", ("to dropped after would like + person", "kata “to” hilang sesudah 'would like' + orang.", "ลืมใส่ 'to' หลัง 'would like' และคนที่ถูกขอให้ทำ"),
             "It has no to, but after would like me the verb needs to.",
             "nggak memakai “to”, padahal sesudah “would like me” kata kerjanya butuh “to”.",
             "ไม่มี 'to' แต่หลัง 'would like me' คำกริยาต้องมี 'to'"),
            ("cleaning", ING_WOULD,
             "It adds -ing, but this pattern takes to + the base verb.",
             "memakai -ing, padahal pola ini diikuti “to” + bentuk dasar.",
             "เติม -ing แต่รูปแบบนี้ต้องตามด้วย 'to' + รูปพื้นฐาน"),
            ("cleaned", ("past form used after would like", "bentuk lampau dipakai sesudah 'would like'.", "ใช้รูปอดีตหลังคำขออย่างสุภาพ 'would like'"),
             "It is a past form, but Mum wants the room cleaned today.",
             "bentuk lampau, padahal ibu ingin kamarnya dibersihkan hari ini.",
             "เป็นรูปอดีต แต่แม่อยากให้ทำความสะอาดห้องวันนี้")]),
    dict(s="would_like_polite_requests", id="A2-316",
         stem="What ___ for your birthday?", opts=["would you like", "you would like", "do you would like", "would you liking"], ans="would you like",
         why=("In a question with what, would comes before the subject, so: What would you like.",
              "Di pertanyaan dengan “what”, “would” ditaruh sebelum subjek, jadi “What would you like”.",
              "ในคำถามที่มี 'what' คำว่า 'would' ต้องอยู่หน้าประธาน จึงเป็น 'What would you like'"),
         others=("'You would like' keeps statement order, 'do you would like' adds an extra do, and 'would you liking' adds -ing.",
                 "“You would like” memakai susunan kalimat berita, “do you would like” menambah “do” yang nggak perlu, dan “would you liking” menambah -ing.",
                 "'you would like' ใช้ลำดับประโยคบอกเล่า ส่วนอีกสองตัวเลือกเติม 'do' เกินมา หรือเติม -ing หลัง 'would'"),
         cue=("What would you like? = Kamu mau apa?", "“What would you like?” = “Kamu mau apa?”", "'What would you like?' แปลว่าอยากได้อะไร"),
         rsn=("notice the question word what -> place would before you -> keep like in its base form",
              "perhatikan kata tanya “What” → taruh “would” sebelum “you” → pakai “like” dalam bentuk dasar",
              "สังเกตคำถาม 'What' → วาง 'would' ไว้หน้า 'you' → ใช้ 'like' รูปพื้นฐาน"),
         d=[("you would like", STATEMENT_Q,
             "It keeps statement order, so it is not a question yet.",
             "memakai susunan kalimat berita, jadi belum jadi pertanyaan.",
             "ใช้ลำดับของประโยคบอกเล่า จึงยังไม่เป็นคำถาม"),
            ("do you would like", ("do added to a question that already has would", "'do' ditambahkan ke pertanyaan yang sudah punya 'would'.", "เติม 'do' ในคำถามที่มี 'would' อยู่แล้ว"),
             "It adds do, but would already makes the question.",
             "menambah “do”, padahal “would” sudah membentuk pertanyaannya.",
             "เติม 'do' แต่ 'would' ทำให้เป็นคำถามอยู่แล้ว"),
            ("would you liking", L("gluing an -ing onto the verb after 'would', a blend of two separate patterns", "-ing ditempel pada kata kerja sesudah “would”.", "เติม -ing ให้คำกริยาหลัง 'would'"),
             "It adds -ing, but after would the verb stays in its base form.",
             "memakai -ing, padahal sesudah “would” kata kerjanya tetap bentuk dasar.",
             "เติม -ing แต่หลัง 'would' คำกริยาต้องเป็นรูปพื้นฐาน")]),
    # ---------------- 22. like/love/hate + -ing ----------------
    dict(s="like_love_hate_plus_gerund_preferences", id="A2-317",
         stem="Nadia loves ___ in the sea.", opts=["swimming", "swim", "swiming", "to swimming"], ans="swimming",
         why=("After loves we use -ing, and swim doubles its m. Hasilnya swimming.".replace(" Hasilnya", " The result is"),
              "Sesudah “loves” pakai -ing, dan “swim” menggandakan huruf m. Hasilnya “swimming”.",
              "หลัง 'loves' ใช้ -ing และ 'swim' ต้องเพิ่ม m อีกตัว จึงเป็น 'swimming'"),
         others=("'Swim' has no -ing, 'swiming' forgets the second m, and 'to swimming' mixes to with -ing.",
                 "“Swim” belum diberi -ing, “swiming” lupa huruf m kedua, dan “to swimming” mencampur “to” dengan -ing.",
                 "'swim' ยังไม่เติม -ing ส่วน 'swiming' ขาด m ตัวที่สอง และ 'to swimming' ผสม 'to' กับ -ing"),
         cue=("Short verb with one vowel + one consonant: double it. swim, swimming; run, running.", "Kata pendek berakhiran satu vokal + satu konsonan: gandakan hurufnya. “Swim” jadi “swimming”, “run” jadi “running”.", "คำสั้นที่ลงท้ายด้วยสระหนึ่งตัวและพยัญชนะหนึ่งตัว ให้เพิ่มพยัญชนะก่อนเติม -ing เช่น 'running'"),
         rsn=("notice loves before the blank -> add -ing to the verb -> add one more m before -ing",
              "lihat “loves” sebelum titik-titik → tambah -ing pada kata kerjanya → tambahkan satu huruf m lagi sebelum -ing",
              "เห็น 'loves' หน้าช่องว่าง → เติม -ing ให้คำกริยา → เพิ่ม m อีกหนึ่งตัวก่อน -ing"),
         d=[("swim", L(FEEL_BARE, "kata kerja dasar langsung ditaruh sesudah “loves”.", "วางคำกริยารูปพื้นฐานต่อจาก 'loves' ทันที"),
             "It has no -ing, but after loves the verb needs it.",
             "belum diberi -ing, padahal sesudah “loves” kata kerjanya butuh -ing.",
             "ยังไม่เติม -ing แต่หลัง 'loves' คำกริยาต้องเติม -ing"),
            ("swiming", ("consonant not doubled before -ing", "huruf mati terakhir nggak digandakan sebelum -ing.", "ไม่เพิ่มพยัญชนะตัวท้ายก่อนเติม -ing"),
             "It forgets to double the m before -ing.",
             "lupa menggandakan huruf m sebelum -ing.",
             "ลืมเพิ่ม m อีกตัวก่อนเติม -ing"),
            ("to swimming", L(TO_ING, "“to” dicampur dengan -ing.", "ผสม 'to' กับ -ing"),
             "It mixes to with -ing in one form.",
             "mencampur “to” dengan -ing dalam satu bentuk.",
             "ผสม 'to' กับ -ing ไว้ในรูปเดียว")]),
    dict(s="like_love_hate_plus_gerund_preferences", id="A2-318",
         stem="My dad hates ___ in traffic jams.", opts=["waiting", "wait", "waits", "is waiting"], ans="waiting",
         why=("After hates we use the -ing form, so: hates waiting.",
              "Sesudah “hates” pakai bentuk -ing, jadi “hates waiting”.",
              "หลังคำว่า 'hates' ต้องใช้คำกริยาเติม -ing จึงเป็น 'waiting'"),
         others=("'Wait' and 'waits' have no -ing, and 'is waiting' adds a second main verb.",
                 "“Wait” dan “waits” belum diberi -ing, dan “is waiting” menambah kata kerja utama kedua.",
                 "'wait' และ 'waits' ยังไม่เติม -ing ส่วน 'is waiting' เพิ่มกริยาหลักตัวที่สองเข้ามา"),
         cue=("Hate + -ing: hate waiting, hate cleaning.", "“Hate” + -ing: “hate waiting”, “hate cleaning”.", "หลังคำว่า 'hate' ต้องเติม -ing ให้คำกริยาเสมอ"),
         rsn=("notice hates before the blank -> recall that feeling verbs take -ing -> add -ing to wait",
              "lihat “hates” sebelum titik-titik → ingat kata kerja perasaan diikuti -ing → tambah -ing pada “wait”",
              "เห็น 'hates' หน้าช่องว่าง → นึกว่ากริยาความรู้สึกตามด้วย -ing → เติม -ing ให้ 'wait'"),
         d=[("wait", L(FEEL_BARE, "kata kerja dasar langsung ditaruh sesudah “hates”.", "วางคำกริยารูปพื้นฐานต่อจาก 'hates' ทันที"),
             "It has no -ing, but after hates the verb needs it.",
             "belum diberi -ing, padahal sesudah “hates” kata kerjanya butuh -ing.",
             "ยังไม่เติม -ing แต่หลัง 'hates' คำกริยาต้องเติม -ing"),
            ("waits", S_SECOND,
             "It adds -s, but hates already has the -s and the second verb needs -ing.",
             "memakai -s, padahal -s sudah ada di “hates” dan kata kerja kedua butuh -ing.",
             "เติม -s แต่ 'hates' มี -s แล้ว และคำกริยาตัวที่สองต้องเติม -ing"),
            ("is waiting", ("second main verb added after a feeling verb", "kata kerja utama kedua ditambahkan sesudah kata kerja perasaan.", "เพิ่มกริยาหลักตัวที่สองหลังกริยาความรู้สึก"),
             "It adds is, making two main verbs in one sentence.",
             "menambah “is”, jadi ada dua kata kerja utama dalam satu kalimat.",
             "เติม 'is' ทำให้มีกริยาหลักสองตัวในประโยคเดียว")]),
    dict(s="like_love_hate_plus_gerund_preferences", id="A2-319",
         stem="My little sister loves ___ to K-pop songs.", opts=["dancing", "danceing", "dance", "to dancing"], ans="dancing",
         why=("After loves we use -ing, and dance drops its e before -ing.",
              "Sesudah “loves” pakai -ing, dan huruf e di akhir “dance” dibuang sebelum -ing.",
              "หลัง 'loves' ใช้ -ing และต้องตัด e ท้าย 'dance' ก่อนเติม -ing"),
         others=("'Danceing' keeps the e, 'dance' has no -ing, and 'to dancing' mixes to with -ing.",
                 "“Danceing” masih menyimpan huruf e, “dance” belum diberi -ing, dan “to dancing” mencampur “to” dengan -ing.",
                 "'danceing' ยังคง e ไว้ ส่วน 'dance' ยังไม่เติม -ing และ 'to dancing' ผสม 'to' กับ -ing"),
         cue=("The final e goes before -ing: dance, dancing; make, making.", "Huruf e di akhir dibuang sebelum -ing: “dance” jadi “dancing”, “make” jadi “making”.", "ตัด e ท้ายคำก่อนเติม -ing เช่น 'making'"),
         rsn=("notice loves before the blank -> add -ing to the verb -> remove the final e",
              "lihat “loves” sebelum titik-titik → tambah -ing pada kata kerjanya → buang huruf e di akhir",
              "เห็น 'loves' หน้าช่องว่าง → เติม -ing ให้คำกริยา → ตัด e ท้ายคำ"),
         d=[("danceing", ("final e kept before -ing", "huruf e di akhir kata dipertahankan sebelum -ing.", "ไม่ตัด e ท้ายคำก่อนเติม -ing"),
             "It keeps the e, but the e drops before -ing.",
             "masih menyimpan huruf e, padahal huruf e dibuang sebelum -ing.",
             "ยังคง e ไว้ แต่ต้องตัด e ก่อนเติม -ing"),
            ("dance", L(FEEL_BARE, "kata kerja dasar langsung ditaruh sesudah “loves”.", "วางคำกริยารูปพื้นฐานต่อจาก 'loves' ทันที"),
             "It has no -ing, but after loves the verb needs it.",
             "belum diberi -ing, padahal sesudah “loves” kata kerjanya butuh -ing.",
             "ยังไม่เติม -ing แต่หลัง 'loves' คำกริยาต้องเติม -ing"),
            ("to dancing", L(TO_ING, "“to” dicampur dengan -ing.", "ผสม 'to' กับ -ing"),
             "It mixes to with -ing in one form.",
             "mencampur “to” dengan -ing dalam satu bentuk.",
             "ผสม 'to' กับ -ing ไว้ในรูปเดียว")]),
    dict(s="like_love_hate_plus_gerund_preferences", id="A2-320",
         stem="Rafi doesn't enjoy ___ homework on Sundays.", opts=["doing", "do", "to do", "does"], ans="doing",
         why=("Enjoy always takes -ing, also in negative sentences, so: doesn't enjoy doing.",
              "“Enjoy” selalu diikuti -ing, termasuk di kalimat negatif, jadi “doesn't enjoy doing”.",
              "'enjoy' ตามด้วย -ing เสมอ แม้ในประโยคปฏิเสธ จึงเป็น 'doesn't enjoy doing'"),
         others=("'Do' has no -ing, 'to do' uses to after enjoy, and 'does' adds -s to the second verb.",
                 "“Do” belum diberi -ing, “to do” memakai “to” sesudah “enjoy”, dan “does” menambah -s pada kata kerja kedua.",
                 "'do' ยังไม่เติม -ing ส่วน 'to do' ใช้ 'to' หลัง 'enjoy' และ 'does' เติม -s ให้คำกริยาตัวที่สอง"),
         cue=("Enjoy + -ing, always: enjoy doing, enjoy playing.", "“Enjoy” selalu + -ing: “enjoy doing”, “enjoy playing”.", "'enjoy' ต้องตามด้วยคำกริยาเติม -ing เสมอ ไม่มีข้อยกเว้น"),
         rsn=("notice enjoy before the blank -> recall that enjoy always takes -ing -> add -ing to do",
              "lihat “enjoy” sebelum titik-titik → ingat “enjoy” selalu diikuti -ing → tambah -ing pada “do”",
              "เห็น 'enjoy' หน้าช่องว่าง → นึกว่า 'enjoy' ตามด้วย -ing เสมอ → เติม -ing ให้ 'do'"),
         d=[("do", L(FEEL_BARE, "kata kerja dasar langsung ditaruh sesudah “enjoy”.", "วางคำกริยารูปพื้นฐานต่อจาก 'enjoy' ทันที"),
             "It has no -ing, but after enjoy the verb needs it.",
             "belum diberi -ing, padahal sesudah “enjoy” kata kerjanya butuh -ing.",
             "ยังไม่เติม -ing แต่หลัง 'enjoy' คำกริยาต้องเติม -ing"),
            ("to do", L("uses a to-infinitive after 'enjoy'", "“to” dipakai sesudah “enjoy”.", "ใช้ 'to' หลัง 'enjoy'"),
             "It uses to, but enjoy is never followed by to.",
             "memakai “to”, padahal “enjoy” nggak pernah diikuti “to”.",
             "ใช้ 'to' แต่ 'enjoy' ไม่เคยตามด้วย 'to'"),
            ("does", S_SECOND,
             "It adds -s, but the second verb needs -ing, not -s.",
             "memakai -s, padahal kata kerja kedua butuh -ing, bukan -s.",
             "เติม -s แต่คำกริยาตัวที่สองต้องเติม -ing ไม่ใช่ -s")]),
    # ---------------- 23. present simple vs continuous ----------------
    dict(s="present_simple_vs_continuous", id="A2-321",
         stem="Dina usually ___ to school, but today she is taking the bus.", opts=["walks", "is walking", "walk", "walked"], ans="walks",
         why=("'Usually' shows a habit, and Dina is she, so: walks.",
              "“Usually” menunjukkan kebiasaan, dan Dina sama dengan “she”, jadi “walks”.",
              "'usually' บอกว่าเป็นกิจวัตร และ 'Dina' คือ 'she' จึงใช้ 'walks'"),
         others=("'Is walking' is for now, 'walk' forgets -s, and 'walked' is past.",
                 "“Is walking” untuk kejadian sekarang, “walk” lupa -s, dan “walked” bentuk lampau.",
                 "'is walking' ใช้กับตอนนี้ ส่วน 'walk' ลืมเติม -s และ 'walked' เป็นรูปอดีต"),
         cue=("Usually = habit = walks. Today = now = is taking.", "“Usually” = kebiasaan = “walks”. “Today” = sekarang = “is taking”.", "'usually' คือกิจวัตรจึงใช้ 'walks' ส่วน 'today' คือตอนนี้จึงใช้ 'is taking'"),
         rsn=("find the time word usually -> identify it as a habit -> choose the habit form for she",
              "cari kata waktunya, “usually” → pastikan itu kebiasaan → pilih bentuk kebiasaan untuk “she”",
              "หาคำบอกเวลา 'usually' → ดูว่าเป็นกิจวัตร → เลือกรูปกิจวัตรของ 'she'"),
         d=[("is walking", ("progressive form used for a habit", "bentuk yang sedang berlangsung dipakai untuk kebiasaan.", "ใช้รูปกำลังทำกับสิ่งที่ทำเป็นประจำ"),
             "It is for now, but usually shows a habit.",
             "untuk kejadian sekarang, padahal “usually” menunjukkan kebiasaan.",
             "ใช้กับตอนนี้ แต่ 'usually' บอกว่าเป็นกิจวัตร"),
            ("walk", L("missing subject-verb agreement / bare form", "bentuk dasar dipakai untuk Dina.", "ใช้รูปพื้นฐานกับ 'Dina'"),
             "It forgets -s, but Dina is she.",
             "lupa -s, padahal Dina sama dengan “she”.",
             "ลืมเติม -s แต่ 'Dina' คือ 'she'"),
            ("walked", L("past tense used for a timeless fact", "bentuk lampau dipakai untuk kebiasaan sekarang.", "ใช้รูปอดีตกับกิจวัตรปัจจุบัน"),
             "It is past, but usually talks about her habit now.",
             "bentuk lampau, padahal “usually” membicarakan kebiasaannya sekarang.",
             "เป็นรูปอดีต แต่ 'usually' พูดถึงกิจวัตรในปัจจุบัน")]),
    dict(s="present_simple_vs_continuous", id="A2-322",
         stem="Be quiet! The students ___ an exam at the moment.", opts=["are taking", "take", "is taking", "takes"], ans="are taking",
         why=("'At the moment' means now, and 'the students' are many, so: are taking.",
              "“At the moment” artinya sekarang, dan muridnya banyak, jadi pakai “are taking”.",
              "'at the moment' แปลว่าตอนนี้ และนักเรียนมีหลายคน จึงใช้ 'are taking'"),
         others=("'Take' and 'takes' are for habits, and 'is taking' is for one person.",
                 "“Take” dan “takes” untuk kebiasaan, dan “is taking” untuk satu orang.",
                 "'take' และ 'takes' ใช้กับกิจวัตร ส่วน 'is taking' ใช้กับคนเดียว"),
         cue=("At the moment = right now = be + -ing.", "“At the moment” = sekarang = “be” + -ing.", "'at the moment' แปลว่าตอนนี้ จึงต้องใช้รูป 'be' + -ing"),
         rsn=("find the time words at the moment -> count the students -> combine the plural be form with -ing",
              "cari kata waktunya, “at the moment” → hitung murid-muridnya → gabungkan bentuk “be” jamak dengan -ing",
              "หาคำบอกเวลา 'at the moment' → นับจำนวนนักเรียน → รวมรูป 'be' พหูพจน์กับ -ing"),
         d=[("take", L("habitual-aspect overgeneralization", "bentuk kebiasaan dipakai untuk kejadian sekarang.", "ใช้รูปกิจวัตรกับสิ่งที่กำลังเกิดขึ้น"),
             "It is for habits, but at the moment means now.",
             "untuk kebiasaan, padahal “at the moment” artinya sekarang.",
             "ใช้กับกิจวัตร แต่ 'at the moment' แปลว่าตอนนี้"),
            ("is taking", PC_SG_PL,
             "Its be word is for one person, but the students are many.",
             "bentuk “be”-nya untuk satu orang, padahal murid-muridnya banyak.",
             "รูป 'be' ที่ใช้เป็นของคนเดียว แต่มีนักเรียนหลายคน"),
            ("takes", ("singular habit form used for a plural action now", "bentuk kebiasaan untuk satu orang dipakai untuk banyak orang yang sedang beraksi.", "ใช้รูปกิจวัตรของคนเดียวกับหลายคนที่กำลังทำอยู่"),
             "It is a habit form for one person, but many students are doing it now.",
             "bentuk kebiasaan untuk satu orang, padahal banyak murid sedang mengerjakannya sekarang.",
             "เป็นรูปกิจวัตรของคนเดียว แต่นักเรียนหลายคนกำลังทำอยู่ตอนนี้")]),
    dict(s="present_simple_vs_continuous", id="A2-323",
         stem="My mum ___ coffee. She only drinks tea.", opts=["doesn't drink", "isn't drinking", "don't drink", "not drinks"], ans="doesn't drink",
         why=("'She only drinks tea' is a general habit, so the negative is doesn't drink.",
              "“She only drinks tea” adalah kebiasaan umum, jadi bentuk negatifnya “doesn't drink”.",
              "'She only drinks tea' เป็นกิจวัตรทั่วไป รูปปฏิเสธจึงเป็น 'doesn't drink'"),
         others=("'Isn't drinking' is only about now, 'don't drink' is for I, you, we, and they, and 'not drinks' has no helper word.",
                 "“Isn't drinking” cuma soal saat ini, “don't drink” untuk “I”, “you”, “we”, dan “they”, dan “not drinks” nggak punya kata bantu.",
                 "'isn't drinking' พูดถึงแค่ตอนนี้ ส่วน 'don't drink' ใช้กับ 'I', 'you', 'we', 'they' และ 'not drinks' ไม่มีกริยาช่วย"),
         cue=("A habit, not just now: she doesn't drink.", "Kebiasaan, bukan cuma saat ini: “she doesn't drink”.", "ถ้าเป็นกิจวัตร ไม่ใช่แค่ตอนนี้ ให้ใช้ 'she doesn't drink'"),
         rsn=("check the second sentence -> identify it as a habit -> choose the habit negative for she",
              "lihat kalimat kedua → pastikan itu kebiasaan → pilih bentuk negatif kebiasaan untuk “she”",
              "ดูประโยคที่สอง → ดูว่าเป็นกิจวัตร → เลือกรูปปฏิเสธแบบกิจวัตรของ 'she'"),
         d=[("isn't drinking", ("progressive negative used for a general habit", "bentuk negatif yang sedang berlangsung dipakai untuk kebiasaan umum.", "ใช้รูปปฏิเสธแบบกำลังทำกับกิจวัตรทั่วไป"),
             "It is only about this moment, but the sentence is about her habit.",
             "cuma soal saat ini, padahal kalimatnya membicarakan kebiasaannya.",
             "พูดถึงแค่ตอนนี้ แต่ประโยคนี้พูดถึงกิจวัตรของเธอ"),
            ("don't drink", ("don't used with he, she, or it", "“don't” dipakai untuk “he”, “she”, atau “it”.", "ใช้ 'don't' กับประธานที่เป็นเขาหรือเธอคนเดียว"),
             "It is for I, you, we, and they, but my mum is she.",
             "untuk “I”, “you”, “we”, dan “they”, padahal “my mum” sama dengan “she”.",
             "ใช้กับหลายคนหรือกับ 'I' และ 'you' แต่แม่ของฉันเป็นคนเดียว"),
            ("not drinks", ("not used without a helper verb in a negative", "“not” dipakai tanpa kata bantu di kalimat negatif.", "ใช้ 'not' โดยไม่มีกริยาช่วยในประโยคปฏิเสธ"),
             "It has no helper word; this negative needs doesn't.",
             "nggak punya kata bantu, padahal kalimat negatif ini butuh “doesn't”.",
             "ไม่มีกริยาช่วย แต่ประโยคปฏิเสธนี้ต้องใช้ 'doesn't'")]),
    dict(s="present_simple_vs_continuous", id="A2-324",
         stem="Why ___ an umbrella? It isn't raining.", opts=["are you carrying", "you are carrying", "are you carry", "do you carrying"], ans="are you carrying",
         why=("It is happening now, so the question uses are + you + -ing, which gives are you carrying.",
              "Kejadiannya sekarang, jadi kalimat tanyanya “are” + “you” + -ing, yaitu “are you carrying”.",
              "เป็นสิ่งที่เกิดขึ้นตอนนี้ คำถามจึงใช้ 'are' + 'you' + -ing คือ 'are you carrying'"),
         others=("'You are carrying' keeps statement order, 'are you carry' forgets -ing, and 'do you carrying' mixes do with -ing.",
                 "“You are carrying” memakai susunan kalimat berita, “are you carry” lupa -ing, dan “do you carrying” mencampur “do” dengan -ing.",
                 "'you are carrying' ใช้ลำดับประโยคบอกเล่า ส่วนอีกสองตัวเลือกลืมเติม -ing หรือเอา 'do' มาผสมกับ -ing"),
         cue=("A question about now: Why are you + -ing?", "Tanya soal sekarang: “Why are you” + -ing?", "ถ้าถามเรื่องตอนนี้ ให้ใช้ 'Why are you' + -ing"),
         rsn=("notice it isn't raining -> identify the action as happening now -> place are before you and add -ing",
              "perhatikan “It isn't raining” → pastikan kejadiannya sekarang → taruh “are” sebelum “you” dan tambah -ing",
              "สังเกต 'It isn't raining' → ดูว่าเกิดขึ้นตอนนี้ → วาง 'are' ไว้หน้า 'you' และเติม -ing"),
         d=[("you are carrying", STATEMENT_Q,
             "It keeps statement order, so it is not a question.",
             "memakai susunan kalimat berita, jadi belum jadi pertanyaan.",
             "ใช้ลำดับของประโยคบอกเล่า จึงยังไม่เป็นคำถาม"),
            ("are you carry", ING_MISSING,
             "It forgets -ing after are.",
             "lupa -ing, padahal sesudah “are” kata kerjanya butuh -ing.",
             "ลืมเติม -ing ทั้งที่หลัง 'are' ต้องเติม -ing"),
            ("do you carrying", ("do mixed with an -ing verb", "kata bantu “do” dicampur dengan kata kerja -ing.", "ผสม 'do' กับคำกริยาเติม -ing"),
             "It mixes do with -ing; an -ing verb needs a be word.",
             "mencampur “do” dengan -ing, padahal kata kerja -ing butuh bentuk “be”.",
             "ผสม 'do' กับ -ing แต่คำกริยา -ing ต้องใช้รูป 'be'")]),
    # ---------------- 24. must / have to / can ----------------
    dict(s="obligation_vs_permission", id="A2-325",
         stem="You ___ use your phone during the test. It's against the rules.", opts=["mustn't", "don't have to", "must", "can"], ans="mustn't",
         why=("'Against the rules' means it is not allowed, so we use mustn't.",
              "“Against the rules” artinya dilarang, jadi pakai “mustn't”.",
              "'against the rules' แปลว่าผิดกฎ จึงเป็นสิ่งที่ห้ามทำ และต้องใช้ 'mustn't'"),
         others=("'Don't have to' means it is not necessary, 'must' means you have to use it, and 'can' gives permission.",
                 "“Don't have to” artinya nggak perlu, “must” artinya wajib memakainya, dan “can” memberi izin.",
                 "'don't have to' แปลว่าไม่จำเป็น ส่วน 'must' แปลว่าต้องใช้ และ 'can' แปลว่าอนุญาต"),
         cue=("Against the rules = mustn't = dilarang.", "Melanggar aturan = “mustn't” = dilarang.", "ผิดกฎใช้ 'mustn't' ซึ่งแปลว่าห้าม"),
         rsn=("notice against the rules -> identify it as a ban -> choose the word for not allowed",
              "perhatikan “against the rules” → pastikan itu larangan → pilih kata untuk “dilarang”",
              "สังเกต 'against the rules' → ดูว่าเป็นข้อห้าม → เลือกคำที่แปลว่าห้าม"),
         d=[("don't have to", ("don't have to used for a ban", "“don't have to” (nggak perlu) dipakai untuk larangan.", "ใช้ 'don't have to' ที่แปลว่าไม่จำเป็นกับข้อห้าม"),
             "It means 'not necessary', so it sounds like a free choice, not a ban.",
             "artinya “nggak perlu”, jadi terdengar seperti pilihan bebas, bukan larangan.",
             "แปลว่าไม่จำเป็น จึงฟังเหมือนเป็นทางเลือก ไม่ใช่ข้อห้าม"),
            ("must", ("must used where the rule forbids the action", "“must” (wajib) dipakai untuk hal yang justru dilarang.", "ใช้ 'must' ที่แปลว่าต้องทำ กับสิ่งที่ถูกห้าม"),
             "It means you have to use your phone, the opposite of the rule.",
             "artinya wajib memakai ponsel, kebalikan dari aturannya.",
             "แปลว่าต้องใช้โทรศัพท์ ซึ่งตรงข้ามกับกฎ"),
            ("can", ("can used for something the rules forbid", "“can” (boleh) dipakai untuk hal yang dilarang aturan.", "ใช้ 'can' ที่แปลว่าทำได้ กับสิ่งที่กฎห้าม"),
             "It gives permission, but the rules say no.",
             "memberi izin, padahal aturannya melarang.",
             "เป็นการอนุญาต แต่กฎห้ามไว้")]),
    dict(s="obligation_vs_permission", id="A2-326",
         stem="Tomorrow is a holiday, so we ___ go to school.", opts=["don't have to", "mustn't", "have to", "can't"], ans="don't have to",
         why=("A holiday means going to school is not necessary, so we use don't have to.",
              "Hari libur artinya nggak perlu ke sekolah, jadi pakai “don't have to”.",
              "วันหยุดแปลว่าไม่จำเป็นต้องไปโรงเรียน จึงใช้ 'don't have to'"),
         others=("'Mustn't' means it is not allowed, 'have to' means it is necessary, and 'can't' means we are not able or allowed.",
                 "“Mustn't” artinya dilarang, “have to” artinya wajib, dan “can't” artinya nggak bisa atau nggak boleh.",
                 "'mustn't' แปลว่าห้าม ส่วน 'have to' แปลว่าต้อง และ 'can't' แปลว่าทำไม่ได้หรือไม่ได้รับอนุญาต"),
         cue=("No need = don't have to. Not allowed = mustn't.", "Nggak perlu = “don't have to”. Dilarang = “mustn't”.", "ไม่จำเป็นใช้ 'don't have to' ส่วนห้ามใช้ 'mustn't'"),
         rsn=("notice a holiday -> decide if going is banned or just not necessary -> choose the words for not necessary",
              "perhatikan “a holiday” → putuskan ke sekolah itu dilarang atau cuma nggak perlu → pilih kata untuk “nggak perlu”",
              "สังเกต 'a holiday' → ตัดสินว่าห้ามไปหรือแค่ไม่จำเป็น → เลือกคำที่แปลว่าไม่จำเป็น"),
         d=[("mustn't", L("treats 'mustn't' as the negation of obligation rather than prohibition", "“mustn't” dibaca sebagai “nggak perlu”.", "อ่าน 'mustn't' ว่าไม่จำเป็น"),
             "It means going to school is not allowed, which is too strong for a holiday.",
             "artinya dilarang ke sekolah, padahal libur cuma berarti nggak perlu.",
             "แปลว่าห้ามไปโรงเรียน แต่วันหยุดแค่ไม่จำเป็นต้องไป"),
            ("have to", ("have to used when there is no need", "“have to” (wajib) dipakai saat nggak ada keharusan.", "ใช้ 'have to' ที่แปลว่าต้อง ทั้งที่ไม่มีความจำเป็น"),
             "It means we must go, but it is a holiday.",
             "artinya wajib pergi, padahal besok libur.",
             "แปลว่าต้องไป แต่พรุ่งนี้เป็นวันหยุด"),
            ("can't", L("confuses lack of requirement with lack of permission/ability", "“can't” dipakai untuk hal yang cuma nggak perlu.", "ใช้ 'can't' กับสิ่งที่แค่ไม่จำเป็น"),
             "It means we are not able or not allowed, but nobody forbids it.",
             "artinya nggak bisa atau nggak boleh, padahal nggak ada yang melarang.",
             "แปลว่าทำไม่ได้หรือไม่ได้รับอนุญาต แต่ไม่มีใครห้าม")]),
    dict(s="obligation_vs_permission", id="A2-327",
         stem="“___ I borrow your pen?” “Sure, here you are.”", opts=["Can", "Must", "Have", "Do"], ans="Can",
         why=("Asking for permission uses Can I…?, and the answer 'Sure' gives it.",
              "Minta izin memakai “Can I…?”, dan jawaban “Sure” memberi izin itu.",
              "การขออนุญาตใช้ 'Can I…?' และคำตอบ 'Sure' คือการอนุญาต"),
         others=("'Must' asks if it is necessary, and 'Have' and 'Do' cannot ask for permission like this.",
                 "“Must” menanyakan apakah wajib, sedangkan “Have” dan “Do” nggak bisa dipakai untuk minta izin seperti ini.",
                 "'must' ถามว่าจำเป็นไหม ส่วน 'have' และ 'do' ใช้ขออนุญาตแบบนี้ไม่ได้"),
         cue=("Asking permission: Can I…? May I…?", "Minta izin: “Can I…?” atau “May I…?”", "ขออนุญาตใช้ 'Can I…?' หรือ 'May I…?'"),
         rsn=("check the answer sure -> identify the question as asking permission -> choose the word for asking permission",
              "lihat jawaban “Sure” → pastikan pertanyaannya minta izin → pilih kata untuk minta izin",
              "ดูคำตอบ 'Sure' → ดูว่าเป็นการขออนุญาต → เลือกคำที่ใช้ขออนุญาต"),
         d=[("Must", ("must used to ask for permission", "“must” (wajib) dipakai untuk minta izin.", "ใช้ 'must' ที่แปลว่าต้อง เพื่อขออนุญาต"),
             "It asks whether you are required to, not whether you are allowed.",
             "menanyakan apakah kamu wajib, bukan apakah kamu boleh.",
             "ถามว่าต้องทำไหม ไม่ได้ถามว่าทำได้ไหม"),
            ("Have", ("have used without to in a question", "“have” dipakai tanpa “to” di kalimat tanya.", "ใช้ 'have' โดยไม่มี 'to' ในคำถาม"),
             "It would need to and would mean 'must', so it cannot ask for permission.",
             "butuh “to” dan artinya “wajib”, jadi nggak bisa dipakai untuk minta izin.",
             "ต้องมี 'to' และแปลว่าต้องทำ จึงใช้ขออนุญาตไม่ได้"),
            ("Do", ("do used to ask for permission", "“do” dipakai untuk minta izin.", "ใช้ 'do' เพื่อขออนุญาต"),
             "It asks about a habit, not for permission.",
             "menanyakan kebiasaan, bukan minta izin.",
             "ถามเรื่องกิจวัตร ไม่ได้ขออนุญาต")]),
    dict(s="obligation_vs_permission", id="A2-328",
         stem="In Indonesia, drivers ___ drive on the left. It's the law.", opts=["have to", "don't have to", "can", "mustn't"], ans="have to",
         why=("'It's the law' means it is necessary, so drivers have to drive on the left.",
              "“It's the law” artinya wajib, jadi pengemudi “have to” menyetir di kiri.",
              "'It's the law' แปลว่าต้องทำ คนขับจึง 'have to' ขับชิดซ้าย"),
         others=("'Don't have to' makes it a free choice, 'can' only gives permission, and 'mustn't' bans it.",
                 "“Don't have to” membuatnya jadi pilihan bebas, “can” cuma memberi izin, dan “mustn't” justru melarangnya.",
                 "'don't have to' ทำให้กลายเป็นทางเลือก ส่วน 'can' แค่อนุญาต และ 'mustn't' กลับเป็นการห้าม"),
         cue=("The law says so = have to or must.", "Diatur hukum = “have to” atau “must”.", "ถ้ากฎหมายกำหนดไว้ ให้ใช้ 'have to' หรือ 'must'"),
         rsn=("notice it's the law -> identify it as a rule -> choose the words for necessary",
              "perhatikan “It's the law” → pastikan itu aturan → pilih kata untuk “wajib”",
              "สังเกต 'It's the law' → ดูว่าเป็นกฎ → เลือกคำที่แปลว่าต้องทำ"),
         d=[("don't have to", ("don't have to used for a law", "“don't have to” (nggak perlu) dipakai untuk hal yang diwajibkan hukum.", "ใช้ 'don't have to' กับสิ่งที่กฎหมายบังคับ"),
             "It makes driving on the left a free choice, but it is the law.",
             "membuat menyetir di kiri jadi pilihan bebas, padahal itu hukum.",
             "ทำให้การขับชิดซ้ายเป็นทางเลือก แต่นี่เป็นกฎหมาย"),
            ("can", L("obligation read as ability/permission", "“can” dipakai untuk kewajiban.", "ใช้ 'can' กับสิ่งที่ต้องทำ"),
             "It only says drivers are allowed to, but the law requires it.",
             "cuma bilang pengemudi boleh, padahal hukum mewajibkannya.",
             "บอกแค่ว่าทำได้ แต่กฎหมายบังคับให้ทำ"),
            ("mustn't", ("mustn't used for something that is required", "“mustn't” (dilarang) dipakai untuk hal yang wajib.", "ใช้ 'mustn't' ที่แปลว่าห้ามกับสิ่งที่ต้องทำ"),
             "It bans driving on the left, the opposite of the law.",
             "melarang menyetir di kiri, kebalikan dari hukumnya.",
             "ห้ามขับชิดซ้าย ซึ่งตรงข้ามกับกฎหมาย")]),
]
