# A2 lesson 32-38: soal latihan baru (m025-376). Format: lihat ../README.md.
LESSONS = {
    "article_omission_with_uncountable": dict(
        obj=("Use no a or an with uncountable nouns like advice, bread, and information, and count them with some or a piece of.",
             "Jangan pakai “a/an” untuk benda yang nggak bisa dihitung seperti “advice”, “bread”, dan “information”; pakai “some” atau “a piece of”.",
             "ไม่ใช้ 'a/an' กับคำนามนับไม่ได้อย่าง 'advice', 'bread' และ 'information' แต่ใช้ 'some' หรือ 'a piece of'"),
        mis=("Learner puts a or an before an uncountable noun or adds -s, treating it like an ordinary noun.",
             "Kamu menaruh “a/an” atau menambah -s pada benda yang nggak bisa dihitung, karena dalam bahasa Indonesia “sebuah nasihat” atau “dua roti” biasa saja.",
             "คุณใส่ 'a/an' หรือเติม -s ให้คำนามนับไม่ได้ เหมือนกับคำนามทั่วไป"),
        rule=("Uncountable nouns (advice, bread, information) take no a or an and no -s. Use some or a piece of, and a singular verb.",
              "Benda yang nggak bisa dihitung (“advice”, “bread”, “information”) nggak pakai “a/an” dan nggak diberi -s. Pakai “some” atau “a piece of”, dan kata kerjanya tunggal.",
              "คำนามนับไม่ได้ ('advice', 'bread', 'information') ไม่ใช้ 'a/an' และไม่เติม -s ให้ใช้ 'some' หรือ 'a piece of' และใช้คำกริยาแบบเอกพจน์"),
        avoid=("Before a or an, ask: can I count this noun one by one?",
               "Sebelum menulis “a/an”, tanya: benda ini bisa dihitung satu per satu?",
               "ก่อนใส่ 'a/an' ให้ถามว่าคำนามนี้นับทีละชิ้นได้ไหม"),
    ),
    "definite_article_with_unique_referents_and_superlatives": dict(
        obj=("Use the before superlatives, order words like first and last, same, and things there is only one of, like the sun.",
             "Pakai “the” sebelum bentuk “paling”, kata urutan seperti “first” dan “last”, kata “same”, dan benda yang cuma ada satu, seperti “the sun”.",
             "ใช้ 'the' หน้าขั้นสูงสุด คำบอกลำดับอย่าง 'first' และ 'last' คำว่า 'same' และสิ่งที่มีอยู่หนึ่งเดียวอย่าง 'the sun'"),
        mis=("Learner leaves out the or uses a, since Indonesian and Thai have no word like the.",
             "Kamu menghilangkan “the” atau memakai “a”, karena bahasa Indonesia nggak punya kata seperti “the”.",
             "คุณไม่ใส่ 'the' หรือใช้ 'a' แทน เพราะภาษาไทยไม่มีคำแบบ 'the'"),
        rule=("If there can be only one, use the: the biggest, the first, the last, the same, the sun.",
              "Kalau bendanya cuma bisa ada satu, pakai “the”: untuk bentuk “paling”, kata urutan seperti “first”, kata “same”, dan benda seperti matahari.",
              "ถ้าสิ่งนั้นมีได้แค่หนึ่งเดียว ให้ใช้ 'the' ทั้งหน้าขั้นสูงสุด หน้าคำบอกลำดับ หน้าคำว่า 'same' และกับสิ่งอย่างดวงอาทิตย์"),
        avoid=("Ask: can there be two of these? If not, use the.",
               "Tanya: mungkinkah ada dua? Kalau nggak, pakai “the”.",
               "ถามว่ามีสองอันได้ไหม ถ้าไม่ได้ให้ใช้ 'the'"),
    ),
    "movement_prepositions_through_across_along_over": dict(
        obj=("Choose across for side to side, through for going inside something, along for following a line, and over for passing above.",
             "Pilih “across” untuk menyeberang dari sisi ke sisi, “through” untuk menembus bagian dalam, “along” untuk menyusuri garis, dan “over” untuk lewat di atas.",
             "เลือก 'across' สำหรับการข้ามจากฝั่งหนึ่งไปอีกฝั่ง 'through' สำหรับการทะลุผ่านข้างใน 'along' สำหรับการเลียบไปตามแนว และ 'over' สำหรับการผ่านเหนือบางอย่าง"),
        mis=("Learner uses one word for every path, since 'lewat' and 'ผ่าน' can mean all four.",
             "Kamu memakai satu kata untuk semua arah gerak, karena kata “lewat” bisa berarti keempatnya.",
             "คุณใช้คำเดียวกับทุกเส้นทาง เพราะคำว่า 'ผ่าน' ใช้ได้ทั้งสี่แบบ"),
        rule=("Across: side to side. Through: inside something, like a tunnel. Along: following a line, like a road. Over: above, like over a wall.",
              "“Across”: dari sisi ke sisi. “Through”: menembus bagian dalam, seperti terowongan. “Along”: menyusuri garis, seperti jalan. “Over”: lewat di atas.",
              "'across' คือข้ามจากฝั่งหนึ่งไปอีกฝั่ง ส่วน 'through' คือทะลุผ่านข้างในอย่างอุโมงค์ 'along' คือเลียบไปตามแนวอย่างถนน และ 'over' คือผ่านข้างบน"),
        avoid=("Picture the path: to the other side, inside, beside a line, or above?",
               "Bayangkan jalurnya: ke seberang, menembus, menyusuri, atau lewat atas?",
               "นึกภาพเส้นทางว่าข้ามไปอีกฝั่ง ทะลุผ่าน เลียบไปตามแนว หรือผ่านข้างบน"),
    ),
    "double_negative_avoidance_single_negation_rule": dict(
        obj=("Use only one negative word in a sentence: don't + anything, or nothing alone.",
             "Pakai satu kata negatif saja dalam satu kalimat: “don't” + “anything”, atau “nothing” saja.",
             "ใช้คำปฏิเสธแค่คำเดียวในหนึ่งประโยค เช่น 'don't' + 'anything' หรือใช้ 'nothing' อย่างเดียว"),
        mis=("Learner puts two negatives together, like don't … nothing, or uses not without a helper verb.",
             "Kamu memakai dua kata negatif sekaligus, seperti “don't … nothing”, atau memakai “not” tanpa kata bantu.",
             "คุณใช้คำปฏิเสธสองคำพร้อมกัน เช่น 'don't … nothing' หรือใช้ 'not' โดยไม่มีกริยาช่วย"),
        rule=("One negative only. Negative verb + any: I don't know anything. Positive verb + a no word: I know nothing. Never and nobody are already negative.",
              "Satu negatif saja. Kata kerja negatif + “any”: “I don't know anything”. Kata kerja positif + kata “no”: “I know nothing”. “Never” dan “nobody” sudah negatif.",
              "ใช้คำปฏิเสธคำเดียว กริยาปฏิเสธใช้คู่กับ 'any' เช่น 'I don't know anything' กริยาบอกเล่าใช้คู่กับคำที่มี 'no' เช่น 'I know nothing' ส่วน 'never' และ 'nobody' เป็นคำปฏิเสธอยู่แล้ว"),
        avoid=("Count the negative words: exactly one.",
               "Hitung kata negatifnya: harus tepat satu.",
               "นับคำปฏิเสธในประโยค ต้องมีแค่หนึ่งคำ"),
    ),
    "state_verbs_resist_continuous_form": dict(
        obj=("Keep state verbs like know, like, want, understand, and have (own) in the simple form, even when you talk about now.",
             "Pakai bentuk biasa (bukan -ing) untuk kata kerja keadaan seperti “know”, “like”, “want”, “understand”, dan “have” (memiliki), walaupun membicarakan saat ini.",
             "ใช้รูปธรรมดา ไม่ใช่ -ing กับคำกริยาบอกสภาพอย่าง 'know', 'like', 'want', 'understand' และ 'have' (มี) แม้จะพูดถึงตอนนี้"),
        mis=("Learner adds -ing to every verb about now, since 'sedang' and 'กำลัง' seem to fit.",
             "Kamu memberi -ing pada semua kata kerja yang terjadi sekarang, karena kata “sedang” terasa cocok.",
             "คุณเติม -ing ให้ทุกคำกริยาที่เกิดตอนนี้ เพราะคิดว่าใช้ 'กำลัง' ได้"),
        rule=("Verbs for thoughts, feelings, and owning are states: know, understand, like, want, have. Use the simple form: I understand.",
              "Kata kerja untuk pikiran, perasaan, dan kepemilikan adalah keadaan: “know”, “understand”, “like”, “want”, “have”. Pakai bentuk biasa: “I understand”.",
              "คำกริยาที่บอกความคิด ความรู้สึก และการเป็นเจ้าของเป็นสภาพ เช่น 'know', 'like', 'want', 'have' ให้ใช้รูปธรรมดา เช่น 'I understand'"),
        avoid=("Ask: is it an action you can see, or a state in your head or heart?",
               "Tanya: ini kegiatan yang kelihatan, atau keadaan di pikiran dan perasaan?",
               "ถามว่าเป็นการกระทำที่มองเห็นได้ หรือเป็นสภาพในความคิดและความรู้สึก"),
    ),
    "preposition_of_time_duration_for_vs_since_vs_during": dict(
        obj=("Use for + a length of time, since + a starting point, and during + an event or period.",
             "Pakai “for” + lamanya waktu, “since” + titik mulai, dan “during” + acara atau masa tertentu.",
             "ใช้ 'for' + ระยะเวลา 'since' + จุดเริ่มต้น และ 'during' + เหตุการณ์หรือช่วงเวลา"),
        mis=("Learner uses during for a length of time, since 'selama' seems to mean during.",
             "Kamu memakai “during” untuk lamanya waktu, karena kata “selama” dikira sama dengan “during”.",
             "คุณใช้ 'during' กับระยะเวลา เพราะคิดว่าเหมือนคำว่า 'ระหว่าง'"),
        rule=("For + how long (for five years). Since + when it started (since Monday). During + in the middle of an event (during the exam).",
              "“For” + berapa lama (“for five years”). “Since” + kapan mulainya (“since Monday”). “During” + di tengah suatu acara (“during the exam”).",
              "'for' ใช้บอกว่านานเท่าไร เช่น 'for five years' ส่วน 'since' บอกว่าเริ่มเมื่อไร เช่น 'since Monday' และ 'during' บอกว่าเกิดระหว่างเหตุการณ์ เช่น 'during the exam'"),
        avoid=("Ask: how long, since when, or during what?",
               "Tanya: berapa lama, sejak kapan, atau di tengah acara apa?",
               "ถามว่านานเท่าไร ตั้งแต่เมื่อไร หรือระหว่างเหตุการณ์อะไร"),
    ),
    "subject_vs_object_questions_word_order": dict(
        obj=("Ask about the doer with Who or What + verb, and about the receiver with Who or What + do, does, or did + subject + base verb.",
             "Tanya pelaku dengan “Who/What” + kata kerja, dan tanya penerima atau objek dengan “Who/What” + “do/does/did” + subjek + kata kerja dasar.",
             "ถามถึงผู้กระทำด้วย 'Who/What' + คำกริยา และถามถึงผู้ถูกกระทำด้วย 'Who/What' + 'do/does/did' + ประธาน + คำกริยารูปพื้นฐาน"),
        mis=("Learner adds do or did to every question, or forgets it when the question word is the object.",
             "Kamu menambah “do/did” di semua kalimat tanya, atau melupakannya saat kata tanyanya menanyakan objek.",
             "คุณใส่ 'do/did' ในทุกคำถาม หรือลืมใส่เมื่อคำแสดงคำถามถามถึงกรรม"),
        rule=("Who or What is the doer: no do (Who called you?). Who or What is the object: add do, does, or did (Who did you call?).",
              "Kalau “who/what” pelakunya: tanpa “do” (“Who called you?”). Kalau “who/what” objeknya: tambah “do/does/did” (“Who did you call?”).",
              "ถ้า 'who/what' เป็นผู้กระทำ ไม่ต้องใช้ 'do' เช่น 'Who called you?' ถ้า 'who/what' เป็นกรรม ให้เติม 'do/does/did' เช่น 'Who did you call?'"),
        avoid=("Ask: is the question word doing the action, or receiving it?",
               "Tanya: kata tanyanya melakukan kegiatan, atau dikenai kegiatan?",
               "ถามว่าคำแสดงคำถามเป็นผู้ทำหรือผู้ถูกกระทำ"),
    ),
}

# ---- label lama (nama persis di grammar-misconception-id.json) ----
SG_ART_UNCOUNT = "singular-article-with-uncountable"
REMOVE_PL = "removes the article correctly but incorrectly pluralizes the uncountable noun"
KEEP_PL = "keeps the indefinite article and also incorrectly pluralizes an uncountable noun"
MANY_UNCOUNT = "countable-quantity-substitution"
SUP_A = "treating a superlative noun phrase as an ordinary indefinite first mention"
AN_SAME = "same indefinite-article error as 'a', plus a vowel-sound trigger confusion"
QUANT_SG = "quantifier substituted for a singular countable reference"
A_FIRST = "uses the indefinite article before 'first'"
ACROSS_ENCL = "using the flat-open-surface preposition for an enclosed three-dimensional space"
ALONG_ENCL = "using the linear-edge preposition (following a line such as a river or street) for movement inside an enclosed space"
OVER_ENCL = "using the above-and-across preposition for movement inside a space, not above it"
ACROSS_LINE = "uses the side-to-side crossing preposition for movement that follows a line"
THROUGH_LINE = "uses the enclosed-space movement preposition for a path along an open line"
OVER_LINE = "uses the above-and-across preposition for movement following a line, not over an obstacle"
DOUBLE_NEG = "combining a negated verb ('didn't') with a negative pronoun, creating a non-standard double negative"
SPLIT_NEG = "incorrectly splitting the compound negative pronoun into two words"
NO_AFTER_NOT = "uses 'no' before a verb already negated with 'not'"
POS_Q_NEG = "positive-quantifier-in-negative"
BARE_AGR = "missing subject-verb agreement / bare form"
PRES_CONT_ALWAYS = "Assumes present time always requires present continuous."
FRAGMENT = "reduces the sentence to a fragment: an -ing form with no finite verb to carry the tense"
WANT_PROG = "forcing a stative desire verb into the progressive to sound ongoing"
IS_MAIN = "inserting 'is' before a main verb, blending the 'be' pattern with the present simple"
WHILE_NP = "Uses the conjunction 'while' where a preposition is grammatically required before a noun phrase."
FOR_POINT = "Applies duration preposition 'for' to a point-in-time event rather than a length of time."
SINCE_DURING = "Confuses 'during' (within a period) with 'since' (marking a starting point)."
DURING_SINCE = "uses the within-a-period preposition 'during' where a starting point needs 'since'"
DID_SUBJ = "Adds the auxiliary 'did' as if this were an object question, following the standard question-formation rule mechanically."
DID_PAST = "Adds 'did' and keeps the past-tense main verb form together."
NO_DID_OBJ = "drops the auxiliary 'did' required in an object question"
OBJ_AS_SUBJ = "reads an object question as a subject question, reversing who did what"
DOES_PAST = "Uses present-tense auxiliary 'does' for a clearly past-time event ('last night')."
BARE_PAST = "bare present form used for a past narrative"

# ---- label baru dari paket g/h (teks harus sama persis) ----
FEW_UNCOUNT = ("few or a few used with an uncountable noun", "“few” atau “a few” dipakai untuk benda yang nggak bisa dihitung.", "ใช้ 'few' หรือ 'a few' กับคำนามนับไม่ได้")
PL_UNCOUNT = ("plural be used with an uncountable noun", "bentuk jamak dipakai untuk benda yang nggak bisa dihitung.", "ใช้รูปพหูพจน์กับคำนามนับไม่ได้")
WERE_SG = ("plural past be used with a singular subject", "bentuk lampau jamak dipakai untuk satu orang atau satu benda.", "ใช้รูปอดีตพหูพจน์กับคนหรือสิ่งเดียว")
THE_DROP = ("the dropped before a superlative", "'the' hilang sebelum bentuk 'paling'.", "ขาด 'the' หน้าขั้นสูงสุด")
ANY_POS = ("negative quantifier used in a positive sentence", "kata jumlah untuk kalimat negatif dipakai di kalimat positif.", "ใช้คำบอกปริมาณของประโยคปฏิเสธในประโยคบอกเล่า")
NOT_NO_HELPER = ("not used without a helper verb in a negative", "“not” dipakai tanpa kata bantu di kalimat negatif.", "ใช้ 'not' โดยไม่มีกริยาช่วยในประโยคปฏิเสธ")
S_AFTER_I = ("-s added to the verb after I", "akhiran -s ditambahkan ke kata kerja untuk subjek “I”.", "เติม -s ให้คำกริยาของ 'I'")
DONT_3SG = ("don't used with he, she, or it", "“don't” dipakai untuk “he”, “she”, atau “it”.", "ใช้ 'don't' กับประธานที่เป็นเขาหรือเธอคนเดียว")
HAS_PL = ("he-she-it have form used with a plural subject", "bentuk “has” untuk “he”, “she”, “it” dipakai untuk subjek jamak.", "ใช้ 'has' ของ 'he', 'she', 'it' กับประธานพหูพจน์")

# ---- label baru paket i ----
A_PIECES = ("a used with the plural pieces", "“a” dipasangkan dengan “pieces” yang jamak.", "ใช้ 'a' คู่กับ 'pieces' ที่เป็นพหูพจน์")
NUM_UNCOUNT = ("number used directly with an uncountable noun", "angka dipakai langsung untuk benda yang nggak bisa dihitung.", "ใช้ตัวเลขกับคำนามนับไม่ได้โดยตรง")
BARE_BE = ("base form be used as the main verb", "bentuk dasar 'be' dipakai tanpa diubah sesuai subjek.", "ใช้ 'be' รูปพื้นฐานโดยไม่เปลี่ยนตามประธาน")
NO_DOUBLE_EST = ("final consonant not doubled before -est", "huruf mati terakhir nggak digandakan sebelum -est.", "ไม่เพิ่มพยัญชนะตัวท้ายก่อนเติม -est")
A_UNIQUE = ("a used for something there is only one of", "“a” dipakai untuk benda yang cuma ada satu.", "ใช้ 'a' กับสิ่งที่มีอยู่หนึ่งเดียว")
THE_DROP_ORD = ("the dropped before an order word", "'the' hilang sebelum kata urutan seperti 'first' atau 'last'.", "ขาด 'the' หน้าคำบอกลำดับอย่าง 'first' หรือ 'last'")
LATEST_LAST = ("latest used to mean the final one", "“latest” (terbaru) dipakai untuk yang terakhir dalam urutan.", "ใช้ 'latest' (ล่าสุด) กับสิ่งที่อยู่ลำดับสุดท้าย")
SAME_WITH = ("same followed by with instead of as", "'same' disambung dengan 'with', meniru 'sama dengan'.", "ใช้ 'with' ตามหลัง 'same' แบบแปลจาก 'เหมือนกับ'")
THE_DROP_SAME = ("the dropped before same", "'the' hilang sebelum kata 'same'.", "ขาด 'the' ที่ต้องอยู่หน้าคำว่า 'same'")
A_SAME = ("a used before same", "“a” dipakai sebelum kata “same”.", "ใช้ 'a' ไว้หน้าคำว่า 'same'")
THROUGH_CROSS = ("through used for crossing an open surface", "kata depan untuk menembus dipakai untuk menyeberangi permukaan terbuka.", "ใช้คำบุพบทของการทะลุผ่านกับการข้ามพื้นผิวที่เปิดโล่ง")
ALONG_CROSS = ("along used for crossing to the other side", "kata depan untuk menyusuri dipakai untuk menyeberang ke sisi lain.", "ใช้คำบุพบทของการเลียบไปตามแนวกับการข้ามไปอีกฝั่ง")
OVER_IN_WATER = ("over used for moving through water, not above it", "kata depan untuk lewat di atas dipakai untuk gerak di dalam air.", "ใช้คำบุพบทของการผ่านข้างบนกับการเคลื่อนที่ในน้ำ")
THROUGH_ABOVE = ("through used for passing above something", "kata depan untuk menembus dipakai untuk benda yang lewat di atas.", "ใช้คำบุพบทของการทะลุผ่านกับสิ่งที่ผ่านไปข้างบน")
ACROSS_ABOVE = ("across used for passing above something", "kata depan untuk menyeberang dipakai untuk benda yang lewat di atas.", "ใช้คำบุพบทของการข้ามกับสิ่งที่ผ่านไปข้างบน")
ALONG_ABOVE = ("along used for passing above something", "kata depan untuk menyusuri dipakai untuk benda yang lewat di atas.", "ใช้คำบุพบทของการเลียบไปตามแนวกับสิ่งที่ผ่านไปข้างบน")
ANY_SUBJ = ("any- word used as the subject for no one", "kata berawalan “any” dipakai sebagai subjek untuk makna “tak seorang pun”.", "ใช้คำที่ขึ้นต้นด้วย 'any' เป็นประธานเพื่อบอกว่าไม่มีใคร")
NOT_ANY_SUBJ = ("not anybody used as a subject", "“not anybody” dipakai sebagai subjek kalimat.", "ใช้ 'not anybody' เป็นประธานของประโยค")
NONE_NOUN = ("none used before a noun", "“none” dipakai langsung sebelum kata benda.", "ใช้ 'none' หน้าคำนามโดยตรง")
SINCE_LENGTH = ("since used with a length of time", "“since” dipakai untuk lamanya waktu.", "ใช้ 'since' กับระยะเวลา")
DURING_LENGTH = ("during used with a length of time", "“during” dipakai untuk lamanya waktu, meniru “selama”.", "ใช้ 'during' กับระยะเวลา")
FROM_SINCE = ("from used alone for a start that continues until now", "“from” dipakai sendirian untuk titik mulai yang masih berlanjut sampai sekarang.", "ใช้ 'from' ตามลำพังกับจุดเริ่มต้นที่ยังต่อเนื่องมาถึงตอนนี้")
DOES_S = ("does combined with a verb that already has -s", "'does' dipasangkan dengan kata kerja yang sudah ber-s.", "ใช้ 'does' คู่กับคำกริยาที่เติม -s แล้ว")
WAS_HAPPENED = ("be added before happened", "'was' ditambahkan sebelum 'happened'.", "เติม 'was' ไว้หน้าคำว่า 'happened' โดยไม่จำเป็น")


def L(name, item_id, item_th):
    return (name, item_id, item_th)


def N(label, item_id, item_th):
    """label baru dengan teks khusus untuk soal ini"""
    return label + (item_id, item_th)


ITEMS = [
    # ---------------- 32. uncountable nouns ----------------
    dict(s="article_omission_with_uncountable", id="A2-357",
         stem="Can you give me ___ about my English test?", opts=["some advice", "an advice", "some advices", "an advices"], ans="some advice",
         why=("Advice cannot be counted, so no a or an and no -s. For an amount we don't state, use some.",
              "“Advice” nggak bisa dihitung, jadi tanpa “a/an” dan tanpa -s. Untuk jumlah yang nggak disebut, pakai “some”.",
              "'advice' นับไม่ได้ จึงไม่ใช้ 'a/an' และไม่เติม -s ถ้าไม่ระบุจำนวนให้ใช้ 'some'"),
         others=("'An advice' adds an, 'some advices' adds -s, and 'an advices' makes both mistakes.",
                 "“An advice” menambah “an”, “some advices” menambah -s, dan “an advices” melakukan dua kesalahan itu sekaligus.",
                 "ตัวเลือกที่มี 'an' ใส่คำนำหน้าที่ไม่ต้องใช้ ตัวเลือกที่เติม -s ทำให้เป็นพหูพจน์ทั้งที่นับไม่ได้ และ 'an advices' ผิดทั้งสองอย่าง"),
         cue=("Advice, information, homework: no a or an, no -s.", "“Advice”, “information”, “homework”: tanpa “a/an”, tanpa -s.", "คำนามนับไม่ได้อย่าง 'advice' ไม่ใช้ 'a/an' และไม่เติม -s"),
         rsn=("check if advice can be counted -> remove a or an -> keep advice without -s",
              "cek “advice” bisa dihitung atau nggak → buang “a/an” → biarkan “advice” tanpa -s",
              "ดูว่า 'advice' นับได้หรือไม่ → ตัด 'a/an' ออก → ใช้ 'advice' โดยไม่เติม -s"),
         d=[("an advice", L(SG_ART_UNCOUNT, "“an” dipakai untuk “advice” yang nggak bisa dihitung.", "ใช้ 'an' กับ 'advice' ซึ่งนับไม่ได้"),
             "It puts an before advice, but advice cannot be counted.",
             "memakai “an”, padahal “advice” nggak bisa dihitung.",
             "ใช้ 'an' แต่ 'advice' นับไม่ได้"),
            ("some advices", L(REMOVE_PL, "“some” sudah benar, tapi “advice” malah diberi -s.", "ใช้ 'some' ถูกแล้ว แต่ไปเติม -s ให้ 'advice'"),
             "Some is right, but advice never takes -s.",
             "sudah benar memakai “some”, tapi “advice” nggak pernah diberi -s.",
             "ใช้ 'some' ถูกแล้ว แต่ 'advice' ไม่เคยเติม -s"),
            ("an advices", L(KEEP_PL, "“an” dan -s dipakai bersamaan untuk “advice”.", "ใช้ 'an' และเติม -s ให้ 'advice' พร้อมกัน"),
             "It makes two mistakes: an before advice and -s at the end.",
             "punya dua kesalahan: “an” di depan “advice” dan -s di belakangnya.",
             "ผิดสองจุด คือมี 'an' ข้างหน้าและเติม -s ข้างหลัง")]),
    dict(s="article_omission_with_uncountable", id="A2-358",
         stem="I'd like ___ rice with my chicken, please.", opts=["some", "a", "many", "a few"], ans="some",
         why=("Rice cannot be counted, so we use some, not a.",
              "“Rice” nggak bisa dihitung, jadi pakai “some”, bukan “a”.",
              "'rice' นับไม่ได้ จึงใช้ 'some' ไม่ใช้ 'a'"),
         others=("'A' needs a countable noun, and 'many' and 'a few' are for countable plurals.",
                 "“A” butuh benda yang bisa dihitung, sedangkan “many” dan “a few” untuk benda jamak yang bisa dihitung.",
                 "'a' ต้องใช้กับคำนามนับได้ ส่วน 'many' กับ 'a few' ใช้กับคำนามพหูพจน์ที่นับได้"),
         cue=("Food you can't count: some rice, some bread, some water.", "Makanan yang nggak bisa dihitung: “some rice”, “some bread”, “some water”.", "อาหารที่นับไม่ได้ใช้ 'some' เช่น 'some rice'"),
         rsn=("check if rice can be counted -> recall that uncountable nouns take no a or an -> choose the word for an amount of an uncountable noun",
              "cek “rice” bisa dihitung atau nggak → ingat benda yang nggak bisa dihitung nggak pakai “a/an” → pilih kata untuk jumlah benda yang nggak bisa dihitung",
              "ดูว่า 'rice' นับได้หรือไม่ → นึกว่าคำนามนับไม่ได้ไม่ใช้ 'a/an' → เลือกคำบอกปริมาณของคำนามนับไม่ได้"),
         d=[("a", L(SG_ART_UNCOUNT, "“a” dipakai untuk “rice” yang nggak bisa dihitung.", "ใช้ 'a' กับ 'rice' ซึ่งนับไม่ได้"),
             "It needs a countable noun; to count rice, say a plate of rice.",
             "butuh benda yang bisa dihitung; kalau mau menghitung nasi, bilang “a plate of rice”.",
             "ต้องใช้กับคำนามนับได้ ถ้าจะนับข้าวให้พูดว่า 'a plate of rice'"),
            ("many", L(MANY_UNCOUNT, "“many” dipakai untuk “rice”.", "ใช้ 'many' กับ 'rice' ซึ่งนับไม่ได้"),
             "It is for things you can count, but rice cannot be counted.",
             "untuk benda yang bisa dihitung, padahal “rice” nggak bisa dihitung.",
             "ใช้กับของที่นับได้ แต่ 'rice' นับไม่ได้"),
            ("a few", N(FEW_UNCOUNT, "“a few” dipakai untuk “rice”.", "ใช้ 'a few' กับ 'rice' ซึ่งนับไม่ได้"),
             "It is for countable plurals, like eggs, not for rice.",
             "untuk benda jamak yang bisa dihitung, seperti telur, bukan untuk nasi.",
             "ใช้กับคำนามพหูพจน์ที่นับได้อย่างไข่ ไม่ใช่ข้าว")]),
    dict(s="article_omission_with_uncountable", id="A2-359",
         stem="I'm hungry. Can I have ___ bread, please?", opts=["a piece of", "a", "a pieces of", "one"], ans="a piece of",
         why=("Bread cannot be counted directly, so we count the pieces with a piece of.",
              "“Bread” nggak bisa dihitung langsung, jadi yang dihitung potongannya dengan “a piece of”.",
              "'bread' นับโดยตรงไม่ได้ จึงนับเป็นชิ้นด้วย 'a piece of'"),
         others=("'A' cannot go straight before bread, 'a pieces of' mixes one and many, and 'one' cannot count bread directly.",
                 "“A” nggak bisa langsung di depan “bread”, “a pieces of” mencampur satu dan banyak, dan “one” nggak bisa menghitung “bread” secara langsung.",
                 "'a' วางหน้า 'bread' โดยตรงไม่ได้ ส่วน 'a pieces of' ผสมหนึ่งกับหลาย และ 'one' ใช้นับ 'bread' โดยตรงไม่ได้"),
         cue=("Count the piece or the container: a piece of bread, a glass of water.", "Hitung potongan atau wadahnya: “a piece of bread”, “a glass of water”.", "นับเป็นชิ้นหรือเป็นภาชนะ เช่น 'a glass of water'"),
         rsn=("check if bread can be counted -> recall that such nouns are counted by pieces or containers -> keep piece singular after a",
              "cek “bread” bisa dihitung atau nggak → ingat benda seperti ini dihitung per potong atau per wadah → pastikan “piece” tetap tunggal sesudah “a”",
              "ดูว่า 'bread' นับได้หรือไม่ → นึกว่าของแบบนี้นับเป็นชิ้นหรือเป็นภาชนะ → ให้ 'piece' เป็นเอกพจน์หลัง 'a'"),
         d=[("a", L(SG_ART_UNCOUNT, "“a” dipakai langsung untuk “bread”.", "ใช้ 'a' กับ 'bread' โดยตรง"),
             "It goes straight before bread, but bread cannot be counted.",
             "ditaruh langsung di depan “bread”, padahal “bread” nggak bisa dihitung.",
             "วางไว้หน้า 'bread' โดยตรง แต่ 'bread' นับไม่ได้"),
            ("a pieces of", A_PIECES,
             "It puts a before pieces; one piece has no -s.",
             "memasangkan “a” dengan “pieces”, padahal untuk satu potong, kata “piece” nggak diberi -s.",
             "ใช้ 'a' คู่กับ 'pieces' แต่ชิ้นเดียวไม่ต้องเติม -s"),
            ("one", NUM_UNCOUNT,
             "Bread cannot be counted with a number; count the pieces instead.",
             "nggak bisa menghitung “bread” secara langsung; yang dihitung potongannya.",
             "ใช้นับ 'bread' โดยตรงไม่ได้ ต้องนับเป็นชิ้นแทน")]),
    dict(s="article_omission_with_uncountable", id="A2-360",
         stem="This information ___ very useful for my project.", opts=["is", "are", "were", "be"], ans="is",
         why=("Information cannot be counted, so the verb is singular, is.",
              "“Information” nggak bisa dihitung, jadi kata kerjanya tunggal, yaitu “is”.",
              "'information' นับไม่ได้ จึงใช้คำกริยาเอกพจน์ คือ 'is'"),
         others=("'Are' and 'were' are plural, and 'be' is not changed to match the subject.",
                 "“Are” dan “were” bentuk jamak, sedangkan “be” belum diubah sesuai subjeknya.",
                 "'are' และ 'were' เป็นรูปพหูพจน์ ส่วน 'be' ยังไม่ได้เปลี่ยนตามประธาน"),
         cue=("Uncountable noun, singular verb: the information is, the news is.", "Benda yang nggak bisa dihitung pakai kata kerja tunggal, misalnya “information is” dan “news is”.", "คำนามนับไม่ได้ใช้คำกริยาเอกพจน์ เช่น 'the news is'"),
         rsn=("identify information as uncountable -> recall that uncountable nouns take a singular verb -> choose the present singular form of be",
              "kenali “information” sebagai benda yang nggak bisa dihitung → ingat benda seperti ini memakai kata kerja tunggal → pilih bentuk “be” tunggal untuk sekarang",
              "ดูว่า 'information' เป็นคำนามนับไม่ได้ → นึกว่าคำนามแบบนี้ใช้คำกริยาเอกพจน์ → เลือก 'be' รูปเอกพจน์ของปัจจุบัน"),
         d=[("are", N(PL_UNCOUNT, "“are” dipakai untuk “information”.", "ใช้ 'are' กับ 'information' ซึ่งนับไม่ได้"),
             "It is plural, but information cannot be counted and takes a singular verb.",
             "bentuk jamak, padahal “information” nggak bisa dihitung dan memakai kata kerja tunggal.",
             "เป็นรูปพหูพจน์ แต่ 'information' นับไม่ได้และใช้คำกริยาเอกพจน์"),
            ("were", N(WERE_SG, "“were” dipakai untuk “information”.", "ใช้ 'were' กับ 'information' ซึ่งนับไม่ได้"),
             "It is the past form for plural subjects, but information always takes a singular verb.",
             "bentuk lampau untuk subjek jamak, padahal “information” selalu memakai kata kerja tunggal.",
             "เป็นรูปอดีตของประธานพหูพจน์ แต่ 'information' ใช้คำกริยาเอกพจน์เสมอ"),
            ("be", BARE_BE,
             "It is the base form; after a subject, this verb must change to match it.",
             "bentuk dasar, padahal sesudah subjek kata kerja ini harus diubah sesuai subjeknya.",
             "เป็นรูปพื้นฐาน แต่หลังประธานต้องเปลี่ยนรูปให้ตรงกับประธาน")]),
    # ---------------- 33. the: unique, superlative, order ----------------
    dict(s="definite_article_with_unique_referents_and_superlatives", id="A2-361",
         stem="Jakarta is ___ city in Indonesia.", opts=["the biggest", "a biggest", "biggest", "the bigest"], ans="the biggest",
         why=("Jakarta is number one among all the cities, so we use the + the -est form.",
              "Jakarta nomor satu di antara semua kota, jadi pakai “the” + bentuk “paling”, yaitu “the biggest”.",
              "จาการ์ตาเป็นอันดับหนึ่งในบรรดาเมืองทั้งหมด จึงใช้ 'the' + ขั้นสูงสุด คือ 'the biggest'"),
         others=("'A biggest' uses a for something only one city can be, 'biggest' forgets the, and 'the bigest' forgets to double the g.",
                 "“A biggest” memakai “a” untuk sesuatu yang cuma bisa satu, “biggest” lupa “the”, dan “the bigest” lupa menggandakan huruf g.",
                 "'a biggest' ใช้ 'a' กับสิ่งที่มีได้แค่หนึ่งเดียว ส่วน 'biggest' ลืม 'the' และ 'the bigest' ลืมเพิ่ม g อีกตัว"),
         cue=("Number one in a group: the + -est.", "Nomor satu di kelompoknya: “the” + -est.", "อันดับหนึ่งในกลุ่มใช้ 'the' + -est"),
         rsn=("notice in Indonesia -> identify Jakarta as number one in a group -> combine the with the -est form",
              "perhatikan “in Indonesia” → pastikan Jakarta nomor satu di kelompoknya → gabungkan “the” dengan bentuk -est",
              "สังเกต 'in Indonesia' → ดูว่าจาการ์ตาเป็นอันดับหนึ่งในกลุ่ม → รวม 'the' กับรูป -est"),
         d=[("a biggest", L(SUP_A, "“a” dipakai sebelum bentuk “paling”.", "ใช้ 'a' หน้าขั้นสูงสุด"),
             "It uses a, but there is only one biggest city.",
             "memakai “a”, padahal kota terbesar cuma ada satu.",
             "ใช้ 'a' แต่เมืองที่ใหญ่ที่สุดมีได้แค่เมืองเดียว"),
            ("biggest", THE_DROP,
             "It has no the; the -est form always comes with the.",
             "tanpa “the”, padahal bentuk -est selalu datang bersama “the”.",
             "ไม่มี 'the' แต่รูป -est ต้องมาพร้อม 'the' เสมอ"),
            ("the bigest", NO_DOUBLE_EST,
             "It forgets to double the g before -est.",
             "lupa menggandakan huruf g sebelum -est.",
             "ลืมเพิ่ม g อีกตัวก่อนเติม -est")]),
    dict(s="definite_article_with_unique_referents_and_superlatives", id="A2-362",
         stem="Never look straight at ___ sun. It can hurt your eyes.", opts=["the", "a", "an", "some"], ans="the",
         why=("There is only one sun in our sky, so we use the.",
              "Matahari di langit kita cuma satu, jadi pakai “the”.",
              "ดวงอาทิตย์บนฟ้าของเรามีดวงเดียว จึงใช้ 'the'"),
         others=("'A' and 'an' are for one of many, and 'some' is for an amount.",
                 "“A” dan “an” untuk salah satu dari banyak benda, sedangkan “some” untuk jumlah.",
                 "'a' กับ 'an' ใช้กับหนึ่งในหลายสิ่ง ส่วน 'some' ใช้บอกปริมาณ"),
         cue=("Only one in the world: the sun, the moon, the sky.", "Benda yang cuma ada satu di dunia selalu pakai “the”, misalnya “the sun”.", "สิ่งที่มีหนึ่งเดียวในโลกใช้ 'the' เช่น 'the moon'"),
         rsn=("identify the sun as the only one -> recall that one-of-a-kind things take the -> apply it before sun",
              "kenali matahari sebagai satu-satunya → ingat benda yang cuma satu memakai “the” → pakai kata itu sebelum “sun”",
              "ดูว่าดวงอาทิตย์มีหนึ่งเดียว → นึกว่าสิ่งที่มีหนึ่งเดียวใช้ 'the' → ใช้คำนั้นหน้า 'sun'"),
         d=[("a", A_UNIQUE,
             "It means one sun among many, but our sky has only one.",
             "berarti salah satu dari banyak matahari, padahal di langit kita cuma ada satu.",
             "หมายถึงดวงอาทิตย์ดวงหนึ่งในหลายดวง แต่บนฟ้าของเรามีดวงเดียว"),
            ("an", L(AN_SAME, "“an” dipakai untuk “sun”, padahal bendanya cuma satu dan bunyi awalnya konsonan.", "ใช้ 'an' กับ 'sun' ทั้งที่มีหนึ่งเดียวและขึ้นต้นด้วยเสียงพยัญชนะ"),
             "It is for a vowel sound, and the sun is one of a kind anyway.",
             "untuk bunyi vokal, dan mataharinya pun cuma satu.",
             "ใช้หน้าเสียงสระ และดวงอาทิตย์ก็มีอยู่ดวงเดียว"),
            ("some", L(QUANT_SG, "kata jumlah dipakai untuk satu-satunya matahari.", "ใช้คำบอกปริมาณกับดวงอาทิตย์ที่มีดวงเดียว"),
             "It is for an amount, but there is just one sun.",
             "untuk menyebut jumlah, padahal mataharinya cuma satu.",
             "ใช้บอกปริมาณ แต่ดวงอาทิตย์มีดวงเดียว")]),
    dict(s="definite_article_with_unique_referents_and_superlatives", id="A2-363",
         stem="December is ___ month of the year.", opts=["the last", "a last", "last", "the latest"], ans="the last",
         why=("December is the final month, and there is only one final month, so we use the last.",
              "Bulan Desember itu bulan penutup, dan bulan penutup cuma ada satu, jadi pakai “the last”.",
              "ธันวาคมเป็นเดือนสุดท้าย และเดือนสุดท้ายมีได้เดือนเดียว จึงใช้ 'the last'"),
         others=("'A last' uses a for something only one can be, 'last' forgets the, and 'the latest' means the newest.",
                 "“A last” memakai “a” untuk sesuatu yang cuma bisa satu, “last” lupa “the”, dan “the latest” artinya yang terbaru.",
                 "'a last' ใช้ 'a' กับสิ่งที่มีได้แค่หนึ่งเดียว ส่วน 'last' ลืม 'the' และ 'the latest' แปลว่าใหม่ล่าสุด"),
         cue=("Order words take the: the first, the second, the last.", "Kata urutan seperti “first” dan “last” selalu didahului “the”.", "คำบอกลำดับใช้ 'the' เสมอ เช่น 'the first'"),
         rsn=("identify December as the final month -> recall that order words take the -> check the meaning of last and latest",
              "kenali Desember sebagai bulan penutup → ingat kata urutan memakai “the” → cek beda arti “last” dan “latest”",
              "ดูว่าธันวาคมเป็นเดือนสุดท้าย → นึกว่าคำบอกลำดับใช้ 'the' → ดูความต่างระหว่าง 'last' กับ 'latest'"),
         d=[("a last", L(A_FIRST, "“a” dipakai sebelum kata urutan “last”.", "ใช้ 'a' หน้าคำบอกลำดับ 'last'"),
             "It uses a, but only one month can be the final one.",
             "memakai “a”, padahal bulan penutup cuma ada satu.",
             "ใช้ 'a' แต่เดือนสุดท้ายมีได้เดือนเดียว"),
            ("last", THE_DROP_ORD,
             "It forgets the; order words like first and last need it.",
             "lupa “the”, padahal kata urutan selalu butuh “the”.",
             "ลืม 'the' แต่คำบอกลำดับต้องมี 'the' เสมอ"),
            ("the latest", LATEST_LAST,
             "It means the newest, like a new phone model, not the final one.",
             "artinya yang terbaru, seperti ponsel keluaran terbaru, bukan yang terakhir dalam urutan.",
             "แปลว่าใหม่ล่าสุด เช่น โทรศัพท์รุ่นใหม่ล่าสุด ไม่ใช่ลำดับสุดท้าย")]),
    dict(s="definite_article_with_unique_referents_and_superlatives", id="A2-364",
         stem="Look! Your bag is ___ mine.", opts=["the same as", "the same with", "same as", "a same as"], ans="the same as",
         why=("Same always comes with the, and it is followed by as.",
              "“Same” selalu didahului “the” dan disambung dengan “as”.",
              "'same' ต้องมี 'the' ข้างหน้าเสมอและตามด้วย 'as'"),
         others=("'The same with' copies 'sama dengan', 'same as' forgets the, and 'a same as' uses a.",
                 "Pilihan dengan “with” meniru “sama dengan”, “same as” lupa “the”, dan “a same as” memakai “a”.",
                 "'the same with' แปลตรงจาก 'เหมือนกับ' ส่วน 'same as' ลืม 'the' และ 'a same as' ใช้ 'a'"),
         cue=("The same as, never same with.", "“The same as”, bukan “same with”.", "จำไว้ว่าต้องพูดว่า 'the same as' ไม่ใช่ 'same with'"),
         rsn=("notice the word same -> recall that same always takes the -> check the word that comes after same",
              "perhatikan kata “same” → ingat “same” selalu didahului “the” → cek kata yang datang sesudah “same”",
              "สังเกตคำว่า 'same' → นึกว่า 'same' ต้องมี 'the' เสมอ → ดูคำที่ตามหลัง 'same'"),
         d=[("the same with", SAME_WITH,
             "It copies 'sama dengan'; after same, English uses as.",
             "meniru “sama dengan”, padahal sesudah “same” bahasa Inggris memakai “as”.",
             "แปลตรงจาก 'เหมือนกับ' แต่หลัง 'same' ภาษาอังกฤษใช้ 'as'"),
            ("same as", THE_DROP_SAME,
             "It forgets the; same always needs it.",
             "lupa “the”, padahal “same” selalu butuh “the”.",
             "ลืม 'the' แต่ 'same' ต้องมี 'the' เสมอ"),
            ("a same as", A_SAME,
             "It uses a, but same always takes the.",
             "memakai “a”, padahal “same” selalu memakai “the”.",
             "ใช้ 'a' แต่ 'same' ต้องใช้กับ 'the' เสมอ")]),
    # ---------------- 34. across / through / along / over ----------------
    dict(s="movement_prepositions_through_across_along_over", id="A2-365",
         stem="Rudi swam ___ the lake to the small island.", opts=["across", "through", "along", "over"], ans="across",
         why=("Rudi went from one side of the lake to the other, so we use across.",
              "Rudi pergi dari satu sisi danau ke sisi lain, jadi pakai “across”.",
              "รูดีว่ายจากฝั่งหนึ่งของทะเลสาบไปอีกฝั่ง จึงใช้ 'across'"),
         others=("'Through' is for going inside something, 'along' follows a line, and 'over' passes above.",
                 "“Through” untuk menembus bagian dalam, “along” untuk menyusuri, dan “over” untuk lewat di atas.",
                 "'through' ใช้กับการทะลุผ่านข้างใน ส่วน 'along' ใช้กับการเลียบไปตามแนว และ 'over' ใช้กับการผ่านข้างบน"),
         cue=("From one side to the other side: across.", "Dari satu sisi ke sisi lain: “across”.", "จากฝั่งหนึ่งไปอีกฝั่งใช้ 'across'"),
         rsn=("identify the path from the shore to the island -> recall the word for going from one side to the other -> apply it before the lake",
              "kenali jalurnya dari tepi ke pulau → ingat kata depan untuk menyeberang dari sisi ke sisi → pakai kata itu sebelum “the lake”",
              "ดูเส้นทางจากฝั่งไปเกาะ → นึกถึงคำบุพบทของการข้ามจากฝั่งหนึ่งไปอีกฝั่ง → ใช้คำนั้นหน้า 'the lake'"),
         d=[("through", THROUGH_CROSS,
             "It is for going inside something, like a tunnel; a lake is an open surface.",
             "untuk menembus bagian dalam sesuatu, seperti terowongan, padahal danau itu permukaan terbuka.",
             "ใช้กับการทะลุผ่านข้างในบางอย่าง เช่น อุโมงค์ แต่ทะเลสาบเป็นพื้นผิวที่เปิดโล่ง"),
            ("along", ALONG_CROSS,
             "It is for following the edge or length of something, not for going to the other side.",
             "untuk menyusuri tepi atau panjang sesuatu, bukan menyeberang ke sisi lain.",
             "ใช้กับการเลียบไปตามขอบหรือความยาว ไม่ใช่การข้ามไปอีกฝั่ง"),
            ("over", OVER_IN_WATER,
             "It is for passing above something, but Rudi swam in the water.",
             "untuk lewat di atas sesuatu, padahal Rudi berenang di dalam air.",
             "ใช้กับการผ่านข้างบน แต่รูดีว่ายอยู่ในน้ำ")]),
    dict(s="movement_prepositions_through_across_along_over", id="A2-366",
         stem="The ball flew ___ the window and broke the glass.", opts=["through", "across", "along", "over"], ans="through",
         why=("The ball went into the window and broke the glass, so we use through.",
              "Bolanya menembus jendela sampai kacanya pecah, jadi pakai “through”.",
              "ลูกบอลทะลุหน้าต่างจนกระจกแตก จึงใช้ 'through'"),
         others=("'Across' is for crossing a surface, 'along' follows a line, and 'over' passes above the window without breaking it.",
                 "“Across” untuk menyeberangi permukaan, “along” untuk menyusuri garis, dan “over” lewat di atas jendela tanpa memecahkannya.",
                 "'across' ใช้กับการข้ามพื้นผิว ส่วน 'along' ใช้กับการเลียบไปตามแนว และ 'over' ผ่านเหนือหน้าต่างโดยไม่ทำให้แตก"),
         cue=("In one side and out the other: through.", "Masuk dari satu sisi, keluar di sisi lain: “through”.", "เข้าทางหนึ่งแล้วออกอีกทางใช้ 'through'"),
         rsn=("notice broke the glass -> identify the path as going into the window -> recall the word for going inside something",
              "perhatikan “broke the glass” → pastikan bolanya menembus jendela → ingat kata depan untuk menembus bagian dalam",
              "สังเกต 'broke the glass' → ดูว่าลูกบอลทะลุผ่านหน้าต่าง → นึกถึงคำบุพบทของการทะลุผ่าน"),
         d=[("across", L(ACROSS_ENCL, "kata depan untuk menyeberang dipakai untuk bola yang menembus jendela.", "ใช้คำบุพบทของการข้ามกับลูกบอลที่ทะลุหน้าต่าง"),
             "It is for crossing a surface, like a road; the ball went into the window.",
             "untuk menyeberangi permukaan seperti jalan, padahal bolanya menembus jendela.",
             "ใช้กับการข้ามพื้นผิวอย่างถนน แต่ลูกบอลทะลุเข้าไปในหน้าต่าง"),
            ("along", L(ALONG_ENCL, "kata depan untuk menyusuri dipakai untuk bola yang menembus jendela.", "ใช้คำบุพบทของการเลียบไปตามแนวกับลูกบอลที่ทะลุหน้าต่าง"),
             "It is for following a line, like a street, not for breaking through glass.",
             "untuk menyusuri garis seperti jalan, bukan untuk menembus kaca.",
             "ใช้กับการเลียบไปตามแนวอย่างถนน ไม่ใช่การทะลุกระจก"),
            ("over", L(OVER_ENCL, "kata depan untuk lewat di atas dipakai untuk bola yang menembus jendela.", "ใช้คำบุพบทของการผ่านข้างบนกับลูกบอลที่ทะลุหน้าต่าง"),
             "It means above the window, so the glass would not break.",
             "artinya lewat di atas jendela, jadi kacanya nggak akan pecah.",
             "แปลว่าผ่านเหนือหน้าต่าง กระจกจึงไม่แตก")]),
    dict(s="movement_prepositions_through_across_along_over", id="A2-367",
         stem="The ball flew ___ my head and landed behind me.", opts=["over", "through", "across", "along"], ans="over",
         why=("The ball passed above my head, so we use over.",
              "Bolanya lewat di atas kepalaku, jadi pakai “over”.",
              "ลูกบอลลอยผ่านเหนือศีรษะของฉัน จึงใช้ 'over'"),
         others=("'Through' would mean going inside my head, 'across' is for crossing a surface, and 'along' follows a line.",
                 "“Through” berarti menembus kepala, “across” untuk menyeberangi permukaan, dan “along” untuk menyusuri garis.",
                 "'through' แปลว่าทะลุศีรษะ ส่วน 'across' ใช้กับการข้ามพื้นผิว และ 'along' ใช้กับการเลียบไปตามแนว"),
         cue=("Above and to the other side: over the wall, over my head.", "Lewat di atas lalu ke sisi lain: “over the wall”, “over my head”.", "ผ่านข้างบนไปอีกฝั่งใช้ 'over' เช่น 'over the wall'"),
         rsn=("notice landed behind me -> identify the path as above my head -> recall the word for passing above something",
              "perhatikan “landed behind me” → pastikan bolanya lewat di atas kepala → ingat kata depan untuk lewat di atas",
              "สังเกต 'landed behind me' → ดูว่าลูกบอลผ่านเหนือศีรษะ → นึกถึงคำบุพบทของการผ่านข้างบน"),
         d=[("through", THROUGH_ABOVE,
             "It would mean the ball went inside my head.",
             "berarti bolanya menembus kepalaku, padahal bolanya lewat di atas.",
             "แปลว่าลูกบอลทะลุศีรษะของฉัน แต่ลูกบอลผ่านไปข้างบน"),
            ("across", ACROSS_ABOVE,
             "It is for crossing a surface, like a road, not for passing above.",
             "untuk menyeberangi permukaan seperti jalan, bukan untuk lewat di atas.",
             "ใช้กับการข้ามพื้นผิวอย่างถนน ไม่ใช่การผ่านข้างบน"),
            ("along", ALONG_ABOVE,
             "It is for following a line, like a river, not for passing above.",
             "untuk menyusuri garis seperti sungai, bukan untuk lewat di atas.",
             "ใช้กับการเลียบไปตามแนวอย่างแม่น้ำ ไม่ใช่การผ่านข้างบน")]),
    dict(s="movement_prepositions_through_across_along_over", id="A2-368",
         stem="Go ___ this road until you see the big mosque.", opts=["along", "across", "through", "over"], ans="along",
         why=("You follow the road until you reach the mosque, so we use along.",
              "Kamu menyusuri jalan itu sampai ketemu masjid, jadi pakai “along”.",
              "คุณเดินไปตามถนนจนเห็นมัสยิด จึงใช้ 'along'"),
         others=("'Across' takes you to the other side, 'through' is for going inside something, and 'over' passes above.",
                 "“Across” membawamu ke seberang, “through” untuk menembus bagian dalam, dan “over” lewat di atas.",
                 "'across' พาไปอีกฝั่ง ส่วน 'through' ใช้กับการทะลุผ่านข้างใน และ 'over' ใช้กับการผ่านข้างบน"),
         cue=("Follow a line: along the road, along the river.", "Menyusuri garis: “along the road”, “along the river”.", "เลียบไปตามแนวใช้ 'along' เช่น 'along the river'"),
         rsn=("notice until you see -> identify the path as following the road -> recall the word for following a line",
              "perhatikan “until you see” → pastikan jalurnya menyusuri jalan → ingat kata depan untuk menyusuri garis",
              "สังเกต 'until you see' → ดูว่าเส้นทางไปตามถนน → นึกถึงคำบุพบทของการเลียบไปตามแนว"),
         d=[("across", L(ACROSS_LINE, "kata depan untuk menyeberang dipakai untuk menyusuri jalan.", "ใช้คำบุพบทของการข้ามกับการเดินไปตามถนน"),
             "It takes you to the other side of the road, not further along it.",
             "membawamu ke seberang jalan, bukan terus menyusurinya.",
             "พาข้ามไปอีกฝั่งของถนน ไม่ใช่เดินไปตามถนน"),
            ("through", L(THROUGH_LINE, "kata depan untuk menembus dipakai untuk menyusuri jalan.", "ใช้คำบุพบทของการทะลุผ่านกับการเดินไปตามถนน"),
             "It is for going inside something, like a tunnel; a road is an open line.",
             "untuk menembus bagian dalam seperti terowongan, padahal jalan itu garis terbuka.",
             "ใช้กับการทะลุผ่านข้างในอย่างอุโมงค์ แต่ถนนเป็นแนวเปิดโล่ง"),
            ("over", L(OVER_LINE, "kata depan untuk lewat di atas dipakai untuk menyusuri jalan.", "ใช้คำบุพบทของการผ่านข้างบนกับการเดินไปตามถนน"),
             "It is for passing above something, like a bridge over a road.",
             "untuk lewat di atas sesuatu, seperti jembatan di atas jalan.",
             "ใช้กับการผ่านข้างบนบางอย่าง เช่น สะพานที่อยู่เหนือถนน")]),
    # ---------------- 35. one negative only ----------------
    dict(s="double_negative_avoidance_single_negation_rule", id="A2-369",
         stem="Don't ask me. I ___ about cars.", opts=["know nothing", "don't know nothing", "know anything", "not know anything"], ans="know nothing",
         why=("Nothing is already negative, so the verb stays positive.",
              "“Nothing” sudah bermakna negatif, jadi kata kerjanya dibiarkan positif.",
              "'nothing' มีความหมายปฏิเสธอยู่แล้ว คำกริยาจึงอยู่ในรูปบอกเล่า"),
         others=("'Don't know nothing' has two negatives, 'know anything' has none, and 'not know anything' has no helper verb.",
                 "“Don't know nothing” punya dua negatif, “know anything” nggak punya negatif sama sekali, dan “not know anything” nggak punya kata bantu.",
                 "ตัวเลือกที่มีทั้ง 'don't' และ 'nothing' ปฏิเสธซ้ำสองครั้ง ตัวเลือกที่มีแค่ 'anything' ไม่มีคำปฏิเสธเลย และตัวเลือกที่ขึ้นต้นด้วย 'not' ไม่มีกริยาช่วย"),
         cue=("One negative only: know nothing = don't know anything.", "Negatifnya satu saja: “know nothing” = “don't know anything”.", "ใช้คำปฏิเสธคำเดียว 'know nothing' มีความหมายเท่ากับ 'don't know anything'"),
         rsn=("count the negative words in each option -> keep exactly one negative -> check that not has a helper verb",
              "hitung kata negatif di tiap pilihan → pertahankan tepat satu negatif → cek “not” punya kata bantu",
              "นับคำปฏิเสธในแต่ละตัวเลือก → ให้เหลือคำปฏิเสธแค่คำเดียว → ดูว่า 'not' มีกริยาช่วย"),
         d=[("don't know nothing", L(DOUBLE_NEG, "“don't” dan “nothing” dipakai bersamaan.", "ใช้ 'don't' กับ 'nothing' พร้อมกัน"),
             "It has two negatives, don't and nothing; English uses only one.",
             "punya dua negatif, “don't” dan “nothing”, padahal bahasa Inggris cuma memakai satu.",
             "มีคำปฏิเสธสองคำ คือ 'don't' และ 'nothing' แต่ภาษาอังกฤษใช้แค่คำเดียว"),
            ("know anything", N(ANY_POS, "“anything” dipakai di kalimat positif.", "ใช้ 'anything' ในประโยคบอกเล่า"),
             "It has no negative at all, so it cannot mean that I don't know.",
             "nggak punya negatif sama sekali, jadi nggak bisa berarti “aku nggak tahu apa-apa”.",
             "ไม่มีคำปฏิเสธเลย จึงไม่ได้แปลว่าฉันไม่รู้อะไร"),
            ("not know anything", N(NOT_NO_HELPER, "“not” dipakai tanpa “don't”.", "ใช้ 'not' โดยไม่มี 'don't'"),
             "It puts not without a helper verb; English needs don't.",
             "memakai “not” tanpa kata bantu, padahal bahasa Inggris butuh “don't”.",
             "ใช้ 'not' โดยไม่มีกริยาช่วย แต่ภาษาอังกฤษต้องใช้ 'don't'")]),
    dict(s="double_negative_avoidance_single_negation_rule", id="A2-370",
         stem="I called Dina's house, but ___ answered the phone.", opts=["nobody", "anybody", "no body", "not anybody"], ans="nobody",
         why=("Nobody is the subject and already negative, so answered stays positive.",
              "“Nobody” jadi subjek dan sudah bermakna negatif, jadi “answered” tetap positif.",
              "'nobody' เป็นประธานและมีความหมายปฏิเสธอยู่แล้ว 'answered' จึงอยู่ในรูปบอกเล่า"),
         others=("'Anybody' is not negative on its own, 'no body' is split into two words, and 'not anybody' cannot be the subject.",
                 "“Anybody” sendiri belum negatif, “no body” dipisah jadi dua kata, dan “not anybody” nggak bisa jadi subjek.",
                 "'anybody' ยังไม่มีความหมายปฏิเสธ ส่วน 'no body' แยกเป็นสองคำ และ 'not anybody' ใช้เป็นประธานไม่ได้"),
         cue=("As the subject: nobody, nothing.", "Di posisi subjek: “nobody”, “nothing”.", "ในตำแหน่งประธานใช้ 'nobody' หรือ 'nothing'"),
         rsn=("identify the blank as the subject of answered -> notice that answered is positive -> choose the one-word negative for people",
              "kenali titik-titik sebagai subjek “answered” → perhatikan “answered” berbentuk positif → pilih kata negatif satu kata untuk orang",
              "ดูว่าช่องว่างเป็นประธานของ 'answered' → สังเกตว่า 'answered' เป็นรูปบอกเล่า → เลือกคำปฏิเสธคำเดียวที่ใช้กับคน"),
         d=[("anybody", ANY_SUBJ,
             "It is not negative by itself, so the sentence would not mean no one answered.",
             "belum bermakna negatif, jadi kalimatnya nggak berarti “nggak ada yang mengangkat”.",
             "ยังไม่มีความหมายปฏิเสธ ประโยคจึงไม่ได้แปลว่าไม่มีใครรับสาย"),
            ("no body", L(SPLIT_NEG, "“nobody” dipecah jadi dua kata.", "แยก 'nobody' เป็นสองคำ"),
             "It splits one word into two, and the meaning becomes 'no physical body'.",
             "memecah satu kata jadi dua, dan artinya berubah jadi “nggak ada tubuh”.",
             "แยกคำเดียวเป็นสองคำ และความหมายกลายเป็นไม่มีร่างกาย"),
            ("not anybody", NOT_ANY_SUBJ,
             "It puts not in front of the subject; English uses one negative word there.",
             "menaruh “not” di depan subjek, padahal bahasa Inggris memakai satu kata negatif di posisi itu.",
             "วาง 'not' ไว้หน้าประธาน แต่ภาษาอังกฤษใช้คำปฏิเสธคำเดียวในตำแหน่งนี้")]),
    dict(s="double_negative_avoidance_single_negation_rule", id="A2-371",
         stem="My little brother never ___ his vegetables.", opts=["eats", "doesn't eat", "eat", "not eats"], ans="eats",
         why=("Never is already negative, and my little brother is he, so we use eats.",
              "“Never” sudah bermakna negatif, dan “my little brother” sama dengan “he”, jadi pakai “eats”.",
              "'never' มีความหมายปฏิเสธอยู่แล้ว และ 'my little brother' คือ 'he' จึงใช้ 'eats'"),
         others=("'Doesn't eat' adds a second negative, 'eat' forgets -s, and 'not eats' adds not without a helper.",
                 "“Doesn't eat” menambah negatif kedua, “eat” lupa -s, dan “not eats” menambah “not” tanpa kata bantu.",
                 "'doesn't eat' เติมคำปฏิเสธคำที่สอง ส่วน 'eat' ลืมเติม -s และ 'not eats' ใส่ 'not' โดยไม่มีกริยาช่วย"),
         cue=("Never + verb with -s: he never eats.", "“Never” + kata kerja ber-s: “he never eats”.", "หลัง 'never' คำกริยาของประธานเอกพจน์ยังต้องเติม -s"),
         rsn=("notice never -> recall that never is already negative -> add -s for he",
              "perhatikan “never” → ingat “never” sudah negatif → tambah -s untuk “he”",
              "สังเกต 'never' → นึกว่า 'never' เป็นคำปฏิเสธอยู่แล้ว → เติม -s ให้ 'he'"),
         d=[("doesn't eat", L(DOUBLE_NEG, "“never” dan “doesn't” dipakai bersamaan.", "ใช้ 'never' กับ 'doesn't' พร้อมกัน"),
             "It adds a second negative; never is already enough.",
             "menambah negatif kedua, padahal “never” saja sudah cukup.",
             "เติมคำปฏิเสธคำที่สอง ทั้งที่ 'never' คำเดียวก็พอ"),
            ("eat", L(BARE_AGR, "bentuk dasar dipakai untuk “my little brother”.", "ใช้รูปพื้นฐานกับ 'my little brother'"),
             "It forgets -s, but my little brother is he.",
             "lupa -s, padahal “my little brother” sama dengan “he”.",
             "ลืมเติม -s ทั้งที่ประธานเป็นน้องชายคนเดียว ซึ่งใช้เหมือน 'he'"),
            ("not eats", N(NOT_NO_HELPER, "“not” ditaruh sesudah “never” tanpa kata bantu.", "ใช้ 'not' หลัง 'never' โดยไม่มีกริยาช่วย"),
             "It adds not without a helper verb, and never already makes it negative.",
             "menambah “not” tanpa kata bantu, padahal “never” sudah membuatnya negatif.",
             "ใส่ 'not' โดยไม่มีกริยาช่วย ทั้งที่ 'never' ทำให้เป็นประโยคปฏิเสธแล้ว")]),
    dict(s="double_negative_avoidance_single_negation_rule", id="A2-372",
         stem="There aren't ___ buses after ten at night.", opts=["any", "no", "none", "some"], ans="any",
         why=("Aren't is already negative, so we use any, not a second negative.",
              "“Aren't” sudah negatif, jadi pakai “any”, bukan negatif kedua.",
              "'aren't' เป็นรูปปฏิเสธอยู่แล้ว จึงใช้ 'any' ไม่ใช้คำปฏิเสธคำที่สอง"),
         others=("'No' adds a second negative, 'none' cannot go before a noun, and 'some' is for positive sentences.",
                 "“No” menambah negatif kedua, “none” nggak bisa ditaruh sebelum kata benda, dan “some” untuk kalimat positif.",
                 "'no' เติมคำปฏิเสธคำที่สอง ส่วน 'none' วางหน้าคำนามไม่ได้ และ 'some' ใช้ในประโยคบอกเล่า"),
         cue=("Not + any: there aren't any buses = there are no buses.", "“Not” + “any”: “there aren't any buses” = “there are no buses”.", "ประโยคปฏิเสธที่มี 'not' ใช้คู่กับ 'any' ไม่ใช้ 'no'"),
         rsn=("notice the negative aren't -> recall that one negative is enough -> choose the word for negatives and questions",
              "perhatikan bentuk negatif “aren't” → ingat satu negatif sudah cukup → pilih kata untuk kalimat negatif dan tanya",
              "สังเกตรูปปฏิเสธ 'aren't' → นึกว่าคำปฏิเสธคำเดียวก็พอ → เลือกคำที่ใช้ในประโยคปฏิเสธและคำถาม"),
         d=[("no", L(NO_AFTER_NOT, "“no” dipakai sesudah “aren't”.", "ใช้ 'no' หลัง 'aren't'"),
             "It adds a second negative; with aren't, one is enough.",
             "menambah negatif kedua, padahal dengan “aren't” satu negatif sudah cukup.",
             "เติมคำปฏิเสธคำที่สอง ทั้งที่มี 'aren't' แล้วคำเดียวก็พอ"),
            ("none", NONE_NOUN,
             "It stands alone and cannot go before a noun like buses.",
             "dipakai sendirian, nggak bisa ditaruh sebelum kata benda seperti “buses”.",
             "ใช้ตามลำพัง วางหน้าคำนามอย่าง 'buses' ไม่ได้"),
            ("some", L(POS_Q_NEG, "“some” dipakai di kalimat negatif.", "ใช้ 'some' ในประโยคปฏิเสธ"),
             "It is for positive sentences, but aren't makes this one negative.",
             "untuk kalimat positif, padahal “aren't” membuat kalimat ini negatif.",
             "ใช้ในประโยคบอกเล่า แต่ 'aren't' ทำให้ประโยคนี้เป็นปฏิเสธ")]),
    # ---------------- 36. state verbs ----------------
    dict(s="state_verbs_resist_continuous_form", id="A2-373",
         stem="I ___ what you mean now. Thanks!", opts=["understand", "am understanding", "understanding", "understands"], ans="understand",
         why=("Understand is a state of mind, so it stays simple even with now.",
              "“Understand” itu keadaan pikiran, jadi tetap bentuk biasa walaupun ada “now”.",
              "'understand' เป็นสภาพในความคิด จึงใช้รูปธรรมดาแม้มีคำว่า 'now'"),
         others=("'Am understanding' uses -ing for a state, 'understanding' has no helper verb, and 'understands' adds -s after I.",
                 "“Am understanding” memakai -ing untuk keadaan, “understanding” nggak punya kata bantu, dan “understands” menambah -s untuk “I”.",
                 "ตัวเลือกที่มี 'am' ใช้ -ing กับสภาพ ส่วนตัวเลือกที่เป็นรูป -ing อย่างเดียวไม่มีกริยาช่วย และ 'understands' เติม -s ให้ 'I'"),
         cue=("Head and heart verbs stay simple: I understand, I know.", "Kata kerja pikiran dan perasaan tetap bentuk biasa: “I understand”, “I know”.", "คำกริยาเกี่ยวกับความคิดและความรู้สึกใช้รูปธรรมดา เช่น 'I know'"),
         rsn=("identify understand as a state of mind -> recall that states take no -ing -> choose the simple form for I",
              "kenali “understand” sebagai keadaan pikiran → ingat keadaan nggak memakai -ing → pilih bentuk biasa untuk “I”",
              "ดูว่า 'understand' เป็นสภาพในความคิด → นึกว่าสภาพไม่ใช้ -ing → เลือกรูปธรรมดาของ 'I'"),
         d=[("am understanding", L(PRES_CONT_ALWAYS, "bentuk -ing dipakai untuk kata kerja pikiran karena ada “now”.", "ใช้รูป -ing กับคำกริยาเกี่ยวกับความคิดเพราะมีคำว่า 'now'"),
             "It uses -ing because of now, but thinking verbs like this take no -ing.",
             "memakai -ing karena ada “now”, padahal kata kerja pikiran seperti ini nggak memakai -ing.",
             "ใช้ -ing เพราะมีคำว่า 'now' แต่คำกริยาเกี่ยวกับความคิดแบบนี้ไม่ใช้ -ing"),
            ("understanding", L(FRAGMENT, "bentuk -ing dipakai sendirian sesudah “I”.", "ใช้รูป -ing ตามลำพังหลัง 'I'"),
             "It has no helper verb, so it cannot be the verb of the sentence.",
             "nggak punya kata bantu, jadi nggak bisa jadi kata kerja kalimat.",
             "ไม่มีกริยาช่วย จึงเป็นคำกริยาของประโยคไม่ได้"),
            ("understands", N(S_AFTER_I, "akhiran -s ditambahkan ke kata kerja untuk “I”.", "เติม -s ให้คำกริยาของ 'I'"),
             "It adds -s, but the verb after I never takes -s.",
             "menambah -s, padahal kata kerja untuk “I” nggak pernah diberi -s.",
             "เติม -s แต่คำกริยาของ 'I' ไม่เคยเติม -s")]),
    dict(s="state_verbs_resist_continuous_form", id="A2-374",
         stem="My little sister ___ a new doll for her birthday.", opts=["wants", "is wanting", "want", "wanting"], ans="wants",
         why=("Want is a feeling, not an action, and my little sister is she, so we use wants.",
              "“Want” itu perasaan, bukan kegiatan, dan “my little sister” sama dengan “she”, jadi pakai “wants”.",
              "'want' เป็นความรู้สึก ไม่ใช่การกระทำ และ 'my little sister' คือ 'she' จึงใช้ 'wants'"),
         others=("'Is wanting' uses -ing for a feeling, 'want' forgets -s, and 'wanting' has no helper verb.",
                 "“Is wanting” memakai -ing untuk perasaan, “want” lupa -s, dan “wanting” nggak punya kata bantu.",
                 "'is wanting' ใช้ -ing กับความรู้สึก ส่วน 'want' ลืมเติม -s และ 'wanting' ไม่มีกริยาช่วย"),
         cue=("Want, need, like: no -ing. She wants.", "“Want”, “need”, “like”: tanpa -ing. “She wants”.", "คำกริยาบอกความต้องการอย่าง 'want' ไม่ใช้ -ing เช่น 'she wants'"),
         rsn=("identify want as a feeling -> recall that feelings take no -ing -> add -s for she",
              "kenali “want” sebagai perasaan → ingat perasaan nggak memakai -ing → tambah -s untuk “she”",
              "ดูว่า 'want' เป็นความรู้สึก → นึกว่าความรู้สึกไม่ใช้ -ing → เติม -s ให้ 'she'"),
         d=[("is wanting", L(WANT_PROG, "bentuk -ing dipakai untuk “want”.", "ใช้รูป -ing กับ 'want'"),
             "It uses -ing, but want is a feeling, not an action.",
             "memakai -ing, padahal “want” itu perasaan, bukan kegiatan.",
             "ใช้ -ing แต่ 'want' เป็นความรู้สึก ไม่ใช่การกระทำ"),
            ("want", L(BARE_AGR, "bentuk dasar dipakai untuk “my little sister”.", "ใช้รูปพื้นฐานกับ 'my little sister'"),
             "It forgets -s, but my little sister is she.",
             "lupa -s, padahal “my little sister” sama dengan “she”.",
             "ลืมเติม -s ทั้งที่ประธานเป็นน้องสาวคนเดียว ซึ่งใช้เหมือน 'she'"),
            ("wanting", L(FRAGMENT, "bentuk -ing dipakai sendirian sebagai kata kerja kalimat.", "ใช้รูป -ing ตามลำพังเป็นคำกริยาของประโยค"),
             "It is only an -ing form with no helper, so the sentence has no verb yet.",
             "cuma bentuk -ing tanpa kata bantu, jadi kalimatnya belum punya kata kerja.",
             "เป็นแค่รูป -ing ที่ไม่มีกริยาช่วย ประโยคจึงยังไม่มีคำกริยา")]),
    dict(s="state_verbs_resist_continuous_form", id="A2-375",
         stem="Rina ___ spicy food. She never eats sambal.", opts=["doesn't like", "isn't liking", "don't like", "not likes"], ans="doesn't like",
         why=("Like is a feeling, so there is no -ing, and the negative for she is doesn't like.",
              "“Like” itu perasaan, jadi tanpa -ing, dan bentuk negatif untuk “she” adalah “doesn't like”.",
              "'like' เป็นความรู้สึก จึงไม่ใช้ -ing และรูปปฏิเสธของ 'she' คือ 'doesn't like'"),
         others=("'Isn't liking' uses -ing for a feeling, 'don't like' is for I, you, we, and they, and 'not likes' has no helper verb.",
                 "“Isn't liking” memakai -ing untuk perasaan, “don't like” untuk “I”, “you”, “we”, “they”, dan “not likes” nggak punya kata bantu.",
                 "'isn't liking' ใช้ -ing กับความรู้สึก ส่วน 'don't like' ใช้กับ 'I', 'you', 'we', 'they' และ 'not likes' ไม่มีกริยาช่วย"),
         cue=("Feelings stay simple: she doesn't like, she loves.", "Perasaan tetap bentuk biasa: “she doesn't like”, “she loves”.", "ความรู้สึกใช้รูปธรรมดา เช่น 'she loves'"),
         rsn=("identify like as a feeling -> recall that feelings take no -ing -> choose the negative helper for she",
              "kenali “like” sebagai perasaan → ingat perasaan nggak memakai -ing → pilih kata bantu negatif untuk “she”",
              "ดูว่า 'like' เป็นความรู้สึก → นึกว่าความรู้สึกไม่ใช้ -ing → เลือกกริยาช่วยปฏิเสธของ 'she'"),
         d=[("isn't liking", L(PRES_CONT_ALWAYS, "bentuk -ing dipakai untuk “like”.", "ใช้รูป -ing กับ 'like'"),
             "It adds -ing to like, but feelings don't take -ing.",
             "memberi -ing pada “like”, padahal perasaan nggak memakai bentuk -ing.",
             "เติม -ing ให้ 'like' แต่ความรู้สึกไม่ใช้รูป -ing"),
            ("don't like", N(DONT_3SG, "“don't” dipakai untuk “Rina”.", "ใช้ 'don't' กับ 'Rina' ซึ่งเป็นคนเดียว"),
             "It is for I, you, we, and they, but Rina is she.",
             "untuk “I”, “you”, “we”, dan “they”, padahal Rina sama dengan “she”.",
             "ใช้กับประธานพหูพจน์หรือกับ 'I' และ 'you' แต่รีน่าเป็นคนเดียว ซึ่งใช้เหมือน 'she'"),
            ("not likes", N(NOT_NO_HELPER, "“not” dipakai tanpa “doesn't”.", "ใช้ 'not' โดยไม่มี 'doesn't'"),
             "It puts not with no helper verb; a negative with she needs doesn't.",
             "menaruh “not” tanpa kata bantu, padahal kalimat negatif untuk “she” butuh “doesn't”.",
             "ใส่ 'not' โดยไม่มีกริยาช่วย ประโยคปฏิเสธของ 'she' ต้องใช้ 'doesn't'")]),
    dict(s="state_verbs_resist_continuous_form", id="A2-376",
         stem="We ___ two cats and a dog at home.", opts=["have", "are having", "has", "are have"], ans="have",
         why=("Have here means own, which is a state, and we takes have.",
              "“Have” di sini artinya memiliki, yaitu keadaan, dan “we” pakai “have”.",
              "'have' ในที่นี้แปลว่ามี ซึ่งเป็นสภาพ และ 'we' ใช้ 'have'"),
         others=("'Are having' uses -ing for owning, 'has' is for he, she, and it, and 'are have' mixes are with have.",
                 "“Are having” memakai -ing untuk kepemilikan, “has” untuk “he”, “she”, “it”, dan “are have” mencampur “are” dengan “have”.",
                 "'are having' ใช้ -ing กับการเป็นเจ้าของ ส่วน 'has' ใช้กับประธานเอกพจน์ และ 'are have' ใส่ 'are' เกินมาหน้าคำกริยาหลัก"),
         cue=("Have for owning: no -ing. We have a cat.", "“Have” untuk memiliki: tanpa -ing. “We have a cat”.", "'have' ที่แปลว่ามีไม่ใช้ -ing เช่น 'we have a cat'"),
         rsn=("identify the verb as meaning own -> recall that owning is a state -> choose the simple form for we",
              "kenali kata kerjanya sebagai memiliki → ingat memiliki itu keadaan → pilih bentuk biasa untuk “we”",
              "ดูว่าคำกริยานี้แปลว่ามี → นึกว่าการมีเป็นสภาพ → เลือกรูปธรรมดาของ 'we'"),
         d=[("are having", L(PRES_CONT_ALWAYS, "bentuk -ing dipakai untuk kata kerja yang artinya memiliki.", "ใช้รูป -ing กับคำกริยาที่แปลว่ามี"),
             "It uses -ing, but here the verb means own, which is a state.",
             "memakai -ing, padahal kata kerja ini di sini artinya memiliki, yaitu keadaan.",
             "ใช้ -ing แต่คำกริยานี้ในที่นี้แปลว่ามี ซึ่งเป็นสภาพ"),
            ("has", N(HAS_PL, "“has” dipakai untuk “we”.", "ใช้ 'has' กับ 'we'"),
             "It is for he, she, or it, but the subject is we.",
             "untuk “he”, “she”, atau “it”, padahal subjeknya “we”.",
             "ใช้กับ 'he', 'she', 'it' แต่ประธานคือ 'we'"),
            ("are have", L(IS_MAIN, "“are” diselipkan di depan kata kerja utama.", "ใส่ 'are' ไว้หน้าคำกริยาหลัก"),
             "It puts are before the main verb; one verb is enough.",
             "menyelipkan “are” di depan kata kerja utama, padahal satu kata kerja sudah cukup.",
             "ใส่ 'are' ไว้หน้าคำกริยาหลัก ทั้งที่ใช้คำกริยาคำเดียวก็พอ")]),
    # ---------------- 37. for / since / during ----------------
    dict(s="preposition_of_time_duration_for_vs_since_vs_during", id="A2-377",
         stem="I have lived in this town ___ five years.", opts=["for", "since", "during", "while"], ans="for",
         why=("Five years is a length of time, so we use for.",
              "“Five years” itu lamanya waktu, jadi pakai “for”.",
              "'five years' เป็นระยะเวลา จึงใช้ 'for'"),
         others=("'Since' needs a starting point, 'during' needs an event, and 'while' needs a subject and verb after it.",
                 "“Since” butuh titik mulai, “during” butuh acara, dan “while” butuh subjek dan kata kerja sesudahnya.",
                 "'since' ต้องตามด้วยจุดเริ่มต้น ส่วน 'during' ต้องตามด้วยเหตุการณ์ และ 'while' ต้องตามด้วยประธานกับคำกริยา"),
         cue=("How long? for: for five years, for two hours.", "Berapa lama? “for”: “for five years”, “for two hours”.", "นานเท่าไรใช้ 'for' เช่น 'for two hours'"),
         rsn=("notice five years -> identify it as a length of time -> recall the word for how long",
              "perhatikan “five years” → pastikan itu lamanya waktu → ingat kata untuk menyebut berapa lama",
              "สังเกต 'five years' → ดูว่าเป็นระยะเวลา → นึกถึงคำที่บอกว่านานเท่าไร"),
         d=[("since", SINCE_LENGTH,
             "It needs a starting point, like 2020, not a length of time.",
             "butuh titik mulai seperti “2020”, bukan lamanya waktu.",
             "ต้องตามด้วยจุดเริ่มต้นอย่าง '2020' ไม่ใช่ระยะเวลา"),
            ("during", DURING_LENGTH,
             "It copies 'selama', but this word is for an event, not a number of years.",
             "meniru “selama”, padahal kata ini dipakai untuk acara, bukan untuk jumlah tahun.",
             "ใช้กับเหตุการณ์หรือช่วงหนึ่ง ไม่ใช่กับจำนวนปี"),
            ("while", L(WHILE_NP, "“while” dipakai sebelum “five years”.", "ใช้ 'while' หน้า 'five years'"),
             "It needs a subject and a verb after it, but five years is only a noun.",
             "butuh subjek dan kata kerja sesudahnya, padahal “five years” cuma kata benda.",
             "ต้องตามด้วยประธานกับคำกริยา แต่ 'five years' เป็นแค่คำนาม")]),
    dict(s="preposition_of_time_duration_for_vs_since_vs_during", id="A2-378",
         stem="We have been best friends ___ primary school.", opts=["since", "for", "during", "while"], ans="since",
         why=("Our friendship started in primary school and still continues, so we use since.",
              "Persahabatan kami mulai sejak SD dan masih berlanjut, jadi pakai “since”.",
              "มิตรภาพของเราเริ่มตั้งแต่ชั้นประถมและยังคงอยู่ จึงใช้ 'since'"),
         others=("'For' needs a length of time, 'during' does not reach up to now, and 'while' needs a subject and verb.",
                 "“For” butuh lamanya waktu, “during” nggak menjangkau sampai sekarang, dan “while” butuh subjek dan kata kerja.",
                 "'for' ต้องตามด้วยระยะเวลา ส่วน 'during' ไม่ได้ต่อเนื่องมาถึงตอนนี้ และ 'while' ต้องตามด้วยประธานกับคำกริยา"),
         cue=("Started then, still true now: since.", "Mulai waktu itu dan masih sampai sekarang: “since”.", "เริ่มตอนนั้นและยังเป็นอยู่ตอนนี้ใช้ 'since'"),
         rsn=("notice have been -> identify primary school as the starting point -> recall the word for when something started",
              "perhatikan “have been” → pastikan SD itu titik mulainya → ingat kata untuk menyebut sejak kapan",
              "สังเกต 'have been' → ดูว่าชั้นประถมเป็นจุดเริ่มต้น → นึกถึงคำที่บอกว่าตั้งแต่เมื่อไร"),
         d=[("for", L(FOR_POINT, "“for” dipakai untuk titik mulai.", "ใช้ 'for' กับจุดเริ่มต้น"),
             "It needs a length of time, like ten years, not a starting point.",
             "butuh lamanya waktu, misalnya sepuluh tahun, bukan titik mulai.",
             "ต้องตามด้วยระยะเวลา เช่น สิบปี ไม่ใช่จุดเริ่มต้น"),
            ("during", L(DURING_SINCE, "“during” dipakai untuk titik mulai yang berlanjut sampai sekarang.", "ใช้ 'during' กับจุดเริ่มต้นที่ต่อเนื่องมาถึงตอนนี้"),
             "It is for something inside a period, but the friendship still continues now.",
             "untuk hal yang terjadi di dalam satu masa, padahal persahabatannya masih berlanjut sampai sekarang.",
             "ใช้กับสิ่งที่เกิดภายในช่วงหนึ่ง แต่มิตรภาพยังดำเนินอยู่ถึงตอนนี้"),
            ("while", L(WHILE_NP, "“while” dipakai sebelum “primary school”.", "ใช้ 'while' หน้า 'primary school'"),
             "It needs a subject and a verb after it, but primary school is only a noun.",
             "butuh subjek dan kata kerja sesudahnya, padahal “primary school” cuma kata benda.",
             "ต้องตามด้วยประธานกับคำกริยา แต่ 'primary school' เป็นแค่คำนาม")]),
    dict(s="preposition_of_time_duration_for_vs_since_vs_during", id="A2-379",
         stem="My phone rang ___ the exam. I was so embarrassed!", opts=["during", "for", "since", "while"], ans="during",
         why=("The phone rang in the middle of the exam, so we use during + the exam.",
              "Deringnya terjadi di tengah ujian, jadi pakai “during” + “the exam”.",
              "โทรศัพท์ดังระหว่างการสอบ จึงใช้ 'during' + 'the exam'"),
         others=("'For' needs a length of time, 'since' needs a starting point, and 'while' needs a subject and verb.",
                 "“For” butuh lamanya waktu, “since” butuh titik mulai, dan “while” butuh subjek dan kata kerja.",
                 "'for' ต้องตามด้วยระยะเวลา ส่วน 'since' ต้องตามด้วยจุดเริ่มต้น และ 'while' ต้องตามด้วยประธานกับคำกริยา"),
         cue=("In the middle of an event: during the exam, during the film.", "Di tengah suatu acara: “during the exam”, “during the film”.", "ระหว่างเหตุการณ์ใช้ 'during' เช่น 'during the film'"),
         rsn=("notice the exam -> identify it as an event -> recall the word for in the middle of an event",
              "perhatikan “the exam” → pastikan itu sebuah acara → ingat kata untuk menyebut di tengah acara",
              "สังเกต 'the exam' → ดูว่าเป็นเหตุการณ์ → นึกถึงคำที่บอกว่าเกิดระหว่างเหตุการณ์"),
         d=[("for", L(FOR_POINT, "“for” dipakai untuk sebuah acara, bukan lamanya waktu.", "ใช้ 'for' กับเหตุการณ์ ไม่ใช่ระยะเวลา"),
             "It needs a length of time, like an hour; the exam is an event.",
             "butuh lamanya waktu, misalnya satu jam, padahal “the exam” itu acara.",
             "ต้องตามด้วยระยะเวลา เช่น หนึ่งชั่วโมง แต่ 'the exam' เป็นเหตุการณ์"),
            ("since", L(SINCE_DURING, "“since” dipakai untuk kejadian di tengah ujian.", "ใช้ 'since' กับเหตุการณ์ที่เกิดระหว่างการสอบ"),
             "It marks when something started, but the phone rang in the middle of the exam.",
             "menandai kapan sesuatu mulai, padahal ponselnya berdering di tengah ujian.",
             "ใช้บอกจุดเริ่มต้น แต่โทรศัพท์ดังระหว่างการสอบ"),
            ("while", L(WHILE_NP, "“while” dipakai sebelum “the exam”.", "ใช้ 'while' หน้า 'the exam'"),
             "It needs a subject and a verb after it, but the exam is only a noun.",
             "butuh subjek dan kata kerja sesudahnya, padahal “the exam” cuma kata benda.",
             "ต้องตามด้วยประธานกับคำกริยา แต่ 'the exam' เป็นแค่คำนาม")]),
    dict(s="preposition_of_time_duration_for_vs_since_vs_during", id="A2-380",
         stem="I have been sick ___ Monday, so I missed two days of school.", opts=["since", "for", "during", "from"], ans="since",
         why=("The sickness started on Monday and I am still sick, so we use since.",
              "Sakitnya mulai hari Senin dan sampai sekarang masih sakit, jadi pakai “since”.",
              "เริ่มป่วยตั้งแต่วันจันทร์และตอนนี้ยังป่วยอยู่ จึงใช้ 'since'"),
         others=("'For' needs a length of time, 'during' is for inside an event, and 'from' is not used alone for a start that continues until now.",
                 "“For” butuh lamanya waktu, “during” untuk hal di dalam satu acara, dan “from” nggak dipakai sendirian untuk titik mulai yang berlanjut sampai sekarang.",
                 "'for' ต้องตามด้วยระยะเวลา ส่วน 'during' ใช้กับสิ่งที่เกิดภายในเหตุการณ์ และ 'from' ไม่ใช้ตามลำพังกับจุดเริ่มต้นที่ต่อเนื่องมาถึงตอนนี้"),
         cue=("have been + since + the start: since Monday, since 2020.", "“Have been” + “since” + titik mulai: “since Monday”, “since 2020”.", "ประโยคที่มี 'have been' ใช้ 'since' กับจุดเริ่มต้น"),
         rsn=("notice have been and Monday -> check that the sickness is still going on -> choose the word for a starting point",
              "perhatikan “have been” dan “Monday” → cek sakitnya masih berlangsung → pilih kata untuk titik mulai",
              "สังเกต 'have been' และ 'Monday' → ดูว่ายังป่วยอยู่ → เลือกคำที่ใช้กับจุดเริ่มต้น"),
         d=[("for", L(FOR_POINT, "“for” dipakai untuk hari Senin, sebuah titik waktu.", "ใช้ 'for' กับวันจันทร์ซึ่งเป็นจุดเวลา"),
             "It needs a length of time, like three days, not the name of a day.",
             "butuh lamanya waktu, misalnya tiga hari, bukan nama hari.",
             "ต้องตามด้วยระยะเวลา เช่น สามวัน ไม่ใช่ชื่อวัน"),
            ("during", L(DURING_SINCE, "“during” dipakai untuk titik mulai sakit yang berlanjut sampai sekarang.", "ใช้ 'during' กับจุดที่เริ่มป่วยซึ่งยังต่อเนื่องมาถึงตอนนี้"),
             "It is for something inside a period, not for when the sickness started.",
             "untuk hal di dalam satu masa, bukan untuk kapan sakitnya mulai.",
             "ใช้กับสิ่งที่เกิดภายในช่วงหนึ่ง ไม่ใช่จุดที่เริ่มป่วย"),
            ("from", FROM_SINCE,
             "It is not used alone for a start that continues until now.",
             "nggak dipakai sendirian untuk titik mulai yang masih berlanjut sampai sekarang.",
             "ไม่ใช้ตามลำพังกับจุดเริ่มต้นที่ยังต่อเนื่องมาถึงตอนนี้")]),
    # ---------------- 38. subject vs object questions ----------------
    dict(s="subject_vs_object_questions_word_order", id="A2-381",
         stem="Who ___ you to school every day?", opts=["takes", "does take", "take", "does takes"], ans="takes",
         why=("Who is the doer here, so there is no does, and who works like he.",
              "“Who” di sini pelakunya, jadi tanpa “does”, dan “who” diperlakukan seperti “he”.",
              "'who' ในที่นี้เป็นผู้กระทำ จึงไม่ต้องใช้ 'does' และ 'who' ใช้เหมือน 'he'"),
         others=("'Does take' adds does to a doer question, 'take' forgets -s, and 'does takes' uses does and -s together.",
                 "“Does take” menambah kata bantu ke pertanyaan tentang pelaku, “take” lupa -s, dan “does takes” memakai kata bantu dan -s sekaligus.",
                 "'does take' เติม 'does' ในคำถามเรื่องผู้กระทำ ส่วน 'take' ลืมเติม -s และ 'does takes' ใช้ 'does' กับ -s พร้อมกัน"),
         cue=("Who is the doer? Who + verb with -s: Who takes you?", "“Who” pelakunya? “Who” + kata kerja ber-s: “Who takes you?”", "ถ้า 'who' เป็นผู้กระทำ ใช้ 'who' + คำกริยาเติม -s"),
         rsn=("identify who as the doer -> remove does from the question -> add -s as for he",
              "kenali “who” sebagai pelaku → buang “does” dari pertanyaannya → tambah -s seperti untuk “he”",
              "ดูว่า 'who' เป็นผู้กระทำ → ตัด 'does' ออกจากคำถาม → เติม -s เหมือนกับ 'he'"),
         d=[("does take", L(DID_SUBJ, "“does” ditambahkan, padahal “who” di sini subjeknya.", "เติม 'does' ทั้งที่ 'who' เป็นประธาน"),
             "It adds does, but who is the doer, so no helper is needed.",
             "menambah “does”, padahal “who” di sini pelakunya, jadi nggak perlu kata bantu.",
             "เติม 'does' แต่ 'who' เป็นผู้กระทำ จึงไม่ต้องใช้กริยาช่วย"),
            ("take", L(BARE_AGR, "bentuk dasar dipakai untuk “who”.", "ใช้รูปพื้นฐานกับ 'who'"),
             "It forgets -s; who as the doer works like he.",
             "lupa -s, padahal “who” sebagai pelaku diperlakukan seperti “he”.",
             "ลืมเติม -s แต่ 'who' ที่เป็นผู้กระทำใช้เหมือน 'he'"),
            ("does takes", DOES_S,
             "It uses does and -s together, and who needs no does here.",
             "memakai “does” dan -s sekaligus, padahal di sini “who” nggak butuh “does”.",
             "ใช้ 'does' กับ -s พร้อมกัน และ 'who' ในที่นี้ไม่ต้องใช้ 'does'")]),
    dict(s="subject_vs_object_questions_word_order", id="A2-382",
         stem="What ___ for dinner yesterday?", opts=["did you eat", "you ate", "did you ate", "do you eat"], ans="did you eat",
         why=("What is the food, not the eater, so we need did + you + the base verb.",
              "“What” di sini makanannya, bukan yang makan, jadi butuh “did” + “you” + kata kerja dasar.",
              "'what' ในที่นี้คืออาหาร ไม่ใช่คนกิน จึงต้องใช้ 'did' + 'you' + คำกริยารูปพื้นฐาน"),
         others=("'You ate' has no did, 'did you ate' marks the past twice, and 'do you eat' is present.",
                 "“You ate” nggak punya “did”, “did you ate” menandai lampau dua kali, dan “do you eat” bentuk sekarang.",
                 "'you ate' ไม่มี 'did' ส่วน 'did you ate' บอกอดีตซ้ำสองครั้ง และ 'do you eat' เป็นรูปปัจจุบัน"),
         cue=("Asking about the object: did + subject + base verb.", "Menanyakan objek: “did” + subjek + kata kerja dasar.", "ถ้าถามถึงกรรม ใช้ 'did' + ประธาน + คำกริยารูปพื้นฐาน"),
         rsn=("identify what as the food eaten -> notice yesterday -> combine did with you and the base verb",
              "kenali “what” sebagai makanan yang dimakan → perhatikan “yesterday” → gabungkan “did” dengan “you” dan kata kerja dasar",
              "ดูว่า 'what' คืออาหารที่ถูกกิน → สังเกต 'yesterday' → รวม 'did' กับ 'you' และคำกริยารูปพื้นฐาน"),
         d=[("you ate", L(NO_DID_OBJ, "“did” hilang dari pertanyaan tentang objek.", "ไม่มี 'did' ในคำถามที่ถามถึงกรรม"),
             "It has no did; a question about the food needs it.",
             "nggak punya “did”, padahal pertanyaan tentang makanannya membutuhkannya.",
             "ไม่มี 'did' แต่คำถามที่ถามถึงอาหารต้องมี 'did'"),
            ("did you ate", L(DID_PAST, "“did” dan “ate” dipakai bersamaan.", "ใช้ 'did' กับ 'ate' พร้อมกัน"),
             "It marks the past twice; after did, use the base verb.",
             "menandai lampau dua kali, padahal sesudah “did” kata kerjanya bentuk dasar.",
             "บอกอดีตซ้ำสองครั้ง แต่หลัง 'did' ต้องใช้คำกริยารูปพื้นฐาน"),
            ("do you eat", L(DOES_PAST, "kata bantu bentuk sekarang dipakai untuk “yesterday”.", "ใช้กริยาช่วยรูปปัจจุบันกับ 'yesterday'"),
             "It is present, but yesterday is in the past.",
             "bentuk sekarang, padahal “yesterday” sudah lewat.",
             "เป็นรูปปัจจุบัน แต่ 'yesterday' ผ่านไปแล้ว")]),
    dict(s="subject_vs_object_questions_word_order", id="A2-383",
         stem="What ___ to your arm? It's all red.", opts=["happened", "did happen", "was happened", "happen"], ans="happened",
         why=("What is the subject here, the thing that happened, so no did is needed.",
              "“What” di sini subjeknya, yaitu hal yang terjadi, jadi nggak perlu “did”.",
              "'what' ในที่นี้เป็นประธาน คือสิ่งที่เกิดขึ้น จึงไม่ต้องใช้ 'did'"),
         others=("'Did happen' adds did to a subject question, 'was happened' adds was, and 'happen' is not past.",
                 "“Did happen” menambah “did” ke pertanyaan tentang subjek, “was happened” menambah “was”, dan “happen” bukan bentuk lampau.",
                 "'did happen' เติม 'did' ในคำถามที่ถามถึงประธาน ส่วน 'was happened' เติม 'was' และ 'happen' ไม่ใช่รูปอดีต"),
         cue=("What happened? No did, no was.", "“What happened?” tanpa “did”, tanpa “was”.", "ถามว่าเกิดอะไรขึ้นใช้ 'What happened?' โดยไม่ต้องมี 'did' หรือ 'was'"),
         rsn=("identify what as the thing that happened -> recall that subject questions need no did -> choose the past form of happen",
              "kenali “what” sebagai hal yang terjadi → ingat pertanyaan tentang subjek nggak butuh “did” → pilih bentuk lampau dari “happen”",
              "ดูว่า 'what' คือสิ่งที่เกิดขึ้น → นึกว่าคำถามที่ถามถึงประธานไม่ต้องใช้ 'did' → เลือกรูปอดีตของ 'happen'"),
         d=[("did happen", L(DID_SUBJ, "“did” ditambahkan, padahal “what” di sini subjeknya.", "เติม 'did' ทั้งที่ 'what' เป็นประธาน"),
             "It adds did, but what is the subject here.",
             "menambah “did”, padahal “what” di sini subjeknya.",
             "เติม 'did' แต่ 'what' ในที่นี้เป็นประธาน"),
            ("was happened", WAS_HAPPENED,
             "It adds was; happen never takes was in the past.",
             "menambah “was”, padahal “happen” nggak pernah memakai “was” untuk bentuk lampau.",
             "เติม 'was' แต่ 'happen' ไม่เคยใช้ 'was' ในรูปอดีต"),
            ("happen", L(BARE_PAST, "bentuk sekarang dipakai untuk kejadian yang sudah lewat.", "ใช้รูปปัจจุบันกับเหตุการณ์ที่ผ่านไปแล้ว"),
             "It is not past, but the arm is red because of something that is already over.",
             "bukan bentuk lampau, padahal lengannya merah karena kejadiannya sudah lewat.",
             "ไม่ใช่รูปอดีต แต่แขนแดงเพราะเรื่องเกิดขึ้นไปแล้ว")]),
    dict(s="subject_vs_object_questions_word_order", id="A2-384",
         stem="Doni wants to call someone. Who ___ to call?", opts=["does he want", "he wants", "does he wants", "wants"], ans="does he want",
         why=("We know Doni is the caller; who asks about the person he calls, so we need does + he + want.",
              "Kita sudah tahu Doni yang mau menelepon; “who” menanyakan orang yang ditelepon, jadi butuh “does” + “he” + “want”.",
              "เรารู้แล้วว่าดอนนี่เป็นคนโทร 'who' ถามถึงคนที่จะถูกโทรหา จึงต้องใช้ 'does' + 'he' + 'want'"),
         others=("'He wants' has no does, 'does he wants' uses does and -s together, and 'wants' asks who wants to call.",
                 "“He wants” nggak punya “does”, “does he wants” memakai “does” dan -s sekaligus, dan “wants” malah menanyakan siapa yang mau menelepon.",
                 "'he wants' ไม่มี 'does' ส่วน 'does he wants' ใช้ 'does' กับ -s พร้อมกัน และ 'wants' กลายเป็นถามว่าใครอยากโทร"),
         cue=("Asking about the receiver: Who does he want to call?", "Menanyakan penerima: “Who does he want to call?”", "ถ้าถามถึงผู้ถูกกระทำ ต้องมี 'does' ตามหลัง 'who'"),
         rsn=("identify who as the person being called -> recall that questions about the receiver need does -> keep want in its base form after does",
              "kenali “who” sebagai orang yang ditelepon → ingat pertanyaan tentang penerima butuh “does” → pastikan “want” tetap bentuk dasar sesudah “does”",
              "ดูว่า 'who' คือคนที่ถูกโทรหา → นึกว่าคำถามเรื่องผู้รับต้องใช้ 'does' → ให้ 'want' เป็นรูปพื้นฐานหลัง 'does'"),
         d=[("he wants", L(NO_DID_OBJ, "“does” hilang dari pertanyaan tentang penerima.", "ไม่มี 'does' ในคำถามที่ถามถึงผู้รับ"),
             "It has no does; a question about the person called needs it.",
             "nggak punya “does”, padahal pertanyaan tentang orang yang ditelepon membutuhkannya.",
             "ไม่มี 'does' แต่คำถามที่ถามถึงคนที่ถูกโทรหาต้องมี 'does'"),
            ("does he wants", DOES_S,
             "It uses does and -s together; after does, want has no -s.",
             "memakai “does” dan -s sekaligus, padahal sesudah “does” kata “want” nggak diberi -s.",
             "ใช้ 'does' กับ -s พร้อมกัน แต่หลัง 'does' คำว่า 'want' ไม่เติม -s"),
            ("wants", L(OBJ_AS_SUBJ, "pertanyaan tentang penerima diubah jadi pertanyaan tentang pelaku.", "เปลี่ยนคำถามเรื่องผู้รับให้เป็นคำถามเรื่องผู้กระทำ"),
             "It asks who wants to call, but we already know it is Doni.",
             "menanyakan siapa yang mau menelepon, padahal kita sudah tahu orangnya Doni.",
             "กลายเป็นถามว่าใครอยากโทร แต่เรารู้แล้วว่าเป็นดอนนี่")]),
]
