#!/usr/bin/env python3
import sys
p='/app/features/speaking-listening/fiezel-speaking-listening-addon.js';s=open(p,encoding='utf-8').read()
R=[]
def rep(old,new):R.append((old,new))

rep("})(typeof self!=='undefined'?self:this,function(global){\n  'use strict';",
"})(typeof self!=='undefined'?self:this,function(global){\n  'use strict';\n  // UI strings resolve through the shared FIEZEL catalogue; without it (unit tests) the key is returned unchanged.\n  const i18n=()=>global.FiezelI18n||null;\n  const tr=(key,params)=>{const api=i18n();return api?api.t(key,params):key};\n  const trHas=key=>{const api=i18n();return api?api.has(key):false};\n  const modeLabel=mode=>trHas(`sl.mode.${mode}`)?tr(`sl.mode.${mode}`):mode;\n  const instructionFor=item=>trHas(`sl.instruction.${item.id}`)?tr(`sl.instruction.${item.id}`):item.instruction;\n  const listeningQuestion=item=>item.mode==='dictation'&&trHas('sl.dictationQuestion')?tr('sl.dictationQuestion'):item.question;")
rep("""<span class="fsl-kicker">FIEZEL SKILLS LAB</span><h1>Speaking + Listening</h1><p>Latihan suara dengan data terisolasi. Speaking mengukur target-language coverage, bukan pronunciation.</p></div></div><div class="fsl-grid"><article class="fsl-card"><span class="fsl-kicker">Listening</span><h2>Dengar lalu pahami</h2><p>Gist, detail, dan dictation. Jawaban baru aktif setelah audio berhasil diputar dan raw dictation tidak disimpan.</p><div class="fsl-actions"><button class="fsl-primary" data-open="listening">Mulai Listening</button></div></article><article class="fsl-card"><span class="fsl-kicker">Speaking</span><h2>Ucapkan dan respons</h2><p>${c.speechRecognition?'Speech recognition tersedia untuk target-language coverage.':'Speech recognition tidak tersedia; mode rekam-dengar mandiri tetap dapat dipakai jika microphone recording tersedia.'}</p><div class="fsl-actions"><button class="fsl-primary" data-open="speaking">Mulai Speaking</button></div></article></div><article class="fsl-card"><span class="fsl-kicker">Capability gate</span><div class="fsl-status">Audio output: <b>${c.neuralVoice?'neural ready':'neural belum diunduh'}</b> · Speech recognition: <b>${c.speechRecognition?'ready':'unavailable'}</b> · Recorder: <b>${c.mediaRecorder?'ready':'unavailable'}</b> · Secure context: <b>${c.secureContext?'yes':'no'}</b></div><p class="fsl-privacy">Browser speech recognition dapat melibatkan layanan pengenal milik browser. FIEZEL tidak menyimpan raw audio, transcript, atau jawaban dictation.</p></article><article class="fsl-card"><span class="fsl-kicker">Evidence lokal</span><p>Listening: <b>${ev.domains.listening.attempts}</b> attempt · average ${ev.domains.listening.averageScore??'-'}%. Speaking: <b>${ev.domains.speaking.attempts}</b> attempt · average ${ev.domains.speaking.averageScore??'-'}%.</p></article></section>`;""",
"""<span class="fsl-kicker">${esc(tr('sl.kicker'))}</span><h1 data-testid="skills-lab-title">${esc(tr('sl.title'))}</h1><p>${esc(tr('sl.subtitle'))}</p></div></div><div class="fsl-grid"><article class="fsl-card"><span class="fsl-kicker">${esc(tr('sl.listening'))}</span><h2>${esc(tr('sl.listening.title'))}</h2><p>${esc(tr('sl.listening.body'))}</p><div class="fsl-actions"><button class="fsl-primary" data-open="listening" data-testid="skills-lab-start-listening">${esc(tr('sl.listening.start'))}</button></div></article><article class="fsl-card"><span class="fsl-kicker">${esc(tr('sl.speaking'))}</span><h2>${esc(tr('sl.speaking.title'))}</h2><p>${esc(tr(c.speechRecognition?'sl.speaking.recognitionOn':'sl.speaking.recognitionOff'))}</p><div class="fsl-actions"><button class="fsl-primary" data-open="speaking" data-testid="skills-lab-start-speaking">${esc(tr('sl.speaking.start'))}</button></div></article></div><article class="fsl-card"><span class="fsl-kicker">${esc(tr('sl.capability'))}</span><div class="fsl-status">${tr('sl.cap.line',{audio:esc(tr(c.neuralVoice?'sl.cap.neuralReady':'sl.cap.neuralMissing')),sr:esc(tr(c.speechRecognition?'sl.cap.ready':'sl.cap.unavailable')),rec:esc(tr(c.mediaRecorder?'sl.cap.ready':'sl.cap.unavailable')),secure:esc(tr(c.secureContext?'sl.cap.yes':'sl.cap.no'))})}</div><p class="fsl-privacy">${esc(tr('sl.privacy'))}</p></article><article class="fsl-card"><span class="fsl-kicker">${esc(tr('sl.evidence'))}</span><p>${tr('sl.evidenceLine',{la:ev.domains.listening.attempts,ls:ev.domains.listening.averageScore??'-',sa:ev.domains.speaking.attempts,ss:ev.domains.speaking.averageScore??'-'})}</p></article></section>`;""")
rep("""<span class="fsl-kicker">${esc(domain)}</span><h2>Pilih level</h2>""","""<span class="fsl-kicker">${esc(tr(domain==='listening'?'sl.listening':'sl.speaking'))}</span><h2>${esc(tr('sl.pickLevel'))}</h2>""")
rep("""<div class="fsl-actions"><button data-back>Kembali</button></div></article></section>`;this.root.querySelectorAll?.('[data-level]')""","""<div class="fsl-actions"><button data-back>${esc(tr('sl.back'))}</button></div></article></section>`;this.root.querySelectorAll?.('[data-level]')""")
rep("""<span class="fsl-kicker">Listening · ${esc(item.level)} · ${esc(item.mode)}</span><h2>${esc(item.question)}</h2><p class="fsl-privacy">Script disembunyikan sampai jawaban dinilai. Jawaban terkunci sampai audio berhasil diputar.</p><div class="fsl-actions"><button class="fsl-primary" data-play>Dengarkan</button><button data-exit>Keluar</button></div><fieldset class="fsl-work" data-work disabled>${isDict?'<input class="fsl-input" data-dictation autocomplete="off" spellcheck="false" placeholder="Ketik yang kamu dengar…"><div class="fsl-actions"><button class="fsl-primary" data-submit>Nilai jawaban</button></div>':""",
"""<span class="fsl-kicker">${esc(tr('sl.listening'))} · ${esc(item.level)} · ${esc(modeLabel(item.mode))}</span><h2 data-testid="listening-question">${esc(listeningQuestion(item))}</h2><p class="fsl-privacy">${esc(tr('sl.scriptHidden'))}</p><div class="fsl-actions"><button class="fsl-primary" data-play data-testid="listening-play">${esc(tr('sl.listen'))}</button><button data-exit>${esc(tr('sl.exit'))}</button></div><fieldset class="fsl-work" data-work disabled>${isDict?`<input class="fsl-input" data-dictation autocomplete="off" spellcheck="false" placeholder="${esc(tr('sl.dictationPlaceholder'))}"><div class="fsl-actions"><button class="fsl-primary" data-submit>${esc(tr('sl.grade'))}</button></div>`:""")
rep("this.setFeedback('Batas replay untuk item ini sudah tercapai.');return}","this.setFeedback(tr('sl.replayLimit'));return}")
rep("this.setFeedback(`Audio siap · replay ${this.replays}/${Number(item.maxReplays||this.config.maxListeningReplays)}.`)}catch{this.store.noteCapability('tts','unavailable');this.setFeedback('Audio tidak tersedia. Item listening ini tetap terkunci dan tidak dinilai.')}",
"this.setFeedback(tr('sl.audioReady',{n:this.replays,max:Number(item.maxReplays||this.config.maxListeningReplays)}))}catch{this.store.noteCapability('tts','unavailable');this.setFeedback(tr('sl.audioUnavailable'))}")
rep("""<span class="fsl-kicker">Speaking · ${esc(item.level)} · ${esc(item.mode)}</span><h2>${esc(item.instruction)}</h2>${item.targetText?`<p class="fsl-prompt">${esc(item.targetText)}</p>`:''}<p class="fsl-privacy">Penilaian otomatis hanya spoken production / target coverage. Ini bukan pengukuran phoneme/pronunciation.</p><div class="fsl-actions">${c.speechRecognition?'<button class="fsl-primary" data-recognize>Mulai bicara</button>':''}${c.mediaRecorder?'<button data-record>Rekam untuk dengar ulang</button>':''}<button data-exit>Keluar</button></div><div data-rec-status class="fsl-status">${c.speechRecognition?'Siap mendengar respons.':'Speech recognition tidak tersedia; gunakan rekam-dengar mandiri tanpa skor otomatis.'}</div>""",
"""<span class="fsl-kicker">${esc(tr('sl.speaking'))} · ${esc(item.level)} · ${esc(modeLabel(item.mode))}</span><h2 data-testid="speaking-instruction">${esc(instructionFor(item))}</h2>${item.targetText?`<p class="fsl-prompt">${esc(item.targetText)}</p>`:''}<p class="fsl-privacy">${esc(tr('sl.scoringNote'))}</p><div class="fsl-actions">${c.speechRecognition?`<button class="fsl-primary" data-recognize data-testid="speaking-start">${esc(tr('sl.speak'))}</button>`:''}${c.mediaRecorder?`<button data-record>${esc(tr('sl.record'))}</button>`:''}<button data-exit>${esc(tr('sl.exit'))}</button></div><div data-rec-status class="fsl-status">${esc(tr(c.speechRecognition?'sl.readyToListen':'sl.noRecognition'))}</div>""")
rep("this.root.querySelector('[data-rec-status]').textContent='Mendengarkan…';","this.root.querySelector('[data-rec-status]').textContent=tr('sl.listening…');")
rep("this.root.querySelector('[data-rec-status]').textContent='Respons diterima. Transcript hanya dipakai sementara untuk penilaian.';","this.root.querySelector('[data-rec-status]').textContent=tr('sl.received');")
rep("this.root.querySelector('[data-rec-status]').textContent=`Tidak dapat menilai otomatis: ${esc(err.message)}.`;","this.root.querySelector('[data-rec-status]').textContent=tr('sl.cannotScore',{message:err.message});")
rep("btn.dataset.active='0';btn.textContent='Rekam untuk dengar ulang';","btn.dataset.active='0';btn.textContent=tr('sl.record');")
rep("""<p class="fsl-privacy">Audio hanya berada di memory browser dan URL blob sementara; tidak disimpan ke state.</p>`}""","""<p class="fsl-privacy">${esc(tr('sl.clipNote'))}</p>`}""")
rep("btn.dataset.active='1';btn.textContent='Stop rekaman';","btn.dataset.active='1';btn.textContent=tr('sl.stopRecord');")
rep("this.setFeedback('Microphone recording tidak tersedia atau izin ditolak.')}}})","this.setFeedback(tr('sl.micUnavailable'))}}})")
rep("const label=result.passed?'Lolos target item':'Belum mencapai target item';const note=this.domain==='speaking'?`Skor ${result.score}% hanya mengukur ${result.metric.replace(/_/g,' ')}; bukan pronunciation.`:`Skor ${result.score}%.`;",
"const label=tr(result.passed?'sl.passed':'sl.notPassed');const note=this.domain==='speaking'?tr('sl.speakingScore',{score:result.score,metric:result.metric.replace(/_/g,' ')}):tr('sl.score',{score:result.score});")
rep("""<strong>${label}</strong><span>${esc(note)}</span>${this.domain==='listening'?`<p><b>Script:</b> ${esc(item.script)}</p>`:`<p><b>Contoh respons:</b> ${esc(item.sampleAnswer||item.targetText||'')}</p>`}<div class="fsl-actions"><button class="fsl-primary" data-next>Lanjut</button></div></div>`;""",
"""<strong data-testid="skills-lab-result">${esc(label)}</strong><span>${esc(note)}</span>${this.domain==='listening'?`<p><b>${esc(tr('sl.script'))}</b> ${esc(item.script)}</p>`:`<p><b>${esc(tr('sl.sampleAnswer'))}</b> ${esc(item.sampleAnswer||item.targetText||'')}</p>`}<div class="fsl-actions"><button class="fsl-primary" data-next data-testid="skills-lab-next">${esc(tr('sl.next'))}</button></div></div>`;""")
rep("""<span class="fsl-kicker">Session complete</span><h2>${this.domain==='listening'?'Listening':'Speaking'} selesai</h2><p>Evidence sidecar saat ini: ${d.attempts} attempt · average ${d.averageScore??'-'}% · pass rate ${d.passRate??'-'}%.</p><p class="fsl-privacy">Tidak ada raw audio, transcript, atau jawaban dictation yang disimpan di state.</p><div class="fsl-actions"><button class="fsl-primary" data-home>Kembali ke lab</button></div>""",
"""<span class="fsl-kicker">${esc(tr('sl.complete'))}</span><h2>${esc(tr('sl.completeTitle',{domain:tr(this.domain==='listening'?'sl.listening':'sl.speaking')}))}</h2><p>${esc(tr('sl.completeBody',{attempts:d.attempts,avg:d.averageScore??'-',pass:d.passRate??'-'}))}</p><p class="fsl-privacy">${esc(tr('sl.completePrivacy'))}</p><div class="fsl-actions"><button class="fsl-primary" data-home>${esc(tr('sl.backToLab'))}</button></div>""")

for old,new in R:
    n=s.count(old)
    if n!=1:
        print('FAIL',n,old[:100]);sys.exit(1)
    s=s.replace(old,new)
open(p,'w',encoding='utf-8').write(s)
print('ok',len(R))
