#!/usr/bin/env python3
import sys
p='/app/app.js';s=open(p,encoding='utf-8').read()
R=[]
def rep(old,new):R.append((old,new))

# vocab hub
rep("shell('Vocabulary Hub',`${V.length.toLocaleString()} kata aktif dan sudah melewati filter QA.`,`<div class=\"toolbar\"><button class=\"primary\" onclick=\"startVocabQuiz()\"><i data-lucide=\"circle-play\"></i> Uji Vocabulary</button><button onclick=\"reviewVocab()\"><i data-lucide=\"history\"></i> Review Due (${Object.values(state.vocab).filter(x=>x.nextReview&&x.nextReview<=Date.now()&&x.mastery<80).length})</button></div><div class=\"grid\">${LEVELS.map(l=>card(`<div class=\"row\"><b>${l}</b><span>${counts[l]||0} kata</span></div><p class=\"muted\">${Object.entries(state.vocab).filter(([id,x])=>V.find(v=>v.id===id)?.level===l&&x.mastery>=80).length} mastered</p>${counts[l]?`<button onclick=\"flashcards('${l}')\">Buka flashcards <i data-lucide=\"arrow-right\"></i></button>`:'<p class=\"muted\">Belum tersedia</p>'}`)).join('')}</div>`)}",
"shell(tr('vocab.title'),tr('vocab.subtitle',{n:V.length.toLocaleString()}),`<div class=\"toolbar\"><button class=\"primary\" onclick=\"startVocabQuiz()\" data-testid=\"vocab-quiz-start\"><i data-lucide=\"circle-play\"></i> ${esc(tr('vocab.quiz'))}</button><button onclick=\"reviewVocab()\" data-testid=\"vocab-review-due\"><i data-lucide=\"history\"></i> ${esc(tr('vocab.reviewDue',{n:Object.values(state.vocab).filter(x=>x.nextReview&&x.nextReview<=Date.now()&&x.mastery<80).length}))}</button></div><div class=\"grid\">${LEVELS.map(l=>card(`<div class=\"row\"><b>${l}</b><span>${esc(tr('vocab.words',{n:counts[l]||0}))}</span></div><p class=\"muted\">${esc(tr('vocab.masteredCount',{n:Object.entries(state.vocab).filter(([id,x])=>V.find(v=>v.id===id)?.level===l&&x.mastery>=80).length}))}</p>${counts[l]?`<button onclick=\"flashcards('${l}')\" data-testid=\"vocab-flashcards-${l}\">${esc(tr('vocab.openFlashcards'))} <i data-lucide=\"arrow-right\"></i></button>`:`<p class=\"muted\">${esc(tr('vocab.unavailable'))}</p>`}`)).join('')}</div>`)}\n// Meaning shown in the UI language. Thai glosses live in vocabulary-th.json; when a word has no Thai gloss yet, an English synonym gloss is used so Indonesian never leaks.\nfunction vocabMeaning(v){if(!v)return '';if(!isThai())return v.meaning||'';const th=VOCAB_TH_MEANINGS[v.id];if(th)return th;const syn=(v.synonyms||[]).slice(0,2).join(', ');return syn}\nfunction vocabExampleTranslation(v){return isThai()?'':(v?.exampleTranslation||'')}")
# flashcards
rep("if(!pool.length)return showToast(`Belum ada vocabulary ${level} yang siap dipelajari.`);","if(!pool.length)return showToast(tr('vocab.noLevel',{level}));")
rep("<button id=\"backVocab\"><i data-lucide=\"arrow-left\"></i> Vocabulary</button><b>${i+1}/${pool.length}</b></div>${card(`<div class=\"flashcard ${flipped?'flipped':''}\" id=\"flashcard\" role=\"button\" tabindex=\"0\"><div class=\"flash-inner\"><div class=\"flash-face flash-front\"><div class=\"eyebrow\">${esc(v.level)} · ${esc(indonesianPartOfSpeech(v.partOfSpeech||'kata'))}</div><h2 class=\"word\">${esc(v.word)}</h2><div class=\"phonetic\">${esc(v.phonetic||'Pelafalan belum tersedia')}</div><p class=\"muted\">Ketuk untuk melihat arti</p></div><div class=\"flash-face flash-back\"><div class=\"eyebrow\">ARTI</div><h3>${esc(v.meaning)}</h3><p>${esc(v.example)}</p>${v.exampleTranslation?`<p class=\"muted\">${esc(v.exampleTranslation)}</p>`:''}<div class=\"flash-actions\"><button id=\"learning\">Masih belajar</button><button class=\"primary\" id=\"mastered\">Sudah dikuasai</button></div><p class=\"muted\">Ketuk untuk kembali ke kata</p></div></div></div><div class=\"actions\"><button id=\"speakWord\"><i data-lucide=\"volume-2\"></i> Dengar kata</button><button id=\"speakSentence\"><i data-lucide=\"audio-lines\"></i> Dengar kalimat</button><button id=\"aiWord\"><i data-lucide=\"sparkles\"></i> Tanya AI</button></div><div class=\"swipe-hint\">Geser ke kiri atau kanan untuk berpindah kartu</div><div class=\"notice\">Status: ${esc(state.vocab[v.id]?.mastery>=80?'Dikuasai':state.vocab[v.id]?.total?'Sedang dipelajari':'Baru')}</div>`)}",
"<button id=\"backVocab\" data-testid=\"flashcard-back\"><i data-lucide=\"arrow-left\"></i> ${esc(tr('vocab.back'))}</button><b>${i+1}/${pool.length}</b></div>${card(`<div class=\"flashcard ${flipped?'flipped':''}\" id=\"flashcard\" role=\"button\" tabindex=\"0\" data-testid=\"flashcard\"><div class=\"flash-inner\"><div class=\"flash-face flash-front\"><div class=\"eyebrow\">${esc(v.level)} · ${esc(indonesianPartOfSpeech(v.partOfSpeech))}</div><h2 class=\"word\" data-testid=\"flashcard-word\">${esc(v.word)}</h2><div class=\"phonetic\">${esc(v.phonetic||tr('vocab.noPhonetic'))}</div><p class=\"muted\">${esc(tr('vocab.tapMeaning'))}</p></div><div class=\"flash-face flash-back\"><div class=\"eyebrow\">${esc(tr('vocab.meaning'))}</div><h3 data-testid=\"flashcard-meaning\">${esc(vocabMeaning(v)||tr('vocab.glossFallback'))}</h3><p>${esc(v.example)}</p>${vocabExampleTranslation(v)?`<p class=\"muted\">${esc(vocabExampleTranslation(v))}</p>`:''}<div class=\"flash-actions\"><button id=\"learning\">${esc(tr('vocab.stillLearning'))}</button><button class=\"primary\" id=\"mastered\">${esc(tr('vocab.markMastered'))}</button></div><p class=\"muted\">${esc(tr('vocab.tapBack'))}</p></div></div></div><div class=\"actions\"><button id=\"speakWord\"><i data-lucide=\"volume-2\"></i> ${esc(tr('vocab.hearWord'))}</button><button id=\"speakSentence\"><i data-lucide=\"audio-lines\"></i> ${esc(tr('vocab.hearSentence'))}</button><button id=\"aiWord\" data-testid=\"flashcard-ask-ai\"><i data-lucide=\"sparkles\"></i> ${esc(tr('vocab.askAI'))}</button></div><div class=\"swipe-hint\">${esc(tr('vocab.swipeHint'))}</div><div class=\"notice\">${esc(tr('vocab.status',{status:tr(state.vocab[v.id]?.mastery>=80?'vocab.status.mastered':state.vocab[v.id]?.total?'vocab.status.learning':'vocab.status.new')}))}</div>`)}")
rep("save();showToast('Progres tersimpan')};","save();showToast(tr('result.toast.saved'))};")
rep("haptic('success');showToast('Ditandai dikuasai');i++;draw()};","haptic('success');showToast(tr('vocab.status.mastered'));i++;draw()};")
# review
rep("if(!due.length)return showToast('Belum ada review yang jatuh tempo.');","if(!due.length)return showToast(tr('vocab.noReview'));")
rep("<button id=\"backReview\"><i data-lucide=\"arrow-left\"></i> Vocabulary</button><b>Ulangan ${i+1}/${due.length}</b></div>${card(`<div class=\"flashcard ${flipped?'flipped':''}\" id=\"reviewCard\" role=\"button\" tabindex=\"0\"><div class=\"flash-inner\"><div class=\"flash-face flash-front\"><div class=\"eyebrow\">ULANGAN · ${esc(v.level)}</div><h2 class=\"word\">${esc(v.word)}</h2><div class=\"phonetic\">${esc(v.phonetic||'Pelafalan belum tersedia')}</div><p class=\"muted\">Ketuk untuk melihat arti</p></div><div class=\"flash-face flash-back\"><div class=\"eyebrow\">ARTI</div><h3>${esc(v.meaning)}</h3><p>${esc(v.example)}</p><div class=\"flash-actions\"><button id=\"reviewLearning\">Masih belajar</button><button class=\"primary\" id=\"reviewMastered\">Sudah dikuasai</button></div><p class=\"muted\">Ketuk untuk kembali ke kata</p></div></div></div><div class=\"swipe-hint\">Geser ke kiri atau kanan untuk berpindah kartu</div>`)}",
"<button id=\"backReview\"><i data-lucide=\"arrow-left\"></i> ${esc(tr('vocab.back'))}</button><b>${esc(tr('vocab.reviewLabel',{i:i+1,n:due.length}))}</b></div>${card(`<div class=\"flashcard ${flipped?'flipped':''}\" id=\"reviewCard\" role=\"button\" tabindex=\"0\"><div class=\"flash-inner\"><div class=\"flash-face flash-front\"><div class=\"eyebrow\">${esc(tr('vocab.reviewKicker'))} · ${esc(v.level)}</div><h2 class=\"word\">${esc(v.word)}</h2><div class=\"phonetic\">${esc(v.phonetic||tr('vocab.noPhonetic'))}</div><p class=\"muted\">${esc(tr('vocab.tapMeaning'))}</p></div><div class=\"flash-face flash-back\"><div class=\"eyebrow\">${esc(tr('vocab.meaning'))}</div><h3>${esc(vocabMeaning(v)||tr('vocab.glossFallback'))}</h3><p>${esc(v.example)}</p><div class=\"flash-actions\"><button id=\"reviewLearning\">${esc(tr('vocab.stillLearning'))}</button><button class=\"primary\" id=\"reviewMastered\">${esc(tr('vocab.markMastered'))}</button></div><p class=\"muted\">${esc(tr('vocab.tapBack'))}</p></div></div></div><div class=\"swipe-hint\">${esc(tr('vocab.swipeHint'))}</div>`)}")
rep("if(!source.length)return showToast('Vocabulary belum tersedia.');","if(!source.length)return showToast(tr('vocab.noVocab'));")
# vocab question factory — meaning resolved through vocabMeaning() so the UI language never leaks
rep("""  const same=V.filter(x=>x.id!==v.id&&x.meaning&&x.level===v.level);
  const allMeaning=V.filter(x=>x.id!==v.id&&x.meaning);
  const uniqueByNorm=arr=>{const seen=new Set();return arr.filter(x=>{const k=norm(x);if(!k||seen.has(k))return false;seen.add(k);return true})};
  const distractMeaning=uniqueByNorm(shuffle(same.map(x=>x.meaning).filter(x=>norm(x)!==norm(v.meaning)))).slice(0,3);
  if(distractMeaning.length<3){
    distractMeaning.push(...uniqueByNorm(shuffle(allMeaning.map(x=>x.meaning).filter(x=>norm(x)!==norm(v.meaning)&&!distractMeaning.some(d=>norm(d)===norm(x))))).slice(0,3-distractMeaning.length));
  }""",
"""  const meaning=vocabMeaning(v);
  const same=V.filter(x=>x.id!==v.id&&vocabMeaning(x)&&x.level===v.level);
  const allMeaning=V.filter(x=>x.id!==v.id&&vocabMeaning(x));
  const uniqueByNorm=arr=>{const seen=new Set();return arr.filter(x=>{const k=norm(x);if(!k||seen.has(k))return false;seen.add(k);return true})};
  const distractMeaning=uniqueByNorm(shuffle(same.map(vocabMeaning).filter(x=>norm(x)!==norm(meaning)))).slice(0,3);
  if(distractMeaning.length<3){
    distractMeaning.push(...uniqueByNorm(shuffle(allMeaning.map(vocabMeaning).filter(x=>norm(x)!==norm(meaning)&&!distractMeaning.some(d=>norm(d)===norm(x))))).slice(0,3-distractMeaning.length));
  }""")
rep("""  if(type==='synonym'&&(!v.synonyms?.length||synonymSources.length<3))type='meaning';
  if(type==='context'&&!v.example)type='meaning';
  if(type==='partOfSpeech'&&!v.partOfSpeech)type='meaning';
  let q,options,answer;
  if(type==='context'){options=shuffle([v.meaning,...distractMeaning]);q=`Dalam kalimat “${v.example}”, arti “${v.word}” yang paling pas apa?`;answer=v.meaning}
  else if(type==='partOfSpeech'){const correctPos=indonesianPartOfSpeech(v.partOfSpeech),pos=['noun','verb','adjective','adverb','preposition','conjunction'].filter(x=>x!==v.partOfSpeech).map(indonesianPartOfSpeech);options=shuffle([correctPos,...pos.slice(0,3)]);q=`Di lesson ini, “${v.word}” termasuk jenis kata apa?`;answer=correctPos}
  else if(type==='synonym'){options=shuffle([v.synonyms[0],...synonymSources.slice(0,3)]);q=`Kata mana yang maknanya paling dekat dengan “${v.word}”?`;answer=v.synonyms[0]}
  else{options=shuffle([v.meaning,...distractMeaning]);q=`Arti Bahasa Indonesia yang paling dekat dengan “${v.word}” apa?`;answer=v.meaning}
  const posLabel=indonesianPartOfSpeech(v.partOfSpeech);const why=type==='context'?`Di kalimat itu, “${v.word}” paling pas dimaknai “${v.meaning}”. Coba lihat tindakan atau situasi di sekeliling katanya.`:type==='partOfSpeech'?`“${v.word}” berfungsi sebagai ${posLabel}. Jenis kata dilihat dari tugasnya di dalam kalimat, bukan hanya dari bentuk katanya.`:type==='synonym'?`“${v.synonyms[0]}” paling dekat maknanya dengan “${v.word}”. Keduanya bisa terasa mirip, walaupun nuansa pemakaiannya dapat berbeda.`:`Intinya, “${v.word}” berarti “${v.meaning}”${v.partOfSpeech?` dan biasanya dipakai sebagai ${posLabel}`:''}.`;
  const rule=type==='partOfSpeech'?'Lihat fungsi kata di dalam kalimat: apakah ia menamai sesuatu, menyatakan tindakan, menerangkan, atau menghubungkan bagian kalimat.':type==='synonym'?'Kata yang bersinonim punya makna inti yang berdekatan, tetapi belum tentu bisa saling menggantikan di setiap kalimat.':'Jangan menebak dari satu kata saja. Baca konteks lengkap supaya arti yang dipilih tetap masuk akal.';
  return{id:`vocab-${v.id}-${type}-${Date.now()}-${Math.random()}`,type:'vocab',skill:`vocabulary_${type}`,target:v.id,difficulty:LEVELS.indexOf(v.level)+1,canary:v.canary||null,question:q,options,answerIndex:options.indexOf(answer),explain:{why,rule,avoid:`Baca seluruh kalimat, lalu bayangkan situasinya sebelum memilih arti “${v.word}”.`,memory:`Ingat pasangan singkat ini: ${v.word} berarti ${v.meaning}.`,distractor:'Pilihan lain memang terlihat mirip atau berada di level yang sama, tetapi maknanya tidak cocok dengan kata target dalam konteks soal ini.'}}""",
"""  const meaningReady=!!meaning&&distractMeaning.length>=3;
  if(type==='synonym'&&(!v.synonyms?.length||synonymSources.length<3))type='meaning';
  if(type==='context'&&!v.example)type='meaning';
  if(type==='partOfSpeech'&&!v.partOfSpeech)type='meaning';
  if((type==='meaning'||type==='context')&&!meaningReady)type=v.synonyms?.length&&synonymSources.length>=3?'synonym':'partOfSpeech';
  let q,options,answer;
  if(type==='context'){options=shuffle([meaning,...distractMeaning]);q=tr('vocab.q.context',{example:v.example,word:v.word});answer=meaning}
  else if(type==='partOfSpeech'){const correctPos=indonesianPartOfSpeech(v.partOfSpeech),pos=['noun','verb','adjective','adverb','preposition','conjunction'].filter(x=>x!==v.partOfSpeech).map(indonesianPartOfSpeech);options=shuffle([correctPos,...pos.slice(0,3)]);q=tr('vocab.q.pos',{word:v.word});answer=correctPos}
  else if(type==='synonym'){options=shuffle([v.synonyms[0],...synonymSources.slice(0,3)]);q=tr('vocab.q.synonym',{word:v.word});answer=v.synonyms[0]}
  else{options=shuffle([meaning,...distractMeaning]);q=tr('vocab.q.meaning',{word:v.word});answer=meaning}
  const posLabel=indonesianPartOfSpeech(v.partOfSpeech),gloss=meaning||(v.synonyms||[]).slice(0,2).join(', ')||v.word;const why=type==='context'?tr('vocab.why.context',{word:v.word,meaning:gloss}):type==='partOfSpeech'?tr('vocab.why.pos',{word:v.word,pos:posLabel}):type==='synonym'?tr('vocab.why.synonym',{synonym:v.synonyms[0],word:v.word}):tr('vocab.why.meaning',{word:v.word,meaning:gloss,pos:v.partOfSpeech?tr('vocab.why.meaningPos',{pos:posLabel}):''});
  const rule=tr(type==='partOfSpeech'?'vocab.rule.pos':type==='synonym'?'vocab.rule.synonym':'vocab.rule.default');
  return{id:`vocab-${v.id}-${type}-${Date.now()}-${Math.random()}`,type:'vocab',skill:`vocabulary_${type}`,target:v.id,difficulty:LEVELS.indexOf(v.level)+1,canary:v.canary||null,question:q,options,answerIndex:options.indexOf(answer),explain:{why,rule,avoid:tr('vocab.avoid',{word:v.word}),memory:tr('vocab.memory',{word:v.word,meaning:gloss}),distractor:tr('vocab.distractor')}}""")
# grammar hub + lesson
rep("shell('Grammar Hub',`${skills.length} lesson. Setiap lesson memiliki 25 soal test grammar dengan penjelasan Bahasa Indonesia.`,`<div class=\"grid grammar-grid\">${skills.map(k=>{const item=G[k]?.[0]||[],family=grammarFamilyLabel(item);return card(`<div class=\"row\"><b>${esc(friendlySkillName(k))}</b><span>${esc(item[5]||'A1')}</span></div><p class=\"muted\">Fokus: ${esc(family)}. Setiap sesi berisi ${GRAMMAR_SESSION_SIZE} soal.</p><div class=\"lesson-card-foot\"><span>Mastery ${state.grammar[k]?.mastery||0}%</span><button onclick=\"openGrammarLesson('${esc(k)}')\">Buka lesson <i data-lucide=\"arrow-right\"></i></button></div>`)}).join('')}</div>`)}",
"shell(tr('grammar.title'),tr('grammar.subtitle',{n:skills.length}),`<div class=\"grid grammar-grid\">${skills.map(k=>{const item=G[k]?.[0]||[],family=grammarFamilyLabel(item);return card(`<div class=\"row\"><b>${esc(friendlySkillName(k))}</b><span>${esc(item[5]||'A1')}</span></div><p class=\"muted\">${esc(tr('grammar.focus',{family,n:GRAMMAR_SESSION_SIZE}))}</p><div class=\"lesson-card-foot\"><span>${esc(tr('grammar.mastery',{n:state.grammar[k]?.mastery||0}))}</span><button onclick=\"openGrammarLesson('${esc(k)}')\" data-testid=\"grammar-open-${esc(k)}\">${esc(tr('grammar.open'))} <i data-lucide=\"arrow-right\"></i></button></div>`)}).join('')}</div>`)}")
rep("if(!arr.length)return showToast('Lesson ini belum memiliki materi.');const item=arr[0],base=item[0],opts=item[1]||[],correct=opts[item[2]],rule=grammarRuleIndonesian(item),clue=grammarClue(base);shell(friendlySkillName(skill),`${item[5]||'A1'} · 1 konsep inti · ${GRAMMAR_SESSION_SIZE} mode latihan setiap sesi`,`${card(`<div class=\"eyebrow\">PAHAMI DULU</div><h2 class=\"lesson-title\">Intinya begini</h2><p>${esc(rule)}</p><div class=\"lesson-example\"><span>Contoh</span><h3>${esc(base)}</h3><p>Jawaban yang pas: <strong>${esc(correct)}</strong>. ${esc(clue)}</p></div><p class=\"memory-tip\"><i data-lucide=\"lightbulb\"></i><span>Jangan buru-buru menghafal rumus. Temukan dulu petunjuk waktu, maksud kalimat, dan hubungan antarbagian.</span></p>`,'grammar-lesson-card')}<div class=\"practice-contract\"><div><h3>${GRAMMAR_SESSION_SIZE} mode latihan terfokus</h3><p>Semua soal tetap menguji konsep lesson ini melalui penerapan, diagnosis distraktor, perbandingan, penjelasan aturan, dan cek penguasaan.</p></div><button onclick=\"practiceSkill('${esc(skill)}')\" class=\"primary\">Mulai ${GRAMMAR_SESSION_SIZE} soal <i data-lucide=\"arrow-right\"></i></button></div><div class=\"toolbar\"><button onclick=\"go('grammar')\"><i data-lucide=\"arrow-left\"></i> Kembali ke Grammar Hub</button></div>`)}",
"if(!arr.length)return showToast(tr('grammar.noContent'));const item=arr[0],base=item[0],opts=item[1]||[],correct=opts[item[2]],rule=grammarRuleIndonesian(item),clue=grammarClue(base);shell(friendlySkillName(skill),tr('grammar.lessonSub',{level:item[5]||'A1',n:GRAMMAR_SESSION_SIZE}),`${card(`<div class=\"eyebrow\">${esc(tr('grammar.understandFirst'))}</div><h2 class=\"lesson-title\" data-testid=\"grammar-lesson-title\">${esc(tr('grammar.gist'))}</h2><p>${esc(rule)}</p><div class=\"lesson-example\"><span>${esc(tr('grammar.example'))}</span><h3>${esc(base)}</h3><p>${tr('grammar.fits',{answer:esc(correct),clue:esc(clue)})}</p></div><p class=\"memory-tip\"><i data-lucide=\"lightbulb\"></i><span>${esc(tr('grammar.tip'))}</span></p>`,'grammar-lesson-card')}<div class=\"practice-contract\"><div><h3>${esc(tr('grammar.modesTitle',{n:GRAMMAR_SESSION_SIZE}))}</h3><p>${esc(tr('grammar.modesBody'))}</p></div><button onclick=\"practiceSkill('${esc(skill)}')\" class=\"primary\" data-testid=\"grammar-practice-start\">${esc(tr('grammar.start',{n:GRAMMAR_SESSION_SIZE}))} <i data-lucide=\"arrow-right\"></i></button></div><div class=\"toolbar\"><button onclick=\"go('grammar')\"><i data-lucide=\"arrow-left\"></i> ${esc(tr('grammar.backHub'))}</button></div>`)}")

for old,new in R:
    n=s.count(old)
    if n!=1:
        print('FAIL',n,old[:100]);sys.exit(1)
    s=s.replace(old,new)
open(p,'w',encoding='utf-8').write(s)
print('ok',len(R))
