#!/usr/bin/env python3
import sys
p='/app/app.js';s=open(p,encoding='utf-8').read()
R=[]
def rep(old,new):R.append((old,new))

# quiz loop
rep("if(cfg.placement&&questions.length<150){showToast(`Validator menemukan ${questions.length} soal unik; 150 belum aman dijalankan.`);return}if(!questions.length){showToast('Belum ada soal yang valid untuk latihan ini.');return}",
"if(cfg.placement&&questions.length<150){showToast(tr('quiz.placementShort',{n:questions.length}));return}if(!questions.length){showToast(tr('quiz.noValid'));return}")
rep("<button id=\"quizExit\"><i data-lucide=\"x\"></i> Keluar</button><div class=\"quiz-progress\"><span>${i+1}</span><em>/ ${questions.length}</em></div><button id=\"quizNext\" class=\"quiz-next\" disabled>Lanjut <i data-lucide=\"arrow-right\"></i></button></div>${q.passage?card(`<div class=\"passage\"><div class=\"eyebrow\">TEKS BACAAN</div>",
"<button id=\"quizExit\" data-testid=\"quiz-exit\"><i data-lucide=\"x\"></i> ${esc(tr('quiz.exit'))}</button><div class=\"quiz-progress\" data-testid=\"quiz-progress\"><span>${i+1}</span><em>/ ${questions.length}</em></div><button id=\"quizNext\" class=\"quiz-next\" disabled data-testid=\"quiz-next\">${esc(tr('quiz.next'))} <i data-lucide=\"arrow-right\"></i></button></div>${q.passage?card(`<div class=\"passage\"><div class=\"eyebrow\">${esc(tr('quiz.passage'))}</div>")
rep("<div class=\"eyebrow\">${esc(friendlySkillName(q.skill||q.type))} · ${esc(q.difficulty||'adaptif')}</div><h2 class=\"question\">${esc(q.question)}</h2><div id=\"options\" class=\"options\"></div><div id=\"feedback\" class=\"feedback hidden\"></div>",
"<div class=\"eyebrow\">${esc(friendlySkillName(q.skill||q.type))} · ${esc(q.difficulty||tr('quiz.adaptive'))}</div><h2 class=\"question\" data-testid=\"quiz-question\">${esc(q.question)}</h2><div id=\"options\" class=\"options\" data-testid=\"quiz-options\"></div><div id=\"feedback\" class=\"feedback hidden\" data-testid=\"quiz-feedback\"></div>")
rep("<b>${ok?'Benar, mantap!':'Belum tepat, tidak apa-apa.'}</b></div><p>Jawabanmu <strong>${esc(q.options[j])}</strong>. Jawaban yang paling tepat adalah <strong>${esc(q.options[q.answerIndex])}</strong>.</p><p><strong>Intinya:</strong> ${esc(q.explain?.why||'Jawaban perlu cocok dengan konteks soal.')} ${q.explain?.rule?esc(q.explain.rule):''}</p><p class=\"muted\">${esc(q.explain?.distractor||'Pilihan lain belum didukung oleh konteks atau aturan yang relevan.')} ${esc(q.explain?.avoid||'Periksa petunjuk utama sebelum memilih.')}</p>",
"<b data-testid=\"quiz-feedback-title\">${esc(tr(ok?'quiz.correct':'quiz.incorrect'))}</b></div><p>${tr('quiz.yourAnswer',{answer:esc(q.options[j]),correct:esc(q.options[q.answerIndex])})}</p><p><strong>${esc(tr('quiz.gist'))}</strong> ${esc(q.explain?.why||tr('quiz.defaultWhy'))} ${q.explain?.rule?esc(q.explain.rule):''}</p><p class=\"muted\">${esc(q.explain?.distractor||tr('quiz.defaultDistractor'))} ${esc(q.explain?.avoid||tr('quiz.defaultAvoid'))}</p>")
rep("<span>${esc(q.explain?.memory||'Cari petunjuk utama dan hubungkan dengan pola yang sedang dipelajari.')}</span></p><button class=\"ai-btn\" id=\"aiExplainBtn\"><i data-lucide=\"sparkles\"></i> Jelaskan dengan cara yang lebih sederhana</button><div class=\"confidence-box\"><b>Tadi seberapa yakin?</b><div class=\"actions\"><button onclick=\"setConfidence(1)\">1 · Masih ragu</button><button onclick=\"setConfidence(2)\">2 · Lumayan yakin</button><button onclick=\"setConfidence(3)\">3 · Yakin sekali</button></div></div>`",
"<span>${esc(q.explain?.memory||tr('quiz.defaultMemory'))}</span></p><button class=\"ai-btn\" id=\"aiExplainBtn\" data-testid=\"quiz-ai-explain\"><i data-lucide=\"sparkles\"></i> ${esc(tr('quiz.aiExplain'))}</button><div class=\"confidence-box\"><b>${esc(tr('quiz.confidence.title'))}</b><div class=\"actions\"><button onclick=\"setConfidence(1)\">${esc(tr('quiz.confidence.1'))}</button><button onclick=\"setConfidence(2)\">${esc(tr('quiz.confidence.2'))}</button><button onclick=\"setConfidence(3)\">${esc(tr('quiz.confidence.3'))}</button></div></div>`")
# results
rep("const outcomeLine=outcome?`<p class=\"muted\">Core menilai strategi sesi ini: <b>${esc(outcome.status)}</b> · outcome score ${Math.round(outcome.score)}/100. ${outcome.status==='positive'?'Strategi ini layak dipertahankan atau dinaikkan pelan-pelan.':outcome.status==='negative'?'Sesi berikutnya akan diperingan atau diturunkan difficulty-nya.':'Core akan pakai hasil ini sebagai evidence untuk policy berikutnya.'}</p>`:'<p class=\"muted\">Progres sudah masuk ke profil skill dan latihan adaptif berikutnya.</p>';",
"const outcomeLine=outcome?`<p class=\"muted\">${tr('result.outcome',{status:esc(outcome.status),score:Math.round(outcome.score),note:esc(tr(outcome.status==='positive'?'result.outcome.positive':outcome.status==='negative'?'result.outcome.negative':'result.outcome.neutral'))})}</p>`:`<p class=\"muted\">${esc(tr('result.saved'))}</p>`;")
rep("SESSION COMPLETE</div><h2>${cfg.placement?'Tes level selesai':'Latihan selesai'}</h2><div class=\"score\">${accuracy}%</div><p>${score} dari ${total} jawaban benar.</p>${outcomeLine}<button class=\"primary\" onclick=\"go('home')\">Kembali ke Home <i data-lucide=\"arrow-right\"></i></button>`",
"${esc(tr('result.mark'))}</div><h2 data-testid=\"result-title\">${esc(tr(cfg.placement?'result.placementDone':'result.practiceDone'))}</h2><div class=\"score\" data-testid=\"result-score\">${accuracy}%</div><p>${esc(tr('result.score',{score,total}))}</p>${outcomeLine}<button class=\"primary\" onclick=\"go('home')\" data-testid=\"result-home\">${esc(tr('result.home'))} <i data-lucide=\"arrow-right\"></i></button>`")
rep("showToast(accuracy>=70?'Sesi kuat. Profil skill diperbarui.':'Progres tersimpan untuk rekomendasi berikutnya.')","showToast(tr(accuracy>=70?'result.toast.strong':'result.toast.saved'))")
# report labels
rep("function reportStatusLabel(){if(!state.preferences?.reportConsent)return'Laporan privat';if(!state.preferences?.reportEndpoint)return'Creator Hub belum tersambung';if(state.reportMeta?.lastStatus==='sent')return`Terkirim ${state.reportMeta.lastSentAt?new Date(state.reportMeta.lastSentAt).toLocaleDateString('id-ID'):''}`.trim();if(state.reportMeta?.lastStatus==='queued')return'Antrean pengiriman aktif';if(state.reportMeta?.lastStatus==='error')return'Menunggu koneksi';return'Siap mengirim otomatis'}",
"function reportStatusLabel(){if(!state.preferences?.reportConsent)return tr('report.private');if(!state.preferences?.reportEndpoint)return tr('report.notConnected');if(state.reportMeta?.lastStatus==='sent')return tr('report.sent',{date:state.reportMeta.lastSentAt?new Date(state.reportMeta.lastSentAt).toLocaleDateString(I18N.intlLocale()):''}).trim();if(state.reportMeta?.lastStatus==='queued')return tr('report.queued');if(state.reportMeta?.lastStatus==='error')return tr('report.waiting');return tr('report.ready')}")
rep("showToast('Laporan agregat terkirim ke Creator Hub')","showToast(tr('report.toast.sent'))")
rep("showToast('Laporan disimpan di antrean dan akan dicoba lagi')","showToast(tr('report.toast.queued'))")
rep("`<div class=\"modal-mark\">PRIVACY PREVIEW</div><h2>Data yang akan dikirim</h2><p>FIEZEL mengirim ringkasan kemampuan, bukan isi jawaban mentah, riwayat browser, password, atau API key.</p><div class=\"report-preview\"><p><b>Level:</b> ${esc(report.summary.estimatedLevel)}</p><p><b>Total latihan:</b> ${esc(report.summary.totalAttempts)}</p><p><b>Akurasi:</b> ${report.summary.totalAccuracy==null?'Belum terukur':esc(report.summary.totalAccuracy)+'%'}</p><p><b>Area lemah:</b> ${esc(report.summary.weakSkills.map(x=>x.skill.replace(/_/g,' ')).join(', ')||'Belum terukur')}</p><p><b>Laporan terakhir:</b> ${esc(reportStatusLabel())}</p></div><div class=\"modal-actions\"><button class=\"primary\" id=\"previewClose\"><i data-lucide=\"arrow-left\"></i> Kembali ke pengaturan</button></div>`",
"`<div class=\"modal-mark\">${esc(tr('report.preview.mark'))}</div><h2>${esc(tr('report.preview.title'))}</h2><p>${esc(tr('report.preview.body'))}</p><div class=\"report-preview\"><p><b>${esc(tr('report.preview.level'))}</b> ${esc(report.summary.estimatedLevel)}</p><p><b>${esc(tr('report.preview.total'))}</b> ${esc(report.summary.totalAttempts)}</p><p><b>${esc(tr('report.preview.accuracy'))}</b> ${report.summary.totalAccuracy==null?esc(tr('progress.diag.unmeasured')):esc(report.summary.totalAccuracy)+'%'}</p><p><b>${esc(tr('report.preview.weak'))}</b> ${esc(report.summary.weakSkills.map(x=>x.skill.replace(/_/g,' ')).join(', ')||tr('progress.diag.unmeasured'))}</p><p><b>${esc(tr('report.preview.last'))}</b> ${esc(reportStatusLabel())}</p></div><div class=\"modal-actions\"><button class=\"primary\" id=\"previewClose\"><i data-lucide=\"arrow-left\"></i> ${esc(tr('report.preview.back'))}</button></div>`")
# placement
rep("function placement(){shell('Latihan 150 Soal','Tes level untuk memetakan kemampuan dari A1 sampai C2.',`<div class=\"card hero\"><div class=\"eyebrow\">PEMETAAN LEVEL</div><h2>150 soal untuk membaca kemampuanmu.</h2><p>Soalnya diambil dari vocabulary, grammar, dan reading. Setelah selesai, FIEZEL menyimpan perkiraan levelmu sebagai dasar latihan adaptif berikutnya.</p><button class=\"primary\" onclick=\"startPlacement()\">Mulai 150 soal <i data-lucide=\"arrow-right\"></i></button></div><div class=\"level-grid\">${LEVELS.map((l,i)=>card(`<button class=\"level-card\" onclick=\"startLevelPractice('${l}')\"><span class=\"level-number\">${i+1}</span><div><b>${l}</b><p>Masuk ke latihan level ${l}</p></div>",
"function placement(){shell(tr('placement.title'),tr('placement.subtitle'),`<div class=\"card hero\" data-testid=\"placement-hero\"><div class=\"eyebrow\">${esc(tr('placement.kicker'))}</div><h2>${esc(tr('placement.heading'))}</h2><p>${esc(tr('placement.body'))}</p><button class=\"primary\" onclick=\"startPlacement()\" data-testid=\"placement-start\">${esc(tr('placement.start'))} <i data-lucide=\"arrow-right\"></i></button></div><div class=\"level-grid\">${LEVELS.map((l,i)=>card(`<button class=\"level-card\" onclick=\"startLevelPractice('${l}')\" data-testid=\"level-practice-${l}\"><span class=\"level-number\">${i+1}</span><div><b>${l}</b><p>${esc(tr('placement.levelEnter',{level:l}))}</p></div>")
rep("if(qs.length<150)return showToast(`Validator menemukan ${qs.length} soal unik. Placement 150 belum aman dijalankan.`);","if(qs.length<150)return showToast(tr('placement.short',{n:qs.length}));")
rep("if(!items.length)return showToast(`Materi level ${level} belum tersedia.`);","if(!items.length)return showToast(tr('placement.levelUnavailable',{level}));")

for old,new in R:
    n=s.count(old)
    if n!=1:
        print('FAIL',n,old[:100]);sys.exit(1)
    s=s.replace(old,new)
open(p,'w',encoding='utf-8').write(s)
print('ok',len(R))
